### ISSUE TITLE
data.label not rendering TRUE when avoiding bindto

### ISSUE THREAD

**Issue by janiceleng** [c3js/c3#1010]
Hi, I used the workaround for multiple charts from Issue #382, but then the data.label didn't render. How can I get my data labels back? Thanks!

**Comment by masayuki0812** [comment]
What version are you using? I think `0.4.10-rc4` will work, so I'd like you to try this version anyway. If it does not work, can you show me your code? I'll look into it. Thanks.

**Comment by panthony** [comment]
No response, please reopen if this is still an issue
