### ISSUE TITLE
invalid characters in generated css class names

### ISSUE THREAD

**Issue by TomMRiddle** [c3js/c3#1015]
since some html class names are generated from the data they need to be sanitized. spaces already become dashes but åäö and other invalid characters also need to be corrected.

**Comment by masayuki0812** [comment]
I think it's not c3's responsibility, but `data.names` option can be used. Can you try that option?
http://c3js.org/reference.html#data-names

**Comment by panthony** [comment]
`åäö` are valid characters for css classes, you can try:

```html
<div class="åäö"></div>`
```
```js
console.log(document.querySelector('.\å\ä\ö'))
```
