### ISSUE TITLE
Show points in sub chart

### ISSUE THREAD

**Issue by pareeohnos** [c3js/c3#1023]
Is there any way of showing points in the subchart?
I have a rather non-standard chart, whereby the y axis is a category, and the points on this axis vary in size where the size represents its value :

![image](https://cloud.githubusercontent.com/assets/1657075/6354905/742e82ac-bc4a-11e4-8c34-57c7528145fc.png)

The problem is that the subchart doesn't show these points. Is there a way I can force them to be rendered in the subchart?

**Comment by aaronmase** [comment]
+1

**Comment by danpatnate** [comment]
:+1:

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
