### ISSUE TITLE
Android device browser fire's resize event

### ISSUE THREAD

**Issue by mistrynilesh440** [c3js/c3#1029]
How can I block resize event while scrolling html page on android device browser ?

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
