### ISSUE TITLE
Add optional headers to charts

### ISSUE THREAD

**Issue by davidpoore** [c3js/c3#1031]
We've already written some code to handle this in the Pivotal Tracker fork of c3 (https://github.com/pivotaltracker/c3) but I am doing some personal work to clean up that code and open pull requests for our most desired features so that they can be part of the c3 core library.

For the charts designs I'm working with, I want to have a header bar with a different background color from the rest of the chart, where the title, legend, etc. can live. I think a simple config option for `header` that allows you to specify a header color would be useful, especially in conjunction with adding titles to the library (see issue #1021).

I imagine the config will look something like this:
```
header: {
    show: true,
    color: '#EBEBEB',
    // for showing a border line along the bottom of the header
    border: {
        show: true,
        color: '#000'
    }
}
```

**Comment by michaelrodov** [comment]
Closing
This was addressed via Add headers for charts #1032
