### ISSUE TITLE
Wrong position of dashlines on chart as well as subchart

### ISSUE THREAD

**Issue by mistrynilesh440** [c3js/c3#1036]
How can I use region dashlines with subchart and x series is timeseries ?
I have 8 lines in single chart. 4 lines are simple and 4 lines are dashline.
Along with I am using subchart and x series as timeseries.

    Please check below code I m using for drawing dashline inside data object,
    ////
    regions: {
          'k1': [{style':'dashed'}], 
          'k2': [{'style':'dashed'}], 
          'k3': [{'style':'dashed'}], 
          'k4': [{'style':'dashed'}], 
       }

It plot dashlines on wrong position in actual chart as well as subchart.
![capture](https://cloud.githubusercontent.com/assets/11177229/6436340/ca4d4820-c0d3-11e4-8ae0-bcc37ca0db02.JPG)

Thanks.

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
