### ISSUE TITLE
Selection circles on stacked area chart in wrong position

### ISSUE THREAD

**Issue by aprowe** [c3js/c3#1038]
Hello,
It seems the selection circles on a stacked area chart render as if it isn't stacked. 
It can be recreated with this (click on the blue series):

```javascript
var chart = c3.generate({
    data: {
        columns: [
            ['data1', 300, 350, 300, 100, 120,130],
            ['data2', 130, 100, 140, 200, 150, 50]
        ],
        groups: [
          ['data1', 'data2']  
        ],
        selection: {
            enabled:true
        },
        type: 'area'
    }
});
```

**Comment by snkashis** [comment]
I assume you mean behavior like this? 

![screen shot 2015-03-04 at 11 09 47 am](https://cloud.githubusercontent.com/assets/361323/6488725/04743bd0-c25f-11e4-892c-2bc988075c02.png)

**Comment by aprowe** [comment]
That's it- thanks for the screenshot

**Comment by michaelrodov** [comment]
Hi there! 
The issue was validated and it was not reproduced on the latest version
If the issue still persists, please upgrade to the latest version.
If you found a way to reproduce it on the latest version, please reopen / open a bug report.

Thank you!​

**Comment by delacure** [comment]
If the graph is in "timeseries" the bug  still alive 

http://jsfiddle.net/qm28hnyo/
