### ISSUE TITLE
subchart.onbrush - mimic zoom.onzoomend

### ISSUE THREAD

**Issue by peterlauri** [c3js/c3#1039]
We have a graph with subgraph. If we zoom enough we need to resample the data. I started to play with subchart.onbrush, but noticed quickly that it is called for each redraw of the graph, and the resampling costs too much so we cannot do that.

We have two possible workarounds, where we are leaning towards the first one to start with.

- Monitor the domain every N seconds and resample based on some conditions.
- Monitor mouseDown events, and keep track if it is pressed down or not.

Is there any callback for when subchart selection has finished, or possible to disable the "live" update of the chart, meaning only on mouseUp the graph will redraw?

**Comment by michaelrodov** [comment]
Hi there! 
The issue was validated and it was not reproduced on the latest version
If the issue still persists, please upgrade to the latest version.
If you found a way to reproduce it on the latest version, please reopen / open a bug report.

Thank you!​
