### ISSUE TITLE
Tooltip options

### ISSUE THREAD

**Issue by netAction** [c3js/c3#1050]
An option to group tooltip values only when they are in a small range would be nice. This is important since I don't have the cursor's value in _tooltips.contents_ option to fix it myself.

It should be possible to order the entries of grouped tooltips by value. Is there a way to run _getTooltipContent()_ from _tooltip.js_ in a _tooltips.contents_ option to achieve this behaviour manually? If not, it would be great to have a _tooltips.contents_ example with the default behaviour.

**Comment by markdboyd** [comment]
I'm not sure if this is what you are looking for, but there is the ability to override the tooltip contents function via an option:

http://c3js.org/reference.html#tooltip-contents

In terms of the default behavior for tooltips, I think this covers it: 

https://github.com/masayuki0812/c3/issues/444#issuecomment-53986614

**Comment by kriticism** [comment]
![image](https://cloud.githubusercontent.com/assets/10485230/8472656/b6283592-20c0-11e5-845b-9f9942ef47c0.png)


It seems that using 'data.order : null' has caused the shown stacking bottom-to-top in the stacked chart, top-to-bottom in tool-tip, and left-to-right in the legend.
I want to change the order of contents displayed in the tool-tip. Like VNe on top, then Ne, then N and so on. Or any other customization (which, say, is stored in an array). 
How do i do that?

**Comment by michaelrodov** [comment]
Hi there
If this Is still relevant please provide a more detailed description of the desired functionality, including drawings when needed and use cases.
thank you for understanding

**Comment by aashish-chaubey** [comment]
Hey people I am having an issue with the tooltip. I did not open a separate issue for this because it seems to be an responsiveness issue. 

![tooltip-issue](https://user-images.githubusercontent.com/12701463/39909808-fce0144a-5511-11e8-8d38-d801513497ad.png)

Please look into the above issue.
The tooltip text goes on the next line. How to fix this.

Thanks

**Comment by Sibasish19** [comment]
Hey people, I am trying to add a functionality in my line chart create using C3. I want to hide the tooltip when the value is 0 and show it only for data points having non-zero values, is it possible? Please suggest me how to accomplish this. Thanks.

**Comment by aaronELBorg** [comment]
I too would like the functionality mentioned by sibasishm.  Has it been added?  Thank you.
