### ISSUE TITLE
Problem parsing date on parseDate function (when date is a string)

### ISSUE THREAD

**Issue by lbortoli** [c3js/c3#1054]
I think I noticed the error:

c3_chart_internal_fn.parseDate = function (date) {
        var $$ = this, parsedDate;
        if (date instanceof Date) {
            parsedDate = date;
        } else if (typeof date === 'number' && !isNaN(date)) {// fixed wrong validation
            parsedDate = new Date(+date);
        } else {
            parsedDate = $$.dataTimeFormat($$.config.data_xFormat).parse(date);
        }
        if (!parsedDate || isNaN(+parsedDate)) {
            window.console.error("Failed to parse x '" + date + "' to Date object");
        }
        return parsedDate;
    };

The issue was on the validation
 if (typeof date === 'number' || !isNaN(date))

it should be
 if (typeof date === 'number' && !isNaN(date))

**Comment by michaelrodov** [comment]
fix commited
