### ISSUE TITLE
IE issue with getBoundingClientRect

### ISSUE THREAD

**Issue by Mustack** [c3js/c3#1056]
I'm not sure what it is about my case that is causing this issue but getBoundingClientRect() in c3_chart_internal_fn.getParentRectValue is causing an "unspecified error" in IE10 and lower.

All I know for now is this has something to do with the parent element not being rendered. I tried wrapping my c3 setup code in $(document).ready() but I was still getting the error.

I can tell you that I'm wrapping c3 in an Angular directive and I'm avoiding bindTo as it was causing issues with having multiple charts.

I'm releasing my work to the client today so I don't have time to investigate more than this but maybe this will be of some value to you. I'm issuing a pull request with my changes that fixed my issues.

**Comment by masayuki0812** [comment]
Thank you very much for working on this issue. Yeah, I merged your PR and I believe now it's ok.
Btw, I'll release this fix in the next version `0.4.10` shortly and I'll let you know when it's released. Thanks!

**Comment by missingdays** [comment]
This issued was fixed in #1003. Maybe this may be closed?
