### ISSUE TITLE
Update chart title on chart.load

### ISSUE THREAD

**Issue by mika76** [c3js/c3#1058]
I think it's pretty safe to assume the title could change in the case of data being reloaded.

**Comment by michaelrodov** [comment]
It's quite possible that could be a bug, but it's really hard to verify it without more information. 

We get a lot of reports and the more info you give us, the more likely we'll be able to address it in a timely fashion.

Please [read the contributing guidelines](https://github.com/masayuki0812/c3/blob/master/CONTRIBUTING.md), then add the following information to your issue:

-  Operating system and web browser (with version)
-  What version of the library
-  If you were doing anything unusual, like using C3 in conjunction with a particular library or framework
-  Ideally, a [JSFiddle](https://jsfiddle.net/) example depicting the specific problem really helps us out. 
	* [Use this JSFiddle template](https://jsfiddle.net/aendrew/L4ocdkcq/)


Thank you for your cooperation — we rely on users like you to help make C3 the best charting library it can be!

**Comment by mika76** [comment]
Hi Michael 

Sorry for the bad report. What I think I meant was when re-loading data (ie calling chart.load a second or third time) could you also re-read the title since something might change with the new data. So not so much a bug but a tiny enhancement.
