### ISSUE TITLE
'becuase' is spelled incorrectly in reference documentation

### ISSUE THREAD

**Issue by skinnybrit51** [c3js/c3#1059]
When chart is not binded, c3 starts observing if chart.element is binded by MutationObserver. In this case, polyfill is required in IE9 and IE10 becuase they do not support MutationObserver. On the other hand, if chart always will be binded, polyfill will not be required because MutationObserver will never be called.

**Comment by akenn** [comment]
I've opened a PR in the documentation repo to fix the issue, so this can be closed.
