### ISSUE TITLE
Dashed styling breaks when zoom enabled

### ISSUE THREAD

**Issue by mattlucas121** [c3js/c3#1061]
When combining the zoom functionality with the "dashed" styling of a region the chart gets the styled X axis stuck on it and never redraws. Here is a jsfiddle showing the issue..

http://jsfiddle.net/ZpBdL/5/

This maybe related/similar to issue #1036. If you need any additional feedback please let me know.

Thanks!

**Comment by tclavijod** [comment]
+1 .. I'm having the same problem :S

**Comment by lejard-h** [comment]
:+1:

**Comment by petogriac** [comment]
same issue, is there any fix ? 

thanks

**Comment by panthony** [comment]
Fix is merged but no ETA for the next release.

**Comment by kt3k** [comment]
The fix is released in [v0.5.2](https://github.com/c3js/c3/releases/tag/v0.5.2).
