### ISSUE TITLE
Modify data.keys.value with data.json and category axis while chart.load()

### ISSUE THREAD

**Issue by norecces** [c3js/c3#1066]
Hi,

Cant figure out how to redefine key.value with chart load keys.
Look at http://jsfiddle.net/norecces/1jj8y21m/1/

on chart.generate I have 
```javascript
keys: {
    x: 'name', // it's possible to specify 'x' when category axis
    value: ['upload', 'download'],
}
```

and then I want to update only keys.value

```javascript
chart.load({
        keys: {
            x: 'name',
            value: ['upload'],
        }
    });
```

Which I thought should remove 'download' seria. Any suggestions ?

**Comment by vladsu** [comment]
Try this
```
chart.load({
keys: {
            x: 'name',
            value: ['upload'],
        },
        unload: ['download']
});
```

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
