### ISSUE TITLE
Question: How to get selection and do something with it

### ISSUE THREAD

**Issue by jgoodall** [c3js/c3#1072]
If I have `data.selection.enabled` set to true in a stacked bar chart, I can get the selected bars doing something like this: 
```
var selected = this.chart.selected();
```

What can I do with `selected` at this point? What I would like to do is change the color scheme for the selected bars, but this does not work:
```
selected.data().colors(newcolors);
```

Any advice on how to accomplish this?

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
