### ISSUE TITLE
Auto chart height resize not working

### ISSUE THREAD

**Issue by michaelbrooks** [c3js/c3#1076]
When the window resizes, I see the chart _width_ update automatically, but the height does not change. I think this is because of the `$$.selectChart.style('max-height', $$.currentHeight + "px");` bit on [line 880](https://github.com/masayuki0812/c3/blob/master/c3.js#L880). When I comment out this line, the chart height updates correctly.

This line forces the `.c3` container element to have the max height `$$.currentHeight`, but on the window resize event, `$$.currentHeight` is set based on the height of that same element (see `getCurrentHeight()` and `getParentHeight()`), which means it gets stuck at the current value.

I can submit a pull request, but it's just a one line change.

**Comment by jonccooke** [comment]
Hello, I have the same issue. Looks like this is still in master branch. Has the change been made?

**Comment by codeHatcher** [comment]
I'm having this issue as well

**Comment by pchaganti** [comment]
👍

**Comment by ashishsajwan** [comment]
any update on this ??

**Comment by panthony** [comment]
closing in favor of #1450

**Comment by allicanseenow** [comment]
Do we have an update on this?

**Comment by szb0151** [comment]
> When the window resizes, I see the chart _width_ update automatically, but the height does not change. I think this is because of the `$$.selectChart.style('max-height', $$.currentHeight + "px");` bit on [line 880](https://github.com/masayuki0812/c3/blob/master/c3.js#L880). When I comment out this line, the chart height updates correctly.
> 
> This line forces the `.c3` container element to have the max height `$$.currentHeight`, but on the window resize event, `$$.currentHeight` is set based on the height of that same element (see `getCurrentHeight()` and `getParentHeight()`), which means it gets stuck at the current value.
> 
> I can submit a pull request, but it's just a one line change.

Commenting out this line did not solve the issue. Is there another solution to this issue?
