### ISSUE TITLE
Multiple columns for Gauge Chart

### ISSUE THREAD

**Issue by tenshis** [c3js/c3#1077]
Would it be possible to display multiple columns as separate archs in the Gauge Chart, [like this](http://stackoverflow.com/questions/29194103/is-there-a-d3-gauge-allowing-multiple-series-columns) ?

**Comment by GoekhanOezen** [comment]
Hi,
I had the same question and after a while i asked myself "why dont you implement it yourself". And now i have a result. although the code could be cleaner it already is quite clean. But it does its work. So i will add some screenshots so you can decide if you want to add it to c3.js. I would be very happy if so. 

![screenshot for c3](https://cloud.githubusercontent.com/assets/11871137/8825198/8b23d046-307d-11e5-9470-764fb7a2a4f5.png)

as you can see i even can change the angle of the gauge. from 1 to 360 degree. it behaious like pie and donut. so let me know when you are interested in an enhancement

**Comment by ffuentes** [comment]
+1
I'll love to ser this in c3!

**Comment by bluegray** [comment]
Wow! Any progress on this feature?

**Comment by bkanber** [comment]
+1 would also love to have this in c3

**Comment by manzerProgen001** [comment]
Wow, We want to use this enhancement in gauge chart. Can anyone help, where Can I find it in c3.js

**Comment by TONYFECTEAU** [comment]
+1, I am looking at this now in 0.4.21... very nice!

**Comment by sridhark158** [comment]
+1 ,even i am looking for this feature :)

**Comment by rahul-winner** [comment]
did we get this feature implemented in C3? I need this in my current assignment.

**Comment by sridhark158** [comment]
@rahul-winner  
check this link http://jsfiddle.net/rtmdeqpg/2/

**Comment by rahul-winner** [comment]
thanks @sridhark158 
I am talking about a little different thing. I wanted the gauge with different thresholds indicated by different colors. 

I'm talking about something of this kind.
![image](https://user-images.githubusercontent.com/4982751/41287050-265b0602-6e5f-11e8-90b4-7885fbc650d1.png)

**Comment by surbhibh** [comment]
Hi, I tried to implement muti column Gauge using c3, but i am still stuck.
I checked out fiddle and plucker as well, in fiddle the code is working but in plunker the chart get overwrite,I need to implement it by Javascript .  
Please help me with this.
