### ISSUE TITLE
Axis Label color and position

### ISSUE THREAD

**Issue by nathancole** [c3js/c3#108]
Is it possible to set the Axis label color and position.  See the image below for an example of what I might like to accomplish.  This is the chart we currently have implemented.

If the color were configurable via css, that would be great.

![dygraphschart](https://cloud.githubusercontent.com/assets/4251865/2575257/a3fed5f6-b94c-11e3-8f8b-2d184977a39d.PNG)

Thanks,
Nathan

**Comment by keyscores** [comment]
@masayuki0812 
Can you document somewhere the css options we have. I don't see it in examples or reference on the website. Thanks!

**Comment by aendrew** [comment]
@keyscores They're at http://www.c3js.org/reference.html, but not documented yet. Apologies, it's something I keep meaning to get around to. Documentation pull requests for [masayuki0819/c3js.org](https://github.com/masayuki0812/c3js.org/) are extremely welcome, if you care to do so! :smile:

**Comment by dew063** [comment]
now i can't set y2 tick color  via css:
.c3-axis-y2 .tick{
    color: #FE7E0D;
}

**Comment by nsteenbeek** [comment]
@dew063 you should use 'fill' instead of 'color':
.c3-axis-y2 .tick {
    fill: #FEFE0D;
}

**Comment by HawiCaesar** [comment]
In light of this is it possible to change the color of the tick data labels via css? Kindly see the picture...
![screenshot from 2017-03-14 17-16-30](https://cloud.githubusercontent.com/assets/6042152/23904897/7e7dfbfa-08da-11e7-97e9-ab71a0f2d60f.png)

**Comment by HibaYousef** [comment]
Can you please add more information where to add this style in the code ??
