### ISSUE TITLE
Problem in hiding parts of pie chart when clicked on legend.

### ISSUE THREAD

**Issue by Dhruva2015** [c3js/c3#1083]
I generated pie chart using the data of blood group as shown below. It has +ve and -ve symbols in it. It renders chart properly but when clicked on legend like AB+ve both AB+ve and AB-ve will get hide and chart also will not join properly.

Sample data : 

[[O+ve, 861.0], [B+ve, 1134.0], [O-ve, 270.0], [AB+ve, 279.0], [0+ve, 211.0], [A+ve, 854.0], [AB-ve, 288.0], [A-ve, 1153.0]]

Initial pie chart display on load
![piechart](https://cloud.githubusercontent.com/assets/11553557/6847858/96192504-d3ef-11e4-8226-9f60e65f4a05.jpg)

On click of legend part of pie chart is not hidden
![piechartissue1](https://cloud.githubusercontent.com/assets/11553557/6847863/a0ac5a72-d3ef-11e4-8460-d47b4688ed3c.jpg)

On mouse over both AB+ve and AB-ve parts are highlighted
![piechartissue2](https://cloud.githubusercontent.com/assets/11553557/6847866/a79d6862-d3ef-11e4-9881-aa0e35f2f31c.jpg)

**Comment by michaelrodov** [comment]
Hi
Can you please post JSFiddle or something similar of the reproduction?
Many Thanks!

**Comment by panthony** [comment]
Duplicate with #1687

This is the `+` and `-` sign in `AB+ve` the issue.
