### ISSUE TITLE
Tool tip hiding behind the next div

### ISSUE THREAD

**Issue by Sheelarkamath** [c3js/c3#1087]
I am trying to show a tool tip for my graph,
It does show up well , but it has many values and making the bottom of tool tip hide behind the next div
Any one aware how to make the tool tip stay on top of page and not hide behind the next div ?
any help is appreciated !

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
