### ISSUE TITLE
scrollbar goes crazy when the tool tip appears on hover

### ISSUE THREAD

**Issue by astroanu** [c3js/c3#1088]
if the chart is at the bottom of the page and there's no more space below that the scrollbar starts flickering and resizing when i'm hovering the chart. I think this has something to do with how the tool tip is added to the document body. The document height increases just for a fraction of a second and goes back to its original size.

**Comment by astroanu** [comment]
The flickering is also there when switching label names on and off.

**Comment by michaelrodov** [comment]
It's quite possible that could be a bug, but it's really hard to verify it without more information. 

We get a lot of reports and the more info you give us, the more likely we'll be able to address it in a timely fashion.

Please [read the contributing guidelines](https://github.com/masayuki0812/c3/blob/master/CONTRIBUTING.md), then add the following information to your issue:

-  Operating system and web browser (with version)
-  What version of the library
-  If you were doing anything unusual, like using C3 in conjunction with a particular library or framework
-  Ideally, a [JSFiddle](https://jsfiddle.net/) example depicting the specific problem really helps us out. 
	* [Use this JSFiddle template](https://jsfiddle.net/aendrew/L4ocdkcq/)


Thank you for your cooperation — we rely on users like you to help make C3 the best charting library it can be!

**Comment by panthony** [comment]
No response from submitter. Please feel free to reopen if issue still occurs with latest version.
