### ISSUE TITLE
How to break y Axis label if its very long 

### ISSUE THREAD

**Issue by kumar31rajesh** [c3js/c3#1089]
Hi @masayuki0812 ,
How do i break y axis label in 2 lines if its very long Exp:

sum of player average heights 
       in Meters
for Y axis label

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
