### ISSUE TITLE
Update data.mimeType documentation to reflect actual option OR change json: option to accept url

### ISSUE THREAD

**Issue by hoprocker** [c3js/c3#1091]
c3 looks great, and is made even better with the option of being able to load JSON dynamically. It took a bit of time to find the 'mimeType' option. When I did, I assumed that this accepted the standard HTTP mimetype "application/json". This didn't seem to work; so finally, I searched through the issues here and found this: #236 

It looks like you need to specify 'json' as the mimeType parameter to load the data correctly. This is not only undocumented, I would argue that it is confusing in how non-standard it is (see [this](https://www.ietf.org/rfc/rfc4627.txt)). I'd like to propose one of the following changes, in increasing order of preference:

1. Update the documentation to specify that the mimetype is 'json';
1. Allow 'application/json' as a valid mimetype; or
1. Implement @masayuki0812's initial suggestion for the syntax:

```
data: {
    json:  obj // or url
}
```

This last option seems the clearest. I'd be happy to submit a pull request for this.

**Comment by jasonlally** [comment]
:+1: Is it not currently possible to load json via a url? 

The documentation here: http://c3js.org/samples/data_json.html doesn't indicate and then the url documentation here: http://c3js.org/samples/data_url.html has json loading but it's just a json representation of a set of columns.

Anyway, I'd love to be able to dynamically load json that looks something like this:
```javascript
[
 {
 "year": "1992",
 "total_units": "8"
 },
 {
 "year": "1993",
 "total_units": "5"
 }
]
```

I can do this based on the first example manually or via code, but I'd love to call it via a url from c3. The workaround I'm attempting now is to load via ajax call into a variable and pass the variable to the chart.

**Comment by hoprocker** [comment]
Your case seems slightly different than mine. Are you saying that json data can only be loaded before the chart is initialized? If so, can you reload the chart somehow (maybe by calling c3.generate() with just the {data:{json: ..}} parameter)?

**Comment by hoprocker** [comment]
Quick fix to docs [here](https://github.com/masayuki0812/c3js.org/pull/31). Doesn't solve the base confusion, tho.

**Comment by michaelrodov** [comment]
Looks like the issue is resolved?
