### ISSUE TITLE
C3.js api not showing all the elements of the data

### ISSUE THREAD

**Issue by amitbarui008** [c3js/c3#1095]
Hi ,

I am using c3.js api for showing the pie chart. it is working fine for everything. 
The only problem is not showing all the data elements in the pie chart.

for example : if i have 30 elements to show in pie chart. it only shows top 16 elements , not all the elements.

How to solve this issue ?. thanks

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
