### ISSUE TITLE
reading array index

### ISSUE THREAD

**Issue by Abusamra** [c3js/c3#1099]
Can C3 read the X , Y value and name of variable stored in multidimensional array
if possible, can u please let me know how?

**Comment by luiscape** [comment]
Hi there @Abusamra, can you provide some example data? There are a [number of ways](http://c3js.org/examples.html) you can organize your data in order for it to work with c3.

**Comment by Abusamra** [comment]
Hi, thanks for your reply

I'm working on GWAS Data and I have SNPsID, Postion, Pvalue ( these are the
columns name of my data I want to plot)

SNPid pos Pvalue
rs16274 118544448   4.93966438022568
rs16274 118544448  6.64539101451465
rs16294 127145069  3.68651425340766
rs16294 127145069 3.47764655382556
rs16301 123642623 3.74862945851971

and I want to plot each SNP where the x axis represents Position and y axis
represents Pvalue and sure I can see these information when I pass on the
SNP

I hope its clear now

And I have Question can I read from sql Query ?

On Tue, Apr 7, 2015 at 10:41 PM, Luis Capelo <notifications@github.com>
wrote:

> Hi there @Abusamra <https://github.com/Abusamra>, can you provide some
> example data? There are a number of ways <http://c3js.org/examples.html>
> you can organize your data in order for it to work with c3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/masayuki0812/c3/issues/1099#issuecomment-90709643>.
>



-- 
Best Wishes  :)
Heba B Abusamra

 King Abdullah University of Science and Technology (KAUST)

 Thuwal | Kingdom of Saudi Arabia

*E:*  heba.abusamra@kaust.edu.sa  <http://marcos.bracchitta@kaust.edu.sa/>

[image: Description: cid:image001.png@01CD25FC.A6E675C0]

-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by Abusamra** [comment]
BTW Im dealing with millions of rows . So I need  away to do it  without
need of write it by hand

On Wed, Apr 8, 2015 at 8:20 AM, Heba Abu Samra <heba.abusamra@kaust.edu.sa>
wrote:

> Hi, thanks for your reply
>
> I'm working on GWAS Data and I have SNPsID, Postion, Pvalue ( these are
> the columns name of my data I want to plot)
>
> SNPid pos Pvalue
> rs16274 118544448   4.93966438022568
> rs16274 118544448  6.64539101451465
> rs16294 127145069  3.68651425340766
> rs16294 127145069 3.47764655382556
> rs16301 123642623 3.74862945851971
>
> and I want to plot each SNP where the x axis represents Position and y
> axis represents Pvalue and sure I can see these information when I pass on
> the SNP
>
> I hope its clear now
>
> And I have Question can I read from sql Query ?
>
> On Tue, Apr 7, 2015 at 10:41 PM, Luis Capelo <notifications@github.com>
> wrote:
>
>> Hi there @Abusamra <https://github.com/Abusamra>, can you provide some
>> example data? There are a number of ways <http://c3js.org/examples.html>
>> you can organize your data in order for it to work with c3.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/masayuki0812/c3/issues/1099#issuecomment-90709643>.
>>
>
>
>
> --
> Best Wishes  :)
> Heba B Abusamra
>
>  King Abdullah University of Science and Technology (KAUST)
>
>  Thuwal | Kingdom of Saudi Arabia
>
> *E:*  heba.abusamra@kaust.edu.sa  <http://marcos.bracchitta@kaust.edu.sa/>
>
> [image: Description: cid:image001.png@01CD25FC.A6E675C0]
>



-- 
Best Wishes  :)
Heba B Abusamra

 King Abdullah University of Science and Technology (KAUST)

 Thuwal | Kingdom of Saudi Arabia

*E:*  heba.abusamra@kaust.edu.sa  <http://marcos.bracchitta@kaust.edu.sa/>

[image: Description: cid:image001.png@01CD25FC.A6E675C0]

-- 

------------------------------
This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
