### ISSUE TITLE
Selection with multiple types

### ISSUE THREAD

**Issue by fbolognaboidi** [c3js/c3#1104]
I've multiple columns of data, i'm showing it with different types, lines, and bars, without groups...
My selection config is {enabled: true, grouped: false, multiple: false}
but when i start selecting it works like multiple selection is on for lines, the points in the lines can't be unselected and if you start selecting alternate between lines and bars, you can select every value in the chart.
Maybe i'm doing something wrong but i think this is a bug.

**Comment by panthony** [comment]
Hi,

Could you provide a JSFiddle, codePen or Plunkr highlighting the issue?

It makes reproduction much easier for everyone.

Thank you!

**Comment by panthony** [comment]
No response
