### ISSUE TITLE
Gauges only use half their container and crop if it's not square (and padding doesn't work)

### ISSUE THREAD

**Issue by ghost** [c3js/c3#1115]
A gauge's "radius" is determined from width and it's ALWAYS drawn centred - which means you MUST use a 'square' (or portrait) container or it will crop the gauge (leaving space below it?)

Gauges are by nature 'half as tall as they're wide' (being semi-circles) so this isn't right surely - at the very least some sort of 'centre point' or 'vertical aling' setting is required?

Padding.top doesn't work with Gauges either - all it does is 'crop off' the padding size (e.g. the gauge isn't moved down to account for padding which is odd because pie charts ARE moved by padding??)

Any hints on how I can hack these things to work a bit better would be lovely - thanks!

**Comment by panthony** [comment]
Hi,

Could you provide a JSFiddle, codePen or Plunkr highlighting the issue?

It makes reproduction much easier for everyone.

Thank you!

**Comment by panthony** [comment]
No response
