### ISSUE TITLE
Document use of d3.locale to choose localisation settings

### ISSUE THREAD

**Issue by lpgeiger** [c3js/c3#1116]
How do I change the labels on the donut chart to display X,Y% (instead of american X.Y%)?

If I try to adjust the labels in D3 locale.js I break the labels. Seems like C3 is calculating the percentages independently of the D3 settings.  

Maybe this is just not documented. Can we document localization and i18n ?

**Comment by aendrew** [comment]
@Kreozot ran into this today and found a solution, sharing it posterity. 

<img width="828" alt="screen shot 2015-11-05 at 11 34 20" src="https://cloud.githubusercontent.com/assets/185041/10967916/e3de0c20-83b5-11e5-99e2-41b74ffd3fce.png">

Essentially, you set custom format handlers using d3.locale. 

Changing this to a documentation question.

**Comment by kt3k** [comment]
Please see the below:
https://github.com/c3js/c3js.org/pull/37

This will be publish at the next release (0.4.12).
