### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'c.scale')

### ISSUE THREAD

**Issue by tudorsirbu** [c3js/c3#1123]
Hello,

Does anyone know why I'm getting this error?

I'm just trying out some of the examples in the documentation and they do not seem to work. I keep getting the above mentioned error. 

![screen shot 2015-04-22 at 10 56 28](https://cloud.githubusercontent.com/assets/6299690/7271847/44716dca-e8de-11e4-99aa-82fd8405f113.png)

**Comment by gregbeams** [comment]
I'm getting the same error as well. Did you ever find out the cause? I was thinking that perhaps c3 couldn't find the element to bind to for some reason...

**Comment by tudorsirbu** [comment]
No, I could not find any solution so I gave up on it. I'm using HighCharts so much better documented.

**Comment by gregbeams** [comment]
It was fixed when I included c3.js not just c3.min.js

**Comment by otmezger** [comment]
this error comes if you don't include d3 library before including c3. I fixed this just by inserting this to my index.html head:

    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js" charset="utf-8"></script>


I'm using c3 version 0.4.10

**Comment by GDFaber** [comment]
I'm closing this issue as it could be solved by including D3.js like shown in the "Getting started" section of the C3.js documentation.
