### ISSUE TITLE
How to rotate the labels above the bar-chart bar items?

### ISSUE THREAD

**Issue by dasjet** [c3js/c3#1125]
![fghfg](https://cloud.githubusercontent.com/assets/1393520/7313577/f9212b48-ea78-11e4-8554-baac379c7928.JPG)

need to rotate highlighted values.

labels: {
 format: function (v, id, i, j) { return v; },
 // rotate: 45 assuming some thing like this!
}

Thanks

**Comment by DemarsM** [comment]
Have you found a way to achieve this?

**Comment by DemarsM** [comment]
You can select them using D3 and then rotate them

you can try something like this:

        d3.selectAll("text[class*='c3-text-']")
            .style("text-anchor", "start")
            .attr("transform", function(d,i){
                return("translate("+this.getBBox().x+","+this.getBBox().y+")rotate(-90)")
            })
            .attr("y", 0)
            .attr("x", 0)

**Comment by michaelrodov** [comment]
Answered.
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
