### ISSUE TITLE
C3 doesn't adjust axis min/max for lines

### ISSUE THREAD

**Issue by egeriis** [c3js/c3#1129]
If my data set contains three values: `[100,110,120]` and I add a line on the Y-axis as `{ value: 200, text: 'My line' }` the line will not be displayed.

This could be solved by having the chart adjust to the lines that have been added.

**Comment by missingdays** [comment]
Why do you need this feature? It doesn't seem that usefull adjusting min/max for grid.

**Comment by egeriis** [comment]
Honestly, I cannot remember the use case.
