### ISSUE TITLE
edge connection on same level

### ISSUE THREAD

**Issue by nitin0708** [c3js/c3#1132]
Hi Alex,

Can you check this one-http://jsbin.com/zunotutoxu/1/edit?html,output
In this example there is one relation between Alok3 and Alok5 but it's looking not properly.

Thanks
Nitin

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
