### ISSUE TITLE
Hide X axis

### ISSUE THREAD

**Issue by CHR15-** [c3js/c3#114]
As there is many ticks on a chart at certain times, it would be great to hide the x axis labels:

![screen shot 2014-04-02 at 14 39 14](https://cloud.githubusercontent.com/assets/5793128/2591510/36e53eb2-ba6c-11e3-967f-99a69d9496ab.png)

**Comment by nitin0708** [comment]
Hi

after culling when we zoom the graph it have to show the hide labels.But its not showing.

Thanks Nitin
