### ISSUE TITLE
min/max/range API does not change y2

### ISSUE THREAD

**Issue by dburdick** [c3js/c3#1150]
The following alterations to y2 do not work:

```
# y is scaled but y2 is not
graph.axis.range({min: {y: 0.5, y2: 0.5}, max: {y: 1, y2: 1}})

graph.axis.min({y:0.5}) # works
graph.axis.min({y2:0.5}) # does not work
```

Note, this is when using `xs` to coordinate x/y values

**Comment by tom-christie** [comment]
Having the same problem. Mine is using json data with categorical x values.

Perhaps related - I also can't set them using the original constructor:

            y2:{
                show:true, #works
                label:'Test duration (s)', #works
                max:100, #does not work
                min:-200, #does not work
                inverted:true #does not work
            }

**Comment by GoekhanOezen** [comment]
Hi,
for me it didn't work because y2 was not bound to data. maybe you have the same reason

```
data: {
   axes: {
      data1: 'y'
      data2: 'y2' // should work
   }
}
```

**Comment by panthony** [comment]
No fiddle to reproduce the issue or response to suggested solution so let's close
