### ISSUE TITLE
bar style with c3-bar problem

### ISSUE THREAD

**Issue by guykatz** [c3js/c3#1158]
I cant seem to change the color of the stroke for a single bar with this class.
how can I achieve single bar styling?
thanks

**Comment by michaelrodov** [comment]
you should do it via CSS
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
