### ISSUE TITLE
Donuts data order

### ISSUE THREAD

**Issue by dragnoir** [c3js/c3#1159]
Hello,

I am using http://c3js.org/samples/chart_donut.html
The order of the data start from the biggest value to the lowest.
From the top center of the donuts to the right (the biggest value), then the next one.
Not like the order of  
data: {
    columns: [
        ...............
How can I disactivate this default order and make the order as the data set on "columns:" ?

Thanks you all.

**Comment by nglasantha** [comment]
http://c3js.org/samples/data_order.html

    data: {
        columns: [
            ['data1', 130, 200, 320, 400, 530, 750],
            ['data2', -130, 10, 130, 200, 150, 250],
            ['data3', -130, -50, -10, -200, -250, -150]
        ],
        type: 'bar',
        groups: [
            ['data1', 'data2', 'data3']
        ],
        order: 'desc' // stack order by sum of values descendantly. this is default.
//      order: 'asc'  // stack order by sum of values ascendantly.
//      order: null   // stack order by data definition.
    },

**Comment by dragnoir** [comment]
Thanks, it's not working like that.
I just changed the default value from c3.js. "data_order: 'desc'," and it's working now.

**Comment by GoekhanOezen** [comment]
Hello,

i want to sort pies and donuts in ascending order. unfortunately "data_order" is ignored for "pies" and "donuts". only if it is set "null" or "", then the if clause unsort the datacolumns. for all other values of "data_order" it will sort in descending order. even if i pass a sorting function it is ignored.

    c3_chart_internal_fn.initPie = function () {
        var $$ = this, d3 = $$.d3, config = $$.config;
        $$.pie = d3.layout.pie().value(function (d) {
            return d.values.reduce(function (a, b) { return a + b.value; }, 0);
        });
        if (!config.data_order) {
            $$.pie.sort(null);
        }
    };

when we could enhance "initPie()" so that it would look for function, i could hand over my own function, as it is described in the documentations.

        if (!config.data_order) {
            $$.pie.sort(null);
        }
        else if (config.data_order instanceof Function) {
            $$.pie.sort(config.data_order);
        }

**Comment by dragnoir** [comment]
you may try changing the default value from c3.js file. "data_order: 'desc'," 
I think this will work for you

**Comment by GoekhanOezen** [comment]
i tried it this value is just a placeholder. it sorts the "pies" and "donuts" in descending order even if you write "hello" instead of "desc". for "" or null the the "pie" is sort in "data_columns" input order.

**Comment by jonjhiggins** [comment]
I ran into the same thing: order and data_order did nothing.

As `data.columns` appears to respect the order of the array you supply it I presorted the array (arranged with smallest value column first) before applying to c3.js and then the segments were in the right order.

Would be nice if it was part of c3.js though.

**Comment by elektron4** [comment]
order = 'asc', //desc, asc, null
Not working at all :(

**Comment by panthony** [comment]
This issue should be resolved. If not please reopen with a fiddle that demonstrate that the problem still occurs. Thanks!
