### ISSUE TITLE
load data functionality from within a callback in chart creation

### ISSUE THREAD

**Issue by guykatz** [c3js/c3#1161]
Hi;
thanks for the great library.
I want to create my charts empty (no data) and load the data afterwards. the only reason for this is the animation that the load function possess that I cant seem to get in chart creation (if I missed it please do tell). for example, using load for a guage chart post creation, will animate the value within the gauge as opposed to declaring the value in creation which will not animate at all.
personally I think a better programming practice would be to provide a 'post create' callback we can hack into in order to get a reference to the chart and call its load function. the 'onrender' does not seem to get a reference to the c3 final chart.
this is a matter of encapsulation which I think should be addressed.
if I missed something you are welcomed to comment. what I am looking for is:

var chart = c3.generate({
    onChartCreate: function(theChart){//this is the function I need
        theChart.load({
            columns: [['data', 10]]
        }); 
    },
    data: {
        columns: [
            ['data']
        ],
        type: 'gauge',
    },
    color: {
        pattern: ['#FF0000', '#F97600', '#F6C600', '#60B044'], // the three color levels for the percentage values.
        threshold: {
            values: [30, 60, 90, 100]
        }
    },
    size: {
        height: 180
    }
});

**Comment by panthony** [comment]
There is a "oninit" callback already:

http://c3js.org/reference.html#oninit

For further help please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

Thank you!
