### ISSUE TITLE
Update donut chart using the c3 library (JQuery)

### ISSUE THREAD

**Issue by latxor** [c3js/c3#1167]
I need to update a donut chart using the c3 library. The chart is created by the following code:

function (datapie) {  
       var chart = c3.generate({
       bindto: '#idpiechart',
       color: {
           pattern: Colors,
       },
      data: {  
            columns: datapie,
            type: 'pie',
    });
}
Now I just need to update this chart from another function, I'm using the load method but this does not work:

function(updatedata){
        var pie = $("#idpiechart");  
       pie.load({
           columns: updatedata
      });
}

**Comment by somayehghazvinian** [comment]
did u find the solution?

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you !
