### ISSUE TITLE
Gaussian - plotting a bell curve

### ISSUE THREAD

**Issue by Bear4** [c3js/c3#1170]
Is it possible plot such a chart in c3?
I trying set of x-axis for digits value, but I can't.
I know that x-axis for 'timeseries' and 'category' is possible to set, but I don't know it is possible to digits value.
Sorry at this message here but in google c3 groups my question is unanswered.

My data:
x-axis: [3.01,6.48,9.95, ...]
y-gaussian: [0.00076635186860469,0.0015737752818841,0.002992197165313, ...]

example chart generating in Excell
![gaussian](https://cloud.githubusercontent.com/assets/8928341/7696811/4dc9f170-fe01-11e4-8023-d49176eaa460.jpg)

**Comment by panthony** [comment]
Closing, this is not an issue and is inactive

**Comment by davidsonlima** [comment]
But is it possible or not?
