### ISSUE TITLE
Docs pointing to two different places

### ISSUE THREAD

**Issue by ryankicks** [c3js/c3#1171]
Love this library. Has saved me tons of time.

Just a quick note: the forum links go to different pages on these two URLs:

http://c3js.org/examples.html -> https://groups.google.com/forum/#!forum/c3js
http://c3js.org/samples/data_xformat.html -> https://github.com/masayuki0812/c3/issues?q=is%3Aopen

Weird.

https://groups.google.com/forum/#!topic/c3js/-540Md9cJME

**Comment by panthony** [comment]
Looks fixed (since `data_xformat.html` does not exists anymore)
