### ISSUE TITLE
Does C3 support extend your own shape or charts

### ISSUE THREAD

**Issue by candy20094369** [c3js/c3#1173]

**Comment by coderek** [comment]
Same question here.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
