### ISSUE TITLE
Change the color of lines according to x-value

### ISSUE THREAD

**Issue by mlapfr** [c3js/c3#1176]
I'm trying to change the color of lines in a line chart, according to x-value.
According to this sample on a barchart, http://c3js.org/samples/data_color.html
I do it : http://jsfiddle.net/h04d2Lb8/
==> only the color of points changes, not the color of lines :-(
Any ideas ? Many thanks

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!

**Comment by roxxid** [comment]
This is a bug as I am also facing the same issue. The bar charts can be given custom colors but in case of a line chart, only the points change colors. Any help is appreciated.
