### ISSUE TITLE
tooltip now showing [not a c3 issue]

### ISSUE THREAD

**Issue by luisrudge** [c3js/c3#1178]
Hi. I'm running [this exact example](http://c3js.org/samples/chart_area_stacked.html) inside our project and the tooltips are not showing up. I know it's not a C3 problem, because the demo works fine, but I want to know if you people can help me find why they aren't showing. Any gotchas you had along the way? THanks

**Comment by luisrudge** [comment]
hey guys, I know it's a long shot. but any toughts? :(

**Comment by mrkeyboard** [comment]
I had a similar issue when I generated the chart on an SVG element by mistake. Tooltip worked again when I changed it back to a Div

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
