### ISSUE TITLE
Hide Legend

### ISSUE THREAD

**Issue by bastiao** [c3js/c3#118]
For instance, if you have a bar chart with multiple values: data1, data2, data3. 

But you only show in the chart data1 and data2. The tooltip will show the data1, data2, and data3. It is ok. But in legend it does not make sense to appear.

**Comment by pkpatels** [comment]
Legends overlap on x axis ticks.
Any solution? 

<img width="1280" alt="screen shot 2016-05-17 at 12 54 57 pm" src="https://cloud.githubusercontent.com/assets/7530957/15314431/5e679332-1c2f-11e6-973a-d6a2e93c27e5.png">

**Comment by Soufraz** [comment]
Up

**Comment by raghav5253** [comment]
Hi @masayuki0812, I need a small help from your, pretty sure that you must be having solution for this one.

I want to disable(it should be visible but in disabled state) few legend elements from c3js chart on page load. Post load, user can enable it by clicking on those legend elements. Also, I want to enable those legend elements on the basis of a flag value which I can setup through a checkbox besides the graph.

$scope.cpuChartArea = {
            data: {
                x: 'x',
                columns: [
                    xLabels,
                    data1,
                    data2,
                    data3
                ],
                xFormat: '%m-%d-%Y %H:%M:%S',
                types: {
                    'data 1': 'area-spline',
                    'data 2': 'area-spline',
                    'data 3': 'area-spline',

                }
            },
            point: {
                show: false
            },
            axis: {
                y: {
                    tick: {
                        format: function (d) { return d + "%"; }
                    }
                },
                x: {
                    type: 'timeseries',
                    tick: {
                        //format: function (x) { return x.getFullYear(); }
                        format: '%H:%M' // format string is also available for timeseries data
                    }
                }
            },
            tooltip:{
                format:{
                    title:function (x) { return x.getDate() + "/" + x.getMonth() + "/" + x.getFullYear() + " " + x.getHours()+ ":" + x.getMinutes() },
                }
            }
        }
