### ISSUE TITLE
drill downs

### ISSUE THREAD

**Issue by terekete** [c3js/c3#1180]
How could one create a drill down, say from a bar chart to further details in the breakdown, example could be going from months to day to hours ect. ? Any suggestions would be appreciated.

**Comment by thelastelf** [comment]
onclick on bars + load corresponding data(monthly->daily->hourly)?

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
