### ISSUE TITLE
need the ability to set back ground color for sub chart or make it less transparent compared to main chart

### ISSUE THREAD

**Issue by smart987** [c3js/c3#1185]
When I am using sub chart, one problem I am facing with user experience is both Main chart and Sub chart are of same importance, I mean same color, etc Instead what I expect is the sub chart should be less transparent or should be provided an option to set back ground color for sub chart.   Is it possible, I don't see any option to set back ground color for the sub chart on documentation page. Any guidance please ...

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
