### ISSUE TITLE
How to fill 'Line chart' ?

### ISSUE THREAD

**Issue by nglasantha** [c3js/c3#1186]
Hi, I am very new to d3/c3,

I need to fill line chart. Chart is getting flat If I change 'line' to 'area' . This chartData json is having around 450 points. Please see my chart settings below

c3.generate({
      data: {
        json: chartData,
        keys: {
          x: 'dt',
          value: ['cls']
        },
        types: {
          cls: 'line',
          // 'line', 'spline', 'step', 'area', 'area-step' are also available to stack
        }, colors: {
          cls: '#1C693F'
        }

        /*
         columns: [
         ['data1', 300, 350, 300, 0, 0, 120],
         ],
         types: {
         data1: 'area',
         // 'line', 'spline', 'step', 'area', 'area-step' are also available to stack
         }*/
      },
      point: {
        show: false
      },
      size: {
        width: 185,
        height: 88
      },
      padding: {
        top: 5,
        right: 15,
        bottom: 1,
        left: 40,
      },
      axis: {
        x: {
          type: 'timeseries',
          localtime: false,
          show: true,
          fit: true,
          tick: {
            //format: '%m %d',
            format: '%H:%m',
            culling: {
              max: 5 // the number of tick texts will be adjusted to less than this value
            },
            count: 5
          },
          padding: {
            top: 0,
            bottom: 0,
            left: 0,
            right: 0
          }

        },
        y: {
          show: true,
          label: {
          },
          tick: {
            culling: {
              max: 3 // the number of tick texts will be adjusted to less than this value
            },
            count: 3,
            fit: true,
            format: function(val) {
              return VivaldiUtil.formatNumber(val, 0)
            }
          }
        }
      },
      legend: {
        show: false
      },
      tooltip: {
        show: false
      }
    })

**Comment by nglasantha** [comment]
found the solution,

area: {
  zerobased: false
}

**Comment by NetanelBasal** [comment]
Not working

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
