### ISSUE TITLE
Dynamically Set Y/Y2 Max

### ISSUE THREAD

**Issue by nathancole** [c3js/c3#119]
Is it currently possible to dynamically set the Max Y value after the chart has already been created?  I'm switching out one of the data series in my chart with data that should conform to a different range, but I want it to be a static range so that it always provides a consistent representation irrespective the subject.

**Comment by forteddyt** [comment]
Refer to #1866 if you're looking to change from a set y-max to c3-dynamic y-max (`undefined`).
