### ISSUE TITLE
How to set region's opacity?

### ISSUE THREAD

**Issue by thelastelf** [c3js/c3#1191]
There is a good example for region style: http://c3js.org/samples/style_region.html
But i tried to set opacity with opacity:0.5 and with fill-opacity:0.5 in my css but nothing changes.
I found in c3.js sources at 5072 line 
 .style("fill-opacity", function (d) { return isValue(d.opacity) ? d.opacity : 0.1; })
but seems it dont work because opacity still 0.1 by default

**Comment by ubermuda** [comment]
Hi @thelastelf, you can set the opacity of a region in its properties, like so:

```
{
    axis: 'x',
    start: 42,
    opacity: 0.5
}
```

**Comment by thelastelf** [comment]
Thanks @ubermuda ! Can i ask 1 more question?
in
'function (d)'
where is d value? So we need to pass d as argument but there is no d declaration. How it took its value?

**Comment by ubermuda** [comment]
From what I understand of this piece of code `d` is the region's properties you defined

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​

**Comment by nirsalon** [comment]
This should be part of the docs http://c3js.org/reference.html#regions
