### ISSUE TITLE
Axis ranges undefined when not explicitly set

### ISSUE THREAD

**Issue by olivierguerriat** [c3js/c3#1195]
The methods `.axis.range`, `.axis.min` and `.axis.max` (used without arguments, as getters) return undefined values when they are not explicitly set in C3's options or later via the API.

The behaviour I expected was to be able to retrieve the automatically computed range.

My use case was to sync the axis range between two charts.

**Comment by dazhbog** [comment]
Same issue here

**Comment by panthony** [comment]
closing in favor of #1122
