### ISSUE TITLE
0.4.11

### ISSUE THREAD

**Issue by masayuki0812** [c3js/c3#1199]
I released `0.4.11-rc1` for RC of v0.4.11.
https://github.com/masayuki0812/c3/releases/tag/0.4.11-rc1

I'll release `0.4.11` after we confirm it's production ready.

Please let me know if you have some trouble in this version. Thanks.

**Comment by archerchiu** [comment]
Hi,
After upgrade to this version, I found has double axis x rendered if axis rotated set true.
![c3-rotated](https://cloud.githubusercontent.com/assets/2604264/8049265/8fe27034-0e8f-11e5-953b-f70557c184b8.png)

**Comment by aendrew** [comment]
I've created a new milestone for 0.4.11 to help organise issues specific to that release.

Collaborators: Please attach any issues specific to 0.4.11 to that milestone.

I'm also considering creating a "blocker" label for issues that should be resolved prior releasing 0.4.11. Please let me know if you think this is a good idea. Thanks!

**Comment by shgattu** [comment]
What is the status of this issue?

**Comment by aendrew** [comment]
@shgattu See #1294, which is almost ready to be merged. 

This particular issue is about 0.4.11 specifically; mind directing discussion to #1292? Thanks!

**Comment by masayuki0812** [comment]
https://github.com/masayuki0812/c3/pull/1294 merged. Then, now it's ok.

**Comment by masayuki0812** [comment]
I released `0.4.11-rc2` https://github.com/masayuki0812/c3/releases/tag/0.4.11-rc2

**Comment by masayuki0812** [comment]
I released `0.4.11-rc3` https://github.com/masayuki0812/c3/releases/tag/0.4.11-rc3

**Comment by aendrew** [comment]
:tada: :+1: :shipit: Yay!

**Comment by raulgomis** [comment]
great work @masayuki0812!!

**Comment by masayuki0812** [comment]
`0.4.11-rc4` has been released. https://github.com/masayuki0812/c3/releases/tag/0.4.11-rc4

The issue for stacking has been fixed in this release. I think we can release `0.4.11` shortly.

**Comment by masayuki0812** [comment]
I created a release branch https://github.com/c3js/c3/pull/1675

**Comment by masayuki0812** [comment]
Finally released. https://github.com/c3js/c3/releases/tag/0.4.11
