### ISSUE TITLE
Retrieving the original value passed to a pie chart

### ISSUE THREAD

**Issue by jasonlally** [c3js/c3#1212]
Is there a way to access the original value simply that was passed to the pie chart? chart.data.values("column_name") returns the derived ratio but not the original value. I'd like to access this simply via the charting API if possible to avoid jumping back to the input and deriving it there.

**Comment by jasonlally** [comment]
My mistake, let me reverse that. How do I grab the ratio via the API? It appears I was grabbing the value! But silly me, the values happened to be 34 and 66, which are equivalent to the ratio in the case I was testing.

Anyway, is there a way to get the ratio that's displayed on the pie chart via an api call?

**Comment by souzadevinicius** [comment]
+1

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
