### ISSUE TITLE
Nested stacked bar chart

### ISSUE THREAD

**Issue by zukilover** [c3js/c3#1213]
Hi, 

Thanks for this wonderful library. 

I'm currently having an issue with rendering a nested stacked bar chart (pic), can you show me how to do this in C3? 

http://si.uploads.im/tl95D.png

**Comment by missingdays** [comment]
Your link is broken.

**Comment by missingdays** [comment]
Anyway, this isn't a bug or anything. For help you can always go to https://groups.google.com/forum/#!forum/c3js or stackoverflow.
So, I think this should be closed.
