### ISSUE TITLE
Enhance to allow binding the legend to an external element

### ISSUE THREAD

**Issue by jmkeppler** [c3js/c3#1216]
Can this be enhanced to allow the legend to be built in an element passed in via configuration (similar to the bindto property for the graph)? I'm envisioning this would then not have to shrink the width of the graph to show the legend, and would allow for the legend to be placed anywhere by just changing css, etc.  Also, can there be a tooltip for the legend item in this case?

**Comment by katalin2003** [comment]
:thumbsup:

**Comment by panthony** [comment]
Won't be fixed, closing.

If you need your legend to be elsewhere you can do your own:

http://c3js.org/samples/legend_custom.html
