### ISSUE TITLE
How to load dashed line regions

### ISSUE THREAD

**Issue by dowling-eoin** [c3js/c3#1234]
Hi,

Is it possible to load dashed line chart regions like: 

chart.load({
    columns:[
        ['data2', 10, 30, 20, 50, 40, 60, 50]
    ],
    regions: {
         'data2': [{'start':3, 'style':'dashed'}]
    }
    });

It doesn't seam to work. I don't want to use the ad regions api - I need dashed lines.

Thank you so much!

**Comment by mrowa** [comment]
There's nothing in the docs for `.load` that it understands `regions` property. You can set regions while generating the chart.

Other possibility is to use CSS, as in https://stackoverflow.com/questions/29150816/c3-js-making-line-appear-dashed - if you want all the lines to appear dashed, add style

`.c3-line{
  stroke-dasharray: 5,5;
}`

You can also add styles per line - using selector `.c3-target-data2`

**Comment by pimlinders** [comment]
as @mrowa suggested a work around is to inject styles to target the lines that need to be dashed. Below is an example of what i'm doing. Note this solution is using jquery.

```
// populate dashed lines array
dashedLines = [{
  key: key,
  dashArray: portfolio.lineDash
}]

// function to inject styles into the header
injectDashStyles = function(dashedLines) {
  if (!this.styleContainer) {
    this.styleContainer = $('<style></style>');
    $('html > head').append(this.styleContainer);
  }
  // ensure style container is empty
  this.styleContainer.empty();
  if (dashed_lines.length) {
    styles = '';
    for (i = 0, len = dashedLines.length; i < len; i+=1) {
      line = dashed_lines[i];
      styles += '.c3-target-' + line.key + ' { stroke-dasharray: 3,6 };';
    }
    return this.styleContainer.append(styles);
  }
};
```

**Comment by michaelrodov** [comment]
You can do it using CSS
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you
