### ISSUE TITLE
Use X axis scale to add elements post creation

### ISSUE THREAD

**Issue by StephaniesHusband** [c3js/c3#1238]
I have figured out how to add new SVG elements post-creation (aka after c3.generate). But I know need to add a particular element at a specific point on the X axis of a subchart AND a different element at a specific point on the X axis of the main chart.  Is there any way to access the scale function so that I can draw at the correct location with appropriate x coordinate (which BTW is a time-series).

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
