### ISSUE TITLE
Javascript error in IE9

### ISSUE THREAD

**Issue by kishoredemica** [c3js/c3#1239]
We receive a javascript error in IE9 when debugging is turned on and the chart does not render. It renders fine in IE11 however the y-axis ticks are cut-off and only 00 is displayed. 

The javascript error occurs in c3.min.js for the statement: 
e.convertJsonToData(JSON.parse(b.response),c)

b.response is undefined. I have changed b.response to b.responseText and the chart now renders correctly on IE9 and the y-axis is displayed correctly. I have tested the fix in IE9, IE11 and Chrome and in all cases the graph and axis render correctly.

**Comment by panthony** [comment]
There was no follow up on this issue after 3 years. Can't test on IE9. Let's close this.

You can open a new issue if this is still relevant.
