### ISSUE TITLE
Allow C3 to render a timeseries axis without scaling it to the given date range

### ISSUE THREAD

**Issue by tclavijod** [c3js/c3#1260]
Hi, is there a way to format the X axis of a timeseries so that it doesn't show the dates that don't have Y values? As if those dates "didn't exist"?.. Check out this fiddle: https://jsfiddle.net/j77dysbv/3/

I would like to avoid the long line shown on the first chart and have a chart similar to the second one (but using timeseries because I need to work with formatting, tick values, etc.)

Thanks and btw great work on the library!

**Comment by zilev** [comment]
I have the same problem :cry:  , is there a way to fix it????

**Comment by Gary-Ascuy** [comment]
+1 yep, I really need this feature too, I think is a very good idea, thanks in advance Mr C3 developers (y)

**Comment by roenfa** [comment]
yes, this problem, not let me work.. Is there a good idea to change it?? please, could you fix it??

**Comment by aendrew** [comment]
Does passing `null` help at all?

**Comment by tclavijod** [comment]
Ohh sorry for that , this one is working! :smile: http://jsfiddle.net/j77dysbv/3/
And no, I tried setting null dates and/or null values but that just doesn't draw the point, the gap or "long line" continues

**Comment by tclavijod** [comment]
@aendrew any thoughts so far?... I could also use any work around as well :)

**Comment by aendrew** [comment]
@tclavijod Ah, apologies, I totally misunderstood the question. Thanks for the updated fiddle, I get it now.

As far as I know, the only way to get what you're wanting is via a categorical axis. A timeseries axis will always scale to reflect distance between dates. Try setting `axis.x.tick.fit` to false ([or play with this example](http://c3js.org/samples/axes_x_tick_fit.html)) to see why it's rendering like that.

That said, using a timeseries doesn't really do anything beyond scaling the axis as per the above; you can probably get pretty close to what you're wanting with a categorical or indexed (default) axis. I kind of avoid timeseries axes where possible, TBH; it's pretty rare that I need that axis scaled in that way and can't get to what I want using a different type of scale.

**Comment by tclavijod** [comment]
Thanks and don't worry!.. Based on what you say, it does make more sense to have it as a categorical axis, but while playing around, I stumbled upon an interesting issue, it seems that formatting for category axis [was available](https://github.com/masayuki0812/c3/issues/605#issuecomment-59603861) in earlier versions, however a user commented that he couldn't do it (I think [this one](https://github.com/masayuki0812/c3/issues/1063) is related as well)

Maybe formatting was lost in some update or something like that? formatting for categories could be very useful and it could solve this problems as well, what do you think?

**Comment by say8425** [comment]
`categorial` axis is useful in this situation. But if you use load to show new data. it's not proper. When axis type is `timeseries`, then data is loaded with scroll animation. But `category` did not. It just change axis so user can't know time is changed. Of course. alternative answer is [flow](http://c3js.org/samples/api_flow.html) But flow seems have memory issue.

**Comment by felipyamorim** [comment]
You can use the propety "centered", like this [jsfiddle](https://jsfiddle.net/j77dysbv/8/).

**Comment by abhinav-axisrooms** [comment]
how to show only part of date in category axis graph like i want to show axis as DD-MM

**Comment by abhi1510** [comment]
How do we format date in category axis graph ?
I needed my axis to show only day and month part.

**Comment by panthony** [comment]
Reason why it works the way it is was explained, for further questions please use the Google Group at https://groups.google.com/forum/#!forum/c3js.
