### ISSUE TITLE
multiple lines using json

### ISSUE THREAD

**Issue by JosephOR** [c3js/c3#1265]
Hey, cool library by the way!

I am using c3.js to draw a line chart using json data from an api. so once i retrieve the data from the api I loop over it and arrange it to the required format for the chart. one line works perfect, but what I want to do is make another api call for another data set, to compare them, but I cant create another line for the second data. I know it can be done using the c3 column layout, but the json format works perfectly as I am using the 'value' to change what is shown.

data: {
    json: [
      {name: 'www.site1.com', upload: 200, download: 200, total: 400},
      {name: 'www.site1.com', upload: 100, download: 300, total: 400},
      {name: 'www.site1.com', upload: 300, download: 200, total: 500},
      {name: 'www.site1.com', upload: 400, download: 100, total: 500},
    ],
    keys: {

```
  value: ['upload'],
}
```

above is the a sample of what the standard is, which will draw a line for upload. what I want to do is something like this:

data: {
    json: [
      {name: 'www.site1.com', upload: 200, download: 200, total: 400},
      {name: 'www.site1.com', upload: 100, download: 300, total: 400},
      {name: 'www.site1.com', upload: 300, download: 200, total: 500},
      {name: 'www.site1.com', upload: 400, download: 100, total: 500},
      {name: 'www.site2.com', upload: 200, download: 200, total: 400},
      {name: 'www.site2.com', upload: 100, download: 300, total: 400},
      {name: 'www.site2.com', upload: 300, download: 200, total: 500},
      {name: 'www.site2.com', upload: 400, download: 100, total: 500},
    ],
    keys: {

```
  value: ['upload'],
}
```

so What im tryin to do is draw a line for www.site1.com, and another line for www.site2.com.

I am really trying to avoid converting it to suit the column layout. Is this possible?. 
cheers, joey

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
