### ISSUE TITLE
Change culling after zooming

### ISSUE THREAD

**Issue by revati** [c3js/c3#1280]
Hello, i have question, is it possible to change **axis.x.tick.culling** value after user changes zoom by selecting some region in a sub chart?

- It probably shouldn't be to hard access **axis.x.tick.culling** value, but will it take new value to rerender x axis ticks?
- How can i get zoomed range that is used (how many values are shown). By browsing source it seems that it is called **domain**.

**Comment by nitin0708** [comment]
I have also stuck from this.

**Comment by catmeme** [comment]
+1 Would love a solution to this.

**Comment by anudeepshetty17** [comment]
I also waiting for the solution for this can somebody tell me if this got resolved lately?

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​

**Comment by catmeme** [comment]
@michaelrodov I understand the desire to clear out the issue queue but this is borderline a feature request.

I interpreted the issue to be requesting the c3 options or API support configuring tick culling values depending on zoom.
