### ISSUE TITLE
Common Legend for two or more charts on Same Page

### ISSUE THREAD

**Issue by 007dpk** [c3js/c3#1283]
I have multiple charts on the same page. Which have their corresponding legends. I want to club and make a common legend for all the charts, as the legends are common for all the charts. Also, when i click on a legend particular legend should be toggled in all the charts.

Also it will be helpful if you can let me know how we can refer a chart when we have multiple charts on the same page.

Please let me know how this can be achieved.

Thanks in advance.

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
