### ISSUE TITLE
In group bar chart, how can I change location of columns

### ISSUE THREAD

**Issue by say8425** [c3js/c3#1284]
![2015-07-23 4 46 02](https://cloud.githubusercontent.com/assets/3258867/8845463/53d6aef0-315a-11e5-9708-5ab55a2163a8.png)

In grouped bar chart, I found smaller column locate to bottom. But I want to locate it to the top. In API document, I can't find any option. Is is possible?

**Comment by say8425** [comment]
I'm so sorry. I can find option. [Please read it](http://stackoverflow.com/questions/26829384/c3js-bar-chart-with-specific-order) and use `order` option. Thanks.

**Comment by say8425** [comment]
And I think `groups` option may be has a bug. Sometime smaller columns locate to top.

**Comment by michaelrodov** [comment]
It's quite possible that could be a bug, but it's really hard to verify it without more information. 

We get a lot of reports and the more info you give us, the more likely we'll be able to address it in a timely fashion.

Please [read the contributing guidelines](https://github.com/masayuki0812/c3/blob/master/CONTRIBUTING.md), then add the following information to your issue:

-  Operating system and web browser (with version)
-  What version of the library
-  If you were doing anything unusual, like using C3 in conjunction with a particular library or framework
-  Ideally, a [JSFiddle](https://jsfiddle.net/) example depicting the specific problem really helps us out. 
	* [Use this JSFiddle template](https://jsfiddle.net/aendrew/L4ocdkcq/)


Thank you for your cooperation — we rely on users like you to help make C3 the best charting library it can be!

**Comment by say8425** [comment]
Hello. I posted this issue last year. 
After that time, I found this issue was already posted.
So I fixed and posted pull request https://github.com/c3js/c3/pull/1543. 
Maybe you can find more information in pull request.

Thanks.
