### ISSUE TITLE
axis x disappears when toggling chart view

### ISSUE THREAD

**Issue by hitigon** [c3js/c3#1287]
I have a chart inside of a parent DIV, and the DIV is controlled by a button for showing/hiding the chart view. Since the chart is dynamic generated with ajax calls, if the parent element is hidden (display: none), the width of the chart could be wrong. Setting visibility on the parent element with hidden attribute (instead of display to be none) looks like is a solution. But when I toggled again (hide and then show), the axis x disappeared.

I tested under 0.4.10 and 0.4.11-RC, both have the same problem, the difference is when i reset the .c3-axis-x to visibility: visible. The axis shows again. I am using it as a temporary solution

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
