### ISSUE TITLE
Can I change the dots animation when I draw dynamic scatter plot?

### ISSUE THREAD

**Issue by hijiangtao** [c3js/c3#1288]
I use setInterval() function to generate dynamic data for scatter plot chart and I set animation of the chart to be 'true'. but I found a problem in the dots refreshing animation styles. Once I use data.push() and data.shift() function in refreshing data (which means the value of dots in the scatter plot chart changed), the default animation styles go in this way: all the dots in one x-axis value animates themselves (these dots goes up and down and then to the end y-axis position).

I am wondering if I can adjust the animation style, and let the dots moving like left and right moving, so as let the dots changing looks like shifting from right to left, called panning effect (timeseries river? i don't know how to describe it exactly)? 

Any suggestions about it? Thanks a lot!

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
