### ISSUE TITLE
How can i bind an json data with a key and Name for display

### ISSUE THREAD

**Issue by kirangsa** [c3js/c3#1293]
Hi there,

I have a situation to bind a json data with a key to plot a graph. But graph is plotting correctly but the name of the data is showing the same key. i need to avoid it .

How can i supply a name for my data. I have tried as follows but its seems not working.
Can any guys help one this.

 data: {
                        //                        columns: [chartData],
                        json: data,
                        keys: {
                            value: [key]
                        },
                        type: chartType,
                        labels: true,  
                        selection: {
                            enabled: false
                        },
                        names: {
                            data1: 'Some Name'  
                        }
                    }

Thanks in Advance :)
Kiran Gopal

**Comment by KurtRMueller** [comment]
According to this the [Using the Issue Queue](https://github.com/masayuki0812/c3#using-the-issue-queue) section in the repo's readme.md, you should direct general support inquiries to their Google Groups forum.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
