### ISSUE TITLE
Bars in bar chart sometimes placed to the right of the main bar

### ISSUE THREAD

**Issue by lennartkramer1988** [c3js/c3#1297]
For my bar chart there is sometimes a glitch that places the bars to the right of the main bar. See screenshots below. Not sure when this occurs and when it doesn't, seems to be with larger amounts of data only. Since the library sets the DOM elements at an exact coordinate I'm not sure why this is happening or how to fix it.

![chart bug](https://cloud.githubusercontent.com/assets/11796532/8955321/d995ad30-35eb-11e5-9f0e-8118cb9aa269.png)

![chart bug 2](https://cloud.githubusercontent.com/assets/11796532/8955316/d44b00c8-35eb-11e5-9837-9f4aff7b8297.png)

**Comment by panthony** [comment]
Hi,

Could you provide a JSFiddle, codePen or Plunkr highlighting the issue?

It makes reproduction much easier for everyone.

Thank you!

**Comment by panthony** [comment]
No response
