### ISSUE TITLE
Pie and donut charts are centered even when the legend is on the right

### ISSUE THREAD

**Issue by webmaven** [c3js/c3#130]
In a limited space, pie and donut charts are not sized to make room for the legend on the right, and are still centered. This causes the legend to be cut off or hidden:

![chart_right_legend](https://cloud.githubusercontent.com/assets/438502/2635495/2e74f6a0-be86-11e3-8319-4982bdab8318.png)

 In this example, the chart is inside a Bootstrap panel-body.

**Comment by craiggeil** [comment]
This still isn't fixed. There should be a property to allow you to align the chart, left, right or center. Right now it's stuck on center and I have to fix the container div and adjust the div. It would be simple enough to let someone pick how they want their chart aligned.
