### ISSUE TITLE
Error: Parsing Date object

### ISSUE THREAD

**Issue by arundanegoudar** [c3js/c3#1301]
Response from the server:

{"x":[["2015-07-01"],["2015-07-02"],["2015-07-03"],["2015-07-06"],["2015-07-07"],["2015-07-08"],["2015-07-09"
],["2015-07-10"],["2015-07-11"],["2015-07-13"],["2015-07-14"],["2015-07-15"],["2015-07-16"],["2015-07-17"
],["2015-07-18"],["2015-07-20"],["2015-07-21"],["2015-07-22"],["2015-07-23"],["2015-07-24"],["2015-07-25"
],["2015-07-27"],["2015-07-28"],["2015-07-29"],["2015-07-30"],["2015-07-31"]],"data1":[["20.64"],["20
.35"],["34.1"],["8.19"],["22.19"],["12.77"],["12.81"],["27.22"],["19.87"],["16.03"],["11.24"],["20.39"
],["27.45"],["23.36"],["9.19"],["14.01"],["15.74"],["26.36"],["13.88"],["15.87"],["11.14"],["12.42"]
,["9.19"],["9.83"],["13.59"],["0"]]}

Error:
Failed to parse x '2015-07-01' to Date object

for all date obejcts

**Comment by bryanph** [comment]
The following code probably causes this:
The data object is converted to an int, which only works if the initial date object was created with a timestamp integer
    
    c3_chart_internal_fn.parseDate = function (date) {
        var $$ = this, parsedDate;
        if (date instanceof Date) {
            parsedDate = date;
        } else if (typeof date === 'string') {
            parsedDate = $$.dataTimeFormat($$.config.data_xFormat).parse(date);
        } else if (typeof date === 'number' || !isNaN(date)) {
            parsedDate = new Date(+date);
        }
        if (!parsedDate || isNaN(+parsedDate)) {
            window.console.error("Failed to parse x '" + date + "' to Date object");
        }
        return parsedDate;
    };

**Comment by panthony** [comment]
The parseDate method was updated since this issue was created.

Please feel free to re-open if you still reproduce the issue.
