### ISSUE TITLE
Unlike D3, Cannot achieve different kinds of transitions through C3

### ISSUE THREAD

**Issue by parunachalam** [c3js/c3#1312]
C3 doesn't provide a way to transitioning the chart by various attributes or elements like one can do with D3.
   It provides a static way of transitioning through "opacity" property using only of these feature user can't see more differences in data flow & changes in UI.
   The problem with these feature is that the developer can't override it through external code.
   Please correct me if I does any mistakes in above statements

**Comment by panthony** [comment]
No you cannot configure how things are transitioning.

Closing as inactive, if such feature is required a new issue with a detailed use case is necessary.
