### ISSUE TITLE
How to show only y2 labels value?

### ISSUE THREAD

**Issue by dew063** [c3js/c3#1319]
i have 'data1' in line chart y axis and 'data2' in bar chart 
but
data: {
       ..
        labels: true
    }

it show both labels .
how to show only 'data2' labels ?
thank you

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
