### ISSUE TITLE
X-label rotation - negative values not adjusting x-axis height dynamically

### ISSUE THREAD

**Issue by mindontheblink** [c3js/c3#1336]
When I do not specify a static x-axis label height, I am able to rotate the X-axis labels using positive values, and the x-axis height updates accordingly based on the labels' size.  

Example: http://jsfiddle.net/4cbhksuq/2/

However, the x-axis height does not seem to update dynamically for negative values.  

Example: http://jsfiddle.net/y152jrrk/2/

Notice the x-axis height difference between the two examples.  

It seems like the only way to enforce visible x-axis labels rotated negatively is to enforce a static x-axis height -- which is not a viable option for my application since the X-axis labels are determined by user input and can vary greatly in string length.

**Comment by GoekhanOezen** [comment]
hi look at #1511

**Comment by alexbain** [comment]
I also opened a PR that makes the fix proposed in #1511  (https://github.com/c3js/c3/pull/1766)

**Comment by panthony** [comment]
Closing in favor of #1511
