### ISSUE TITLE
Gauge in stacked mode

### ISSUE THREAD

**Issue by eregnier** [c3js/c3#1340]
The gauge chart does not seems to support fully stacked display as in this example
http://jsfiddle.net/bt56r29q/323/
series can only overlaps

**Comment by eregnier** [comment]
it seems solved in new versions : http://jsfiddle.net/bt56r29q/683/ :+1:

**Comment by srinivasyl** [comment]
Can we provide different max values for each data as mentioned in  jsfiddle example??? 
like s1 data with max value of 100 and s2 data with max of 200
