### ISSUE TITLE
Gauge max value not formatable

### ISSUE THREAD

**Issue by eregnier** [c3js/c3#1341]
The gauge chart does not well support formating for the max value. When I set a string in the max value, it is displayed correctly, but it can't be understood by the chart.
this feature could be usefull for human readable values.
https://jsfiddle.net/bt56r29q/323/

**Comment by EspadaV8** [comment]
Your link is broken, but I think you meant something like this - http://jsfiddle.net/bt56r29q/330/

I've just submitted a pull request for this https://github.com/masayuki0812/c3/pull/1354 if you'd like to test it out (if it is what you're after).

**Comment by eregnier** [comment]
Thank you EspadaV8, I'll try it soon.

**Comment by nym** [comment]
Also ran into this issue, except I need to format as $. What I expect to happen is gauge.label.format to be applied to gMin/gMax in https://github.com/masayuki0812/c3/blob/afa5f52ac759e4a1f3d118784bf25a22ba1d2621/src/arc.js#L399

gauge: {
        label: {
            format: function(value, ratio) {
                return "$" + value;
            },
            show: true // to turn off the min/max labels.
        },
...

**Comment by EspadaV8** [comment]
@eregnier sorry for the late reply. Probably the quickest way to test it would be to do the following...

```
git clone git@github.com:EspadaV8/c3.git
cd c3
git checkout feature/gauge-min-max-formater
npm install
grunt
```

That should clone my copy, switch to the branch with the changes and then build `c3.js` and `c3.min.js` in the root folder with my changes included.

Another option would be to just copy my few changes into your own `c3.js` file. The locations will be different from the pull request but they should be easily findable.

**Comment by eregnier** [comment]
ok, i will test. I just did not found the how-to about c3 but I am quite comfortable with node environment.

**Comment by eregnier** [comment]
This is not good :/ http://pastebin.com/WCLWwM0E

**Comment by eregnier** [comment]
I will test by modifying the c3js file directly

**Comment by michaelrodov** [comment]
Please let me know if this can be closed

**Comment by NullVoxPopuli** [comment]
I believe the problem still exists.

**Comment by eregnier** [comment]
I am not sure to understane today. I repaired my example, and it seems to work
https://jsfiddle.net/bt56r29q/693/
but the result display is so-so (I think I wanted % symbol displayed on each side of the gauche on the right of the 0-100 min max values.

**Comment by EspadaV8** [comment]
@eregnier like this? https://jsfiddle.net/bt56r29q/694/

**Comment by EspadaV8** [comment]
No idea what happened to that version, check this instead please - https://jsfiddle.net/bt56r29q/696/

**Comment by EspadaV8** [comment]
The extra bit of code you're after is

```js
extents: function(value, isMax) {
    return value + '%'
}
```

**Comment by eregnier** [comment]
Well, I think I just needed the extents method override for what I wanted, I guess.
The final of what I wanted may be this https://jsfiddle.net/bt56r29q/698/.
This time it is clear that the issue is solved and C3 is still awesome !
thank you @EspadaV8 !

**Comment by bj00rn** [comment]
I can confirm this is working. 

However, is usage of gauge.label.extents documented somewhere?

**Comment by bj00rn** [comment]
#2550
