### ISSUE TITLE
Grouping got broken between 0.4.11-rc2 and 0.4.11-rc3

### ISSUE THREAD

**Issue by ergo** [c3js/c3#1342]
Hi,

I've updated to 0.4.11-rc3 and noticed that my charts are broken.
Basicly it looks like Y axis is actually updated correctly but the series are not grouped at all.

0.4.11-rc2
![screenshot - 21 08 2015 - 10 54 40 0.4.11-rc2](https://cloud.githubusercontent.com/assets/33021/9404894/6a463cf0-47f3-11e5-9ce5-466d35c62ba5.png)

0.4.11-rc3
![screenshot - 21 08 2015 - 10 56 03 0.4.11-rc3](https://cloud.githubusercontent.com/assets/33021/9404896/75036866-47f3-11e5-84af-18d21820a4c0.png)

**Comment by masayuki0812** [comment]
Sorry this is a bug and I think it's has been fixed now.
