### ISSUE TITLE
Gap between chart and legend

### ISSUE THREAD

**Issue by marekeiba** [c3js/c3#1348]
Hi, this issue has been appearing on smaller resolutions...
![chart](https://cloud.githubusercontent.com/assets/1807616/9436323/a0af8faa-4a4e-11e5-8b87-140e5153acef.png)

legend: {
  position: $(window).width() > 768 ? 'right' : 'bottom'
}
(or http://pastebin.com/0pVqtcR6)

I can't figure out what's causing it... Is there anything I can do about it? position: inset is not really helpful because it sometimes covers bits of the chart... Thanks!

**Comment by panthony** [comment]
You configured a fixed height of `130x` for your xAxis ticks. That's the space you are seeing.
