### ISSUE TITLE
Add ability to hide X-Axis

### ISSUE THREAD

**Issue by kjavia** [c3js/c3#135]
We currently have the ability to hide Y-Axis but we need to hide X-Axis too.

 (case-in-point: sparkline charts).

**Comment by luisrudge** [comment]
@kjavia can you share your sparkline code? :)

**Comment by kjavia** [comment]
```javascript
var chart = c3.generate({
    data: {
        columns: [
            ['data1', 30, 200, 100, 400, 150, 250],
            ['data2', 50, 20, 10, 40, 15, 25]
        ]
    },
        axis: {
            x: {show:false},
            y: {show:false}
        }
});
```

**Comment by luisrudge** [comment]
Duh. Sorry! I thought it was something more specific. But I guess it's just a matter of making it really small. Thanks!

**Comment by DogaIster** [comment]
axis: {show:false} works too

**Comment by stl-shabnamshariaty** [comment]
@masayuki0812: Is there any way to keep the labels when removing the axis? Thanks

**Comment by sitchie** [comment]
Is there any way, we can hide only axis lines but not labels?
