### ISSUE TITLE
Any solution for text rotation on axis if values of texts is bigger (e.g date, name of month).

### ISSUE THREAD

**Issue by kiran3490** [c3js/c3#1353]
![issue](https://cloud.githubusercontent.com/assets/6681850/9492353/6f1e194e-4c14-11e5-86ce-878f7bffdfc7.png)

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
