### ISSUE TITLE
X axis tick culling on 0.1.29

### ISSUE THREAD

**Issue by panubear** [c3js/c3#136]
Hi Masayuki,

I have some problem with x axis tick culling on your latest version. Previously, culling make equal tick space but the new version is not. Part of my code related to culling had shown below. Do you have any idea what I need to made change to get the same result when I had run with previous version?
Thanks,
Panuwat

---

x: {
        type : 'timeseries',
        tick : {
            format : "%Y",
            culling: {max: 6    }
},

![1](https://cloud.githubusercontent.com/assets/6915603/2640370/42bcd8da-bee5-11e3-8e2a-61ed53886deb.jpg)

![2](https://cloud.githubusercontent.com/assets/6915603/2640371/495faef6-bee5-11e3-858d-af5a337d06d5.jpg)

**Comment by aendrew** [comment]
@jmnunezizu Mind creating a Plunker demonstrating the issue? It's a lot easier to help with one. :smile: 

Alternately, this might be a good question for the [Google Group](https://groups.google.com/forum/#!forum/c3js), where it will probably get more attention than a closed issue. :+1: Thanks!
