### ISSUE TITLE
X or Y-axis logscale

### ISSUE THREAD

**Issue by Chris00** [c3js/c3#1360]
Having the possibility to represent data using log-scale (with the ticks and tooltip showing the data values — not its log₁₀) would be nice.

**Comment by panthony** [comment]
Tried to tackle this issue (#2100). This is not 100% perfect but it may be sufficient for a lot of cases.

**Comment by Chris00** [comment]
Thanks for your efforts.

**Comment by jacobq** [comment]
Is any further work on this happening / likely to happen? Robust support for logarithmic scaling is required for the application I'm working on, and I'm having a surprisingly difficult time finding a JS plot library that supports it.
