### ISSUE TITLE
Event binding for onresize/onresized laggy, even without callback

### ISSUE THREAD

**Issue by AncientBob** [c3js/c3#1380]
So I've jury-rigged a fix for this that'll get me by, but figured I'd leave my 2¢ here in case it helps anybody else. This issue applies to c3 v. 0.4.10.

I have a page rendering multiple charts, and wanted their heights to resize appropriately when the window is resized. No problem it seemed - c3 docs [describe just how to set these callbacks](http://c3js.org/reference.html#onresize). So I tried something like this:
```
onresized: function () {
    var newWidth = $("#" + containerID).width();
    var newHeight = (window.innerHeight - 80) / 2;
    this.api.resize({
        width: newWidth,
        height: newHeight
    });
}
```
Turns out, this was so crazy laggy that not only did it take several seconds for the callback to execute after window resize (à la #939) but it caused IE and Firefox to stutter and freeze during the resize.

Then I discovered the browser lag persisted even after removing the "onresized" option. It wasn't as bad, but still obvious and only on pages with c3 charts. So the issue isn't just with the execution of the callback, but the event binding itself.

My "solution" was to comment out the "Bind resize event" section in c3.js, which solved the lag immediately. Then I implemented a chart factory to create/loop through the charts, and added my own event listener for window resize. It ended up looking something like this:
```
$(window).resize(function () {
    waitForFinalEvent(function () {
        this.ChartFactory.each(function () {
            var newWidth = $("#" + containerID).width();
            var newHeight = (window.innerHeight - 80) / 2;
            this.resize({
                width: newWidth ,
                height: newHeight 
            });
        });
    }, 500, "resize");
});
```
...where "WaitForFinalEvent" is a debouncing function from [user brahn of StackOverflow](http://stackoverflow.com/a/4541963). I imagine this would work fine with an array instead of a factory - in my case the factory served other purposes.

I never did figure out what was up with c3's resize event binding, unfortunately.

**Comment by michaelrodov** [comment]
thanks for the comment
closing
