### ISSUE TITLE
Focus on specific data point

### ISSUE THREAD

**Issue by strig** [c3js/c3#1389]
Is there any way to do `chart.focus('data1', [1, 2, 3])` or something similar in order to trigger focus on the bars with index 1, 2, 3? I wish to highlight certain bars programmatically by hovering on data points in a different graph.

**Comment by shivguru** [comment]
Even I am looking for a solution for this problem. Please Help!

**Comment by DemersM** [comment]
Anyone have a solution for this?

**Comment by DemersM** [comment]
This post might be helpful for this issue: http://stackoverflow.com/questions/35008483/how-to-focus-the-clicked-bar-in-c3-js-bar-graph

**Comment by nbdavies** [comment]
That's a pretty rough workaround. Or there's the option of defining every data point as its own column. Yuck.

Another option might be to coopt the select/unselect API, assuming you aren't already using that for something else, since select/unselect can take indices. And then style the selected state to look more like the hover state.

But I agree, it would be nice if focus/unfocus could take indices as well.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!

**Comment by nbdavies** [comment]
@panthony Sorry for broaching the topic of workarounds, my intent was just to emphasize how inconvenient the issue is.

I'll keep an eye out for whether you reopen this issue, and otherwise I'll open a new one, because this is still an issue. 

Thanks for helping maintain the C3 issue list!

**Comment by panthony** [comment]
@nbdavies Al'right! If you open a new issue, don't forget the fiddle/codepen ;)

I try to tidy up the overwhelming list of issues the best I can, in this case I saw `How to`, `I wish` and `workaround`.
