### ISSUE TITLE
Labels for Data Sets

### ISSUE THREAD

**Issue by osterhase90** [c3js/c3#1398]
Hi,
Here is the chart I have: https://jsfiddle.net/hqjz321d/

In my chart, the values are given with arrays. My chart has a time span of about 2 years. In my example are 3 data points, but usually I have much more! The performance is good, but for every data point I need a label as you can see in the example.

1.) As JSON object, as I can do it for the data values: http://c3js.org/samples/data_json.html

or

with an additional data serie, like HiddenLabel in my example. But I need to rotate the labels (90°) and make the bar for the label invisible (the same colour as the background has or bar width = 0 or value = 0 and set the heigh of the label)

Is this possible at the moment?

2.) Subchart:
- the colour of HiddenLabel in the subchart is not changed to black (maybe a bug?)

I would like to zoom the area I want to see, hide the subchart, and then make a screenshot of the zoomed area without the subchart. Is that possible? This is not so important for me as point 1.

**Comment by osterhase90** [comment]
Any idea here? =)

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
