### ISSUE TITLE
zoomed c3 graph

### ISSUE THREAD

**Issue by nitin0708** [c3js/c3#1402]
Hi
I have too much data in graph so i mentioned the culling 100.Now i zoomed the graph so how to show the x-axis  label for particular area which i zoomed.Because some label was restricted because of first culling value.

Thanks

Nitin

**Comment by nitin0708** [comment]
Hi

Can we redraw chart with new culling value?

Thanks

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
