### ISSUE TITLE
Why not use x ranges for c3 dependency?

### ISSUE THREAD

**Issue by neothemachine** [c3js/c3#1406]
I find it strange that c3 currently requires d3<=3.5.0. Why should new patch versions like 3.5.1 not work? For me it would make more sense to specify the version in package.json as `<=3.5.x`. This would make it easier to adopt certain fixes without waiting for a new c3 version. I use JSPM for dependency management.

**Comment by Stargator** [comment]
Better clarification on why anything < 3.5.0 doesn't work would be very helpful. Some of the fixes in 3.5.x releases would be useful.

Is there an API change after 3.5.0? There doesn't seem to be any documentation (which i can find) which states that.

**Comment by missingdays** [comment]
Is this issue still relevant?

**Comment by neothemachine** [comment]
No, that's fine now, thanks.
