### ISSUE TITLE
Chart API: load and unload

### ISSUE THREAD

**Issue by ramdog** [c3js/c3#1407]
As I understand it, when I call `.load`,

> if data that has the same target id is given, the chart will be updated. Otherwise, new target will be added.

This is quite useful.  If I give it the data `unload: true`, it will unload everything first.  Alternatively, I can unload specific data by target id like `unload: ['foo', 'bar']`.

However, It would be nice if there was an option to call load with a new dataset and have it do all 3 things for you:
1.  Update existing target ids
2.  Add new ones
3.  Drop any that are not in the newly "loaded" data

I know that today I can simply call it with `unload: true`, and while this would effectively work, I would lose all the pretty animations I get from `c3` for the new, updated, and removed items.  Is this possible to do what I'm trying to achieve without having to figure out specifically which items were removed?

**Comment by aendrew** [comment]
This seems like a pretty reasonable request. Maybe something like `chart.update` or something?

**Comment by passkey1510** [comment]
:+1:
