### ISSUE TITLE
How to overlap two bars 

### ISSUE THREAD

**Issue by Ravikumar087** [c3js/c3#1409]
Hi i want to show two bars in a same position, with overlapped with different size, and i ll give lighter color to the top one so that i can see the below one. i m breaking my head to over lap and give diffrent size to bars plz look into it..!!!

**Comment by k010** [comment]
@Ravikumar087, Did you try adding groups to your data series?? check this out http://c3js.org/samples/chart_bar_stacked.html.

**Comment by Ravikumar087** [comment]
@k010, I have tried it, but i want some thing like this....>  http://www.highcharts.com/demo/column-placement

**Comment by ljerka** [comment]
Overlapping bars would be great! I often need them. When having only 2 bars, I usually make one chart data "area-step", and other one "bar". It kind of simulates overlapping 2 bars, but doesn't have options that overlapping bars would have.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
