### ISSUE TITLE
Graph has incorrect width, gets crushed to right side

### ISSUE THREAD

**Issue by xcoder123** [c3js/c3#1413]
Hello,

First of all thanks for the great plotting library.

However, I think I encountered an issue with c3js. When I run the following code everything gets crushed to the right. But it only happens on these values and if I set the y range in decimal values.

``` javascript
var chart = c3.generate({
                            bindto: '#chart1',
                            size: {
                                height: 50,
                                width: 150
                            },
                            data: {
                              columns: [
                                ['d1', 2.88,2.94,3.06,2.84,2.83,2.9,2.96,3.1,3.32,3.35,3.58, 3.96]

                              ],
                              //type: "spline",
                              colors: {
                                d1: '#099998'
                              }
                            },                      
                            axis: {
                                y: {                    
                                    tick:{
                                        count: 2                    
                                    },
                                    default: 0,
                                    padding: {top:0, bottom:0}

                                },
                                x: {
                                    show:false,
                                    tick: {
                                        fit:false
                                    }
                                }
                            },
                            legend: {
                                show: false
                            },
                            tooltip: {
                                show: false
                            },
                            point: {
                                show:false
                            }
                        });
```

It produces the following result:
![Bad graph](http://morf.lv/viskas/c3issue.PNG)

But if I set Y axis min and max values to integer numbers it works. For example in the data set above I'd set min max with the following values:

y: {  
    tick:{
            count: 2  
        },
            default: 0,
                        min: 2,
                        max: 4,
            padding: {top:0, bottom:0}

},

And we got the following result: 
![Good graph](http://morf.lv/viskas/c3expected.PNG)

The width is correct, however I still need to have decimal points as my min max values otherwise the graph cannot be properly viewed and looks too smooth.

I'm using c3-0.4.10 and d3-3.5.6

**Comment by panthony** [comment]
Screens not available anymore. Chart doesn't seems to be crushed IMO.

Probably fixed.
