### ISSUE TITLE
Modularise C3 pieces using CommonJS

### ISSUE THREAD

**Issue by aendrew** [c3js/c3#1417]
Probably in relation to #351, currently all C3 does upon build is concatenate a boatload of files together.

This is fraught with peril for numerous reasons:
- It doesn't leave any room for choosing which pieces of the library are loaded. If we wanted to create some sort of tool to build a custom version of C3 (e.g., "only series charts; no pie, donut or gauge charts"), it would be incredibly difficult due to this.
- By not using common module loading patterns, it isn't at all straight-forward to add new pieces and it's next to impossible to figure out application flow (I've been using this library for years now and still have no idea how I'd write a custom chart).
- It becomes harder to trace where a problem is happening during debug, as you're just told "c3.js" and not the particular file wherein the problematic code is stored.

In order to do #351, I think we should move to the CommonJS format for loading all the modules, then use Webpack to build the web version of it. This should improve Node.js support and remove the need to have a Gruntfile. It should also make it easier to write plugins.

What does everyone think?

**Comment by ggamir** [comment]
I agree with the perilous reasons, and I support moving to a more modular form. It will lessen the barrier to entry and open up opportunities for more people to contribute and expand C3. 

Would you considering looking at RequireJS as an alternative to CommonJS?

**Comment by aendrew** [comment]
@ggamir I come from a Node background, and one of the use cases for C3 is in Node, ergo my initial suggestion re: CommonJS (the fact I've used it and have an idea of how to integrate it with Webpack also doesn't hurt). That's not to say using RequireJS would make C3 not work in Node; am just stating that's where I'm coming from.

Thinking about it all a bit further though, Node really isn't the primary audience, and being able to load modules asynchronously would be hugely useful — if we can make all the chart types into their own modules, it matters far less for things like whether less-used charts like gauge are included in the build (I've considered building a "builder"-style tool to trim down the C3 library size, but using AMD would greatly reduce the need to create such a sub-project — if you don't use gauge, don't include it, and your users will never have to download that code. Assuming I'm understanding how AMD works correctly...). 

So, yes — absolutely RequireJS should be considered, and this issue is entirely the right place to discuss the merits of each. :smile: 

A question: can you use RequireJS with Webpack? I'm sure you can; any documentation links are most welcome.

**Comment by ggamir** [comment]
@aendrew I meant specifically using RequireJS, but now that you mention Webpack, I think that is the best choice! Either way, an AMD approach would be great.

**Comment by caneroj1** [comment]
I know this is somewhat old at this point, but has there been any progress at all on this front? It would be really great if one could pick and choose which chart types to include from c3 in a build.

**Comment by aendrew** [comment]
@caneroj1 Yes and no — C3 is now comprised of ES6 modules, but we still lack any sort of "builder" that allows custom builds of C3.

That said: in the meantime, if you use C3 as a dependency with Webpack or Rollup, tree-shaking might be sufficient to only use the parts of the library you need in a particular project.

Closing because the original focus on the issue is now fulfilled. If there's demand for a custom build tool, please open a new issue.
