### ISSUE TITLE
Normalized Stacked Chart

### ISSUE THREAD

**Issue by lblb** [c3js/c3#142]
Hi Masayuki,
I was looking for a way to implement stacked chart expressed as percentages, similar to this example: http://bl.ocks.org/mbostock/3886394
However I was overwhelmed by so many intermediate steps you are using to calculate Y offset and height of bars. I'm confused so far...
A quick and dirty way to do this is to normalize data before drawing chart and then set Y range to 0-100%. However this is not suitable as I need to present both percentages and original values in labels on chart and in tooltips.
The same normalization should be also applicable to area charts.
Please advice what would be the best way to go and I'll be glad to contribute.

**Comment by mglgiordani** [comment]
+1
would be very helpful

**Comment by scottjason** [comment]
+ 1

**Comment by carlosJack** [comment]
Any update on the ability to built Normalized Stack Bar Chart using c3.js

**Comment by phantasma2983** [comment]
+100

**Comment by ataft** [comment]
+1

**Comment by ahmednoureldeen** [comment]
+1

**Comment by crauliuc** [comment]
Any new updates here?

**Comment by dmurphy779** [comment]
Came here to say +1. Status?

**Comment by mattbloomfield** [comment]
+1? :)

**Comment by artemanufrij** [comment]
new updates?

**Comment by mia0x75** [comment]
+1, both Normalized Stacked Bar Chart and Normalized Stacked Area Chart.

**Comment by Code7Bit** [comment]
+1
