### ISSUE TITLE
Wrong stacked chart render on load data BUG

### ISSUE THREAD

**Issue by Timopheym** [c3js/c3#1423]
When i load data into stacked chart i got spaces, but them should not be there. 
Second rendering in this (https://jsfiddle.net/3t1crx65/1/) fiddle is wrong and third is right one. 
Why is it so? How could it be fixed? Looks like internal.redraw do not properly recalculate positions..

Thanks.

**Comment by Timopheym** [comment]
Oops. Looks like it should be loaded on unload done. Sorry.

**Comment by rosorrentino** [comment]
I am having the same issue, is there any fix for that?

**Comment by michaelrodov** [comment]
looks like it's resolved
