### ISSUE TITLE
Serving D3 via the non-production Rawgit URL is leading to test failures

### ISSUE THREAD

**Issue by missingdays** [c3js/c3#1425]
I'm working with local copy of latest c3 and want to test it.
When I run `grunt` I get a lot of errors `TypeError: 'undefined' is not an object (evaluating 'd3.scale') in file:///srv/missingdays/Projects/c3/c3.js (line 5708) (1)` on this line

``` js
pattern = notEmpty(config.color_pattern) ? config.color_pattern : d3.scale.category10().range(),
```

I don't seem to find any other way to test that library is actually installed correctly.
P.S. Yes, I know I can use examples but this is not the solution I want/

**Comment by missingdays** [comment]
Adding bower_components/d3/d3.js helped
Don't know why, may be d3 cdn wasn't available or something

**Comment by aendrew** [comment]
Hmm, odd that D3 wasn't being pulled in by the "vendor" parameter in the Gruntfile. See [ln. 95](https://github.com/masayuki0812/c3/blob/master/Gruntfile.coffee#L95).

It shouldn't require Bower just to test.

**Comment by aendrew** [comment]
Closing as `can't confirm`. If you need any more help or are able to better identify the issue, please let me know and I'll reopen. Thanks!

**Comment by aendrew** [comment]
Actually — just noticed that the gruntfile is using Rawgit's non-CDN URL. Could be that it's being over-subscribed. From Rawgit.com:
<img width="1304" alt="screen shot 2015-10-11 at 22 07 57" src="https://cloud.githubusercontent.com/assets/185041/10419102/982d254a-7064-11e5-974d-071f1ba06a2b.png">

Reopening and renaming issue appropriately.

**Comment by kt3k** [comment]
We switched to use npm version of d3 in unit test. Thanks for reporting!
