### ISSUE TITLE
Loading new csv data on click

### ISSUE THREAD

**Issue by kthotav** [c3js/c3#1428]
Is it possible to load new csv data on click. For example, I have 5 .csv files, one for each day (Monday, Tuesday,...) and I want to load different data from each day on click. Is this possible ? 
Thanks

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
