### ISSUE TITLE
Create an organisation?

### ISSUE THREAD

**Issue by aendrew** [c3js/c3#1440]
As C3 grows in size and becomes a more self-sustaining community, we will likely at some point want to move C3 to its own organisation. Alas, [c3](https://github.com/c3) is an active user and [c3js](https://github.com/c3js) is an unused organisation.

I've worked with GitHub before to secure namespaces, they were super helpful when we requested an inactive account be renamespaced so we could use [https://github.com/times](times) To that end, I suggest we ask them if we can create an organisation at `c3js`. Am happy to spearhead this if it is something the community does in fact want.

Any thoughts, @masayuki0812?

**Comment by xtianjohns** [comment]
I think this would be very useful. What can folks do to help expedite?

**Comment by aendrew** [comment]
@xtianjohns Contributing to this issue is a good place to start! :smile: 

Assigning this to @masayuki0812 because ultimately the next step is getting a response from him as to whether this is something he'd go for.

**Comment by xtianjohns** [comment]
I'm not new to c3 but I'm not familiar with what, if any, roadmapping has been done. Is it possible that c3 could end up being fragmented into different repositories focused on different things? Or a plugin-esque architecture? In those scenarios, it seems like it would make sense to have the organization exist as an umbrella for each of the repositories.

Is there any way having an organization could help alleviate some of the maintenance issues we have right now?

**Comment by aendrew** [comment]
@xtianjohns You've highlighted one of the fundamental challenges facing the community at the moment — where do we go after this version, and how do we work with C3 architecturally so that it improves into the future? I think a big part of it is ensuring that interesting forks and related projects have somewhere to go, and the community forming around the library is able to access information about how to use C3, contribute back to the library and extend it in useful ways. 

Currently, a big issue is the amount of psychic debt caused by the size of the issue queue. The only people able to close issues are currently myself and @masayuki0812, and there's a huge need for people to be able contribute to the community by helping us manage that, and having an org would allow finer-tuned permissions for things of that nature.

**Comment by xtianjohns** [comment]
Heard. Sounds like all the more reason to prioritize migrating into an organization. It doesn't sound like there is a shortage of interest in usage. Is there a lack of enthusiasm for maintenance?

Another way: are things largely bogged down because no one is super jazzed about triaging issues, or is it more of a structural thing?

**Comment by aendrew** [comment]
@xtianjohns I think it's a bit of both, really. The lack of a plugin architecture leads to a lot of feature request-y issues that could honestly be provided by the community, causing these issues to build up, which makes the issue queue seem impossible to manage, which leads to more feature request-y issues because new users can't be arsed to search through 400 issues in order to prevent a duplicate. This size problem then has a knock-on effect with actually finding legitimate bugs, and the same thing happens with bug reports. There are also a *lot* of support requests from folks who can't be bothered to use one of the two approved support channels, but that's another issue. 

On one hand, some serious triaging needs to be done (I plan to spend a solid week towards Christmas working on this), but I get the feeling we'll be back in the same place a year from now if we don't improve our organisation and are able to delegate queue duties to more people.

**Comment by kyhy** [comment]
I would love to see c3 not stagnate. If it means c3 needs to be moved to an organization/restructuring, you have all my support. I use it pretty extensively at work and would love to help.

I'm new to contributing to open source projects and not sure where to start.

**Comment by wiibaa** [comment]
@aendrew this is ok now, right? Can be closed

**Comment by aendrew** [comment]
@wiibaa Absolutely, thanks for reminding me!
