### ISSUE TITLE
Set bar chart domain name

### ISSUE THREAD

**Issue by amgir** [c3js/c3#1448]
I couldn't find anything about how to set domain (description for each column) on the document. 
I'd like to have String as description. (Jan Feb Mar,etc)
Currently It's always N. (1 2 3 4 5 etc)
P.S : Also, I don't like c3js to omit some domain titles as seen on the image. (red)
It should be 0 1 2 3 4 5 not 0 3 5 

Preview: http://s6.picofile.com/file/8219814450/prob.png

**Comment by laurence-hudson-tessella** [comment]
Both of the problems you are having are covered in the documentation here:
http://c3js.org/samples/data_stringx.html
Setting axis.x.type to category will prevent the tick culling. 
Setting data.x will allow you to specify tick text.

**Comment by www-amg** [comment]
thank you @laurence-hudson-tessella.

**Comment by laurence-hudson-tessella** [comment]
@aendrew Close the issue?

**Comment by www-amg** [comment]
Yes @aendrew

**Comment by michaelrodov** [comment]
closed
