### ISSUE TITLE
Change Bar Width of Grouped Data

### ISSUE THREAD

**Issue by DomHudson** [c3js/c3#1449]
Hey how's it going?

I've been trying for a while to change the width of the bars in c3. It works fine if you have single data sets but if you group your data like in the example beneath it seems to be treated as one dataset and the ability to add white space between the bars is lost.

This is how it currently appears:
![image](https://cloud.githubusercontent.com/assets/10864294/10825406/d2bbe768-7e5c-11e5-9c63-93d48b88f1d6.png)

This is how I would like it to appear:
![image](https://cloud.githubusercontent.com/assets/10864294/10825486/1dfbdb98-7e5d-11e5-9be5-f8ccb4423b0a.png)

Is this possible with the current framework? Any help or suggestions would be great.

Many thanks
Dom

**Comment by hanu412** [comment]
did you find any solution? I have a similar problem.

**Comment by panthony** [comment]
There is a `bar.space` option (value between 0 and 1) and a `bar.width.ratio` option (value between 0 and 1) that should resolve your issue.
