### ISSUE TITLE
Blank Charts on Visualforce Page containing <apex:form> tag and Salesforce1

### ISSUE THREAD

**Issue by JeetAtGitHub** [c3js/c3#1452]
I have implemented c3 charts with visualforce page(Salesforce). But facing some issues from new release of Salesforce.
here is the scenarios. 
If there will be one apex:form tag in Visualforce page,  the charts are displaying as blank. 
Also it doesn't work on the Salesforce1 App
for more details: 
https://devinthecloud.wordpress.com/2015/10/23/winter-16-the-curious-incident-of-the-chart-in-the-form-tag/

I would like to appreciated the help, If this can be fixed as earlier; will help my app to release with c3js.

**Comment by ajagnanan** [comment]
+1 on this, we did try removing the apex:form tag also, but no luck. The charts are rendered in a component, not sure if thats a reason too.

**Comment by aendrew** [comment]
I have honestly no experience with anything Salesforce or Visualforce, though seems like there's been some investigation at [here](https://github.com/masayuki0812/c3/issues/1189#issuecomment-152659868). Seems the issue is that Salesforce includes Sizzle globally, which D3 picks up and makes it choke. It's really more a D3 + Sizzle issue than anything.

**Comment by aendrew** [comment]
If one of y'all could create a test case in a jsFiddle or something, that would help everyone tremendously.

**Comment by aendrew** [comment]
Troubleshooting this a bit further, the issue is with [c3_chart_internal_fn.getTextRect](https://github.com/masayuki0812/c3/blame/master/c3.js#L3402). The line creating the dummy element is null when jQuery is included before D3, have no idea why.

**Comment by aendrew** [comment]
Okay, more investigation. It seems if you remove the clip-path on the main `.c3-chart` object, all the lines suddenly reappear... So, it's something to do with how Sizzle is creating the clip path.

**Comment by JeetAtGitHub** [comment]
I appreciate your help.
Thanks for your investigation and support towards this.
I will try to find out the solution and update the PR.

**Comment by JeetAtGitHub** [comment]
here is my work around, it could be a hack,but making this as the solution for the time being.
first of all thanks to @aendrew for showing lights into this issue. also to @impatient ( #1189 ).

- after the release of Winter 16, visualforce page is loading with some extra js libraries which conflicting with c3Js and unable to form the <rect> tag with proper width and height. 
![image](https://cloud.githubusercontent.com/assets/15628068/11299667/ad3508a4-8fae-11e5-933b-fdadb63dcab7.png)
which is causing blank graphs. 
I was trying to dig into the c3js library codes, but unable to find the "rect" formation section.
thought of to update above <rect> with width and height after the DOM loads. it worked.
Add these lines of code on your page:
window.onload = function () { 
    $(document).find('svg').each(function(){ 
        var svgHeight = $(this).attr("height"); var svgWidth = $(this).attr("width");	
        $(this).find("rect").each( function() { $(this).attr('width',svgHeight).attr('height','266'); return false;});
    });
};
