### ISSUE TITLE
Wrong stack order when grouping data

### ISSUE THREAD

**Issue by thomasbg** [c3js/c3#1468]
When changing the data values the stack order is sometimes wrong.

With

```
['data1', -10, -5],
['data2', 3, -5],
```

everything is ob but with

```
['data1', -10, -5],
['data2', 13, -5],
```

the order of the second bar changes (red on the bottom, grey at the top).

![grouping](https://cloud.githubusercontent.com/assets/15909855/11244298/211f9c50-8e0d-11e5-97b4-18a0d7d9c5cd.JPG)

Here is the whole sample code:

```
var chart = c3.generate({
data: {
    x : 'x',
    columns: [
        ['x', 'data1', 'data2'],
        ['data1', -10, -1],
        ['data2', 13, -9],
    ],
    groups: [
        ['data1', 'data2']
    ],
    type: 'bar',
    colors: {
        data1: 'grey',
        data2: 'green'
    },
    color: function (color, d) {
        return d.value < 0 && d.id === 'data2' ? 'red' : color;
    },
},
axis: {
    x: {
        type: 'category',
    },
},
grid: {
    y: {
        lines: [
            {value: 0, text: ''},
        ]
    }
},
});
```

**Comment by aendrew** [comment]
Sounds like a bug. Please correct me if I'm wrong and it's actually just a property of how stacked charts render (I'm not too familiar with them), @masayuki0812.

**Comment by GoekhanOezen** [comment]
no its not a bug its the standard ``data_order = 'desc'``. if you set ``data_order = null`` (means no sorting) you will see that there is no change. 
the ``c3_chart_internal_fn.orderTargets`` function orders the targets in absolute value order, so 
10 + 5 > 3 + 5  => data1 > data2 and
10 + 5 < 13 + 5 => data < data2

**Comment by panthony** [comment]
No a bug, GoekhanOezen nailed it.
