### ISSUE TITLE
Loading nested JSON objects

### ISSUE THREAD

**Issue by kelthuzad** [c3js/c3#1471]
When I load JSON as chart data, I cannot load any nested objects or array values, but only objects in the first "level" of the JSON object.

This works fine:
```javascript
c3.generate({
data: [{myVal:1}],
keys: {value: ['myVal']} // load property "myVal" 
});
```
But this does not work:
```javascript
c3.generate({
data: [{myVal: {innerVal:1}}],
keys: {value: ['myVal.innerVal']} // cannot access nested data here
});
```
There would only be a small change needed to implement the access of nested values, and it would make loading of JSON objects much easier in some cases.

**Comment by deeg** [comment]
+1

**Comment by crearc** [comment]
+1

**Comment by kelthuzad** [comment]
I just opened a pull request but the CI says my new test cases don't work. However they work fine on my machine. Any suggestions why they don't work here: https://travis-ci.org/masayuki0812/c3/builds/96603362 ?

**Comment by tdharris** [comment]
I would like for this to work.

**Comment by kelthuzad** [comment]
Just fixed my pull request, so tests work now!

**Comment by z** [comment]
This looks great. Looking forward to this being merged.

**Comment by aendrew** [comment]
This is a solid idea. Merging PR to `dev` now.

**Comment by kelthuzad** [comment]
For anyone who is interested, this is a simple jsfiddle that demonstrates the new feature: http://jsfiddle.net/h0wag7ur/

**Comment by michaelrodov** [comment]
Great feature! 
Will allow us to stop massaging the jsons prior to charts building

**Comment by z** [comment]
Awesome! So happy to see this merged. Appreciate the demo too.

**Comment by akshaysGit** [comment]
Hello,

I am trying to use following JSON data input for stacked bar chart, however its not working for nested input. If I put everything on one level, it works fine. Its just that nested is causing issue. can you pls help?

JSON data - 
`[
	{
		"Month": "Sample 1",
		"TotalAmount": "$100",
		"StartDate:
		"EndDate:		
		"Detail":
			[
				{ "Type": "A", "Unit": "50",  "Amount": "20"},
				{ "Type": "B", "Unit": "20",  "Amount": "70"},
				{ "Type": "C", "Unit": "2",  "Amount": "10"},
			]
	},
	{
		"Month": "Sample 2",
		"TotalAmount": "$150",
		"Detail":
			[
				{ "Type": "A", "Unit": "50",  "Amount": "20"},
				{ "Type": "C", "Unit": "2",  "Amount": "10"},
			]
	},
	
]`
