### ISSUE TITLE
Drag to Zoom

### ISSUE THREAD

**Issue by mistic** [c3js/c3#1485]
Hi guys,

It's possible to apply the zoom on the chart with a drag over x-axys like in http://dygraphs.com/ ?

Regards

**Comment by xtianjohns** [comment]
@aendrew this sounds like the same thread being followed in Gitter. @misticini, are you working on an implementation for this? It sounded like brushing directly over the chart hasn't been implemented yet.

**Comment by agarwalhitesh83** [comment]
+1

**Comment by unstephenk** [comment]
Would like this as well.

**Comment by kt3k** [comment]
refs: #1500 #2439

**Comment by kt3k** [comment]
The feature added at #2439. Released as v0.6.7.
