### ISSUE TITLE
Tick's labels overlaps each other

### ISSUE THREAD

**Issue by Timopheym** [c3js/c3#1487]
There is not proper heuristics for rotation ticks labels. 
![screen shot 2015-12-04 at 10 42 44](https://cloud.githubusercontent.com/assets/525039/11584310/f623fd48-9a73-11e5-8e9f-914d2879fa42.png)
Could it be done better? What is the code responsible for that?
Thanks!

**Comment by panthony** [comment]
There is a `multiline` option for axis but since it's a single word (a number) you should either format it to make it shorter (ex: 20M instead of 20 000 000) or rotate the axis label:

http://c3js.org/reference.html#axis-x-tick-rotate

Nothing else to do.
