### ISSUE TITLE
dist-tags on NPM returns 0.4.11-rc4

### ISSUE THREAD

**Issue by aendrew** [c3js/c3#1492]
Via @megapctr, [the version NPM is currently returning is always 0.4.11-rc4](https://gitter.im/masayuki0812/c3?at=5666f71d981d328249336480), which is a bad practice given that's a pre-release version. Although great for getting more people using and contributing to the latest version, this is somewhat fraught with peril as users will install an unstable version by default.

I'd recommend only pushing full releases to NPM.

**Comment by wiibaa** [comment]
As I suppose the discussion will come back for 1.0.0 pre-releases, maybe applying the same as was done for d3 v4 is a good option by using `npm publish --tag next` 
Info source => https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420#.4xrhs0eu4

Then this issue could be closed I think

**Comment by kt3k** [comment]
Now it returns 0.4.15!

```console
$ npm view c3 dist-tags
{ latest: '0.4.15' }
```
