### ISSUE TITLE
Event while click on exactly over the line in line chart

### ISSUE THREAD

**Issue by suriya61991** [c3js/c3#1493]
Hi,
I want to trigger an event, while click exactly on over the line in line chart.

plz help me

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
