### ISSUE TITLE
Issues with `chart.zoom()` getter method

### ISSUE THREAD

**Issue by megapctr** [c3js/c3#1497]
**JSFiddle: http://jsfiddle.net/zhw1q40p/1/**

`chart.zoom()` getter works very weird - at first, it displays the same value for start and end - "1999, 1999" in this example. But zoom the chart in and out and notice that the value changes to "1999, 2004"

Also, zooming the chart manually does not affect the result of `chart.zoom()`. See updateLog function for details

**Comment by robhybrid** [comment]
I'm having the same issue, but the start and end never show anything other that the same value.
