### ISSUE TITLE
Spline lines go backwards

### ISSUE THREAD

**Issue by megapctr** [c3js/c3#1501]
Spline lines go backwards in some cases. This is invalid for charts like timeseries.

**JSFiddle: http://jsfiddle.net/mkw4h54r/**

**Comment by tearwyx** [comment]
+1

**Comment by zdychacek** [comment]
Hi, is there any ETA when this issue will be fixed?

Thanks for a response.

**Comment by jstone-ponderosa** [comment]
I am having this same issue and submitting another ticket.  Did anyone hear back on this?

**Comment by kt3k** [comment]
With version 0.5.1 of c3.js, `spline: { interpolation: { type: 'monotone' } }` option resolves this issue.

See https://jsfiddle.net/mkw4h54r/5/ for example.

**Comment by tearwyx** [comment]
And what about `area-spline`?
