### ISSUE TITLE
Creating a Combination chart(line and bar) for same json data

### ISSUE THREAD

**Issue by nithingit** [c3js/c3#1509]
I want to create a combination chart (line and bar) for same json data so that the line touches the all the bars since datapoints are same.

Here is the code

var graphdata=[
{ 'indicator': 'X', 'total': 100 },
            { 'indicator': 'Y', 'total': 200 },
            { 'indicator': 'Z', 'total': 300 }
];
var g1=[
{ 'indicator': 'X', 'total': 150 },
            { 'indicator': 'Y', 'total': 220 },
            { 'indicator': 'Z', 'total': 330 }
];
setTimeout(function () {
    chart.load({
          data: {
        type: 'line',
        json: g1,
        keys: {
            x: 'indicator',
            value: ['total']
        },

```
},
axis: {
        x: {
            type: 'category'
        }
},
});
```

}, 1000);
var chart = c3.generate({
    data: {
        type: 'bar',
        json: graphdata,
        keys: {
            x: 'indicator',
            value: ['total']
        },

```
},
axis: {
        x: {
            type: 'category'
        }
},
bar: {
    width: {
        ratio: 0.5
    }
}
```

});

The output of this is only bar chart,the line chart is not loading.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
