### ISSUE TITLE
rotated ticks don't adjust height automatically on rotating to left side

### ISSUE THREAD

**Issue by smtryingcode** [c3js/c3#1511]
http://c3js.org/samples/axes_x_tick_rotate.html

This can be tested in the above example, remove height attribute then changing the rotation to -ve value hide the ticks

**Comment by GoekhanOezen** [comment]
Having same issue if rotation is a negative value.

It seems a ``Math.abs(...)`` in ``getHorizontalAxisHeight`` for ``config.axis_x_tick_rotate`` fixes this issue.

**Comment by alexbain** [comment]
Opened a PR with a fix: https://github.com/c3js/c3/pull/1766

**Comment by Tak0r** [comment]
Why is this still not merged?

**Comment by EBZ-Krisemendt** [comment]
some month later i'm still experiencing that error using current release...

**Comment by pistou** [comment]
RT if still not fixed in 2018

**Comment by kt3k** [comment]
Sorry for the long delay.

#1766 is merged and released as v0.5.1.

You need to update D3.js as well as c3 to update it to v0.5.x.
