### ISSUE TITLE
Add "Total" row to tooltip

### ISSUE THREAD

**Issue by Dakkers** [c3js/c3#1513]
(I searched for this issue already and I didn't find it so hopefully this isn't redundant).

It would be nice to be able to show the sum of the data values at a specific x-value - for stacked graphs, it's hard to tell exactly what the cumulative value is.

I already have this working in a fork, so if you think it's of value, I'll submit a PR.

**Comment by ffuentes** [comment]
+1

**Comment by rosorrentino** [comment]
+1 too, but isn’t this possible using tooltip.contents?

**Comment by stephanvierkant** [comment]
I think #984 is related.

**Comment by atodorov** [comment]
@Dakkers where is the PR ? I don't see it.

**Comment by Dakkers** [comment]
Not sure why I never made the PR but I don't think I have access to that
code anymore. I moved on to chartJS a while back anyway. Sorry!
