### ISSUE TITLE
legend's text overlaps when working with Chinese characters

### ISSUE THREAD

**Issue by HelloListen** [c3js/c3#1526]
<img width="228" alt="pic" src="https://cloud.githubusercontent.com/assets/11993503/12087393/79c3efa8-b30d-11e5-8f88-cc0331310d18.png">
I don't find any clue on how to format legend's text from the official documentation, so I wonder if there's a way to fix this problem.
As you can see from the screenshot, when comes to Chinese, it looks Overlapping.
Thanks!

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
