### ISSUE TITLE
Border color of area chart

### ISSUE THREAD

**Issue by raks81** [c3js/c3#1528]
This is my area spline which renders with a 'light-red' fill and a 'dark-red' border:
[http://jsfiddle.net/sctc5yrL/](http://jsfiddle.net/sctc5yrL/)

Is it possible to remove the 'dark-red' border or set the border color of the area? I went through the reference but could not find any explicit option to set this.

Thanks
Rakshith

**Comment by Skotu** [comment]
Hi,

Not sure if you can do this from js, however you can achieve it by changing css a bit. 
http://jsfiddle.net/L8kgyLc4/2/

.c3-shapes.c3-shapes-data1.c3-lines.c3-lines-data1 > path {
  stroke: rgba(255, 0, 0, 0) !important;
  opacity: 0 !important;
}

Only one of above properties is needed, and both will work.

**Comment by raks81** [comment]
Ah! that works as well. Thanks for the tip! 👍
