### ISSUE TITLE
Legend double click hide all but the clicked

### ISSUE THREAD

**Issue by souzadevinicius** [c3js/c3#1531]
When legend is clicked twice all legends are hide, but the clicked.

http://jsfiddle.net/su2axgsd/4

**Comment by ljerka** [comment]
I have the same problem. But for me - everything is working fine on desktop browsers. The problem is on mobile/tablet browsers (chrome on desktop is working on, but chrome on mobile have this issue).

**Comment by panthony** [comment]
Not sure if feature request or bug report.

But this if feature it is it's already exiting using alt+click on a legend item.
