### ISSUE TITLE
Legend order sporadic shuffling after click hide

### ISSUE THREAD

**Issue by souzadevinicius** [c3js/c3#1535]
Before click:

![edit fiddle jsfiddle_ok](https://cloud.githubusercontent.com/assets/6750638/12262532/a85b0e2a-b90f-11e5-9f78-7e97b883e7ec.png)

After click:

![edit fiddle jsfiddle](https://cloud.githubusercontent.com/assets/6750638/12262596/f7c08670-b90f-11e5-9560-dcc9e776d2f6.png)

http://jsfiddle.net/yzqa91fh/

**Comment by EijiSugiura** [comment]
This issue may be same with my issue #1741.
My fix will be helpful for you.

**Comment by souzadevinicius** [comment]
Thank you @EijiSugiura
