### ISSUE TITLE
Releasing new version

### ISSUE THREAD

**Issue by ferlores** [c3js/c3#1537]
Are you planning to release a new version with the latest changes?  v0.4.11-rc4 was released last August. I'm interested in this changes in particular https://github.com/masayuki0812/c3/commit/5170fed8173108009715bc9b9fedc2fb01e14a01

Thanks!
F

**Comment by Timopheym** [comment]
[+1] I think you might ask community for help, just share your plan =)

**Comment by wiibaa** [comment]
@aendrew can this be closed as 0.4.11 was released ?

**Comment by aendrew** [comment]
Yep! Thanks @wiibaa!
