### ISSUE TITLE
Is it able to load new color in horizontal bar chart?

### ISSUE THREAD

**Issue by say8425** [c3js/c3#1548]
I can find horizontal bar chart color can be changed in https://github.com/masayuki0812/c3/issues/259
But it do not works with [data color API](http://c3js.org/samples/api_data_color.html)

Is it not possible? or I got wrong code?
https://jsfiddle.net/say8425/40hqnsv5/1/

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
