### ISSUE TITLE
change y grid stoke color

### ISSUE THREAD

**Issue by hendamin** [c3js/c3#1557]
I need to change the stroke color for y grids. all i found was changing the color of extra lines using ygrids, but what i need is to change the color of the original y grid.

**Comment by gthomas3** [comment]
Use the console to find the element you want to change. Most elements of the SVG object and comprehensively labelled with class names you can target in your CSS.

**Comment by panthony** [comment]
As explained, find the SVG element you are interested in and use css to change its color.
