### ISSUE TITLE
add attrTween transition to Donut chart

### ISSUE THREAD

**Issue by luffy1701** [c3js/c3#1567]
Hi,
How to add attrTween transition to donut chart when initialize event?

**Comment by aendrew** [comment]
Hi there! We try to keep the issue queue clear for specific code-related problems with C3, could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3) instead? Thank you!
