### ISSUE TITLE
Is it possible to implement drill down bar chart?

### ISSUE THREAD

**Issue by pekq** [c3js/c3#157]
I have a basic bar chart and I would like to attach a click event on the bars themselves or on the labels. As a return I would get the ID of the clicked bar/label so I could use that to redraw the chart with new remote data based on user interaction. Is this possible with the current state of c3js? If not, how should I approach this?

Here is how it looks like in highcharts: http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/drilldown/basic/

**Comment by souravmondal45** [comment]
Yes Its possible, Here i have tried to implement. May this helps you http://dotnetawesome.com/mvc/how-to-implement-drill-down-google-chart-in-mvc4

**Comment by bhuvan-ganesan** [comment]
Check this out http://jsfiddle.net/mcuepavh/1/

**Comment by SSKSoftware** [comment]
The example http://jsfiddle.net/mcuepavh/1/ doesn't work in Crome (Version 48.0.2564.97 m)
