### ISSUE TITLE
Adds function handling for point's size on focus and select

### ISSUE THREAD

**Issue by panthony** [c3js/c3#1571]
The options `point.focus.expand.r` and `point.select.r` should both be able to take a function with either the data or the current point size.

Today when you use a function for `point.r` to make the point's size vary according to some data the default ratio of `4` and `1.75`.

I'd be happy to provide a PR if I knew it would be merged eventually.

**Comment by aendrew** [comment]
Agreed, this should take an optional callback.

**Comment by panthony** [comment]
This ticket was partially fixed by #1610.

Now only `point.focus.expand.r` is missing the handling of function as value.
