### ISSUE TITLE
Gauge unfilled section for full circle is not visible.

### ISSUE THREAD

**Issue by Kinlaw** [c3js/c3#1602]
If the gauge is set to fullCircle and has a data value that is less than the max value, the unfilled section of the gauge is not visible.

**Comment by aendrew** [comment]
Good catch! Please see #1604, I've added a few suggestions. :smile:

**Comment by Kinlaw** [comment]
Sorry for the delay. Here's a JSFiddle showing the incomplete unfilled section of the 360 gauge:
http://jsfiddle.net/vkt2pvc9/
