### ISSUE TITLE
Tooltip Error when displaying missing time series

### ISSUE THREAD

**Issue by nlacoff** [c3js/c3#1620]
In the code below, I am showing 2 separate time series.  The first dataset starts on 1/1/2013 and I am loading a second data set that starts with 1/2/2013 (data3 started taking data 1 day after data1 and data2).  The charts display fine however mousing over the points  to bring up the tool tip throws the following exception in the function c3_chart_internal_fn.getTooltipContent on line return orderAsc ?a.value-b.value : b.value- a.value

0x800a138f - JavaScript runtime error: Unable to get property 'value' of undefined or null reference 

Below is the code

        var chart = c3.generate({
            data: {
                x: 'x',
                //        xFormat: '%Y%m%d', // 'xFormat' can be used as custom format of 'x'
                columns: [
                    ['x', '2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06'],
        //            ['x', '20130101', '20130102', '20130103', '20130104', '20130105', '20130106'],
                    ['data1', 30, 200, 100, 400, 150, 250],
                    ['data2', 130, 340, 200, 500, 250, 350]
                ]
            },
            axis: {
                x: {
                    type: 'timeseries',
                    tick: {
                        format: '%Y-%m-%d'
                    }
                }
            }
        });

       
            chart.load({
                columns: [
                    ['x', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06'],
                    ['data3', 500, 450, 700, 600, 500]
                ]
            });

**Comment by aendrew** [comment]
Confirming bug, I think it's specific to 0.4.11. Fiddle [here](https://jsfiddle.net/aendrew/78ag7p6w/2/).

**Comment by masayuki0812** [comment]
This was fixed by https://github.com/c3js/c3/issues/1631 together.
Btw, x of loading data must have the same `x` with current x. Otherwise, x grid focus line will not be rendered correctly.

This should work:
```
chart.load({
            columns: [
                ['x', '2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06'],
                ['data3', null, 500, 450, 700, 600, 500]
            ]
        });
```
