### ISSUE TITLE
Data is not rendering. Jade, node.js 5.3

### ISSUE THREAD

**Issue by YannisMarios** [c3js/c3#1621]
Hello, 

I am using c3.js 0.4.10, d3.js 3.5.16, node.js 5.3.3, angular 1.4.8 and Jade 1.11.0 template engine IDE is webstorm 10

I try to render demo data like this:

div(id="chart")

script.
$(document).ready(function () {
      var chart = c3.generate({
         bindto: '#chart',
         data: {
            columns: [
               ['data1', 100, 200, 150, 300, 200],
               ['data2', 400, 500, 250, 700, 300]
            ]
         }
      });
   });

What I get is axis rendered and no lines, just blank space.

Are there any compatibility issues with the d3.js, node.js, angular.js, jade versions I am using?

I tried Chrome, Firefox, IE, Edge on windows 10 but no luck.

I get no errors on dev tools console and all d3.min.js, c3.min.js and c3.min.css are loaded properly.
I also tried your latest 0.4.11-rc4 but no luck.

![image](https://cloud.githubusercontent.com/assets/11289298/13727897/c5a3e276-e90d-11e5-8346-881d23bd3616.png)

here is a screenshot from dev tools in chrome:

![image](https://cloud.githubusercontent.com/assets/11289298/13727971/7d78ec3c-e910-11e5-8207-5049e4ac94fa.png)

**Comment by hisuwh** [comment]
I'm experiencing the same issue though not with node

**Comment by aendrew** [comment]
I have no idea, I've used C3 with all of those except Jade. Mind writing a JSFiddle?

**Comment by YannisMarios** [comment]
I am writing above: "I also tried your latest 0.4.11-rc4 but no luck."

**Comment by panthony** [comment]
For questions involving the interplay between C3.js and any other library (react, vuejs, ..) please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

Thank you!
