### ISSUE TITLE
Bar chart: error showing tooltip with different number of columns

### ISSUE THREAD

**Issue by stevelacy** [c3js/c3#1631]
The chart lookup for mouseover functions tries to determine the value of `a` and `b` on this line: https://github.com/masayuki0812/c3/blob/master/c3.js#L3864
It then attempts to read the value of null when b is null.

JSFiddle: https://jsfiddle.net/gv2tfkzf/6/

Method to reproduce: hover over the second bar group
![selection_0382016dt](https://cloud.githubusercontent.com/assets/5648999/14002565/0809fc14-f10a-11e5-87d5-c48c41bc2b42.png)

**Comment by aendrew** [comment]
Lulz, wow. That's weak. Thanks for the report, marking as bug.

**Comment by stevelacy** [comment]
:smile_cat:
