### ISSUE TITLE
snapping pointer position and bar center does not align when animation is turned on

### ISSUE THREAD

**Issue by astroanu** [c3js/c3#1633]
in bar charts the center of the bar and the snapping point does not align properly. This has something to do with the animation, since if i turn off animation it works okay. 

The snapping pointer position is calculated before the animation is finished giving wrong positions of the bars.

c3 v 0.4.10
d3 v 3.5.12
on chrome  48.0.2564.116 (64-bit)

**Comment by aendrew** [comment]
Hi @astroanu — could you please create a JSFiddle to help us reproduce the issue? 

As well, mind trying to update C3 to 0.4.11-rc4 and seeing whether the issue persists? Thanks!

**Comment by panthony** [comment]
No response from submitter
