### ISSUE TITLE
X-axis values appear weird after disabling other plots

### ISSUE THREAD

**Issue by scottydelta** [c3js/c3#1639]
The data has a value of float with one precision but the x axis shows float with more than 10 precision when only that particular plot is kept enabled. See image
![screen shot 2016-03-31 at 11 58 49 pm](https://cloud.githubusercontent.com/assets/2242189/14200019/090e21a0-f79d-11e5-9ad5-2319ab6ceb43.png)

**Comment by scottydelta** [comment]
`                tick: {
                    fit: true
                }` is working kind of reverse, keeping it `true` shows un-uniform axis and making it false fixes it. Not sure what's happening.

**Comment by aendrew** [comment]
@scottydelta Could you please put this into a JSFiddle? Seems like a bug to me...

**Comment by scottydelta** [comment]
@aendrew , I would love to put that on the JSFiddle but I dont have access to the data which was causing this anymore, just the code. Let me know if that helps.

thanks

**Comment by panthony** [comment]
No response + duplicate of more recent issue
