### ISSUE TITLE
Please publish 0.4.11 to npm (and update d3 dependency)

### ISSUE THREAD

**Issue by homerjam** [c3js/c3#1681]
Right now the current version can't be installed with node 6.0 as there is a dependency on d3#3.5.0 > jsdom > contextify (which fails to build).

Thanks

**Comment by aendrew** [comment]
@homerjam Thanks for letting us know, we'll try and push an update allowing that ASAP.

@masayuki0812 — any thoughts on how to handle this? Updating package.json and force-pushing the tag doesn't seem like a good plan, but we should get this released relatively soon.

**Comment by lilasquared** [comment]
@aendrew in the same vain as this can the nuget package get updated as well?

**Comment by kt3k** [comment]
d3 dependency is now `~3.5.0` and I think this is solved.
