### ISSUE TITLE
When the column name includes sign, C3 cannot tell the difference between signs

### ISSUE THREAD

**Issue by LuqiYan** [c3js/c3#1687]
**C3 Version:** v0.4.11
**Browsers:** Chrome(Version 50.0.2661.94 (64-bit))   Safari(Version 9.1)
*_Bug: *_ One column name is with '+' and the other is '-', when I only select 'data+' from legend, it will highlight both.

<img width="1712" alt="screen shot 2016-05-06 at 1 47 02 pm" src="https://cloud.githubusercontent.com/assets/13910271/15085870/ca6d3772-1391-11e6-9193-48bc9acc6ee1.png">

**Comment by amenadiel** [comment]
Please, try to work around this behavior by adding other strings to the column names. For example, adding an empty string may force C3 to cast the label as such, whereas in your case it might be evaluating it.

**Comment by kt3k** [comment]
The fix is released in [v0.5.2](https://github.com/c3js/c3/releases/tag/v0.5.2).
