### ISSUE TITLE
Space before first tick on y-axis

### ISSUE THREAD

**Issue by joeshub** [c3js/c3#1692]
Hi,

Is it possible to add some space before the first tick mark on the y axis? Basically I don't want the first ticks on the x and y axis to be touching

**For example:**
<img width="98" alt="screen shot 2016-05-06 at 9 12 49 am" src="https://cloud.githubusercontent.com/assets/764006/15207247/9a27e4b2-17d9-11e6-9d23-e03ba7432f4d.png">

In this screenshot I basically want **2.52** to _move up_ about 20 pixels so that it doesn't look mashed up against **05-01**

Thank you

**Comment by joeshub** [comment]
There has to be a way to do this, has anyone found a way to add a bit of padding to the y axis starting point?

**Comment by heliodor** [comment]
Set the padding for the x axis to move it down a bit:
chart.axis.x.padding.top = 10

**Comment by michaelrodov** [comment]
as Heliodor stated u need to add padding 
in general we encourage users to ask questions via Google groups
si im closing this thread
