### ISSUE TITLE
Disable a colum by Default

### ISSUE THREAD

**Issue by Ne00n** [c3js/c3#1698]
Hey,

When I click on a colum its disabled aka its not more displaying any data.
Is it possible, to set a colum by default to disabled, so a User needs to click on it to enable it and view the Data?

Thanks.

**Comment by mister-raindrop** [comment]
If you're still looking for it, use data.hide. http://c3js.org/reference.html#data-hide

Codepen example: http://codepen.io/doomkookie/pen/jrrwrO

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you
