### ISSUE TITLE
SVG pathSegList is deprecated 

### ISSUE THREAD

**Issue by DoomyTheFroomy** [c3js/c3#1703]
In current Chrome (48) the svg pathSegList is not available anymore. This will lead to errors in `c3_chart_internal_fn.getPathBox`, `isWithinBar` and `c3_chart_internal_fn.getPathBox`. A [stackoverflow article](http://stackoverflow.com/questions/34352624/alternative-for-deprecated-svg-pathseglist) has already mentioned the workaround/fixes.

**Comment by aendrew** [comment]
This is long since fixed. #1465 #1552 #1565 #1564 #1515 all relate to this. Please search before filing new issues — thank you!
