### ISSUE TITLE
Auto scale for x axis?

### ISSUE THREAD

**Issue by ericrange** [c3js/c3#1707]
Is there any x axis auto scaling for timeseries?

e.g. if i have a dataset for one day = show hours
       if i have a dataset for one week = show days

such as many, that there is always the same padding between the values.
is there something available? or do i have to do this on my own?

d3 does offer this feature!

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you
