### ISSUE TITLE
Time series min/max on x axis doesn't work

### ISSUE THREAD

**Issue by danelkhen** [c3js/c3#171]
The following code throws an error (getTime function not defined on Number).
If I change the numbers into Date objects (in both the data and the min/max setting) - the min/max values are ignored.

```
var chart = c3.generate({
    bindto: '#chart',
    data: {
        x: "date",
        rows: [
            ["date", 'data1', 'data2', 'data3'],
            [1398154158000, 10, 70, 20],
            [1398154159000, 10, 70, 20],
            [1398154160000, 10, 70, 20],
            [1398154161000, 10, 70, 20],
        ]
    },
    axis: {
        x: {
            type: 'timeseries',
            tick: {
                format: '%Y-%m-%d %H:%M:%S'
            },
            min: 1398154158000,
            max: 1398155158000,
        },
    },
});
```

**Comment by abhay316-prog** [comment]
hello @masayuki0812  how to make the max/min value visible?
scenario : I am able to put the max limit but I want the max date that is todays date (in my case) to be always visible at the end of the x axis . is that something possible?
