### ISSUE TITLE
Line chart - dashed line only between two points 

### ISSUE THREAD

**Issue by tarundhillon** [c3js/c3#1711]
Hi

I was wondering if there was a way to change the line style only between two points. E.g. I want to show projections in dashed line, where as live data can be in solid lines. 

I have see stroke-dasharray but I think it applies to the entire path coordinates. Any suggestions  ? 

Thanks 
ps- great work on this library.

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you
