### ISSUE TITLE
Hyphen interfering with 'use strict';

### ISSUE THREAD

**Issue by cablegunmaster** [c3js/c3#1712]
Is it possible to rewrite this part without the ` hyphen so I can include this library in React-native? :)

> 
>     c3_chart_internal_fn.getTargetSelectorSuffix = function (targetId) {
>         return targetId || targetId === 0 ? ('-' + targetId).replace(/[\s?!@#$%^&*()_=+,.<>'":;\[\]\/|~`{}\\]/g, '-') : '';
>     };
> 

Especially this part " ~`{}\ " 

Shortly said if this hyphen can be destroyed , rewritten, replaced with something else I could use it within react-native webview. Which I would really love to, as the website is also running on this library.

- Line 6045 but not sure how to change this line.

**Comment by aendrew** [comment]
Hi @cablegunmaster! 

Interesting, though I'm not sure I understand the issue. Would merely escaping the backtick fix this?

**Comment by cablegunmaster** [comment]
No it didnt might be a react native bug related. Close issue plz

**Comment by aendrew** [comment]
@cablegunmaster Cool, will do — let me know if you figure it out, we're definitely wanting interoperability with React Native.

Closing at request of submitter.
