### ISSUE TITLE
input data question

### ISSUE THREAD

**Issue by sparvu** [c3js/c3#1716]
We have an application which handles time series data. Our data looks like this, for each time series:

```
"values" : [
    [ 1025409600000 , 23.041422681023] , 
    [ 1028088000000 , 19.854291255832] , 
    [ 1030766400000 , 21.02286281168] , 
    [ 1033358400000 , 22.093608385173] , 
    [ 1036040400000 , 25.108079299458] ...
]
```

and C3 seems is expecting the input like this:

```
data: {
        x: 'x',
        columns: [
            ['x', '2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06'],
            ['data1', 30, 200, 100, 400, 150, 250],
            ['data2', 130, 340, 200, 500, 250, 350]
        ]
    },
...
```

Is there any hope for us to be able to use C3 to feed such data input ? 

Thanks

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you
