### ISSUE TITLE
Pie Chart not full fill the size specify

### ISSUE THREAD

**Issue by tao-findly** [c3js/c3#1718]
I try to make a small 30x30 pie chart with follow code, but it seems the pie chart not full fill the area and looks much smaller than 30x30. Is this the normal behavior of the pie chart?

```
var chart = c3.generate({
    data: {
        columns: [
            ['data1', 30],
            ['data2', 120],
        ],
        type : 'pie'
    },
    pie: {
	  expand: false,
	  label: {
		show: false,
	  },
	},
	size: {
	  width:30, 
	  height:30
	},
	legend: {
	  show: false,
	},
	tooltip: {
	  show: false,
	},
});
```

**Comment by michaelrodov** [comment]
I think padding might come handy in this case 
var chart = c3.generate({
padding: {
        top: -10,
        right: -10,
        bottom: -10,
        left: -10,
    },
    data: {
        columns: [
            ['data1', 30],
            ['data2', 120],
        ],
        type : 'pie'
    },
    pie: {
      expand: false,
      label: {
        show: false,
      },
    },
    size: {
      width:230, 
      height:230
    },
    legend: {
      show: false,
    },
    tooltip: {
      show: false,
    },
});

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you

**Comment by tao-findly** [comment]
Thanks for your answer, Michael. I will ask questions on Google Group in the future.

**Comment by leohammes** [comment]
I have the same issue here, someone found any solution?

**Comment by WoodrowShigeru** [comment]
I have discovered that the pie becomes smaller if you add the configuration `axis.rotated = true`.

You can confirm that in this demo: https://c3js.org/samples/chart_pie.html
