### ISSUE TITLE
Set up the axis X on top the graph

### ISSUE THREAD

**Issue by nice00xt** [c3js/c3#1725]
¿is there any option to set the Axis X on top the graph, because I am currently setting this with a javascript line, but I'm looking for another form to do this

this is my currently line on c3 properties
`
oninit: function () {
        const setAxisX = () => {
          return document.getElementsByClassName('c3-axis-x')[0].setAttribute('transform', 'translate(0,-30)')
        }
        setAxisX()
        window.onresize = (event) => {
          setTimeout(function () {
            return setAxisX()
          }, 100)
        }
      },
`
any idea?

**Comment by michaelrodov** [comment]
CSS?

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you
