### ISSUE TITLE
tooltip custmize 

### ISSUE THREAD

**Issue by salok64** [c3js/c3#1726]
i want to show additional value in tooltip that is not shown in the chart

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you
