### ISSUE TITLE
Pie. Show data in the values 

### ISSUE THREAD

**Issue by pshulga-softheme** [c3js/c3#1731]
Hi, I can showing data in pie chart in the values (not percentage)?

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
