### ISSUE TITLE
Space in bar chart with single data points

### ISSUE THREAD

**Issue by hanu412** [c3js/c3#1732]
I have data like this -  var bardata = {
            "0-1000":[20],
            "1000-5000":[30],
            "5000-10000":[40],
            "10000-Above":[50],
            }

When render this , it looks like below.. I want to have some space separating the bars. How do I do it?
Any help will be appreciated.

Note that if push multiple elements into the array like below, I see spaces
 var bardata = {
            "0-1000":[20,30,40],
            "1000-5000":[30,40,50],
            "5000-10000":[40,50,60],
            "10000-Above":[50,60,87],
            }

I am using data.json to populate the data property.

![image](https://cloud.githubusercontent.com/assets/11040896/16265240/cb8c66c6-389b-11e6-97a7-d933a6b433e0.png)

**Comment by panthony** [comment]
Hi,

I think this is not possible unless #1327 is fixed :)

Maybe this ticket could be closed ?

**Comment by hanu412** [comment]
This can be closed. I figured out a way. Will share the exact code in a
while. Currently our TFS server is down and I have a working copy of the
code. Will paste the production version .

**Comment by panthony** [comment]
I'd be interested because I was looking to add some space between bars too :)

**Comment by hanu412** [comment]
Here is the JS file I am using in production. I actually wrote the code using Typescript.

Hope it helps.


/// <reference path="typings/c3/c3.d.ts" />
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var ChartData = (function () {
    function ChartData(dataTitle, data, dataCategories) {
        this.ChartTitle = dataTitle;
        this.Categories = dataCategories;
        this.Data = data;
    }
    return ChartData;
}());
var TIBChart = (function () {
    function TIBChart(elementId, data) {
       
        this.Columns = [];
        this.Title = data.ChartTitle;
        this.Data = data.Data;
        this.Categories = data.Categories;
        this.DomElement = document.getElementById(elementId);
        this.Columns.push(data.ChartTitle);
        for (var x in data.Data) {
            this.Columns.push(data.Data[x]);
        }
    }
    TIBChart.prototype.DrawChart = function (configuration) {
        c3.generate(configuration);
    };
    return TIBChart;
}());
var BarChart = (function (_super) {
    __extends(BarChart, _super);
    function BarChart(elementId, data) {
        _super.call(this, elementId, data);
    }
    BarChart.prototype.ConfigureChart = function (height, width, barwidth) {
        this.Type = 'bar';
        this.BarWidth = barwidth;
        this.Configuration = {
            bindto: this.DomElement,
            size: {
                width: width,
                height: height
            },
            data: {
                columns: [this.Columns],
                type: this.Type
            },
            color: {
                pattern: ['rgb(127,171,60)', 'rgb(0,172,230)', 'rgb(153, 204, 0)', 'red', 'grey']
            },
            bar: {
                width: {
                    ratio: this.BarWidth
                }
            },
            tooltip: {
                show: true,
                format: {
                    name: function (name, ratio, id, index) { return name + '    :   ' + '   '; }
                },
                position: function (data, width, height, element) {
                    return { top: 10, left: 10 }
                }
               
            },
            legend: {
                position: 'bottom'
            },
            axis: {
                x: {
                    type: 'category',
                    categories: this.Categories
                }
            }
        };
    };
    BarChart.prototype.Draw = function () {
        ///<summary>This Function will draw the svg bar chart and bind it to the DOM element specified </summary>
        this.DrawChart(this.Configuration);
    };
    return BarChart;
}(TIBChart));
var DonutChart = (function (_super) {
    __extends(DonutChart, _super);
    function DonutChart(elementId, cdata) {
        _super.call(this, elementId, cdata);
    }
    DonutChart.prototype.ConfigureChart = function (donutwidth, width, height) {
        this.Columns = [];
        for (var index in this.Categories) {
            var graphdata = [];
            graphdata.push(this.Categories[index]);
            graphdata.push(this.Data[index]);
            this.Columns.push(graphdata);
        }
        this.Configuration = {
            bindto: this.DomElement,
            size: {
                width: width,
                height: height
            },
            data: {
                columns: this.Columns,
                type: 'donut'
            },
            color: {
                pattern: ['rgb(127,171,60)', 'rgb(0,172,230)', 'red', 'grey', 'yellow', 'blue']
            },
            donut: {
                title: this.Title,
                width: donutwidth ? donutwidth : 50,
                expand: true,
                label: {
                    show: true,
                    threshold: 0.2
                }
            },
            tooltip: {
                show: true,
                format: {
                                       name: function (name, ratio, id, index) { return name + '   :   ' + '   '; }
                },
                position: function (data, width, height, element) {
                    return { top: 10, left: 10 }
                }
            },
            legend: {
                position: 'right'
            }
            
        };
    };
    DonutChart.prototype.Draw = function () {
        ///<summary>This Function will draw the svg donut chart and bind it to the DOM element specified </summary>
        
        this.DrawChart(this.Configuration);
    };
    return DonutChart;
}(TIBChart));
//# sourceMappingURL=tibchart.js.map
