### ISSUE TITLE
Suggestion: Option for Bar max width.

### ISSUE THREAD

**Issue by fabric-io-rodrigues** [c3js/c3#174]
Hello to all ,

I'm brazilian, sorry for english ( not very good ) .

I would suggest : Include an option that sets the maximum width of each bar ( the bar graph ) .

Which is only visible ( highlighted) when only one or two values ​​in the chart. As shown in the figure :

![image](https://cloud.githubusercontent.com/assets/4131392/2778355/4b33fca6-caf1-11e3-84a9-a7545c8f6d1f.png)

By setting this option , looks like this:

![image](https://cloud.githubusercontent.com/assets/4131392/2778370/649fd50c-caf1-11e3-8b31-6029882892e4.png)

---

I've done the modification in my code , but worked well as it was interesting to share this suggestion .

In the JS code :
....
220:
![image](https://cloud.githubusercontent.com/assets/4131392/2778435/17ebb554-caf2-11e3-951d-6501b80ad6b8.png)

1900:
![image](https://cloud.githubusercontent.com/assets/4131392/2778422/f2eb6ae2-caf1-11e3-8be9-97b7c19acc56.png)

---

In HTML : 
## ![image](https://cloud.githubusercontent.com/assets/4131392/2778414/e078938a-caf1-11e3-9bba-d2d354ecc6c0.png)

Congratulations for the work , this chart will help me a lot.
Sincerely,
Fabrício

**Comment by buremba** [comment]
It seems `bar.width.max` option is removed. Is there any specific reason for this?

**Comment by haroon786** [comment]
plz help me out how to set

**Comment by haroon786** [comment]
http://stackoverflow.com/questions/39590838/how-to-set-bar-width?noredirect=1#comment66490537_39590838
plz help me out ,how to set bar width for single comes dynamically

**Comment by aendrew** [comment]
@haroon786 Ask in any support channel that is [not here](https://github.com/c3js/c3#using-the-issue-queue).

**Comment by haroon786** [comment]
Actually i want solution of already discussed by *FabricioRHS
<https://github.com/FabricioRHS>  in detail *

On Tue, Sep 20, 2016 at 6:02 PM, Ændrew Rininsland <notifications@github.com
