### ISSUE TITLE
Wrong D3 version for dependencies on the website

### ISSUE THREAD

**Issue by stof** [c3js/c3#1743]
The readme says that C3 depends on D3 `~3.5.0`. But the website says that it depends on D3 `<= 3.5.0`, which is not the same at all

**Comment by Manu1400** [comment]
Repository about c3js.org website : https://github.com/c3js/c3js.org

**Comment by aendrew** [comment]
Once we drop 1.0.0, the docs website will be auto-generated and this won't be an issue. See: c3js/c3js.org#43.

**Comment by kt3k** [comment]
Fixed in this PR https://github.com/c3js/c3js.org/pull/40

Thanks for reporting!
