### ISSUE TITLE
Exploded pie

### ISSUE THREAD

**Issue by missingdays** [c3js/c3#1754]
Would be great if there was an option to explode all pieces of pie chart like this
![exploded pie](https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Charts_SVG_Example_13_-_Exploded_Pie_Chart.svg/2000px-Charts_SVG_Example_13_-_Exploded_Pie_Chart.svg.png)

For example, this explode radius could be set via pie.explodeRadius, and it would be available through 
chart.pie.explodeRadius() API.

I have already implemented this in my fork, but I need some hints about integrating it.
For example, should this option be animated?

Anyway, I will send my pull request, and if something is incorrect, I will fix it.

**Comment by panthony** [comment]
Is this the same feature as #1920 ? If so, I'd close in favor of #1920 as `padAngle` is matching the d3 option name.

**Comment by missingdays** [comment]
@panthony yep, looks like #1920 is the same

**Comment by panthony** [comment]
Ok ! Let's close this one then !
