### ISSUE TITLE
Floating Labels

### ISSUE THREAD

**Issue by GermainBergeron** [c3js/c3#1758]
Related to #1079, if you enable the labels you can get in a weird state where the labels are visible, but not correctly placed. 

![image](https://cloud.githubusercontent.com/assets/260007/16631857/5c77628c-438f-11e6-841e-121b337da544.png)

**JSFiddle where this can be reproduced on all the major browsers:**

http://jsfiddle.net/cqwrc2od/

**Steps to reproduce:**
1. Double click an item on the legend, effectively disabling and re-enabling one of the columns before the animation has time to complete.

I reviewed the code and I think it can happens on the grid and regions too. The transitions are used in the same way.

**Comment by panthony** [comment]
This issue seems to be resolved.
