### ISSUE TITLE
TypeError: c.scale is undefined

### ISSUE THREAD

**Issue by DestructionOfPlanetJupiter** [c3js/c3#1761]
```
...is,b=a.config,c=a.d3,d=b.data_colors,e=v(b.color_pattern)?b.color_pattern:c.scal...
```
```
<html>
<div id="chartContainer">
  <!-- Load c3.css -->
<link href="c3/c3.css" rel="stylesheet" type="text/css">

<!-- Load d3.js and c3.js -->
<script src="c3/d3.js" charset="utf-8"></script>
<script src="c3/c3.min.js"></script>

  

<div id="chart"></div>

<script>
var chart = c3.generate({
    bindto: '#chart',
    data: {
      columns: [
        ['data1', 30, 200, 100, 400, 150, 250],
        ['data2', 50, 20, 10, 40, 15, 25]
      ]
    }
});
</script>
</div>
</html>
```

**Comment by clemsept** [comment]
I have the same problem (with the same example).
The error message changes to `d3.scale is undefined (c3.js:5783:22)` when we replace the `c3.min.js` file by `c3.js`.

**Comment by hirnwunde** [comment]
I had with both, `c3.js` and `c3.min.js` the same behavior.
After some investigation and code changing it figured out `d3` is the problem.
```javascript
var chart = c3.generate({
	bindto: '#chart',
	data: {
		columns: [
			['data1', 30, 200, 100, 400, 150, 250],
			['data2', 50, 20, 10, 40, 15, 25]
		]
	}
});

```
Gave me the error `TypeError: d3.scale is undefined c3.js:5504:23`  
c3 version: 0.4.10 - not minified - local copy
d3 version: 4.0.0 - also not minified - local copy

after changing to d3 version 3.5.17 (loaded from http://d3js.org/d3.v3.js) the chart renders flawleslly.

**Comment by DestructionOfPlanetJupiter** [comment]
which version of c3 and d3 am I supposed to take?

**Comment by DestructionOfPlanetJupiter** [comment]
Tested locally and it works ...

**Comment by alantygel** [comment]
The trick here is to include d3 before c3.
