### ISSUE TITLE
Flow History

### ISSUE THREAD

**Issue by AnjumanR** [c3js/c3#1769]
@masayuki0812 
Is there a way to pause a flow in C3 and go back to look at previous data?

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
