### ISSUE TITLE
[question] Do you know how to do rainbow line color for line chart?

### ISSUE THREAD

**Issue by mtermoul** [c3js/c3#1777]
Is there a way to make the line chart line color set as a rainbow starting from red to blue let's say?

I think in D3 there is a feature called 

`var color = d3.interpolateRainbow;`

here is an example:

http://bl.ocks.org/mbostock/4163057

I want something similar but in regards of the line chart color.

**Comment by aendrew** [comment]
Hi there! We try to keep the issue queue clear for specific code-related problems with C3, could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3) instead? Thank you!
