### ISSUE TITLE
error installing: "window is not defined"

### ISSUE THREAD

**Issue by paulgiordano** [c3js/c3#1785]
When installing c3 0.4.11 receive the following:

git clone https://github.com/c3js/c3
zip -r c3.zip c3

root@logstash-chi:/opt/kibana# bin/kibana plugin --install c3 --url file:///opt/kibana/c3.zip
Installing c3
Attempting to transfer from file:///opt/kibana/c3.zip
Transferring 6917184 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
[BABEL] Note: The code generator has deoptimised the styling of "/opt/kibana/installedPlugins/c3/c3.js" as it exceeds the max of "100KB".
Plugin installation was unsuccessful due to error "window is not defined"

**Comment by panthony** [comment]
For questions involving the interplay between C3.js and any other library (react, vuejs, ..) please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

May be related with #1847 though.
