### ISSUE TITLE
Need help for multi line time series chart

### ISSUE THREAD

**Issue by rajmvr25** [c3js/c3#1791]
Hi Team,

I have created new multi line time series chart.I have  two lines which represents min and max values.But the requirement is to plot min max values in to one line for particular time .
Can any one help me on this.

![image](https://cloud.githubusercontent.com/assets/8037007/17380173/7ff70432-59e3-11e6-9c0f-a63903ccd698.png)

Above image two black lines are min max values .I need to combine or plot the data in one line.Can any one provide example or solution?

Thanks in advance,
Rajesh.

**Comment by rajmvr25** [comment]
Here is my code for plot the chart
function generateTimeSeriesGraph(dataX,dataA,dataNLC,starttime,minSafeTmp,maxSafeTmp,timeticks,timeformat,minScaleTemp,maxScaleTemp) {
	  //alert(timescale)
	  //alert(prevDate)

	  var labelMin = 'Min Air Temperature';
	  var labelMax = 'Max Air Temperature';
	  var labelAvg = 'Average Air Temperature';
	  var labelNLC = 'Est. Product Temperature';
	  var times = 'times';
	  var dataTimeX = [times].concat(getCol(dataX,0));
	  //dataTimeX = getCol(dataX,0);
	  var dataXMax = [labelMax].concat(getCol(dataX,1));
	  var dataXMin = [labelMin].concat(getCol(dataX,2));
	  var c3DataA = [labelAvg].concat(getCol(dataA,1));
	  var c3DataNLC = [labelNLC].concat(getCol(dataNLC, 1));
	  //alert(dataTimeX);
	  var d = (30 * 24 * 3600); // last 30 days

	  var array_times = dataTimeX;
	  //var array_values = [67, 66.22, 68, 68, 68, 77];
	  //var window_period = (30 * 24 * 3600); // last 30 days


	  function dateToString(e) {
		  //alert(e);
	      var date = new Date(e);
	      //alert(date);
	     // return monthNames[date.getMonth()].concat(" "+date.getFullYear());
	       return date.toDateString().substring(4);;
	  }
    
	 
	  var chart = c3.generate({
	      bindto: '#timeseries',
	      data: {
	    	 selection: { 
            enabled : false
				  }, 
	    	 x: 'times',
	    	
	          columns: [
	                dataTimeX,dataXMax,dataXMin,c3DataA,c3DataNLC
	           
	          ],
	         
	          type: 'spline',
	          
	          types: {
	        	  
	        	  'Est. Product Temperature' : 'spline',
	        	  'Average Air Temperature' :'spline'
	        	  },
	        	 
	          colors: {
	        	  
	        	  'Min Air Temperature': "black",
	        	  'Max Air Temperature': "black",
	        	  //'Est. Product Temperature': 'FE720F'
	        	  'Est. Product Temperature': 'orange'
	        	
	          },
	          empty : {
					label : {
						text : "No Data Available"
					}
				},
				
				
	      },
	      tooltip: {
              show: false
          },
	      bar: {
    		  width: 2,
    		 // zerobased: false,
    		},
	      point: {
	          r: 2.8
	      },
	      legend: {
	          show: true
	      },
	      grid: {
	          x: {
	              show: true
	          },
	          y: {
	              show: true
	          }
	      },
	      subchart: {
	          show: true
	        },
	        zoom: {
	        	 enabled: true
	           // type: 'drag', // can be [drag, scroll]
	            //disableDefaultBehavior: false
	        },
	        axis: {
	            x: {
	            	
	            	extent: [prevDate,now],
	            	//default:starttime,now,
	                label: {
	                    text: 'Time ['+timescale+']'
	                },
	                type: 'timeseries',
	                tick: {
	                	
	                	culling: {
	                        max: 1 // the number of tick texts will be adjusted to less than this value
	                    },
	                     count: timeticks,
	                    //rotate: -75,
	                    multiline: false,
	                    format: timeformat
	               
	                
	                },
	               
	            },
	        
	        y: {
	            label: {
	                text: 'Temperature',
	                position: 'outer',
	                
	            },
	            tick: {
	            	
	                	
	                format: function (e, d) {
	                    return parseFloat(e).toFixed(1);
	                }
	            }
	        }
	        }
	        ,
	        regions: [
	                  
	                  {axis: 'y', end: minSafeTmp, class: 'regionRED'},
	                  {axis: 'y', start:minSafeTmp, end: maxSafeTmp, class: 'regionSAFE'},
	                  {axis: 'y', start: maxSafeTmp, class: 'regionRED'},
	              ],
	        area: {
	        	 
	        	}
	        ,
	        legend: {
	            item: {
	                onclick: function () {
	                	
	                }
	            }
	        }/*
	        Disables interaction on the graph
	        ,
	        interaction: {
	            enabled: false
	        }*/
	        
	  });
	  
	  chart.axis.range({
		    min: {
		       x: starttime,
		       y:minScaleTemp
		       
		    },
		    max: {
		      x: now,
		      y:maxScaleTemp
		       
		    }
		});
	  
	}

**Comment by brookemarshassoc** [comment]
Try an area chart.. with max = black and min = white (undo the black)

http://c3js.org/samples/chart_area.html

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
