### ISSUE TITLE
Quit curve on data point with zero value

### ISSUE THREAD

**Issue by nice00xt** [c3js/c3#1792]
i have a graph when set the zero values don't show the dots, but if it have values then it show 
the graph look like this
https://drive.google.com/open?id=0B3i_LHuXTynabVpiU1RQdF9OakE
the issue is that i want to quit the curve only when show zero values and set a flat line only in that part
it is possible?

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
