### ISSUE TITLE
Is it possible to have more values on the tooltip?

### ISSUE THREAD

**Issue by vparakh14** [c3js/c3#180]
In the tool tip, is there a way where in more information along with the data on the y-axis can be shown? My use-case is, I am having probabilities on the y-axis but in the tool tip, along with the probabilities I would also like to show the sample data size. Is there a way to do this?

**Comment by qfan** [comment]
Found a solution:
http://stackoverflow.com/a/25750639/1003746

**Comment by intotecho** [comment]
Building on that solution to insert metadata data into the chart using data.classes
https://stackoverflow.com/a/47824091/2023941

**Comment by pchaganti** [comment]
👍

**Comment by Reynolddoss** [comment]
Absolutely ... Just modify  the tooltip content and add your own html format that suits your requirement.
