### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by ericrange** [c3js/c3#1801]
I use c3 in one of my projects and i dont want to switch to another one in the future.
Can anybody tell me if c3 is dead? i see all the issues but nothing happends in the code anymore :/

**Comment by aendrew** [comment]
It's an ongoing struggle to maintain the issue queue but C3 is still very much still in development. See #1540.

If you want to help, talk to me on Gitter about aiding us with issue queue triage. :smile:
