### ISSUE TITLE
Bar Chart not displaying correctly when reading data from JSON

### ISSUE THREAD

**Issue by jmcguire23** [c3js/c3#1802]
Hi all,

I have discovered a bug when reading from an external json source and rendering a bar chart, the bars appear off center and thinner than the usual default setting. Trying to set a width for the bars doesn't have affect on this and they scale beyond the chart if there a multiple bars in view.

I have replicated this bug here : http://jsfiddle.net/j49hdn1p/18/

**Comment by panthony** [comment]
Hi,

I think you are not using the JSON input properly, you are doing this essentially:

http://jsfiddle.net/t1hcuh7L/

Note that in the exemple:

http://c3js.org/reference.html#data-json

All json items have all values.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.
