### ISSUE TITLE
Calling on external function within onClick

### ISSUE THREAD

**Issue by steverhodes10** [c3js/c3#1804]
For some reason I cannot call upon my method within the c3.generate function that is in the same component.

The c3 chart is called from the template and it works perfectly. I have tested my somethingMethod() with a button in the template and it works.

I want to be able to call on the somethingMethod() with the c3 onclick function but it's not working. It won't even load this.someTypeTitle='asda'; But an alert works so I'm thinking that I am out of scope but not exactly sure how to fix it.

@Component({
    selector: 'something',
    templateUrl: 'something.component.html',

})
export class SomethingComponent{

    someTypeTitle: string;
getData(input: string): Array<number>{
return data;
}
somethingMethod(input: string){
someTypeTitle=input;
}

getChart() {
var chart = c3.generate({
            bindto: '#stackedbar',

            data: {
                x: 'x',
                columns: [
                   this.getData(someString),
                   this.getData(someString) //These work
                ],

                onclick: function (d, e) {

               alert(this.internal.config.axis_x_categories[d.x]); // This works
               this.someTypeTitle="asdad"; //This doesn't work.
               this.someTypeTitle=  this.internal.config.axis_x_categories[d.x]; //This doesn't work.              
               this.somethingMethod(this.internal.config.axis_x_categories[d.x]); //This doesn't work.

                },
}...

**Comment by missingdays** [comment]
onclick method doesn't keep it contex, thus **this** will not be original **this** or **chart**. As far as I know it gets bound to html element.
You should reference **chart*** by it's name.

```javascript
var chart = c3.generate({
    onclick: function(d, e){
        chart.somethingMethod(chart.internal.config.axis_x_categories[d.x]);
    }
});
```

**Comment by steverhodes10** [comment]
I'm at work and those sites are banned but if you go here, http://c3js.org/samples/categorized.html and then put in this function right after columns: [] it seems to simulate what I am doing.
        onclick: function (d,e){
            alert(this.internal.config.axis_x_categories[d.x]);
        }

it works. 

 Is there a way to call on an external function from within there?
Thanks.

-Steve
