### ISSUE TITLE
data.onclick not working in firefox (mac v47.0)

### ISSUE THREAD

**Issue by themichaelkarpen** [c3js/c3#1808]
When I console.log(d) in the onclick event, it works great in chrome. But nothing happens in firefox (testing on a mac - v47.0). In fact, when hovering over the data point, the cursor does not change (no indication of a link).

Here is my code:
`c3.generate({
            bindto: '#chart_trends',
            padding: { right: 40 },
            color: { pattern: ['#428BCA', '#fee500', '#989898', '#333333'] },
            legend: { hide: false },
            data: {
                x: 'x',
                xFormat: '%m/%d/%y',
                columns: [
                    ['x', '08/03/16', '08/04/16', '08/05/16', '08/06/16', '08/07/16', '08/08/16'],
                    ['Total Post Value', 30, 200, 100, 400, 150, 250]
                ], 
                selection: { enabled: true }, 
                onclick: function (d, element) {
                    console.log(d)
                }
            },
            axis: {
                x: {
                    type: 'timeseries',
                    tick: { format: '%m/%d' }
                },
                y: { tick: { format: d3.format("$,") } }
            }
});
`

**Comment by jarea** [comment]
I found that were some bugs in Firefox’s implementation of getScreenCTM. You can see the similar issue here: https://github.com/d3/d3/issues/2810

**Comment by panthony** [comment]
This was apprently a bug upstream. Fill free to reopen if still an issue
