### ISSUE TITLE
Weird line chart - line become lasso

### ISSUE THREAD

**Issue by indr4winata** [c3js/c3#1817]
Graph is OK (type: area-spline) when there are only few points or many points but the gap is near.
But when it try to render many points and the gap between previous point to next point is far (many null data), line on graph become lasso-like. It is very weird

My options are:
`data: {
	columns: [
		["Max. Signal Bars",2,2,2,2,2,null,2,2,2,2,2,2,2,2,2,2,2,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null
,null,null,null,null,null,null,3,2,1,1,2,null,1,2,1,null,1,1,1,2,null,1,null,1,1,2,2,2,1,2,null,2,2,2
,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,null,null,1,2,1,2,2,2,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,null
,2,2,2,2,2,null,1,2,2,2,2,2,2,2,2,2,2,2,null,null,null,null]
	],
	type: "area-spline",
	empty: {
		label: {
			text: "No Data"
		}
	}
},
line: {
	connectNull: true
},
axis: {
	x: {
		type: 'category',
		categories: ["31 Jul (23:00 - 23:59)","01
 Aug (00:00 - 00:59)","01 Aug (01:00 - 01:59)","01 Aug (02:00 - 02:59)","01 Aug (03:00 - 03:59)","01
 Aug (04:00 - 04:59)","01 Aug (05:00 - 05:59)","01 Aug (06:00 - 06:59)","01 Aug (07:00 - 07:59)","01
 Aug (08:00 - 08:59)","01 Aug (09:00 - 09:59)","01 Aug (10:00 - 10:59)","01 Aug (11:00 - 11:59)","01
 Aug (12:00 - 12:59)","01 Aug (13:00 - 13:59)","01 Aug (14:00 - 14:59)","01 Aug (15:00 - 15:59)","01
 Aug (16:00 - 16:59)","01 Aug (17:00 - 17:59)","01 Aug (18:00 - 18:59)","01 Aug (19:00 - 19:59)","01
 Aug (20:00 - 20:59)","01 Aug (21:00 - 21:59)","01 Aug (22:00 - 22:59)","01 Aug (23:00 - 23:59)","02
 Aug (00:00 - 00:59)","02 Aug (01:00 - 01:59)","02 Aug (02:00 - 02:59)","02 Aug (03:00 - 03:59)","02
 Aug (04:00 - 04:59)","02 Aug (05:00 - 05:59)","02 Aug (06:00 - 06:59)","02 Aug (07:00 - 07:59)","02
 Aug (08:00 - 08:59)","02 Aug (09:00 - 09:59)","02 Aug (10:00 - 10:59)","02 Aug (11:00 - 11:59)","02
 Aug (12:00 - 12:59)","02 Aug (13:00 - 13:59)","02 Aug (14:00 - 14:59)","02 Aug (15:00 - 15:59)","02
 Aug (16:00 - 16:59)","02 Aug (17:00 - 17:59)","02 Aug (18:00 - 18:59)","02 Aug (19:00 - 19:59)","02
 Aug (20:00 - 20:59)","02 Aug (21:00 - 21:59)","02 Aug (22:00 - 22:59)","02 Aug (23:00 - 23:59)","03
 Aug (00:00 - 00:59)","03 Aug (01:00 - 01:59)","03 Aug (02:00 - 02:59)","03 Aug (03:00 - 03:59)","03
 Aug (04:00 - 04:59)","03 Aug (05:00 - 05:59)","03 Aug (06:00 - 06:59)","03 Aug (07:00 - 07:59)","03
 Aug (08:00 - 08:59)","03 Aug (09:00 - 09:59)","03 Aug (10:00 - 10:59)","03 Aug (11:00 - 11:59)","03
 Aug (12:00 - 12:59)","03 Aug (13:00 - 13:59)","03 Aug (14:00 - 14:59)","03 Aug (15:00 - 15:59)","03
 Aug (16:00 - 16:59)","03 Aug (17:00 - 17:59)","03 Aug (18:00 - 18:59)","03 Aug (19:00 - 19:59)","03
 Aug (20:00 - 20:59)","03 Aug (21:00 - 21:59)","03 Aug (22:00 - 22:59)","03 Aug (23:00 - 23:59)","04
 Aug (00:00 - 00:59)","04 Aug (01:00 - 01:59)","04 Aug (02:00 - 02:59)","04 Aug (03:00 - 03:59)","04
 Aug (04:00 - 04:59)","04 Aug (05:00 - 05:59)","04 Aug (06:00 - 06:59)","04 Aug (07:00 - 07:59)","04
 Aug (08:00 - 08:59)","04 Aug (09:00 - 09:59)","04 Aug (10:00 - 10:59)","04 Aug (11:00 - 11:59)","04
 Aug (12:00 - 12:59)","04 Aug (13:00 - 13:59)","04 Aug (14:00 - 14:59)","04 Aug (15:00 - 15:59)","04
 Aug (16:00 - 16:59)","04 Aug (17:00 - 17:59)","04 Aug (18:00 - 18:59)","04 Aug (19:00 - 19:59)","04
 Aug (20:00 - 20:59)","04 Aug (21:00 - 21:59)","04 Aug (22:00 - 22:59)","04 Aug (23:00 - 23:59)","05
 Aug (00:00 - 00:59)","05 Aug (01:00 - 01:59)","05 Aug (02:00 - 02:59)","05 Aug (03:00 - 03:59)","05
 Aug (04:00 - 04:59)","05 Aug (05:00 - 05:59)","05 Aug (06:00 - 06:59)","05 Aug (07:00 - 07:59)","05
 Aug (08:00 - 08:59)","05 Aug (09:00 - 09:59)","05 Aug (10:00 - 10:59)","05 Aug (11:00 - 11:59)","05
 Aug (12:00 - 12:59)","05 Aug (13:00 - 13:59)","05 Aug (14:00 - 14:59)","05 Aug (15:00 - 15:59)","05
 Aug (16:00 - 16:59)","05 Aug (17:00 - 17:59)","05 Aug (18:00 - 18:59)","05 Aug (19:00 - 19:59)","05
 Aug (20:00 - 20:59)","05 Aug (21:00 - 21:59)","05 Aug (22:00 - 22:59)","05 Aug (23:00 - 23:59)","06
 Aug (00:00 - 00:59)","06 Aug (01:00 - 01:59)","06 Aug (02:00 - 02:59)","06 Aug (03:00 - 03:59)","06
 Aug (04:00 - 04:59)","06 Aug (05:00 - 05:59)","06 Aug (06:00 - 06:59)","06 Aug (07:00 - 07:59)","06
 Aug (08:00 - 08:59)","06 Aug (09:00 - 09:59)","06 Aug (10:00 - 10:59)","06 Aug (11:00 - 11:59)","06
 Aug (12:00 - 12:59)","06 Aug (13:00 - 13:59)","06 Aug (14:00 - 14:59)","06 Aug (15:00 - 15:59)","06
 Aug (16:00 - 16:59)","06 Aug (17:00 - 17:59)","06 Aug (18:00 - 18:59)","06 Aug (19:00 - 19:59)","06
 Aug (20:00 - 20:59)","06 Aug (21:00 - 21:59)","06 Aug (22:00 - 22:59)","06 Aug (23:00 - 23:59)","07
 Aug (00:00 - 00:59)","07 Aug (01:00 - 01:59)","07 Aug (02:00 - 02:59)","07 Aug (03:00 - 03:59)","07
 Aug (04:00 - 04:59)","07 Aug (05:00 - 05:59)","07 Aug (06:00 - 06:59)","07 Aug (07:00 - 07:59)","07
 Aug (08:00 - 08:59)","07 Aug (09:00 - 09:59)","07 Aug (10:00 - 10:59)","07 Aug (11:00 - 11:59)","07
 Aug (12:00 - 12:59)","07 Aug (13:00 - 13:59)","07 Aug (14:00 - 14:59)","07 Aug (15:00 - 15:59)","07
 Aug (16:00 - 16:59)","07 Aug (17:00 - 17:59)","07 Aug (18:00 - 18:59)","07 Aug (19:00 - 19:59)","07
 Aug (20:00 - 20:59)","07 Aug (21:00 - 21:59)","07 Aug (22:00 - 22:59)","07 Aug (23:00 - 23:59)","08
 Aug (00:00 - 00:59)","08 Aug (01:00 - 01:59)","08 Aug (02:00 - 02:59)","08 Aug (03:00 - 03:59)","08
 Aug (04:00 - 04:59)","08 Aug (05:00 - 05:59)","08 Aug (06:00 - 06:59)","08 Aug (07:00 - 07:59)","08
 Aug (08:00 - 08:59)","08 Aug (09:00 - 09:59)","08 Aug (10:00 - 10:59)","08 Aug (11:00 - 11:59)","08
 Aug (12:00 - 12:59)","08 Aug (13:00 - 13:59)","08 Aug (14:00 - 14:59)","08 Aug (15:00 - 15:59)","08
 Aug (16:00 - 16:59)","08 Aug (17:00 - 17:59)","08 Aug (18:00 - 18:59)","08 Aug (19:00 - 19:59)","08
 Aug (20:00 - 20:59)","08 Aug (21:00 - 21:59)","08 Aug (22:00 - 22:59)","08 Aug (23:00 - 23:59)","09
 Aug (00:00 - 00:59)","09 Aug (01:00 - 01:59)","09 Aug (02:00 - 02:59)","09 Aug (03:00 - 03:59)","09
 Aug (04:00 - 04:59)","09 Aug (05:00 - 05:59)","09 Aug (06:00 - 06:59)","09 Aug (07:00 - 07:59)","09
 Aug (08:00 - 08:59)","09 Aug (09:00 - 09:59)","09 Aug (10:00 - 10:59)","09 Aug (11:00 - 11:59)","09
 Aug (12:00 - 12:59)","09 Aug (13:00 - 13:59)","09 Aug (14:00 - 14:59)","09 Aug (15:00 - 15:59)","09
 Aug (16:00 - 16:59)","09 Aug (17:00 - 17:59)","09 Aug (18:00 - 18:59)","09 Aug (19:00 - 19:59)","09
 Aug (20:00 - 20:59)","09 Aug (21:00 - 21:59)","09 Aug (22:00 - 22:59)","09 Aug (23:00 - 23:59)","10
 Aug (00:00 - 00:59)","10 Aug (01:00 - 01:59)","10 Aug (02:00 - 02:59)","10 Aug (03:00 - 03:59)","10
 Aug (04:00 - 04:59)","10 Aug (05:00 - 05:59)","10 Aug (06:00 - 06:59)","10 Aug (07:00 - 07:59)","10
 Aug (08:00 - 08:59)","10 Aug (09:00 - 09:59)","10 Aug (10:00 - 10:59)","10 Aug (11:00 - 11:59)","10
 Aug (12:00 - 12:59)","10 Aug (13:00 - 13:59)","10 Aug (14:00 - 14:59)","10 Aug (15:00 - 15:59)","10
 Aug (16:00 - 16:59)","10 Aug (17:00 - 17:59)","10 Aug (18:00 - 18:59)","10 Aug (19:00 - 19:59)","10
 Aug (20:00 - 20:59)","10 Aug (21:00 - 21:59)","10 Aug (22:00 - 22:59)","10 Aug (23:00 - 23:59)","11
 Aug (00:00 - 00:59)","11 Aug (01:00 - 01:59)","11 Aug (02:00 - 02:59)","11 Aug (03:00 - 03:59)","11
 Aug (04:00 - 04:59)","11 Aug (05:00 - 05:59)","11 Aug (06:00 - 06:59)","11 Aug (07:00 - 07:59)","11
 Aug (08:00 - 08:59)","11 Aug (09:00 - 09:59)","11 Aug (10:00 - 10:59)","11 Aug (11:00 - 11:59)","11
 Aug (12:00 - 12:59)","11 Aug (13:00 - 13:59)","11 Aug (14:00 - 14:59)","11 Aug (15:00 - 15:59)","11
 Aug (16:00 - 16:59)","11 Aug (17:00 - 17:59)","11 Aug (18:00 - 18:59)","11 Aug (19:00 - 19:59)","11
 Aug (20:00 - 20:59)","11 Aug (21:00 - 21:59)","11 Aug (22:00 - 22:59)","11 Aug (23:00 - 23:59)","12
 Aug (00:00 - 00:59)","12 Aug (01:00 - 01:59)","12 Aug (02:00 - 02:59)","12 Aug (03:00 - 03:59)","12
 Aug (04:00 - 04:59)","12 Aug (05:00 - 05:59)","12 Aug (06:00 - 06:59)","12 Aug (07:00 - 07:59)","12
 Aug (08:00 - 08:59)","12 Aug (09:00 - 09:59)","12 Aug (10:00 - 10:59)","12 Aug (11:00 - 11:59)","12
 Aug (12:00 - 12:59)","12 Aug (13:00 - 13:59)","12 Aug (14:00 - 14:59)","12 Aug (15:00 - 15:59)","12
 Aug (16:00 - 16:59)","12 Aug (17:00 - 17:59)","12 Aug (18:00 - 18:59)","12 Aug (19:00 - 19:59)","12
 Aug (20:00 - 20:59)","12 Aug (21:00 - 21:59)","12 Aug (22:00 - 22:59)","12 Aug (23:00 - 23:59)","13
 Aug (00:00 - 00:59)","13 Aug (01:00 - 01:59)","13 Aug (02:00 - 02:59)","13 Aug (03:00 - 03:59)","13
 Aug (04:00 - 04:59)","13 Aug (05:00 - 05:59)","13 Aug (06:00 - 06:59)","13 Aug (07:00 - 07:59)","13
 Aug (08:00 - 08:59)","13 Aug (09:00 - 09:59)","13 Aug (10:00 - 10:59)","13 Aug (11:00 - 11:59)","13
 Aug (12:00 - 12:59)","13 Aug (13:00 - 13:59)","13 Aug (14:00 - 14:59)","13 Aug (15:00 - 15:59)","13
 Aug (16:00 - 16:59)","13 Aug (17:00 - 17:59)","13 Aug (18:00 - 18:59)","13 Aug (19:00 - 19:59)","13
 Aug (20:00 - 20:59)","13 Aug (21:00 - 21:59)","13 Aug (22:00 - 22:59)","13 Aug (23:00 - 23:59)","14
 Aug (00:00 - 00:59)","14 Aug (01:00 - 01:59)","14 Aug (02:00 - 02:59)","14 Aug (03:00 - 03:59)","14
 Aug (04:00 - 04:59)","14 Aug (05:00 - 05:59)","14 Aug (06:00 - 06:59)","14 Aug (07:00 - 07:59)","14
 Aug (08:00 - 08:59)","14 Aug (09:00 - 09:59)","14 Aug (10:00 - 10:59)","14 Aug (11:00 - 11:59)","14
 Aug (12:00 - 12:59)","14 Aug (13:00 - 13:59)","14 Aug (14:00 - 14:59)","14 Aug (15:00 - 15:59)","14
 Aug (16:00 - 16:59)","14 Aug (17:00 - 17:59)","14 Aug (18:00 - 18:59)","14 Aug (19:00 - 19:59)","14
 Aug (20:00 - 20:59)","14 Aug (21:00 - 21:59)","14 Aug (22:00 - 22:59)","14 Aug (23:00 - 23:59)","15
 Aug (00:00 - 00:59)","15 Aug (01:00 - 01:59)","15 Aug (02:00 - 02:59)","15 Aug (03:00 - 03:59)","15
 Aug (04:00 - 04:59)","15 Aug (05:00 - 05:59)","15 Aug (06:00 - 06:59)","15 Aug (07:00 - 07:59)","15
 Aug (08:00 - 08:59)","15 Aug (09:00 - 09:59)","15 Aug (10:00 - 10:59)","15 Aug (11:00 - 11:59)","15
 Aug (12:00 - 12:59)","15 Aug (13:00 - 13:59)","15 Aug (14:00 - 14:59)","15 Aug (15:00 - 15:59)","15
 Aug (16:00 - 16:59)","15 Aug (17:00 - 17:59)","15 Aug (18:00 - 18:59)","15 Aug (19:00 - 19:59)","15
 Aug (20:00 - 20:59)","15 Aug (21:00 - 21:59)","15 Aug (22:00 - 22:59)","15 Aug (23:00 - 23:59)","16
 Aug (00:00 - 00:59)","16 Aug (01:00 - 01:59)","16 Aug (02:00 - 02:59)","16 Aug (03:00 - 03:59)","16
 Aug (04:00 - 04:59)","16 Aug (05:00 - 05:59)","16 Aug (06:00 - 06:59)","16 Aug (07:00 - 07:59)","16
 Aug (08:00 - 08:59)","16 Aug (09:00 - 09:59)","16 Aug (10:00 - 10:59)","16 Aug (11:00 - 11:59)","16
 Aug (12:00 - 12:59)","16 Aug (13:00 - 13:59)","16 Aug (14:00 - 14:59)","16 Aug (15:00 - 15:59)","16
 Aug (16:00 - 16:59)","16 Aug (17:00 - 17:59)","16 Aug (18:00 - 18:59)","16 Aug (19:00 - 19:59)","16
 Aug (20:00 - 20:59)","16 Aug (21:00 - 21:59)","16 Aug (22:00 - 22:59)","16 Aug (23:00 - 23:59)","17
 Aug (00:00 - 00:59)","17 Aug (01:00 - 01:59)","17 Aug (02:00 - 02:59)","17 Aug (03:00 - 03:59)","17
 Aug (04:00 - 04:59)","17 Aug (05:00 - 05:59)","17 Aug (06:00 - 06:59)","17 Aug (07:00 - 07:59)","17
 Aug (08:00 - 08:59)","17 Aug (09:00 - 09:59)","17 Aug (10:00 - 10:59)","17 Aug (11:00 - 11:59)","17
 Aug (12:00 - 12:59)","17 Aug (13:00 - 13:59)","17 Aug (14:00 - 14:59)","17 Aug (15:00 - 15:59)","17
 Aug (16:00 - 16:59)","17 Aug (17:00 - 17:59)","17 Aug (18:00 - 18:59)","17 Aug (19:00 - 19:59)","17
 Aug (20:00 - 20:59)","17 Aug (21:00 - 21:59)","17 Aug (22:00 - 22:59)","17 Aug (23:00 - 23:59)","18
 Aug (00:00 - 00:59)","18 Aug (01:00 - 01:59)","18 Aug (02:00 - 02:59)","18 Aug (03:00 - 03:59)","18
 Aug (04:00 - 04:59)","18 Aug (05:00 - 05:59)","18 Aug (06:00 - 06:59)","18 Aug (07:00 - 07:59)","18
 Aug (08:00 - 08:59)","18 Aug (09:00 - 09:59)","18 Aug (10:00 - 10:59)","18 Aug (11:00 - 11:59)","18
 Aug (12:00 - 12:59)","18 Aug (13:00 - 13:59)","18 Aug (14:00 - 14:59)","18 Aug (15:00 - 15:59)","18
 Aug (16:00 - 16:59)","18 Aug (17:00 - 17:59)","18 Aug (18:00 - 18:59)","18 Aug (19:00 - 19:59)","18
 Aug (20:00 - 20:59)","18 Aug (21:00 - 21:59)","18 Aug (22:00 - 22:59)","18 Aug (23:00 - 23:59)","19
 Aug (00:00 - 00:59)","19 Aug (01:00 - 01:59)","19 Aug (02:00 - 02:59)","19 Aug (03:00 - 03:59)","19
 Aug (04:00 - 04:59)","19 Aug (05:00 - 05:59)","19 Aug (06:00 - 06:59)","19 Aug (07:00 - 07:59)","19
 Aug (08:00 - 08:59)","19 Aug (09:00 - 09:59)","19 Aug (10:00 - 10:59)","19 Aug (11:00 - 11:59)","19
 Aug (12:00 - 12:59)","19 Aug (13:00 - 13:59)","19 Aug (14:00 - 14:59)","19 Aug (15:00 - 15:59)","19
 Aug (16:00 - 16:59)","19 Aug (17:00 - 17:59)","19 Aug (18:00 - 18:59)","19 Aug (19:00 - 19:59)","19
 Aug (20:00 - 20:59)","19 Aug (21:00 - 21:59)","19 Aug (22:00 - 22:59)","19 Aug (23:00 - 23:59)","20
 Aug (00:00 - 00:59)","20 Aug (01:00 - 01:59)","20 Aug (02:00 - 02:59)","20 Aug (03:00 - 03:59)","20
 Aug (04:00 - 04:59)","20 Aug (05:00 - 05:59)","20 Aug (06:00 - 06:59)","20 Aug (07:00 - 07:59)","20
 Aug (08:00 - 08:59)","20 Aug (09:00 - 09:59)","20 Aug (10:00 - 10:59)","20 Aug (11:00 - 11:59)","20
 Aug (12:00 - 12:59)","20 Aug (13:00 - 13:59)","20 Aug (14:00 - 14:59)","20 Aug (15:00 - 15:59)","20
 Aug (16:00 - 16:59)","20 Aug (17:00 - 17:59)","20 Aug (18:00 - 18:59)","20 Aug (19:00 - 19:59)","20
 Aug (20:00 - 20:59)","20 Aug (21:00 - 21:59)","20 Aug (22:00 - 22:59)","20 Aug (23:00 - 23:59)","21
 Aug (00:00 - 00:59)","21 Aug (01:00 - 01:59)","21 Aug (02:00 - 02:59)","21 Aug (03:00 - 03:59)","21
 Aug (04:00 - 04:59)","21 Aug (05:00 - 05:59)","21 Aug (06:00 - 06:59)","21 Aug (07:00 - 07:59)","21
 Aug (08:00 - 08:59)","21 Aug (09:00 - 09:59)","21 Aug (10:00 - 10:59)","21 Aug (11:00 - 11:59)","21
 Aug (12:00 - 12:59)","21 Aug (13:00 - 13:59)","21 Aug (14:00 - 14:59)","21 Aug (15:00 - 15:59)","21
 Aug (16:00 - 16:59)","21 Aug (17:00 - 17:59)","21 Aug (18:00 - 18:59)","21 Aug (19:00 - 19:59)","21
 Aug (20:00 - 20:59)","21 Aug (21:00 - 21:59)","21 Aug (22:00 - 22:59)","21 Aug (23:00 - 23:59)","22
 Aug (00:00 - 00:59)","22 Aug (01:00 - 01:59)","22 Aug (02:00 - 02:59)","22 Aug (03:00 - 03:59)","22
 Aug (04:00 - 04:59)","22 Aug (05:00 - 05:59)","22 Aug (06:00 - 06:59)","22 Aug (07:00 - 07:59)","22
 Aug (08:00 - 08:59)","22 Aug (09:00 - 09:59)","22 Aug (10:00 - 10:59)","22 Aug (11:00 - 11:59)","22
 Aug (12:00 - 12:59)","22 Aug (13:00 - 13:59)","22 Aug (14:00 - 14:59)","22 Aug (15:00 - 15:59)","22
 Aug (16:00 - 16:59)","22 Aug (17:00 - 17:59)","22 Aug (18:00 - 18:59)","22 Aug (19:00 - 19:59)","22
 Aug (20:00 - 20:59)","22 Aug (21:00 - 21:59)","22 Aug (22:00 - 22:59)","22 Aug (23:00 - 23:59)","23
 Aug (00:00 - 00:59)","23 Aug (01:00 - 01:59)","23 Aug (02:00 - 02:59)","23 Aug (03:00 - 03:59)","23
 Aug (04:00 - 04:59)","23 Aug (05:00 - 05:59)","23 Aug (06:00 - 06:59)","23 Aug (07:00 - 07:59)","23
 Aug (08:00 - 08:59)","23 Aug (09:00 - 09:59)","23 Aug (10:00 - 10:59)","23 Aug (11:00 - 11:59)","23
 Aug (12:00 - 12:59)","23 Aug (13:00 - 13:59)","23 Aug (14:00 - 14:59)","23 Aug (15:00 - 15:59)","23
 Aug (16:00 - 16:59)","23 Aug (17:00 - 17:59)","23 Aug (18:00 - 18:59)","23 Aug (19:00 - 19:59)","23
 Aug (20:00 - 20:59)","23 Aug (21:00 - 21:59)","23 Aug (22:00 - 22:59)","23 Aug (23:00 - 23:59)","24
 Aug (00:00 - 00:59)","24 Aug (01:00 - 01:59)","24 Aug (02:00 - 02:59)","24 Aug (03:00 - 03:59)","24
 Aug (04:00 - 04:59)","24 Aug (05:00 - 05:59)","24 Aug (06:00 - 06:59)","24 Aug (07:00 - 07:59)","24
 Aug (08:00 - 08:59)","24 Aug (09:00 - 09:59)","24 Aug (10:00 - 10:59)","24 Aug (11:00 - 11:59)","24
 Aug (12:00 - 12:59)","24 Aug (13:00 - 13:59)","24 Aug (14:00 - 14:59)","24 Aug (15:00 - 15:59)","24
 Aug (16:00 - 16:59)","24 Aug (17:00 - 17:59)","24 Aug (18:00 - 18:59)","24 Aug (19:00 - 19:59)","24
 Aug (20:00 - 20:59)","24 Aug (21:00 - 21:59)","24 Aug (22:00 - 22:59)","24 Aug (23:00 - 23:59)","25
 Aug (00:00 - 00:59)","25 Aug (01:00 - 01:59)","25 Aug (02:00 - 02:59)","25 Aug (03:00 - 03:59)","25
 Aug (04:00 - 04:59)","25 Aug (05:00 - 05:59)","25 Aug (06:00 - 06:59)","25 Aug (07:00 - 07:59)","25
 Aug (08:00 - 08:59)","25 Aug (09:00 - 09:59)","25 Aug (10:00 - 10:59)","25 Aug (11:00 - 11:59)","25
 Aug (12:00 - 12:59)","25 Aug (13:00 - 13:59)","25 Aug (14:00 - 14:59)","25 Aug (15:00 - 15:59)","25
 Aug (16:00 - 16:59)","25 Aug (17:00 - 17:59)","25 Aug (18:00 - 18:59)","25 Aug (19:00 - 19:59)","25
 Aug (20:00 - 20:59)","25 Aug (21:00 - 21:59)","25 Aug (22:00 - 22:59)","25 Aug (23:00 - 23:59)","26
 Aug (00:00 - 00:59)","26 Aug (01:00 - 01:59)","26 Aug (02:00 - 02:59)","26 Aug (03:00 - 03:59)","26
 Aug (04:00 - 04:59)","26 Aug (05:00 - 05:59)","26 Aug (06:00 - 06:59)","26 Aug (07:00 - 07:59)","26
 Aug (08:00 - 08:59)","26 Aug (09:00 - 09:59)","26 Aug (10:00 - 10:59)","26 Aug (11:00 - 11:59)","26
 Aug (12:00 - 12:59)","26 Aug (13:00 - 13:59)","26 Aug (14:00 - 14:59)","26 Aug (15:00 - 15:59)","26
 Aug (16:00 - 16:59)","26 Aug (17:00 - 17:59)","26 Aug (18:00 - 18:59)","26 Aug (19:00 - 19:59)","26
 Aug (20:00 - 20:59)","26 Aug (21:00 - 21:59)","26 Aug (22:00 - 22:59)","26 Aug (23:00 - 23:59)","27
 Aug (00:00 - 00:59)","27 Aug (01:00 - 01:59)","27 Aug (02:00 - 02:59)"],
		show:true,
		tick: {
			outer:false,
			culling:{
				max: 8
			},
			multiline: true,
			width:80
		}
	},
	y: {
		show: true,
		tick: {
			outer: false,
			format: function (d) { 
				d = Math.round(d * 100) / 100;
				return d;
			}
		},
		padding: 0
	}
},`

The graph result are: 
![weird](https://cloud.githubusercontent.com/assets/9997892/17992548/a0a20ff6-6b72-11e6-8d7e-e160d69a8388.PNG)

Can you fix the "lasso" things? it should be direct line

**Comment by aendrew** [comment]
@indr4winata Not sure how easy that is to fix because of the interpolation with the spline style of chart. If you change it to just a regular area chart, does that fix things?

**Comment by indr4winata** [comment]
@aendrew : If I use normal area ( data.type = "area" ), the chart is OK, no "lasso" thing. it only happen with spline (normal spline and area-spline). Don't know about the others, but as far as I check, line and area is works well.

**Comment by aendrew** [comment]
@indr4winata Yeah, it's definitely an interpolation issue with the spline chart. If you've ever used the "pen" tool in Adobe Illustrator, you get that effect by drawing shapes with some space between the points and some curvature on them. 

Try this: set `spline.interpolation.type` to one of `basis`, `cardinal` or `monotone` and see if that improves.

**Comment by indr4winata** [comment]
@aendrew : There is no documentation for your `spline.interpolation.type`. Why don't you put it?

Well, if I use `spline.interpolation.type` = `cardinal` or `monotone`, it still remain the same. But if I set it to `basis`, it solve the "lasso" problem but give another problem: the line does not adhere with the point. See my image below. My data will always in integer, 1, 2, 3, 4, or 5. the point is right, but the line is not. I use the same data but I zoom in to give clear visualization.
![linenotinpoint](https://cloud.githubusercontent.com/assets/9997892/18633665/964687b0-7ea7-11e6-86ae-a3b7e74fec9b.PNG)

Well, maybe can you update your code with the easiest way (maybe start with the "basis" type)? Or do you have any other things that I should try that have not been in the c3 documentation? :)

Thank you anyway.

**Comment by aendrew** [comment]
@indr4winata There's a lot of the API that's been added and isn't documented. V1 will have extensive inline documentation that will generate the documentation site, which should help that somewhat. 

Kind of the issue with splines is more of an upstream D3 issue; I find it's generally better to use lines unless you really have a specific use for a spline. Closing as `wontfix`.
