### ISSUE TITLE
Colors bug on unload/load

### ISSUE THREAD

**Issue by yohankoehler** [c3js/c3#182]
I can't explain why colors gone so wrong with this code -> http://jsbin.com/qacoqasu/11/edit

When you choose a type from options boxes I just unload and then load new columns to the chart, colors in legend seems to be ok but not in the donut...

**Comment by keyscores** [comment]
Hello this was very helpful. Can we please make this more visible in the api reference/docs . Especially "unload" param of load. Also would be nice to be explicit that 'null' should be used when all is cleared.

      chart.load({
          json: setData(),
          unload: null,
          keys: {
            value: listSeries() ,
            x: 'timeStamp'
          },
       });

**Comment by wheresjames** [comment]
This problem still exists for me even when using the suggested patches.  [This will eventually fail.](https://jsfiddle.net/rynby30n/3/).  Also, thanks for all the hard work guys, amazing library :)

**Comment by sushantdhiman** [comment]
Can confirm this problem still exists but its apparently random, not sure what is the reason behind it. I am facing this problem with line chart

**Comment by tochoromero** [comment]
I'm also seeing similar problems.
On my case I have two charts, I want to keep the items between charts with the same color, so I just make sure the order of the items is the same between charts.

At the beginning everything is fine, but once I start loading and unloading the colors get out of sync even if the order is the same.

**Comment by adrian1358** [comment]
I think I have the exact same issue, like the one tochoromero has. I'm using the graph inside React, and when new data comes to the graph (via props), I trigger the following code:

```
this.graph.instance.load({
                unload: true,
                columns: [...]
            });
```

Graph reloads, but colors change. 

This is before reload:

![image](https://cloud.githubusercontent.com/assets/5121148/21807088/4ae268c2-d73d-11e6-886c-499982bd9e36.png)

This is after reload:

![image](https://cloud.githubusercontent.com/assets/5121148/21807107/5a3f139c-d73d-11e6-99a0-bca2b04e846d.png)

The graph was initialized with:

```
  color: {
                pattern: ['red', 'blue', 'yellow', 'orange', 'brown', 'green', 'black', 'grey']
            }
```

Anyone else experiencing something similar ?

Thanks!

**Comment by wheresjames** [comment]
@tochoromero, @adrian1358, I don't think you can prevent that from happening with `unload: true`, try instead to remove only the outdated items such as `unload: ['data1', ...]`.  [See this example](https://jsfiddle.net/rynby30n/3/).

**Comment by woohling** [comment]
http://c3js.org/samples/data_stringx.html 
even the official example has bug... after all the data loaded and then choose the color tag, color mismatches...
