### ISSUE TITLE
C3 rotate y-axis label

### ISSUE THREAD

**Issue by abankspdx** [c3js/c3#1821]
Currently the y-axis label is oriented like this: http://imgur.com/a/fbJQb

Either the functionality doesn't exist out of the box or my Google Foo is failing (this is probably the case), but is it possible to make "Friend" the same orientation as the 400? As in, I want the y-axis label to read left-to-right instead of bottom-to-top.

**Comment by netil** [comment]
@alexanderbanks, you can do removing transform attribute of y axis label element as below.
To control the label element position, you need set proper attributes(x, y, dy, dx) values on your necessities.

```js
c3.generate({
    data: { ... },
    onrendered: function() {
       // remove transform attribute
        d3.select("."+ c3.chart.internal.fn.CLASS.axisYLabel)
            .attr("transform",null);
    }
});
```

**Comment by alexanderbanks** [comment]
Removing the transform attribute makes the label not-visible.

**Comment by ahoereth** [comment]
Having a `axis.y.label.rotate` (and `axis.y2.label.rotate`) option like for `axis.y.ticks.rotate` would be awesome!

**Comment by aashish-chaubey** [comment]
Hey can we rotate a donut chart by 180 deg along the y-axis?
