### ISSUE TITLE
C3 needs a logo

### ISSUE THREAD

**Issue by aendrew** [c3js/c3#1832]
I've created the following basic logo in about 35 seconds in Illustrator to replace the default logo for the org, however, I am _in no way whatsoever_ a graphic designer, and have absolutely zero doubt somebody with more skill could produce something better. If interested, please post your mockups here — or, if you want to contribute without doing any graphic design yourself, please use the thumbs up/down response emoji to indicate whether you like a design or not.

**Comment by aendrew** [comment]
Here's my initial attempt.

![temp-c3-logo](https://cloud.githubusercontent.com/assets/185041/18413437/556856de-77a8-11e6-971b-bbf65fcf6291.png)

**Comment by kt3k** [comment]
Here's my attempt. `C` letter represents the donut chart and `3` (`III`) denotes bar chart.

![ciii](https://cloud.githubusercontent.com/assets/613956/26527180/f6d1b208-43c8-11e7-9908-13a31ba2ee71.png)

**Comment by tbarn** [comment]
Do y'all mind if I share this issue a few places? It could be a great beginner issue for someone with some design skills.

**Comment by kt3k** [comment]
@tbarn 
Contributions are welcome!

**Comment by KyleRConway** [comment]
@kt3k (and others). I'd love to work on a logo (and, sidenote, I've actually been looking for a tool like C3, so thanks for making it!). Lightening question round (these are silly but helpful to the process):

1. Three verbs to describe C3:
2. Two adjectives to describe C3:
3. Name one color:
4. Up, Down, or sideways?
5. Solid, malleable, or liquid?
6. Round, Rectangle, or sharp?

Looking forward to it!

**Comment by KyleRConway** [comment]
Here's a quick mock-up of one idea:

![c3-blk](https://user-images.githubusercontent.com/5899012/27064799-d9d0135a-4fbe-11e7-91e0-ac4e024bcf3b.png)

And the same with various colors you've used for the charts:

![c3-colors](https://user-images.githubusercontent.com/5899012/27064807-e7a2dd96-4fbe-11e7-866f-dff46d92b5e8.png)

I have some others in draft form, but any feedback you could provide would be helpful (along with the lightening round questions above). Thanks!

**Comment by kt3k** [comment]
Thanks for the quick work!

I collected the opinions of other maintainers. Here're our answers for the above.

- Three verbs to describe C3:
  - visualize, show, inspire
- Two adjectives to describe C3:
  - flexible, simple
- Name one color:
  - blue(ish)
- Up, Down, or sideways?
  - Sideway
- Solid, malleable, or liquid?
  - Either is fine, but not too solid
- Round, Rectangle, or sharp?
  - Either is fine, but not complicated one

Thanks!

**Comment by KyleRConway** [comment]
Thanks for the comments! Will look into working on them. Another question: why does the "quick" design above *not* work? (This will help me clarify future versions as well)! 

Thanks!

**Comment by kt3k** [comment]
I don't think the above doesn't work. I like its simple and static tone! (See the reactions on your comment!) If I have to point one thing, that very unequal handling of c and 3 looked a bit odd to me because we consider "c3" as a single word and it feels a little hard to read as c3 (escpecially if the logo is resized small).
