### ISSUE TITLE
Style of legend for one chart only

### ISSUE THREAD

**Issue by Java1Guy** [c3js/c3#1845]
I have several charts on my page.  I would like to set the legend font size on the charts independently.  Each of the text items gets a CSS class, but I would like to set for the whole chart.
E.g.
<g class="c3-legend-item c3-legend-item-entry1"...>...</g>
<g class="c3-legend-item c3-legend-item-entry2"...>...</g>
<g class="c3-legend-item c3-legend-item-entry2"...>...</g>
Adding the chart name/id to the class would make things easier:
<g class="c3-legend-item c3-legend-item-chart1 c3-legend-item-entry1"...>...</g>
(which would be backward compatible) or
<g class="c3-legend-item c3-legend-item-chart1-entry1"...>...</g>
(which wouldn't be...)

Thanks, Mark

**Comment by aendrew** [comment]
Just add a class to the parent container.

Please don't use the issue queue for support requests, thanks.
