### ISSUE TITLE
Duplicates dates in timeseries data in c3.js

### ISSUE THREAD

**Issue by Abhi-joshi** [c3js/c3#1850]
We're looking for an approach where we want to show two similar dates in the x-axis.

For example 2016-11-01 00:00 and 2016-11-01 00:00 Can we acheive this with the c3.js timeseries chart?

We're using category type chart currently to support this but then the x axis is not labelling properly on the ticks

This is what we want to achieve but currently this code is overrlapping the similar dates.
[http://stackoverflow.com/questions/39656006/duplicates-dates-in-timeseries-data-in-c3-js](url)

**Comment by aendrew** [comment]
Hi there! We try to keep the issue queue clear for specific code-related problems with C3, could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3) instead? Thank you!
