### ISSUE TITLE
axis.x.tick.format on bar charts

### ISSUE THREAD

**Issue by matthewsuan** [c3js/c3#1851]
Hi guys. 

When you have a bar chart and you want to manipulate the x-axis ticks, typically you would invoke a function to axis.x.tick.format property.

My problem is that the function parameter returns the index instead of the actual tick values.

Is there another way to get hold of the actual x axis tick values instead of the index?

Thank you.

**Comment by cowlibob** [comment]
Hi, you can query `this.data` in the function to use the provided index into the column data.
For me, `function(index){ return this.data.xs.points[index]; }' gives the value (points is one of my multiple data columns). For a single data chart, you will likely have to use `function(index){ return this.data.x.points[index];}`
