### ISSUE TITLE
[Question] Show Multiple tooltip Programatically trigger

### ISSUE THREAD

**Issue by bORm** [c3js/c3#1852]
Subj, as example something like this
![tooltip](https://cloud.githubusercontent.com/assets/4027842/18815778/7ceb94dc-8342-11e6-8556-11b44fc10779.jpg)

I`am find in google and finding only this issue
https://github.com/c3js/c3/issues/467

I`am try 
```
chart.tooltip.show({ index: [2,3] });
```
but
```
d3.js:562Uncaught SyntaxError: Failed to execute 'querySelector' on 'Element': '.c3-event-rect-2,3' is not a valid selector.
```

**Comment by bORm** [comment]
up

**Comment by aendrew** [comment]
Hi there! We try to keep the issue queue clear for specific code-related problems with C3, could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) or [Gitter](https://gitter.im/masayuki0812/c3) instead? Thank you!
