### ISSUE TITLE
Multiple Y-Axis with Json Data

### ISSUE THREAD

**Issue by ghost** [c3js/c3#1859]
Multiple Y-Axis with Json Data, Y2 axis does not scale it just plots from 0-1

**Comment by HamzaWaheed** [comment]
I am having the same issue as well.
@ghost did you find any solution?

**Comment by panthony** [comment]
Hi,

Could you provide a JSFiddle, codePen or Plunkr highlighting the issue?

It makes reproduction much easier for everyone.

Thank you!
