### ISSUE TITLE
Mouse position of onclick event

### ISSUE THREAD

**Issue by varuag** [c3js/c3#1862]
Is there a way to get the mouse position of an onclick event on a data item? I'm trying to show a context menu when say a bar in a bar chart is clicked, and need the positon of the mouse to position the menu.

Thanks

**Comment by panthony** [comment]
I believe you can simply do the following to retrieve the mouse's position:

```js
{
   data: {
    onclick: function(d) {
         const pos = d3.mouse(d3.event.target)
    }
  }
} 
```

The changes suggested by #2001 seems unnecessary (and wrong since I could not find any `event` within the scope of the function).

What do you think @kt3k ?

**Comment by kt3k** [comment]
@panthony I agree with you. `d3.event` is the way to access the current event (ref: https://github.com/d3/d3-selection#event ), and #2001 seems wrong to me as well. Let's close it.

@varuag Please use the above example for using the mouse positions in click events.
