### ISSUE TITLE
After downloading c3, I just have blank screen instead of charts.

### ISSUE THREAD

**Issue by yaslamenace** [c3js/c3#1863]
Hi everyone,

I am pretty new to C3js and gloabaly to javascript so please be nice with me :p .
I just downloaded the last release of C3js: c3-0.4.11 (from this url https://github.com/c3js/c3/releases/tag/0.4.11 ) . When I try to visualize some charts in the forlders example nothing appears. I just have a blank screen.

Do  you know how I can "fix" this ?

Thank you very much for your attention and your patience.

Yas

**Comment by Nerdenator** [comment]
Could you provide us a JSFiddle of your code?

**Comment by kiranreddy1** [comment]
I am experiencing the same issue when i try to open the chart. Here is the simple HTML that I am using:
`<head>
<meta charset='utf-8'>
<meta content='IE=edge,chrome=1' http-equiv='X-UA-Compatible'>
<meta content='D3 based reusable chart library' name='description'>
<meta content='c3js.org' name='author'>
<meta content='width=device-width' name='viewport'>
    <link rel="stylesheet" type="text/css" href="../css/c3.css">
	<link href="../css/bootstrap.min.css" rel="stylesheet">
    <link href="../css/index.css" rel="stylesheet">
  </head>
  <body>

    <script src="../js/d3.v3.min.js" charset="utf-8"></script>
    <script src="../js/c3.js"></script>
	<script src="../js/c3.min.js"></script>	
	
    <script>
		var chart = c3.generate({
		  data: {
			json: [
			  {name: 'www.site1.com', upload: 50, download: 200, total: 400},
			  {name: 'www.site2.com', upload: 100, download: 300, total: 400},
			  {name: 'www.site3.com', upload: 300, download: 200, total: 500},
			  {name: 'www.site4.com', upload: 400, download: 100, total: 500}
			],
			keys: {
			  // x: 'name', // it's possible to specify 'x' when category axis
			  value: ['upload', 'download']
			}
		  }
		});
    </script>	
	<div id="chart"></div>	
  </body>
</html>`

**Comment by panthony** [comment]
@yaslamenace Unfortunatetly the "samples" directory in the downloaded zip is not meant to be opened directly using your browser, it fails to load the resources that's why you see a blank page.

It's supposed to be served using a small HTTP server than you can launch using npm:

https://github.com/c3js/c3#tutorial-and-examples
