### ISSUE TITLE
Test broken: should show custom min/max guage labels

### ISSUE THREAD

**Issue by MOctavio** [c3js/c3#1872]
Looks like test for custom min/max gauge labels is broken it looks easy to fix but I'm not sure if a change broke the test or if the test didn't get updated after a change.

```
should show custom min/max guage labels
  Expected '0' to match 'Min: 0%'.
      at C:/Users/jimarioo/workspace/c3/spec/arc-spec.js:191
      at C:/Users/jimarioo/workspace/c3/spec/c3-helper.js:42

  Expected '100' to match 'Max: 100%'.
      at C:/Users/jimarioo/workspace/c3/spec/arc-spec.js:192
      at C:/Users/jimarioo/workspace/c3/spec/c3-helper.js:42
```

C3 version 0.4.11, to reproduce it runt `grunt test` the log is visible in the console logs.

**Comment by panthony** [comment]
Should be fixed since the tests are green
