### ISSUE TITLE
How to hide Column labels?

### ISSUE THREAD

**Issue by mfarooq100** [c3js/c3#1879]
The following code shows labels on the x-axis. Is there a way to hide these labels? Thanks.

data: {
          x:'x',
          columns: [
              ['x', 10, 20, 30, 40, 50, 60],
              ['data1', 30, 40, 25, 50, 60, 20],
              ['data2', 50, 20, 10, 40, 15, 25]
            ],
            type: 'line'
        },

**Comment by mariusl-a** [comment]
This should work for you.. 

`axis: {
  x: {
    show: false
  }
}`

http://c3js.org/reference.html#axis-x-show

**Comment by LeoPerez28** [comment]
hi , 
is there a way to do it by a simple function like:
**Chart.data.labels.hide();**

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
