### ISSUE TITLE
interactions.enabled = false does not disable interaction with chart legend.

### ISSUE THREAD

**Issue by andjd** [c3js/c3#1882]
Working with the Donut chart, setting interaction.enabled to false does not disable the default onmouseover/onclick events for the legend of the chart.

example: (0.4.11)

http://jsfiddle.net/kzzzp70s/5/

**Comment by karvanit** [comment]
This is still present and should either be fixed or added as a feature in the documentation.

**Comment by GDFaber** [comment]
I'll give this one a try on the upcoming weekend.
