### ISSUE TITLE
Doesn't work with D3 v4.

### ISSUE THREAD

**Issue by pyotr777** [c3js/c3#1883]
If link to v4 of D3 with
`<script src="https://d3js.org/d3.v4.min.js"></script>`
get an error and no graphs displayed for Getting started sample.

Safari 10.0.1 on OSX 10.11.6 error message:
```
generateColor — c3.min.js:4:24593
TypeError: undefined is not an object (evaluating 'c.scale.category10')
```

Firefox 49.0.2:
```
TypeError: c.scale is undefined
i.generateColor()   c3.min.js:4
i.initParams()      c3.min.js:1
i.init()            c3.min.js:1
d()                 c3.min.js:1
k.generate()        c3.min.js:1
<anonymous>         index.html:12
```

**Comment by gneatgeek** [comment]
Hi @pyotr777, just wanted to give you a heads up that this is a known issue and work is being done to make it compatible with D3 v4: https://github.com/c3js/c3/issues/1648

**Comment by pyotr777** [comment]
Thanks! Looking forward!
