### ISSUE TITLE
Unable to sort legend

### ISSUE THREAD

**Issue by tedcurrent** [c3js/c3#1892]
Is there any way to sort the legend box according to some order? I would love to be able to give it an array of keys to sort by, similar to [data-groups](http://c3js.org/reference.html#data-groups). Of course just one array would be enough. Maybe a similar sorting than for stacked bars would also be ok, but it would be easier to give the exact order. Is this a feature that's coming up or does anyone have a suggestion? I'd rather not try to sort the data itself before sending it to c3.js as it is very counter-intuitive.

I am using the latest, v0.4.11 version of c3.js.

**Comment by greenafrican** [comment]
My view is that the legend should be sorted based on `data.order` if set, but this doesn't happen.

**Comment by khumphrey-sb** [comment]
This is especially problematic with pie/donut charts.  The order of the legend does not mirror the order of the data.  It appears to exclusively sort them by key name.

**Comment by panthony** [comment]
There was a fix around data ordering not being honored by pie charts.

Since you can pass a function to order the data it is possible to implement a static ordering.

Closing this issue
