### ISSUE TITLE
Exporting to CSV or other

### ISSUE THREAD

**Issue by tedcurrent** [c3js/c3#1893]
Is there a way to export the data from a c3.js chart as CSV? I guess it could be done by hand, but if someone has a good suggestion for that, it would be great. I couldn't find anything for c3.js. Been using Highcharts for a while and that also requires a new library to be added to the project. Anything similar for c3?

**Comment by panthony** [comment]
Kind of out of c3js scope I guess but personally I do something like this in an onClick event of an export button:

```javascript
    const link = document.createElement('a');
    link.setAttribute('download', `export.csv`);
    link.setAttribute('href', encodeURI(`data:text/csv;charset=utf-8,${csvLines.join('\n')}`));
    link.click();
```

**Comment by thesageinpilani** [comment]
It says csvLines as undefined.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
