### ISSUE TITLE
Prevent page scroll to top when chart is regenerated

### ISSUE THREAD

**Issue by Nagasubba-Reddy** [c3js/c3#1907]
Hi,
Is it possible to prevent page scroll to page top when chart is regenerated ?

After the page is loaded with C3 chart, I scrolled to bottom of the page.
I have auto refresh event which will regenerate chart.
After chart getting regenerated, scrollbar is moving to top of the page.

Thanks for your help!

Regards,
Subbu

**Comment by netil** [comment]
I think isn't related to C3. To prevent you should control your auto-refresh process.

But, if you can't for some reasons,
you need to control scrolling your page where chart element is located.

If your chart element's id is `chart`
```html
<div id="chart"></div>
```

then, excute below code(somewhere on body.onload or in the bottom of page) when page is reloaded.
```js

document.getElementById("chart").scrollIntoView();
```

**Comment by panthony** [comment]
Closing as not related to c3js
