### ISSUE TITLE
Remove tick marks on far left and far right side of x-axis line?

### ISSUE THREAD

**Issue by veronicaerick** [c3js/c3#1908]
I need to remove the two ticks that contain the x-axis line.. I was able to hide all of the inner ones with the CSS 
`.c3-axis .tick line {
    display: none;
}`

but this does not remove the two marks at either end on the x-axis line. How can I remove these?
![screen shot 2016-12-14 at 4 23 14 pm](https://cloud.githubusercontent.com/assets/18318386/21207220/bb32e142-c21b-11e6-84ac-5e8c9714cca7.png)

**Comment by netil** [comment]
@veronicaerick you mean the tick marked as red box?
![image](https://cloud.githubusercontent.com/assets/2178435/21800208/e892ed18-d75f-11e6-8467-ff98f11ded8e.png)

If so, you can do setting option like:
```js
c3.generate({
           ...
    "axis":{
        "x":{
            tick: {
                outer: false
            }
        },
});
```
- checkout the API: http://c3js.org/reference.html#axis-x-tick-outer

**Comment by aashish-chaubey** [comment]
@netil I used you solution but this just removes the tick from one end of the axis not on both the ends. Is there any option to remove the tick from the other end as well?

Thanks.

**Comment by prasanthmaran1** [comment]
@veronicaerick, @netil solution working well 👍,

**Comment by panthony** [comment]
As this issue queue is to be used for reporting defects and problems with C3.js, not a catch-all support forum, i'm closing this issue.

For further support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

Thank you!
