### ISSUE TITLE
Metric Chart

### ISSUE THREAD

**Issue by dewanshamsul** [c3js/c3#1910]
I would love to see metric chart in C3.
Example: http://keen.github.io/keen-dataviz.js/

**Comment by ontelo** [comment]
It's not a chart is it? Just basic div element, with aligned text.

**Comment by dewanshamsul** [comment]
It is. When I hover mouse over the colored area it shows the actual value. It looks gorgeous and can be used in to make any dashboard look super cool.

![metric chart](https://cloud.githubusercontent.com/assets/22762429/21347072/46760fd6-c6d1-11e6-9b2e-0f3e3a24f139.png)

**Comment by ontelo** [comment]
Still really simple html. In my opinion there's no need to add this to js/svg based library.
https://jsfiddle.net/zoscu0fr/

**Comment by dewanshamsul** [comment]
Will it load data from csv and json?

**Comment by dewanshamsul** [comment]
Figured out how to get data from csv and mysql that's why I'm closing the issue now.
