### ISSUE TITLE
Line chart issue

### ISSUE THREAD

**Issue by samskrithib** [c3js/c3#1911]
Hi, 

I am trying to get a line chart. Here is my [fiddle](https://jsfiddle.net/Samskrithi/y640uh0k/)

with one more extra value in each array the chart is rendering a different graph. here is the [fiddle](https://jsfiddle.net/Samskrithi/2yaquk9j/)

I tried to debug it. I find it if the length of the arrays are greater than 11, the first 2 values are mapping wrongly.

I would like the graph to look like the first one. Please help me. Its urgent.

**Comment by shlrur** [comment]
That's why "xSort" config is true(default). This config item is "not yet" commented(http://c3js.org/reference.html#data-xSort). But, it is operating with "true" value.

I think,, xSort default value will be 'false'.

See that: https://jsfiddle.net/2yaquk9j/1/

**Comment by samskrithib** [comment]
Thanks a lot. It works.
