### ISSUE TITLE
Always show all tooltips

### ISSUE THREAD

**Issue by SergeyPensov** [c3js/c3#1916]
Hi!
I need always show my tooltips, but (if I understand) I can only hide all tooltips or show only one. Maybe who have any idea?

**Comment by pacahon** [comment]
Hi. Not sure you can do something easier than append html elements with d3js and position them based on coordinates from `.c3-event-rects`.

**Comment by netil** [comment]
@SergeyPensov Do you want to not hide tooltip shown?

In that case you can override hide method, which even after mouseout the tooltip layer will maintained diplayed.

```js
c3.chart.internal.fn.hideTooltip=function(){};
```

**Comment by yasu47b** [comment]
Here it is. maybe ugly but enough?
https://jsfiddle.net/yasu47b/kkr9a8tg/

**Comment by panthony** [comment]
Workaround provided with no response from submitter.

Seems like such an edge case it's not worth supporting by default.
