### ISSUE TITLE
Only increasing legend width/height

### ISSUE THREAD

**Issue by DinakaranS** [c3js/c3#1919]
Hi,

I am trying to show legend below chart. 

Using legend: {
                                     show: true,
                                     position: 'inset',
                                     inset: {
                                         anchor: 'bottom-left',
                                         x:undefined,
                                         y:undefined,
                                         step: 5
                                     }
                                 }
x,y, will be custom values. But the legend is overlapping the donut/pie chart. I want to set height and width to the legend separately so that, the legend will show below the donut chart in a table format.

Is there any way to set this?
<img width="381" alt="screen shot 2017-01-02 at 2 50 54 pm" src="https://cloud.githubusercontent.com/assets/8424594/21586797/f595986e-d0fa-11e6-905c-91acb9a7fbc7.png">

**Comment by urm47** [comment]
Have tried to pad the chart?
            padding: {
                bottom: 40
            },

**Comment by DinakaranS** [comment]
Thanks Meier, I have increased the height of the chart and set padding. Now everything is working fine.
