### ISSUE TITLE
Click handler for x grid lines

### ISSUE THREAD

**Issue by pchaganti** [c3js/c3#1924]
Is there any way to add a click handler for either x or y grid lines? Trying to display some information when user clicks on a grid line. Any pointers?

thanks!

**Comment by netil** [comment]
@pchaganti, is not perfect solution, but you can set additional event handler for optional grid elements.

```js
// if c3 is geneated with grid options as below
grid: {
        x: { lines: [ ... ] }, 
        y: { lines: [ ... ] }
}

// then you can set additional event handler for grids
d3.select(".c3-grid-lines")
	.on("click", function() {
		var event = d3.event;
		var el = event.target;

		if(el.tagName === "line") {
			// do something here
			console.log("clicked a grid line");
		}
	});
```

Isn't perfect, because in some area the grid element and user clicked element can have interferences.
Just only take above example to start your needs.

**Comment by pchaganti** [comment]
@netil That works very well. Thx!
