### ISSUE TITLE
c3 charts within gridster are not fitting gridster boxes properly 

### ISSUE THREAD

**Issue by smart987** [c3js/c3#1927]
Hi, I am using c3 charts inside gridster. But the charts are not remaining within the gridster boxes, if I do not give size property for the chart. If I give fixed height and width they are appearing pretty bad (as small charts within gridster boxes). How can I make the charts to occupy proper height and width of gridster boxes and the charts inside the gridster box should auto resize according to the height and width of gridster boxes. How can I achieve it? When I give the following size property for the chart they are pretty small to view.

size: {
height: 100,
width: 100
}

I have even tried with percentage for size but still no luck,

size: {
height: '100%',
width: '100%'
}

Please find my reference plunker : http://plnkr.co/edit/jndmn90giNGQHN2TGVff?p=preview

**Comment by netil** [comment]
## Why this happens

At the initialization, when parent element's `width` is 0 (or falsy), C3 tries to get from the parent's node.
Your HTML structure is like:

```html
<ul class="with-3d-shadow with-transitions"> <!-- reach at this point and get the width of the chart -->
	...
	<div id="widget1">  <!-- start here -->
```

But, in terms of height value, when is 0, it gets value dividing from 320.
The C3's code getting height is as below:
```js
    c3_chart_internal_fn.getCurrentHeight = function () {
        var $$ = this, config = $$.config,
            h = config.size_height ? config.size_height : $$.getParentHeight();
        return h > 0 ? h : 320 / ($$.hasType('gauge') && !config.gauge_fullCircle ? 2 : 1);
    };
```

So, your page chart holder element is initialized from 0x0, which actually ends having:
- width: taken from: `<ul class="with-3d-shadow with-transitions">`
- heght: is `320`

## Solution

This solution isn't perfect, but it will resize according the box's dimension on every chart re-rendering happens.

- Upgrade your C3 version from 0.4.4 to latest which is `0.4.11`
- and put following option and remove size option

```js
        onrendered: function() {
            var chart = this.api.internal.selectChart.node();
            var parent = this._parent;

            if (!parent) {
                parent = chart;

                while (parent && parent.tagName !== "BODY") {
                    // try to get dimension from the gridster box element
                    if (parent.getAttribute("gridster-item")) {
                        break;
                    }

                    parent = parent.parentNode;
                }
                this._parent = parent;
            }

            parent = d3.select(parent);
            var size = {
                width: parseInt(parent.style("width")),
                height: parseInt(parent.style("height"))
            };

            (size.width !== this.config.size_width ||
                    size.height !== this.config.size_height) &&
                        this.api.resize(size);
        }
```

**Comment by panthony** [comment]
For questions involving the interplay between C3.js and any other library (react, vuejs, ..) please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

Thank you!
