### ISSUE TITLE
Adding a horizontal line (level 0 at axis y)

### ISSUE THREAD

**Issue by pmirandaarias** [c3js/c3#1931]
Is there a way for to add color to Grid lines? something like:

grid: {
        x: {
            show: true, color:'red'
        },
        y: {
            show: true, color:'blue'
        }
    }

**Comment by netil** [comment]
Not directly, but you can set css class name to specific grid.
If you create a grid line with below option
```js
grid: {
  x: {
    lines: [
      {value: 5, text: 'Label', class: 'color-grid'}
    ]
  }
}
```

then the DOM structure will be like

```html
<g class="c3-xgrid-line color-grid">
    <line x1="453" x2="453" y1="0" y2="226" style="opacity: 1;"></line>
    <text text-anchor="middle" transform="rotate(-90)" dx="0" dy="-5" style="opacity: 1;" x="-113" y="453">Label</text>
</g>
```

In that circumstances, if you want to set some color on line element, set some css rule as follow.
```css
.label-color > line {
    stroke: red;
}
```

Check out the reference for grid:
- http://c3js.org/reference.html#grid-x-lines
