### ISSUE TITLE
Timeseries values on tick value incorrect

### ISSUE THREAD

**Issue by sam-mckay** [c3js/c3#1933]
It seems there is an issue with time series data, i'm trying to floor time stamps to the previous half hour point. i.e 12;34 is 1230 etc 

this is fine but when working with a moderate amount of data you eventually end up with a situation like so 

1230 1300 1400

this seems to be because the `v` value in the tick function has had a value added to it over time specifically 38.29787 to the point where a number that should round down to 1330 has become something like 1401 and now rounds to 1400 causing obvious problems

temporary workaround is really poor, which is too keep a global count of the amount times the tick function is called and to remove this value * 38.29787 everytime you want to round it.. 

this 39.29787 seems to be being added internally in c3.js and there's seemingly no cause within my code. is anyone else having this issue?

**Comment by netil** [comment]
Could you provide some online code bin to check your issue?

**Comment by panthony** [comment]
No response from submitter
