### ISSUE TITLE
Min 1 pixel for bar heights in bar chart

### ISSUE THREAD

**Issue by mbooshehrian** [c3js/c3#1935]
Hi,

Is there a way to show at least 1 pixel for bars with data in a bar chart? If the scale is very huge, the bars with very low numbers are not visible on the screen, so I'd like to specify a min height for the bars with data.

Thanks

**Comment by netil** [comment]
No you can't.
Because the bars are relatively drawn according its data.

If there is bar with data 1, and others are extremely high (ex 1M), in that occasion drawing 1px bar will not reflecting correctly data bound.
Even though, you want to be drawn something, you need handle manually to draw bar.

**Comment by panthony** [comment]
Closing as not possible.
