### ISSUE TITLE
C3 Js chart not loading when we pass bindto and div id dynamically from angular 2

### ISSUE THREAD

**Issue by arun4san** [c3js/c3#1936]
Hi,
I'm trying to create c3js chart component in angular 2 but when we will pass the bindto and div id dynamically from angular 2 the chart is not loading.

this my ts file code,

import {Component, OnInit,Input} from '@angular/core';
declare var c3:any;

@Component({
    selector: 'chart-component',
    template: `<h1>{{chartId}}</h1>
	<div [id] = {{chartId}} class="c3"> </div>`
   
})

export class ChartComponent implements OnInit  {
	
	constructor(){ }

	@Input('chartType') chartType:string;
	@Input('chartId') chartId:Object;
	@Input('chartData') chartData:any[];

	ngOnInit() {
		this.chartId = Object("chart1");
		let chart = c3.generate({
			 bindto: '#'+this.chartId,	
		    data: {

		       /* columns: [
		            ['Online', 98],
		            ['offline', 2],
		        ],*/
		        json:this.chartData,
		        type: this.chartType,
		    },
		    legend: {
				  show: true
				}
		});

	}

}

from html calling the component

<chart-component chartType="bar"  chartId="chart1" [chartData]="chartData"></chart-component>

please some one help me out for this issue.

Thanks,
Arun S

**Comment by netil** [comment]
Plz, provide some online code bin(jsbin, jsfiddle, etc) for check.

**Comment by Tarek-Adra** [comment]
The main problem is id="chart1" is not initialized yet.... if you put it statically it will work or use another way to try like class selector 
like this way :
1- Add class and try to select it by class 
<h1>{{chartId}}</h1> <div [id] = {{chartId}} class="c3 chart"> </div>

2- bind to class: 
 bindto: '.chart',

and it will work .... 

FYI: to use c3 you have to  downgrading from  D3.js v4 (4.1.1) to v3 (3.5.17).

**Comment by Tarek-Adra** [comment]
Or Try to use it into 
`ngAfterViewInit(){`  }

**Comment by arun4san** [comment]
Yes I have used ngAfterviewInit(){} and now its working ..Thanks guys for your response.
