### ISSUE TITLE
Labels or text on regions

### ISSUE THREAD

**Issue by stahlmanDesign** [c3js/c3#194]
How can I add text to regions? In SVG, text cannot be appended to &lt;rect> so I was not able to do this. I want to label the regions as Game 1, Game 2 etc. It needs to be in the chart (in SVG as opposed to HTML) because it needs to flow when resizing.
![capture decran 2014-04-29 a 13 38 42](https://cloud.githubusercontent.com/assets/972804/2832490/42ad0900-cfc5-11e3-8d72-25d7cffd5521.png)

**Comment by afraprie** [comment]
I have made a simple mod of the 0.4.10 cs.js to add text labels to a given region. 

See the Comparison HERE:
https://github.com/masayuki0812/c3/compare/master...afraprie:master

Its a fairly strait forward change, however, I am sure it could use some cleanup.

**Comment by aendrew** [comment]
@afraprie Cool, haven't tested that code but looks like it's towards the right direction. Might be a really good PR candidate! :smile: :shipit: :+1:

**Comment by afraprie** [comment]
Oops, Missed a semi col... correcting now.

I copied it over by hand. I am new to Git Hub.

**Comment by luklau88** [comment]
@afraprie thank you for the code. I have tried to get the label text to orient vertically with no success. Can you show me how to do it? thanks a lot

p.s. I added  -moz-transform: rotate(-90deg)

**Comment by afraprie** [comment]
@luklau88 

Took a 'second' to get this to work... below is a code snippet to HACK it in. The trick is to reverse the X and Y offsets of the SVG 'text' element. 

I would like to make this configurable, but that will take a little more effort/time.

Simply replace the below function in your c3.js file

c3_chart_internal_fn.redrawRegion = function (withTransition) {
        var $$ = this,
            regions = $$.mainRegion.selectAll('rect'),
            x = $$.regionX.bind($$),
            y = $$.regionY.bind($$),
            w = $$.regionWidth.bind($$),
            h = $$.regionHeight.bind($$);

            var labelX = x;
            var labelY = $$.regionY($$) + 10; //Padding - To allow for text height
            
            //-----------------
            //TEMP
            //Vertical Label
            var decorativePadding = 5; //NOTE: Otherwise the text is right on the edge of the section
            labelX = $$.regionY($$) + decorativePadding;
            labelY = function($$){ return -(decorativePadding+x($$)); }; //For 90Deg, Bottom Left

            /*NOTE: Must include this style in your css
            .c3-region>text
            {
                transform: rotate(90deg);
                transform-origin: bottom left;
            } 
            */

            //TEMP
            //-----------------

            var regionLabels = $$.mainRegion.selectAll('text');
        return [
            (withTransition ? regions.transition() : regions)
                .attr("x", x)
                .attr("y", y)
                .attr("width", w)
                .attr("height", h)
                .style("fill-opacity", function (d) { return isValue(d.opacity) ? d.opacity : 0.1; }),
                regionLabels
                .attr("x", labelX)
                .attr("y", labelY)
        ];
    };

**Comment by afraprie** [comment]
[Code Change Comparison](https://github.com/masayuki0812/c3/compare/master...afraprie:master)

I have implemented custom configuration options for label orientation (horizontal or vertical) and custom padding

See latest revision [afraprie/c3](https://github.com/afraprie/c3)

**Comment by heenaI** [comment]
@afraprie Is there an example how to implement this? 
i tried to do something like this but it does not work

{axis: 'x', start: "2016-02-01", end: "2016-06-14", class: 'regionX',  text: 'abkddhk'},

**Comment by heenaI** [comment]
{axis: 'x', start: "2016-02-01", end: "2016-06-14", class: 'regionX', label: 'Label #1', vertical: true, padding: 10}

**Comment by ahansen1** [comment]
@heenaI the functionality @afraprie mentions has not been merged into this repo.  @afraprie would it be possible to do a pull request?  Maybe then @masayuki0812 would merge this functionality.

**Comment by afraprie** [comment]
This is what my region array looks like

'regions': [
{'axis': 'x', 'start': 0, 'end': 30, 'class': 'regionX1', 'label': 'Label #1', 'vertical': true, 'padding': 10},
{'axis': 'x', 'start': 31, 'end': 60, 'class': 'regionX2', 'label': 'Label #2', 'vertical': false, 'padding': 0},
{'axis': 'x', 'start': 61, 'end': 90, 'class': 'regionX3', 'label': 'Label #3', 'padding': 20 },
{'axis': 'y', 'start': 50, 'end': 90, 'class': 'regionY1', 'label': 'Label #4', 'vertical': true}
],

ALSO

I am new to github. I think I tried to do a pull request and it failed continuous integration. What do I do to fix that??

See: https://github.com/masayuki0812/c3/pull/1586

**Comment by ahansen1** [comment]
@afraprie fantastic!  It looks like it's because it is failing the lint.  I'll bet if you fix the suggestions noted there, e.g. removing unused variables, using dot notation, etc. it will pass the integration and have a better shot of making it in.  I could use this feature.  Appreciate your work!

**Comment by luklau88** [comment]
Wow, incredible!
Thank you so much :)

Luk

**Comment by afraprie** [comment]
@ahansen1 - THANK YOU! I took a closer look at the CI output and saw the Lint suggestions. (I LOVE LINT). 

Pull request success!! https://github.com/masayuki0812/c3/pull/1586

**Comment by panthony** [comment]
Apparently this was fixed.
