### ISSUE TITLE
several: degree symbol, sequentiality, losing lagging element

### ISSUE THREAD

**Issue by jimlynnjulian** [c3js/c3#1943]
Hello,

   A couple of issues. 
   
   -The degree symbol associated with temperature seems to create a problem when used in the header of a csv file. I use csv files created on a linux machine and use c3 on a Windows machine running Apache as a local server for testing. If I run the files through a unix2dos converter, the problem goes away.
   -Before I make the conversion, some files will show the degree mark in the legend but others will show a black diamond with a question mark in the center instead.
   -I am using the data/legend hide function to conceal all but three of twenty variables/columns.
   The data hide effects the legend hide so I don't seem to need both.
   -If I have the source files (css, js) in the same directory as the html, no problem. If I put the source files in a subdirectory to keep things neat, the last element of the hide list in not hidden. I'm using the following examples: "url: './data/dataXY_11-21-2016.csv' " and "    <script src="./resources/c3.js"></script>" where the directory structure is:
	localhost/d3/c3/test/dataXY_11-21-2016.html
	localhost/d3/c3/test/resources/c3.js
	localhost/d3/c3/test/data/dataXY_11-21-2016.csv
   -sequentiality: the sequence of elements in c3 is important. If I place the data:colors: functionn after the data/hide function, the colors function does n ot work. I*f I move the data:colors: function higher in the file, the data:colors: function works.
   
   A suggestion: make importing csv data into a graph easier. I'm attempting to use d3.csv.js to filter the data columns.
   The json format takes too much space and is less common in science. I have a data aquisition system working and the last step is to display the data in a web page. That's the only place I have to use json files. Make a csv-to-json converter, if nothing else.
   
   
Thank you,
Jim J.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

Otherwise, please create an issue **per** bug or feature request and provide a JSFiddle, codePen or Plunkr highlighting the issue.

Thank you!
