### ISSUE TITLE
Note the parameters on which to build a chart JSON

### ISSUE THREAD

**Issue by vitulskiy** [c3js/c3#1946]
Hey. Let's say I have a JSON like this:

`[
{"country": "Russia", "date": 20170101, "sessions", 111}, 
{"country": "France", "date": 20170101, "sessions", 111}, 
{"country": "Italy", "date": 20170101, "sessions", 111}, 
{"country": "Russia", "date": 20170102, "sessions", 222}, 
{"country": "France", "date": 20170102, "sessions", 222}, 
{"country": "Italy", "date": 20170102, "sessions", 222}, 
]`

How can I draw a graph for each country? That is, I need three separate lines on the same graph.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
