### ISSUE TITLE
Windows to Unix, something lost in the translation.

### ISSUE THREAD

**Issue by jimlynnjulian** [c3js/c3#1950]
Hello,

   I've finished a webpage that loads csv data and creates a line chart. The data file is in a subdirectory as are the other resource files. I copied everything to the '/var/www/html' directory on a Raspberry Pi 3B/Raspbian.
The directory references in the html/javascript are './data2min/11-21-2016.csv' and './resources/C3.js' and './C3.css'. 
   The chart background draws perfectly, but the data is not plotted. I tried running the example csv datafile through a DOS-toUNIX converter with no luck. I tried adding a discrete d3.csv.js file that malfunctioned and removed the reference.
   Any ideas?

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
