### ISSUE TITLE
how to display pure numbers in pie chart

### ISSUE THREAD

**Issue by cyberhck** [c3js/c3#1951]
Right now pie chart displays percentage values, but I require to display pure numbers there, how do I do that? is it supported?

**Comment by netil** [comment]
Just set pie format option as below.

- jsbin: http://jsbin.com/lafeyiv/edit?html,js,output

```js
pie: {
   label: {
      format: function(value, ratio) {
        return value;
      }
    }
}
```

**Comment by cyberhck** [comment]
thanks.
