### ISSUE TITLE
Combo Chart Y2 Axis

### ISSUE THREAD

**Issue by gajmp** [c3js/c3#1955]
I have tried the below data for combo chart. It showing Y2 axis like 0.1, 0.2, 0.3 etc but Y axis showing correctly. because of this Y2 axis I couldn't see data2 in the chart

var chart = c3.generate({
    data: {
        columns: [
            ['data1', 30543, 2045346, 50765767, 4067657, 605676, 50665],
            ['data2', 200, 130, 90, 240, 130, 220]
        ],
        type: 'bar',
        types: {
            data2: 'line',
        }
    },
    axis: {
			y2: {
				show: true
	 		}
		}
});

Please let me know the solution for the same

**Comment by Starfight** [comment]
You need to specify binding between data and y axis:
```javascript
var chart = c3.generate({
    data: {
        columns: [
            ['data1', 30543, 2045346, 50765767, 4067657, 605676, 50665],
            ['data2', 200, 130, 90, 240, 130, 220]
        ],
        type: 'bar',
        types: {
            data2: 'line',
        },
        axes: {
            data1: 'y',
            data2: 'y2'
        }
    },
    axis: {
        y2: {
            show: true
        }
    }
});
```
You can find an example here: [http://c3js.org/samples/axes_y2.html](http://c3js.org/samples/axes_y2.html)

**Comment by gajmp** [comment]
Its working now
