### ISSUE TITLE
Not being maintained?

### ISSUE THREAD

**Issue by netil** [c3js/c3#1965]
There are tons of PRs and a lot of issues are unanswered.

I think C3 is great, but it needs more maintainers and activities to fulfill features implementing these days techs.

What is the current status and future plans for C3 @masayuki0812 @aendrew ?

**Comment by aendrew** [comment]
Hi @netil,

To answer the implicit question in the issue title — yep, pretty much.

I quite agree there needs to be more maintainers, I know personally I'm way too busy to be able to adequately maintain anything C3-related and I haven't heard much from @masayuki0812 as of late. There are a few folks reviewing the PR and issue backlogs, but those seem to have fallen off lately.

To be totally honest, a ground-up rewrite is probably necessary at some point in the future. I can't claim to be familiar enough with the code to feel confident I myself could accomplish this, and I don't have much in the way of project management skills (as perhaps evidenced by the failure of #1871 to make much headway).

I'd really like for somebody to step up and do something great with C3, but my feeling is that until the tests are unfucked (See #1843) there's no safe way of merging PRs and thus bugs will go unfixed, the issue queue will continue to grow to unmanageable levels, people will lose interest, and the project will die. In all honesty, given the whole test situation and the absolute garbage tests people were submitting with PRs, I'm really starting to question whether the continuous flood of messages I receive about C3 (and the related anxiety that results) is really worth it.

-Æ.

**Comment by netil** [comment]
Thanks @aendrew for your sincere answer and I'm totally understand the current status you shared.

As you said accumulated issues and PRs are in unmanageable levels. If this status continues, as your worries and concerns, is quite reasonable to predict the death of the project.

I don't know what's going on internally, but the original author @masayuki0812 should show his opinions in anyways about it.

But, seems that there's no many alternatives now.
- Seeking some volunteer maintainers
- Or if @masayuki0812 clarify not to maintain, will be more easier to take other decision.
  (fork and start new project or find someone to take over the project)

If needs some helps I can give a hand, but if the project discontinues probably I'll take a decision to fork and starting new project.

**Comment by aendrew** [comment]
We're starting to see some progress due to @kt3k's excellent contributions, we have some momentum carrying us forward and a plan to get to v1. As such, can happily say this issue can be closed. 🎉

**Comment by netil** [comment]
As I anticipated, today released the forked version of C3.js, named **'billboard.js'**.
- https://naver.github.io/billboard.js/

Read the short reason of fork: [Why we decided to start billboard.js?](https://github.com/naver/billboard.js/wiki/Why-we-decided-to-start-billboard.js%3F)

I know that recently, @aendrew and @kt3k are working to move forward, but the time of noticing that, the forked project was almost reaching the end. So, I decided to release as planned.

I hope to C3.js continue its way evolving as expected.

Anyway, anyone interested in the new forked project are welcoming!

**Comment by ataft** [comment]
Does it make sense for the current maintainers of C3.js to close this project and be maintainers on Billboard.js? I'd love to see the great work that people are putting in go to a single purpose. I posted this question in the Google group too:
https://groups.google.com/forum/#!topic/c3js/sANt7-Nw1Ow
