### ISSUE TITLE
Working with variables

### ISSUE THREAD

**Issue by khsopro** [c3js/c3#1969]
I want use variables for the data. In columns working but not in names. 
Want can I do?

var dataname1 = 'data1';
var chart = c3.generate({
    data: {
        columns: [
            [dataname1, 30, 200, 100, 400, 150, 250],
            ['data2', 50, 20, 10, 40, 15, 25]
        ],
        names: {
            dataname1: 'Name 1',
            'data2': 'Name 2'
        }
    }
});

**Comment by netil** [comment]
@khsopro, is not a C3's problem.
It's JavaScript specification which not allowing use variable as object's key name in a environment `< ES6`.

In ES6 you can do just surrounding square bracket
```js
 names: {
        [dataname1]: 'Name 1',
        'data2': 'Name 2'
 }
```

But, to be work with compatibility, you can set name's value as below.
```js
    var dataname1 = 'data1';
    var chart = c3.generate({
        bindto: "#line_chart1",
        data: {
            columns: [
                [dataname1, 30, 200, 100, 400, 150, 250],
                ['data2', 50, 20, 10, 40, 15, 25]
            ],
            names: (function() {
                var names = {};
                names[dataname1] = "Name 1";
                names.data2 = "Name 2";
                return names;
            })
        }
    });
```

**Comment by alleyj** [comment]
@netil Your example is most of the way there but you need to invoke that function for it to work.
```javascript
names: (function() {
  var names = {};
  names[dataname1] = "Name 1";
  names.data2 = "Name 2";
  return names;
}())
```

**Comment by netil** [comment]
Ah, yeah. I missed put parenthesis at the end. :)

**Comment by khsopro** [comment]
Thanks a lot!
