### ISSUE TITLE
How to make x-grid line named "Today" to be shown only to some y value (for example from y =0 to y=25)

### ISSUE THREAD

**Issue by KrisKulivnyk** [c3js/c3#1971]
How to make x-grid line named "Today" to be shown only to some y value (for example from y =0 to y=25) 
```
grid: {

    x: {
        lines: [
            {value: 4, text: 'Today',position: 'start'},
            {value: 12}

        ]
    },
```

Fiddle: https://jsfiddle.net/KrisKuliv/74fkuyw4/4/

**Comment by netil** [comment]
Do you want resize x grid line like this?

![image](https://cloud.githubusercontent.com/assets/2178435/23354158/2e014a9c-fd13-11e6-87e3-678e9b23c6f1.png)

In that case you need to manipulate manually modifying grid's attribute.
Put below to your C3 generate option.

```js
   onrendered: function() {
       // select the tick which you need to be aligned with.
       var y1 = ~~document.querySelector(".c3-axis-y > .tick:nth-last-child(3)")
                     .getAttribute("transform")
                     .replace(/\D/g,"");
      
       document.querySelector(".c3-xgrid-line > line")
           .setAttribute("y1", y1);
   }
```

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
