### ISSUE TITLE
How to enadle only some points(dots) to be shown

### ISSUE THREAD

**Issue by KrisKulivnyk** [c3js/c3#1972]
How can I make only some dots (for ex. (12,30), (12,25)) to be shown?
Now all dots that I have have parameters **show:false**

```
point: {
        show: false,
    },
```
Fiddle: https://jsfiddle.net/KrisKuliv/74fkuyw4/4/

**Comment by tapostrophemo** [comment]
You should reference properties on `d` inside the function you use to determine the radius. It has `id`, `name`, `x`, `value`, and `index` fields. Using those properties, you can make the radius zero for data points you wish to hide, and non-zero for data points you wish to show.

For example:

```JavaScript
// only display points (using radius 2) whose value is greater than 15
point: {
  show: true,
  r: function (d) { return d.value > 15 ? 2 : 0; }
}
```

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
