### ISSUE TITLE
Different timezones in subchart domain on brushing

### ISSUE THREAD

**Issue by greenafrican** [c3js/c3#1974]
My x values are time and timezone ignorant (eg. `2016-03-03`) but when I log the domain, during brushing, I'm seeing mixed timezone:

<img width="312" alt="screen shot 2017-02-26 at 11 32 40 am" src="https://cloud.githubusercontent.com/assets/1160732/23341533/5414d642-fc17-11e6-9bad-71204de05dfd.png">

I understand that it may be interpolating the time but not sure why it is using different timezones?

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
