### ISSUE TITLE
data.json doesn't allow for special characters in keys

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [c3js/c3#1975]
**Edit**: looks to be duplicate of #1691 

---
When using `data.json` to load data, the API doesn't allow for characters such as periods (.) or dashes (-) in the key, see [fiddle](https://jsfiddle.net/becyhr69/).

```
var data = [
      {'tmp.row': 200, 'tmp_row': 200},
      {'tmp.row': 100, 'tmp_row': 300},
      {'tmp.row': 300, 'tmp_row': 200},
      {'tmp.row': 400, 'tmp_row': 100},
    ]

var chart = c3.generate({
  data: {
    json: data,
    keys: {
      value: ['tmp_row', 'tmp.row'],
    }
  },
});
```

**Comment by schwassj** [comment]
There's a simple workaround - modify the key values being passed in the JSON on the server side.

**Comment by panthony** [comment]
Closing in favor of #1691
