### ISSUE TITLE
Stacked area ordering

### ISSUE THREAD

**Issue by rlcomte** [c3js/c3#1979]
We were experimenting with the stacked area graph. We want to have a data set with larger values for the lowest area, and a data set with smaller values for the area on top. Like: [6, 7, 8] and on top of it [1,2,1]. However the stacked area keeps on putting the smaller values at the lowest area.

Is there a way to change this? An option?
Is it a known issue?

What would be a fix?

**Comment by netil** [comment]
I don't know if I understood correctly. Let's say generating chart with follow options.

```js
c3.generate({
	bindto: "#chart",
	data: {
	    type: "area",
	    colors: {
	        data1: "red",
	        data2: "green"
	    },
	    columns: [
	        ['data1', 1,2,1],
	        ['data2', 6,7,8]
	    ]
	}
});
```
In that case, `data1` is positioned prior `data2`, so `data2` area will be on the top.
![image](https://cloud.githubusercontent.com/assets/2178435/23539289/9e70b2c4-001d-11e7-9f76-1e021785137c.png)

But, if you want `data1` to be on top, like this screenshot
![image](https://cloud.githubusercontent.com/assets/2178435/23539307/c7174f26-001d-11e7-9273-083bb11a49f3.png)

Just change the position of data binding when generating.

```js
    columns: [
        ['data2', 6,7,8],
        ['data1', 1,2,1]
    ]
```

C3 generate area node following data binding order regardless of data's value.
There's [data.order](http://c3js.org/reference.html#data-order) option, but it is for some other data types, not for area.

**Comment by rlcomte** [comment]
Maybe I am missing the point here. But I see two similar screenshots.
What I want is that the second screenshot has the green area at the bottom and the brown one at the top.

**Comment by netil** [comment]
Yeah, isn't really distinguishable, but if you see carefully, the second screenshot is what you want.
The red area is on the top of green area. 

Just bind the data in order, which the latter will be on the top
```js
    columns: [
        ['data3', 9,10,11],  // this will be on the bottom
        ['data2', 6,7,8],    // this will on the second
        ['data1', 1,2,1]     // will place on the top
    ]
```

**Comment by rlcomte** [comment]
I must be very stupid not to see what you see. Here is what I did in the C3.js examples:
![image](https://cloud.githubusercontent.com/assets/4147146/23554101/f4af2048-0023-11e7-8227-edf28cb3d999.png)

**Comment by netil** [comment]
Maybe I'm missing the point.
From your question subject, "stacked area ordering", I though like this.
![image](https://cloud.githubusercontent.com/assets/2178435/23594803/3c1a7a8e-0260-11e7-8f75-b1e151219396.png)

In that assumption, `data1` is on the top(Layer 1 position in the screenshot above), and `data3` at the bottom.
From this perspective, ordering data binding are valid, but I think is not what you need according your comment.

I think you're mentioning `top` and `bottom` from this perspective, right?
![image](https://cloud.githubusercontent.com/assets/2178435/23594935/5c519eee-0261-11e7-95a5-8a2c696e65ef.png)

**Comment by rlcomte** [comment]
Indeed. actually I want to control how the red (data1), green and blue are arranged. In our particular case I want to have data3 at the bottom of the visual display.

**Comment by netil** [comment]
Like this? I'm not sure that this is what you want.
- Working demo: http://jsbin.com/gukogul/edit?js,output
![image](https://cloud.githubusercontent.com/assets/2178435/23600458/01cc6aca-028a-11e7-82b3-a66ed46c3f06.png)

The **"chart"** is the tool to represent the data in a visualized way. Whatever your necessities, the previous illustrations are correct based on that theory technically.

Luckily, C3 has an API to invert axis.
- http://c3js.org/reference.html#axis-y-inverted

Just set follow option, and you can see that y axis is inverted starting 0 from the top.
```js
    axis: {
      y: {
        inverted: true
      }
    }
```

**Comment by rlcomte** [comment]
I see I need to explain it a bit better. I have a set of sensor values, say [7, 6, 5, 7, 4, 8]. For this sensor I have a threshold value of 6. All areas below the threshold should be colored green, the areas above the threshold should be red. So I split the initial values in two sets A [6, 6, 5, 6, 4, 6] and B [1, 0, 0, 1, 0, 2]. Visually I want a stacked area graph (not inverted), with set A occupying the lower part and set B occupying the upper part. I played in Excel and this is what I was able to create.
![image](https://cloud.githubusercontent.com/assets/4147146/23606084/7ea9bee2-025f-11e7-8fc0-3f9ac7784dcb.png)

**Comment by netil** [comment]
I don't think this format as stacked chart.

You can say that is stacked from the baseline, but from the point of view on visualizing the data,
the data 'B' is having  `[7, 6, 5, 7, 4, 8]`.

So, it looks "stacked" in some perspective, but I can say is not.

To represent as you want, you need to set the data to be appeared like that.

```js
// baseline
var A = [6, 6, 5, 6, 4, 6];

// data split from baseline
var B = [ 1, 0, 0, 1, 0, 2];

// but, B should be, sum with baseline data
var B = [ 7, 6, 5, 7, 4, 8];
```
- working demo: http://jsbin.com/gukogul/4/edit?js,output
![image](https://cloud.githubusercontent.com/assets/2178435/23639077/b296ddce-0328-11e7-8cd1-dd61125ab3e5.png)

**Comment by rlcomte** [comment]
Hi Jae Sung,

I appreciate the effort you put in answering my questions. This setup would
work for me, and actually I have the full B data.
Still I don't understand the reasons why the stacked area keeps on putting
the smaller values at the bottom? Is there some theory behind that which I
could check out?


Met vriendelijke groet, kind regards,

Rine le Comte

M rlcomte@gmail.com

**Comment by netil** [comment]
There's no special theory behind that. 

![image](https://cloud.githubusercontent.com/assets/2178435/23652188/46d14cf8-036b-11e7-8684-7f4f7beef57d.png)

In this chart, the 3 circle points, are represented having 7, 7 and 8 respectively, because its points are aligned with the left axis y having those values.

Maybe you still think they are stacked, but is not. The data `B` is there because of its value.
Forget the term `stacked` and just focus about its value and try approach with axis values.

**Comment by rlcomte** [comment]
Sure. And one of my colleagues actually found the most simple solution: add
'order:false'. See http://jsfiddle.net/k9Dbf/26/.

Thanks.

Met vriendelijke groet, kind regards,

Rine le Comte

M rlcomte@gmail.com
