### ISSUE TITLE
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '.c3-ygrid-line.grid99.87' is not a valid selector.

### ISSUE THREAD

**Issue by samskrithib** [c3js/c3#1980]
problem selecting the specific gridline in d3.
Here is my code 

 **var selector = ".c3-ygrid-line."+station.class;
    d3.select(selector).select('text')**

it throws the exception "Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '.c3-ygrid-line.grid99.87' is not a valid selector."
Can anyone help me? 
Many thanks in advance.

**Comment by yasu47b** [comment]
the class name "87" is invalid.

**Comment by alihassan8193** [comment]
### ### 

> 

> 

- _`**_`_**__******_`_**`_
