### ISSUE TITLE
C3 pie chart label position

### ISSUE THREAD

**Issue by gballampalli** [c3js/c3#1982]
I need to know how to configure position of pie chart labels in customised way that is outside the pie chart

**Comment by netil** [comment]
Currently there's no option for that purposes.
You need positioning text label manually like this way.

```js
onrendered: function() {
	d3.selectAll(".c3-chart-arc text").each(function(v) {
		var label = d3.select(this);
		var pos = label.attr("transform").match(/-?\d+(\.\d+)?/g);

		// pos[0] is x, pos[1] is y. Do some position changes and update value
		label.attr("transform", "translate("+ pos[0] +","+ pos[1] +")");
	});
});
```

And don't forget change label text color updating `fill` property value as your necessity.
```css
.c3-chart-arc text {
    fill: red;
    font-size: 13px;
}
```

**Comment by gballampalli** [comment]
@Jae Thanks a lot... One more thing on hovering the tooltip is going inside
the div which should be in front of div...other types of charts except pie
in c3 handle properly the position of tooltip

**Comment by netil** [comment]
@gballampalli, set `tooltip.position` callback to handle the position of tooltip.
- http://c3js.org/reference.html#tooltip-position

```js
        tooltip: {
            position: function (data, width, height, element) {
                // in this case, tooltip will appear x,30 and y:20
                return {
                    top: 20, left: 30
                };
            }
        }
```

**Comment by sathiathirumal** [comment]
Can we make this a native option in C3?

**Comment by diegodominguezm** [comment]
Alguna solución para C3?

**Comment by DigitalWheelie** [comment]
Any feedback about making this native to C3?

**Comment by StanicaAndi89** [comment]
![capture2](https://user-images.githubusercontent.com/45101681/48628987-2c89fa00-e9c1-11e8-96f5-cd46579aa9e6.PNG)

The top and bottom labels are cutoff , do you have any solutions for this?

**Comment by StanicaAndi89** [comment]
Do you know if BillboardJs is working with Rotativa? I need to export these charts to a pdf, C3.js is the only library that I found to work (I ve tried chart.js / chartist.js/ and d3.js)

**Comment by StanicaAndi89** [comment]
I ve just tried and is not showing up in pdf :(

**Comment by vishal-macha** [comment]
@StanicaAndi89 -- I do have a similar requirement as yours..I f you are using C3 JS or D3 JS Please Can you share me an example to display the labels outside the doughnut chart..

Thanks in Advance
