### ISSUE TITLE
Chart loading is extremely slow in IE 11

### ISSUE THREAD

**Issue by djkeh** [c3js/c3#1986]
Tested c3.js version is `0.4.11`. When drawing 14 charts in a page, it doesn't show any problem in Chrome and Firefox, but does in IE 11. It takes over 10 seconds to load every chart on screen.

In javascript debug console, it shows 1 error message, "doesn't support 'undefined' properties or methods:  - jquery.easnig.1.3.min.js", but seems that this message definitely has nothing to do with this latency problem.

When looking at the profiler, the slowest function is `getBoundingClientRect`, which took 13,802.85 ms to be called 3,251 times. This looks strongly suspicious as the function has no such problem in Chrome, which took only 377.8 ms.

So I dug in to the `getBoundingClientRect` function, still no clue. We have some issues here that deal with the related keywords like `IE` or `getBoundingClientRect`, but I can't see the one which is mentioning the same problem with this. Please help.

**Comment by bchociej** [comment]
Same here. Just discovered that C3 graphs take way, way longer to render in IE than in Chrome. We are also using 0.4.11. `getBoundingClientRect` took 11,944.35ms in IE 11 versus 568.9ms in Chrome

**Comment by jagwire16** [comment]
We are also having this problem. We have about 12 charts on the page and they take about 3 seconds to generate in Chrome and about 50 seconds to generate in IE 11.

**Comment by bchociej** [comment]
I just wanted to let everyone in this issue know about some fairly crude fixes I made that might also be of use to others. The idea is to drastically reduce the amount of calls to getBoundingClientRect by whatever means possible, which in this case is some dead simple caching and a tweak to some assumptions about when tick sizes need recalculated. These changes may introduce unforeseen problems, but they are working well for my company.

Importantly, another helpful change was to wrap my calls to `c3.generate(...)` in a `setTimeout(...)`.

Without further ado: https://github.com/juristat/c3/commit/9a809b13ba64ebe96674b4054a0b301cdaf3b090

**Comment by watsocd** [comment]
I played with this for hours and even used bchociej's code. I still had issues in IE11 but not Edge with performance.

What worked was putting this in my HEAD section:
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.5.0/bluebird.core.min.js"></script>

Performance in IE11 is now acceptable. I don't know why.

**Comment by panthony** [comment]
closing in favor of #2303 as there are already too many issues opened for the same reason: poor performances.

There is much to do to improve c3js performance. It's just happen that chrome is much more performant than IE so it's less visible.
