### ISSUE TITLE
Unable to display time

### ISSUE THREAD

**Issue by gadje29** [c3js/c3#1995]
Hi everybody ( and sorry for my deplorable english),
I would like to display the time in addition to the date on the X axis of my charts.
I tried to do this using this syntax:
axis: {
	x: {
	type: 'timeseries', 
	tick: {
	//localtime : false,
	format: '%d/%m/%Y %H:%M:%S'
		}
	}
},
I load my data from a csv like this:
date,Ouverture_Porte_Entree_Exterieur,Ouverture_Porte_Entree_Salon,Ouverture_Porte_Salon_Chambre
2017-03-16 17:08:14,0,2,0
2017-03-17 09:31:33,0,1,0
But the result is not good, it looks like this:
![pb graph_portes](https://cloud.githubusercontent.com/assets/26566984/24139267/be4be292-0e1b-11e7-8fda-dac62357aa6c.jpg)
And when i don't use the hour format everything is ok, like this:
![pb graph_portes2](https://cloud.githubusercontent.com/assets/26566984/24139548/ba157250-0e1c-11e7-9280-2bb33c728ebc.jpg)
If somebody could help me.
Thanks

**Comment by gadje29** [comment]
This is my code:

`var chart = c3.generate({
	data: {
	x : 'date',
	x_format: '%Y/%m/%dT%H:%M:%S',
	//dateFormat: '%Y',
	columns: [
		['date'],
	],
	type: graph,
	selection: {
		draggable: true,
	},
	        colors: {
	data1: '#ff0000',
		},
	},
									
	axis: {
	x: {
	        type: 'timeseries', 
	        tick: {
			format: '%d-%m %H:%M'
			}
		}
	},
		//Durée de la transition
		transition: {
			duration: 2000
		},
		//Taille du graph
		size: {
			height: 500,
			width: 1500
		},
		//Position des légendes
		legend: {
			position: 'right'
	         },
	         //Sous graphique
		subchart: {
			show: true,
			size: {
				height: 30
			}
		},
		//Fonction de zoom
		zoom: {
			enabled: true,
		        extent: [1, 100] // enable more zooming
			//rescale: true
		},
		// Affichage de grille	
		grid: {
			x: {
				show: true											
			},
			y: {
				show: false
			}
		}
	});
        setTimeout(function () {
		chart.load({
			url: groupeEquip
		});
	});`
Thanks

**Comment by urm47** [comment]
Maybe the "input" format is wrong?
xFormat instead of x_format

**Comment by gadje29** [comment]
It works like this:
`xFormat: '%Y-%m-%d %H:%M:%S',`
