### ISSUE TITLE
C3js curve display problem

### ISSUE THREAD

**Issue by gadje29** [c3js/c3#1996]
Hi everybody,
I 'm unable to displaying correctly the C3js spline. The charts look like that :
![pb graph_eclairages1](https://cloud.githubusercontent.com/assets/26566984/24153312/52c6ffce-0e4e-11e7-9055-d18c858855b8.jpg)
Is there somebody who knows how to fix this problem ?
Thanks

**Comment by netil** [comment]
Could you provide online demo for that?
Just screenshot there is limitation to check

**Comment by conceptualspace** [comment]
known issue in d3, unfortunately the upstream fix is in v4, which won't be in c3 any time soon.. (https://github.com/c3js/c3/pull/1871)

**Comment by kt3k** [comment]
Use c3 v0.5.1 or above and `spline: { interpolation: { type: 'monotone' } }` option.

related: #1501
