### ISSUE TITLE
Custom text in legend

### ISSUE THREAD

**Issue by Jaaichandran** [c3js/c3#1997]
I am using c3 graph with angularJS, I am binding the time information in the graph. My data is like 3.88, 55.2, 85 so. But I need to add 'hours' suffixed with the time value in the legends. I have searched in the docs, but haven't found anything. Any help is appreciable.

**Comment by netil** [comment]
You can make a custom legend for that.
Checkout the example below.
- http://c3js.org/samples/legend_custom.html

**Comment by ripdajacker** [comment]
In my company we use the C3 library, but we export the SVG files as images.

Is it possible to create custom legends that are within the <svg> tags?
If not, would you be interested in a pull request for said feature?

**Comment by panthony** [comment]
Original request was answered. If any new feature request arise feel free to open a new issue.
