### ISSUE TITLE
Load multiple csv files in a chart

### ISSUE THREAD

**Issue by gadje29** [c3js/c3#2006]
Hi,
i would be able to load multiple csv, (5~7 files) in the same chart.
Is there anybody knows how can i do this ?
I looked about d3js queue [http://learnjsdata.com/read_data.html](url) but i don't know if c3js is able to do that or if there is another way to do something like that.
Thanks.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
