### ISSUE TITLE
Tooltip default data order.

### ISSUE THREAD

**Issue by shasiuk1** [c3js/c3#2009]
In method '**getTooltipContent**' you're forcing to sort data in asc or desc way. 
But what if in config order is set to 'null' and I want to have default order of data within tooltip (same as legends)? 
Why can't you just check if order is neither asc nor desc than just don't sort the data?

**Comment by martinberlin** [comment]
Completely agree with this one. Will be very nice in some charts not to sort at all the tooltips!

**Comment by ivarkallejarv** [comment]
@martinberlin Could you specify where this option might be? I'm not seeing it in the TooltipOptions interface.

**Comment by panthony** [comment]
This issue was resolved. Please feel free to reopen if you think that it's not.
