### ISSUE TITLE
show hide default grids in Js

### ISSUE THREAD

**Issue by samskrithib** [c3js/c3#2010]
Hi,

Is there a way to show default gridlines onload.
I dont have any custom gridlines. I want to show default grids that appear with code below onload the chart.
grid :{
  y: {
    show : true,
}
}

Many thanks in advance.

**Comment by dhvsandeep** [comment]
refer [this](http://c3js.org/reference.html#grid-y-lines)
set datapoints for which you want to show grid lines

**Comment by samskrithib** [comment]
Thanks for your response but that does not work for me. I have to load different charts on every click and should provide an button to show hide grid lines. 
I solved it using d3
**to show:**
d3.selectAll('.c3-grid line')
            .style('visibility', 'visible')

**to hide**
 d3.selectAll('.c3-grid line')
            .style('visibility', 'hidden')

But it would be better If i have that option in c3

**Comment by dhvsandeep** [comment]
can you post the fiddle here, i'll try that

**Comment by panthony** [comment]
no response from submitter
