### ISSUE TITLE
Inconsistent data/legend/tooltip order

### ISSUE THREAD

**Issue by mgerner** [c3js/c3#2011]
In https://jsfiddle.net/k9Dbf/1605/ , I have a very simple stacked graph. Here, the order of the tooltip items  matches what is seen visually, but the items are ordered differently in the legend. This makes the chart a little more difficult to read. 

![image](https://cloud.githubusercontent.com/assets/995315/24700838/4dc4cbc0-19f0-11e7-8aac-6cf919d9a337.png)

https://jsfiddle.net/k9Dbf/1607/ is an alternative testcase, where the data has been rearranged and ordering has been disabled. The same issue is visible there.

**Comment by panthony** [comment]
@mgerner Your issue appears to be resolved, maybe you could close your ticket.

**Comment by mgerner** [comment]
Indeed. Thanks.
