### ISSUE TITLE
onclick function in area chart is being fired more than once 

### ISSUE THREAD

**Issue by Sreelakshmigc** [c3js/c3#2015]
I am using c3 onclick function to show the details of the chart data. This works fine in pie/donut charts and even bar charts. But while using area chart, the event is being fired again and again on selecting an area having multiple points. Please help me with a solution for this.

the function call I am using is as below
onclick: function(d,i) { //my function }

![areachartonclickissue](https://cloud.githubusercontent.com/assets/6168602/24862096/d49e889e-1e18-11e7-80b3-243b51dc4be2.png)

**Comment by dhvsandeep** [comment]
you may have data.selection.grouped = true, if you change that option to false, onclick will fire only when you click on particular datapoint
but if you have used true, wherever you click on that particular datapoint line, the event will be triggered.

**Comment by Sreelakshmigc** [comment]
Thank you, Sandeep. But the given solution is not working for me. Still waiting for a solution to resolve this issue.

**Comment by dhvsandeep** [comment]
Here is the [fiddle](https://jsfiddle.net/dhvsandeep/mo09afsn/)
Please click on particular data point to trigger onclick event.
If you change grouped key to true, you will have multiple triggers, depends of number of data points.

**Comment by guswo5580** [comment]
My chart has one type and "grouped: false" was not working. what should I do?

**Comment by Sreelakshmigc** [comment]
Hi I found a better solution to this problem. 

- This happens only if you have overlapping values in the charts.

- It is called with respect to the overlapping numbers like if I have 3 vaues falling under count of 5 on the same date in the above graph the click will be called for each of them making it 3 clicks. 

- I resolved this by having multiple tabs dialog / modal on click of the chart.

- All 3 values will be shown a seperate tab inside my modal. 

Code bit looks something like below:

```
onclick: function (d, i) {
                            clickCount++;
                            var axis_x_Value = this.internal.config.axis_x_categories[d.x];
                            var axis_x_label = this.internal.config.axis_x_label;
                            showPivotTableForCharts(input, d, axis_x_label, axis_x_Value);
                       }
```

Hope this helps. Thanks closing this issue.
