### ISSUE TITLE
Rendering in angular service

### ISSUE THREAD

**Issue by preraksola** [c3js/c3#2016]
I am using this library in my angular service, to render the gauge chart.
I have this function in my service:

```
this.setup = function() {
    var chart = c3.generate({
      bindto: '#chart1',
      data: {
        columns: [
          ['data', 91.4]
        ],
        type: 'gauge',
      },
      size: {
        height: 180
      }
    });
    console.log("in setup");
  };
};
```

I call this function from my controller and I also have a `div` element in my html with the id `chart1`.
Upon execution I get the console output but the gauge chart is not rendered. As per my understanding, it is not binding to the html element. Upon normal usage, it is working completely fine but in the setup of my application I am having the issue. Here's the fiddle of the way that I am using it: https://jsfiddle.net/prerak6962/htm4yssL/21/

Is there something that I am missing or that I need to add?
Any help or guidance will be very useful.

Prerak

**Comment by preraksola** [comment]
**Update:**

I was able to generate the chart by calling the setup method in `ng-init`. However, the `bindto` value is determined at runtime as I have multiple charts on the same page. And it fails to render the graph in this scenario. If I hardcode the value for `bindto`, it works fine. Here's the updated [fiddle](https://jsfiddle.net/prerak6962/htm4yssL/27/)

**Comment by panthony** [comment]
For questions involving the interplay between C3.js and any other library (react, vuejs, ..) please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

Thank you!
