### ISSUE TITLE
Data Percentages hide in donut chart for smaller categories

### ISSUE THREAD

**Issue by asadchachar** [c3js/c3#2023]
I am using c3JS donut chart to diplay expenses. The percentage values for smaller expenses get hide because they have lower area on chart.

Is there any way that all data percentages must be displayed or 
Is there any way we can show data percentages to point the chart (instead of displaying on chart)?
![Uploading chart.PNG…]()

**Comment by dhvsandeep** [comment]
the pic is not available

**Comment by asadchachar** [comment]
![image](https://cloud.githubusercontent.com/assets/6999888/25618980/8ea2b440-2f62-11e7-9b29-84ff33bee4cc.png)

**Comment by asadchachar** [comment]
this is picture

**Comment by dhvsandeep** [comment]
if the value is going to be larger, try pie chart
if you insist on using donut, show percentage, and data-label will show the original value
coming to the issue, try setting donut.label.threshold to minimal level of 0.01 to show.

**Comment by asadchachar** [comment]
yeah it worked for me. Thanks.
