### ISSUE TITLE
Fixing zero baseline x axis to be same for both Y axis in dual Y-axis area chart

### ISSUE THREAD

**Issue by asadchachar** [c3js/c3#2024]
Hi,

I am using c3JS dual Y-axis area chart. It is working fine in normal scenarios. I want to fix the zero line x-axis of both Y axes to have same zero x-axis. While y axis grow dynamically, as per data.

Please find screenshot.

![chart](https://cloud.githubusercontent.com/assets/6999888/25417394/3bfa7cc8-2a5d-11e7-8bf0-447c7078b385.PNG)

**Comment by dhvsandeep** [comment]
can you post your jsfiddle code here?

**Comment by asadchachar** [comment]
Issue is resolved by using axis.max and axis.min property dynamically
`var maxi = <max of axis>
var mini = <min of axis>
chart.axis.max({y: maxi, y2: maxi});
chart.axis.min({y: mini, y2: mini});`

![chart](https://cloud.githubusercontent.com/assets/6999888/25762380/003801a4-31f8-11e7-958d-f014a5bad767.PNG)
