### ISSUE TITLE
chart.x() doesn't hold 'localtime: true' into account?

### ISSUE THREAD

**Issue by jurb** [c3js/c3#2028]
When I output the dates in my 'x' column with `chart.x()`, the dates are formatted as follows, whether I enable `'localtime: true'` in the x-axis part of the generate object or not:

`[Tue Mar 20 1990 00:00:00 GMT+0100 (CET), Sat Sep 22 1990 00:00:00 GMT+0200 (CEST)]`

The input is an array with strings representing dates formatted like this: `['Date', '1990-03-20', '1990-09-22',]`

Example of localtime configuration:

```
axis: {
	x: {
	   type: 'timeseries',
           localtime: true,
```

If try to create the dates locally, they are off by one or two hours (depending on DST) from what I get from c3.js:

```
console.log(new Date('1990-03-20')) // returns 'Tue Mar 20 1990 01:00:00 GMT+0100 (CET)'
console.log(new Date( '1990-09-22')) // returns 'Sat Sep 22 1990 02:00:00 GMT+0200 (CEST)'
```

Background information: I want this because I want to write a function that lets you input x-values to select points in a graph. The current chart.select needs an index, which is not really feasible when you have a lot of data points or want people to be able to select a date with a picker. It would be great if I could just select on the column/line and the raw x-value I want.

**Comment by jurb** [comment]
Looking at this further, this seems to be browser/system related, and not C3. On my locale, an hour gets added from (date at exactly 0:00 am) when I use `new Date`, and I don't know why. If someone could explain this to me (new to javascript obviously) what is going on here, that would be very much appreciated.

I can solve my problem using moment.js, which converts both c3's chart.x() output and my dumb string of dates into the same format with this function:

```
function convertToIsoStrings (inputArray) {
                var outputArray = [];
                for (var i = 0; i < inputArray.length; i++){
                    outputArray.push((moment(chartXDates[i]).format()))
                };
                return outputArray;}
```

Running this on the first 2 dates from c3's chart.x() object and my array of `['1990-03-20', '1990-09-22']` returns `["1990-03-20T00:00:00+01:00", "1990-09-22T00:00:00+02:00", "1991-03-20T00:00:00+01:00"]` for both. So I can use `indexOf()` to lookup the index I need to select the points with the `chart.select()` function.

That's a great relief, but I still would like to understand why I can't hack this with vanilla javascript.

**Comment by panthony** [comment]
Closing because not related to c3js, maybe take a look at [Date.UTC](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC).

For further help you should use the Google Group at https://groups.google.com/forum/#!forum/c3js
