### ISSUE TITLE
Multiple Donut chart SVG width and scaling

### ISSUE THREAD

**Issue by Multi-Thinker** [c3js/c3#2032]
Hi, I'm trying to add three donut charts to bootstrap three tabs. 

```
<div id="pie-chart" style="max-height:280px; position:relative"></div>
<div id="pie-chart1" style="max-height:280px; position:relative"></div>
<div id="pie-chart2" style="max-height:280px; position:relative"></div>
```

JS code: 
 ```
var donut = c3.generate({
             bindto: d3.select('#pie-chart'),
            data: {
                columns: [
                    ['Eng', 46],
                    ['Chin', 24],
                    ['Math', 30]
                ],
                type : 'donut'
            },
            legend:{
                position:"right",
            },
            donut: {
                title: "4X+2C",
                width: 8,
				label: { 
					show:true
				}
            },
            color: {
            	pattern: ["#f4f8fb", "#5d9cec", "#5fbeaa"]
            }
        }); 
          var donut1 =   c3.generate({
             bindto: d3.select('#pie-chart1'),
            data: {
                columns: [
                    ['Eng', 46],
                    ['Chin', 24],
                    ['Math', 30] //<-- look over this.. we have new array layout
                ],
                type : 'donut'
            },
            legend:{
                position:"right",
            },
            donut: {
                title: "4X+2C",
                width: 8,
				label: { 
					show:true
				}
            },
            color: {
            	pattern: ["#f4f8fb", "#5d9cec", "#5fbeaa"]
            }
        });
              var donut2 =    c3.generate({
             bindto: d3.select('#pie-chart2'),
            data: {
                columns: [
                    ['Eng', 46],
                    ['Chin', 24],
                    ['Math', 30]
                ],
                type : 'donut'
            },
            legend:{
                position:"right",
            },
            donut: {
                title: "4X+2C",
                width: 8,
				label: { 
					show:true
				}
            },
            color: {
            	pattern: ["#f4f8fb", "#5d9cec", "#5fbeaa"]
            }
        });
```

each chart div is inside a div of fix width of 280px with padding and `position:relative`
first donut-chart appears normal but other two charts appear with donut chart svg width=1083+
first chart svg width is normal, other two charts have 1000+ width can't adjust them. 

here is code of first and second div. 
1st div: 
`<div id="pie-chart" style="position: relative; max-height: 320px;" class="c3"><svg width="284.9250183105469" height="320" style="overflow: hidden;"></svg></div>
`
2nd div:
`<div id="pie-chart1" style="position: relative; max-height: 320px;" class="c3"><svg width="1325.7333984375" height="320" style="overflow: hidden;"></svg><div class="c3-tooltip-container" style="position: absolute; pointer-events: none; display: none;"></div></div>`

again, all of these chart divs are in div of fixed width with padding and margin and position relative. is there a way i can adjust these widths? 

Thank you.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

**It is not a catch-all support forum.**

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
