### ISSUE TITLE
Older webkit version - SVGPathElement not present

### ISSUE THREAD

**Issue by Leprosy** [c3js/c3#2039]
I'm using c3 on an older version of webkit and it throws me a `Can't find variable: SVGPathElement` message(d3 lib is loaded fine)...is there a workaround?

**Comment by Leprosy** [comment]
I've used this script:

```
navigator.sayswho= (function(){
    var ua= navigator.userAgent, tem, 
    M= ua.match(/(opera|chrome|safari|firefox|msie|trident(?=\/))\/?\s*(\d+)/i) || [];
    if(/trident/i.test(M[1])){
        tem=  /\brv[ :]+(\d+)/g.exec(ua) || [];
        return 'IE '+(tem[1] || '');
    }
    if(M[1]=== 'Chrome'){
        tem= ua.match(/\b(OPR|Edge)\/(\d+)/);
        if(tem!= null) return tem.slice(1).join(' ').replace('OPR', 'Opera');
    }
    M= M[2]? [M[1], M[2]]: [navigator.appName, navigator.appVersion, '-?'];
    if((tem= ua.match(/version\/(\d+)/i))!= null) M.splice(1, 1, tem[1]);
    return M.join(' ');
})();
```


...and it tells me this: Safari 532

**Comment by Leprosy** [comment]
Further experimentation made me to discover that this webkit version's only SVG element present is SVGAngle...

Is there anyone having this same issue?

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
