### ISSUE TITLE
Negative floats get rounded to integers

### ISSUE THREAD

**Issue by babjak** [c3js/c3#2056]
As pointed out in this stackoverflow post for pivottable.js (https://stackoverflow.com/questions/38799996/r-rpivottable-bug-the-value-on-the-table-is-not-the-same-with-the-value-on-ba), c3.js seems to have a bug rounding negative floats to integers. v0.4.11 has this bug as well.

**Comment by nicolaskruchten** [comment]
I can confirm that this is actually a bug in PivotTable.js and will be fixed shortly... @babjak you should probably close this issue.

**Comment by babjak** [comment]
The issue is tracked on the PivotTable.js GitHub page here:
https://github.com/nicolaskruchten/pivottable/issues/716

**Comment by maximus009** [comment]
Has this been resolved yet?
I am still facing the issue when passing a negative value.

**Comment by nicolaskruchten** [comment]
Yes this was traced to a bug in PivotTable.js which was fixed.

**Comment by maximus009** [comment]
Thank you for the quick response!

Any negative float (eg. -1.5) I pass gets rounded up (-2).
When I print it on the console, it shows -1.5, however, the chart plots the point at -2.

Could you kindly guide me with how I could rectify that.

Thanks in advance.

**Comment by nicolaskruchten** [comment]
Using pivottable.js or just c3js by itself? If it's with pivottable.js:
which version are you using? Try the latest one with the bug fix :)

**Comment by maximus009** [comment]
I am using c3js by itself; in the c3.generate(...) call.
Please refer to this <a href="http://jsfiddle.net/6gzfjrof/" target=_blank>Fiddle</a>

Thanks.

**Comment by nicolaskruchten** [comment]
Ah in that case I recommend creating a new issue... the source of this one
was a bug in PivotTable.js and likely has no relation to your issue :)

**Comment by maximus009** [comment]
Okay, thank you. :)
