### ISSUE TITLE
Is it possible to hide line mark circles? 

### ISSUE THREAD

**Issue by kosamari** [c3js/c3#206]
Is there a way to hide line mark circles? (image)
I'm creating dashboard with Line Chart and Scatter Plot. 

My line chart has many data points that having line mark gets too crowded. 
I comment out "selectedCircle" "selectedCircles" "circle" "circles" CLASSes to achieve it, but then that also disabled Scatter Plot circles to appear. 
Is there hide line mark method??

Current : 
![withlinemark](https://cloud.githubusercontent.com/assets/4581495/2864022/c16878ea-d20b-11e3-9ff4-75331cf77cc7.png)

Want it to be : 
![nolinemark](https://cloud.githubusercontent.com/assets/4581495/2864032/ce9289d4-d20b-11e3-84dc-53c51a1477e3.png)

**Comment by jayankarthik** [comment]
Is it possible to hide the line using the API? I know I could use a scatter graph instead, but I got to use spline with my requirements
