### ISSUE TITLE
Customize axes thickness?

### ISSUE THREAD

**Issue by Tamba32** [c3js/c3#2061]
Any way to change the thickness of the axes?  Right now they are too wide/bold for the scale of my chart.

Thanks.

![image](https://cloud.githubusercontent.com/assets/15708264/26653118/22c36092-4620-11e7-836b-7404d4970ff8.png)

**Comment by martingraham** [comment]
That looks like you might be missing the c3.css file altogether

If not, this rule usually fixes that problem in axes -->
```
.c3 path, .c3 line {
  fill: none;
  stroke: #000; }
```

**Comment by nobitagit** [comment]
Did you try to search for existing, related issues on here? 
This one #1962 could help you.

**Comment by netil** [comment]
try modifying `stroke-width`

```css
.c3-axis .tick line {
    stroke-width: 0.5px;
}
```

**Comment by Tamba32** [comment]
Thanks everyone. I had forgotten to manually import the css.
