### ISSUE TITLE
Adding Non  Chata Arrays

### ISSUE THREAD

**Issue by delgado92651** [c3js/c3#2071]
I have code for a C3 multiple line xy chart.  I would like to add an additional array of year values:

     2011, 2012, 2013, 2014, 2016, 2017

these will not be used in the chart itself, based on the data point that is clicked the year corresponding to that data point will be included in the onclick parameter expression. 

I don't know what syntax to use for the year array or where to locate the year array, and don't know how to extract the year from year array to put into var = clickYear. 

External to the chart I have built a message dialog box to display all of the parameters passed, Data, Value, Cat & Year. I now the first three passed to my Filemaker database. I couldn't figure out how to include all information in a tooltip or label, this seems to work.

    `var chart = c3.generate({
    point: {
    r: function(d) { 
       return (d.x + d.value)*3 ;
    } //weighted point size
    },
    data: {
        xs: {
            'data1': 'x1',
            'data2': 'x2',
            'data3': 'x3',
            'data4': 'x4',
        },
        columns: [
        //   **Data1**
            ['x1', 10, 30, 45, 50, 70, 100],
            ['x2', 30, 50, 75, 100, 120],
            ['data1', 30, 200, 100, 400, 150, 250],
            ['data2', 20, 180, 240, 100, 190]
        ],

        //onclick 
    onclick: function (d) { 
    var clickData = d.id;
    var clickValue = d.value;   //y value ROS
    var clickCat = [d.x];       //x value AU
    //  var clickYear = ??

    var allTogether = clickData+"|"+clickValue+"|"+clickCat;
    var theURL = "fmp://$/**FileName**?script=**ScriptName**&param=" + allTogether
    window.location = theURL;}, //onClick 
    },
        zoom: {
            enabled: true,
            rescale: true
                 } //zoom
    });
    };
`

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
