### ISSUE TITLE
C3 chart tick values position

### ISSUE THREAD

**Issue by adrianavaz-omibee** [c3js/c3#2074]
I'm building a chart and this is what I have so far: https://i.stack.imgur.com/li1Yn.png

It is a chart with horizontal bar, so the x axis is rotated. I would like to change the position of the ticks (tick 1, tick 2, tick 3) to have something like this: https://i.stack.imgur.com/9BG7I.png

Is this possible to do with c3? I didn't find anything on the references.

Thank you!

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
