### ISSUE TITLE
Move built files to dist, remove from version control

### ISSUE THREAD

**Issue by aendrew** [c3js/c3#2076]
A thought — should we set `lib/index.js` to the `module`, `dist/c3.js` to the `main` attribute in `package.json`, move all the built files to `dist`, put `dist` in `.gitignore` and then set Travis or Circle to build on release?

## Advantages:

* No built files showing up in PRs
* Using C3 as a ES6 module totally bypasses build process — it gets built as part of downstream bundler in consumer project
* This in turn will enable people creating plugins to bundle them and C3 together in downstream projects, which may result yield better file sizes due to letting the bundler handle minification. Possibly, I'm not at all sure.
* Possibly opens the way for better use on the server?

Reference re: `pkg.module`: https://github.com/rollup/rollup/wiki/pkg.module

**Comment by aendrew** [comment]
Err, by `lib` I mean `src`, though thinking about it a bit more, I wouldn't mind renaming `src` to `lib` because it might help differentiate between earlier versions of code, i.e., before the change to Rollup and modules happened.

**Comment by kt3k** [comment]
I agree with .gitignoring the built files somehow. How about ignoring /c3{.min}.{css,js} and copy them under /dist/ only when releasing the new versions?

I think it's a little too early to support ES module thing at this moment. Though rollup supports pkg.module for pointing ES module, Node.js community seems going to a different direction. (See [1](http://2ality.com/2017/05/es-module-specifiers.html) or [2](https://twitter.com/nodemjs). I'm quite skeptical that pkg.module is going to be the standard.
I'd prefer to keep the current dist style at least until Node.js (and npm) community fixed the spec of ES module.

**Comment by aendrew** [comment]
Eurgh, I'd thought the whole .mjs idea had died off and `pkg.module` was what people were considering. 

Agreed, let's let everything stabilise before jumping into that. Cool otherwise re: dist files.

**Comment by kt3k** [comment]
Built files are moved to `/htdocs` and removed from the version control.

refs: #2424
