### ISSUE TITLE
Timeseries Chart: bars overlapping each other

### ISSUE THREAD

**Issue by vikshab** [c3js/c3#2079]
<pre>
var chart = c3.generate({
    data: {
        x: 'x',
        columns: [
            ["ChartHttpCodes", 1, 7, 95, 191, 645, 1],
            ["x", 1496955600000, 1496995200000, 1496998800000, 1497002400000, 1497006000000, 1497052800000]
                ],
        type: 'bar' 
    }
    axis: {
        x: {
            type: 'timeseries',
            tick: {
                format: '%m/%d %H:%M'
            }
        }
    }
});
</pre>
![screen shot 2017-06-13 at 11 23 21 am](https://user-images.githubusercontent.com/10720549/27098005-e75ff316-502a-11e7-9ae4-165f096c94a1.png)

<pre>
var chart = c3.generate({
    data: {
        x: 'x',
        columns: [
           ["ChartHttpCodes", 14, 14, 28]
            ["x", 1496998800000, 1497002400000, 1497006000000]
                ],
        type: 'bar' 
    }
    axis: {
        x: {
            type: 'timeseries',
            tick: {
                format: '%m/%d %H:%M'
            }
        }
    }
});
</pre>
![screen shot 2017-06-13 at 11 27 01 am](https://user-images.githubusercontent.com/10720549/27098105-3f0e3bea-502b-11e7-9012-1ec7d0cad5d1.png)

Why bars on the first chart get overlapping?
Is it because there is a large gap between data point in the first example (06/08 14:00 and 06/09 )

**Comment by panthony** [comment]
An issue was already open for this bug, see #1386
