### ISSUE TITLE
how to make c3 not create point ?

### ISSUE THREAD

**Issue by chaserstrong** [c3js/c3#2085]
My data is large and i needn't show these points over my polygonal line.
so i set point.show false. however, it can just set opacity:0 for circle label.
are there any other solutions?

**Comment by kt3k** [comment]
I guess this is a mistake.

**Comment by chaserstrong** [comment]
@kt3k  yes,i hadn't finished  just now.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!

**Comment by Mshardul** [comment]
> 
> 
> My data is large and i needn't show these points over my polygonal line.
> so i set point.show false. however, it can just set opacity:0 for circle label.
> are there any other solutions?

You can set the point-radius to 0. 
`point: { r: 0 }`
