### ISSUE TITLE
How to fill only 33%, but other 66% leave empty?

### ISSUE THREAD

**Issue by Nikulio** [c3js/c3#2086]
Greetings, commrads 
I have one minor issue 

I have this data columns : 

`	columns: [
	    ['data1', 33],
	],
`
and was expecting, that c3 fill only 33% of donut, and other 66% leave white. On timeout I am loading other 33% and so on. But atm it filling 100% instead of only 33%.
How may I fix this trouble?

Thanks

**Comment by panthony** [comment]
The columns expect absolute values, no percentage, so 33 represent 100% of the total.

For further support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.
