### ISSUE TITLE
big values in axis y

### ISSUE THREAD

**Issue by gasparmedina** [c3js/c3#2087]
Hello I'm trying to put values of hundreds of thousands and millions in the axis of the and, but according to my design of the application or the size of the graph these values are broken.
The solution that occurred to me was to shorten the thousands and millions with another format for example

* 7 = 7
* 12 = 12
* 856 = 856
* 1000 = 1k
* 5821 = 5.8k
* 10500 = 10k
      * 101800 = 102k
2000000 = 2m
* 7800000 = 7.8m
* 92150000 = 92m
* 123200000 = 123m
* 9999999 = 10m

But I can not combine the values and the following axis / and / tick / values properties with, axis / min, axis / max, and grid / and / lines

Can someone help me solve this?
![captura](https://user-images.githubusercontent.com/15022741/27440429-1979c8d2-5741-11e7-87e5-80324ea31443.PNG)

**Comment by kjavia** [comment]
Overriding the `axis.y.tick.format` function may help.

**Comment by forteddyt** [comment]
Like @kjavia said, overriding the `axis.y.tick.format` is probably close to what you're looking for. The main thing you're going to try to do is to assign a function to be run on each value, and return a string representation of it afterwards.

Here's a [fiddle](https://jsfiddle.net/forteddyt/hthwhqs8/) of roughly what you're looking for. Modify as needed!
