### ISSUE TITLE
Guig is not a valid selector for chart.

### ISSUE THREAD

**Issue by rdcm** [c3js/c3#2089]
I'am trying use c3 chart in angular4 app, for several charts on page, i need specify unique id for each.
But when i set guid like a string to bindto, i see error in browser console:
'0058bc4d-754b-43d7-8e91-860d47012f4d' - is not a valid selector.

if i concat guid with char like 'z0058bc4d-754b-43d7-8e91-860d47012f4d', all work perfect.

This is bug or feature?

C3 version:
"c3": "0.4.14",

**Comment by causztic** [comment]
https://github.com/d3/d3/issues/1858

**Comment by rdcm** [comment]
Thanks, i'm not strong in css :) issue closed
