### ISSUE TITLE
Line data not show

### ISSUE THREAD

**Issue by thinhnk** [c3js/c3#2094]
i use c3 v0.4.14 and d3 v3.5.17
My code
```
var chart = c3.generate({
                data: {
                    columns: [
                        ['data1', 30, 200, 100, 400, 150, 250],
                        ['data2', 50, 20, 10, 40, 15, 25]
                    ]
                }
            });
```

screenshot

![linechart](https://user-images.githubusercontent.com/3068902/27860331-521dacfc-61a6-11e7-9f9a-3de086fa64ad.png)

**Comment by kt3k** [comment]
Can you provide a little more context? (browser versions etc)

Does this example work on your environment? http://jsfiddle.net/kt3k/71b85fha/

**Comment by adius** [comment]
I'm having the same issue. Really frustrating when even the simplest of all examples doesn't work 😭.

**Comment by kt3k** [comment]
I checked the above example in chrome, firefox, safari and IE11 (on mac) but didn't reproduce the above error.

Can you provide some information about your environment. (Browser version & OS version)

**Comment by adius** [comment]
The problem for me was, that I hadn't specified a height for the container element and was using flexbox. So the chart had a height of `0` and just didn't show up. It's really annoying that c3 has all kinds of quirks in a flexbox environment ...
