### ISSUE TITLE
How to use custom functions to decorate tooltip

### ISSUE THREAD

**Issue by ceremcem** [c3js/c3#2095]
Can we pass a function to decorate the tooltip?

## Edit 

![image](https://user-images.githubusercontent.com/6639874/27891825-afe6cbb2-6204-11e7-9741-6c412c014a64.png)

`x axis` is a simple unix time but I need to convert it to a human readable form. `y axis`, on the other hand, contains many decimal digits. I also have [another function](https://github.com/aktos-io/scada.js/blob/master/src/lib/aea/formatting.ls#L133-L158) to perform rounding and zero padding, when needed. 

So I want to pass these functions to convert a data before displaying on the tooltip.

**Comment by fernandoluizao** [comment]
Maybe this helps?

http://c3js.org/samples/tooltip_format.html

**Comment by panthony** [comment]
No response from submitter
