### ISSUE TITLE
offset for Null point

### ISSUE THREAD

**Issue by mpushkix** [c3js/c3#2102]
i have next value for columns:

`[null, null, null, 1.34, 1.23]`
![screenshot from 2017-07-14 09-23-34](https://user-images.githubusercontent.com/4003435/28203606-1e9b003a-6883-11e7-99ec-00d1a5f965db.png)

Also I have several arrays of the same length to display the corresponding information. I would like to shift the graph to hide zero elements and do not clean other arrays that depend on the length. Is there a way to do this with this library? I did not find an example of such cases.

**Comment by panthony** [comment]
No there are no such option.

If you do not want to plot a `null` point you have to filter out before passing it to the charts.

For further support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.
