### ISSUE TITLE
C3 & Vue 2.0 - Customizing Columns based on JSON data ? 

### ISSUE THREAD

**Issue by nygter** [c3js/c3#2103]
Greetings :)

Well.. might be that someone already asked this question, either though i could not find anything similar to what i need (maybe i need a better grade in googling).. 

Thing is... 

I have this JSON result from API-call: 
```
"buckets": [
                {
                    "key": "Fornyet ikke lastet ned",
                    "doc_count": 7861
                },
                {
                    "key": "Bekreftet levert til mobil",
                    "doc_count": 5259
                },
                {
                    "key": "Betaling kansellert",
                    "doc_count": 1037
                },
                .... etc.etc.etc....
```

And by that... i'm trying to use this as the source of the cake diagram i'm creating like this : 

```
var c3 = require('c3')

export default {
    name: "statorderstatus",
    mounted() {
           this.$store.dispatch('getStatisticsForOrderStatus'),
           c3.generate({
                bindto: this.$el,
                data: {
                    columns : this.statOrderStatus,
                    type : 'pie',
                    onclick: function (d, i) { console.log("onclick", d, i); },
                    onmouseover: function (d, i) { console.log("onmouseover", d, i); },
                    onmouseout: function (d, i) { console.log("onmouseout", d, i); }
                    
                }
            })
            

        },
        computed: {
            ...mapGetters(["statOrderStatus"])
        },
}
```

But i cannot seem to get my head around how to actually.... customize the columns, and tell the columns that it's "key" and "doc_count" which is the key/value pairing wanted for creating the columns..

Anyone know how to do this ?

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
