### ISSUE TITLE
Change chart title size

### ISSUE THREAD

**Issue by chendachao** [c3js/c3#2106]
The first time I use c3 I loved it. But if it could have the property to allow developer change the size of title, it would be better.

**Comment by samskrithib** [comment]
.c3-chart-arcs-title {
  font-size: 1.3em;
}

**Comment by chendachao** [comment]
Yes, you're right. If c3 has such build-in property it would be better.

**Comment by panthony** [comment]
There is little value to ask for custom styles for all elements (title, data labels, legends, ticks, ...) using JS properties instead of simply overriding the css.

Closing because we are not likely to add such an option (any time soon).

**Comment by Llorx** [comment]
There is value when you let the user create multiple dynamic charts in different forms and shapes inside the same panel. Dealing with classes is a pain in this case.

**Comment by buckelieg** [comment]
> There is little value to ask for custom styles for all elements (title, data labels, legends, ticks, ...) using JS properties instead of simply overriding the css.
> 
> Closing because we are not likely to add such an option (any time soon).

How about this case:

![image](https://user-images.githubusercontent.com/23184851/68289361-03adb980-0097-11ea-9008-3a3e6616e95b.png)
