### ISSUE TITLE
Legend Order Screwed Up After Transform

### ISSUE THREAD

**Issue by ja153903** [c3js/c3#2119]
So I have this visualization where I want the user to be able to turn the area chart I made into a stacked bar chart and give them another button so that the graph can go back to being an area chart.

The problem is that when you transform back to the area chart, the colors do not match up.

When I hover over the red legend key, it corresponds to the blue one, etc.

Is there a fix for this?

**Comment by cwackerfuss-rl** [comment]
Hey @ja153903 same problem here:

![chart bug](https://user-images.githubusercontent.com/25306403/32850231-37111fb6-c9f7-11e7-89c3-fb2031da977e.gif)
