### ISSUE TITLE
zoom in and zoom out how to reset my zoom in...

### ISSUE THREAD

**Issue by chardats** [c3js/c3#2122]
i have 5000 values and c3 is very slow,so i made averages every 39 values to make values less.So i want when i zoom in the values to be more and when i zoom out the values to be in the place they were before the zoom in.Is it possible?

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
