### ISSUE TITLE
how to access json data received in url call

### ISSUE THREAD

**Issue by abhi11verma** [c3js/c3#2124]
Below is the code to generate barchart using C3 js library

```
var chart = c3.generate({
    bindto: '#barchart',
    data: {
      url: './API/get_bar_chart_data.php',
      mimeType: 'json',
      type: 'bar',
      keys: {
             x: 'category', // it's possible to specify 'x' when category axis
             value: [ 'number']
            },
      onclick: function (d, i) { 

                              console.log(chart.categories()[d.index]); 

                              onclick_barchart();
                              }
      },
  bar: {
        width: {
            ratio: 0.5 // this makes bar width 50% of length between ticks
               }
       },    
    axis: {
        x: {
            type: 'category' // this needed to load string x value
        }
    }

});
```
In the above code I am getting data from URL in json format.

Now on click I want to pass this complete json received to onclick_barchart() function.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
