### ISSUE TITLE
Click on Line graph 

### ISSUE THREAD

**Issue by mikias10** [c3js/c3#2126]
Is there anyway to click on a selected line on a time series to see a tooltip instead of clicking on the dots and see a specific information?
I am interested in showing the total over a period of time when the user clicks anywhere on the line. 
Currently I can only click on the dots.

**Comment by Cobry** [comment]
You can take my code : http://jsfiddle.net/6dahdmda/

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
