### ISSUE TITLE
[missing doc] Unable to figure out how to align horizontally different data sets

### ISSUE THREAD

**Issue by edmondo1984** [c3js/c3#2128]
The following JS fiddle https://jsfiddle.net/9tczevk4/ shows an example of a realistic use case: some grouped bars and line charts (without a line) that represent a "upper bound".

How can the circles for the line chart be aligned correctly to the bars?

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
