### ISSUE TITLE
Horizontal bar stroke doesn't get dynamic color

### ISSUE THREAD

**Issue by nbdavies** [c3js/c3#2136]
I'm trying to style a bunch of bar charts to have opaque edges and translucent interiors:

```
.c3-bar {
  stroke-width: 2px;
  stroke-opacity: 1;
  fill-opacity: 0.8;
}
```

The color of the bars in these charts is determined via a data.color function that's different for each chart.

For vertical bar charts this works great, because the same color (determined via function) gets applied to the bar's fill and its stroke. But for horizontal bar charts, with flipped axes, the color determined by the function only gets applied to the bar's fill, not to its stroke. So the stroke color defaults to black.

Because the color of each bar is being dynamically determined by function, it's not practical to override the colors from a CSS file.

**Comment by nbdavies** [comment]
I think I see what's going on. In c3/shape.bar.js, updateBar() updates both:
```
        .style("stroke", color)
        .style("fill", color);
```
While redrawBar() does not:
```
            .style("fill", this.color)
```
Horizontal bar graphs must be doing a redrawBar(). I tested making redrawBar() consistent with updateBar(), and it would indeed solve the problem.

I'll try to put together a PR.

**Comment by kt3k** [comment]
Thanks for reporting!

Confirmed as a bug. Thanks!
https://jsfiddle.net/kt3k/p2ncr8xs/4/
