### ISSUE TITLE
How Can I display % value in Pie chart Legend Item text.

### ISSUE THREAD

**Issue by sunilariel** [c3js/c3#2159]
I have created Pie chart and it is working ok. In Pie Labels showing % values and it is also fine. But now I just want to show % value(number) in Legend item text also.
e.g. 

**var ChartDesignCreated = c3.generate({
                    bindto: "#Chart1",                       
                    data: {                       
                        columns: [
                               ['Football', 10)],
                               ['Cricket', 10)],                             
                        ],                          
                        type: 'pie'
                    }
                });**

**_Legend item text should be display like :
Football = 50%
Cricket =  50%_**

Is it possible?

Thanks.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
