### ISSUE TITLE
Some problem with rendering of Pie Charts in Firefox

### ISSUE THREAD

**Issue by ottodranik** [c3js/c3#2163]
Hi all.

After my Firefox browser was update to 55 version I started see some problem with rendering of Pie Charts. 
I am sorry if this issue does not have relation to c3.js exactly, but I want to understand what is the problem.
Pls, see screenshots. Problem is reproduced only on Firefox 55 and not reproduced for Firefox 54 or latest Chrome. 
![2017-09-05 11 58 00](https://user-images.githubusercontent.com/3233447/30054111-a9252198-9233-11e7-8b2b-b4c52da17b28.png)
![2017-09-05 12 14 55](https://user-images.githubusercontent.com/3233447/30054178-e2fbcd18-9233-11e7-8d21-93ccf495c39f.png)

Thank you for your response and sorry for the trouble.

**Comment by panthony** [comment]
Hi,

Could you provide a JSFiddle, codePen or Plunkr highlighting the issue?

It makes reproduction much easier for everyone.

Thank you!
