### ISSUE TITLE
Y axis line background

### ISSUE THREAD

**Issue by rook-tain** [c3js/c3#2166]
Hi, I have a problem, I want to do the background on my chart on Y axis.
<img width="361" alt="zrzut ekranu 2017-09-07 o 17 23 19" src="https://user-images.githubusercontent.com/10730889/30171160-5e27db9e-93f1-11e7-8144-da2e705efd14.png">

Is it possible? I tried couple of times but no success.

**Comment by martingraham** [comment]
You can do most of that by adding some y-grid lines and changing the css on them and the y-axis. Change the values to what suits you best.

http://jsfiddle.net/8Lp3k7ac/1/

The only thing I couldn't do was shift the gridlines over to include the axis numbers, In an .onrendered function I tried nulling the clip for the grids, but changing the x1 attr for the lines never took affect, I think the grid stuff must get set up after that point

**Comment by rook-tain** [comment]
Thank you thats perfect, I tried to fight to move that too, no results, but I agreed with designer to not shift the gridlines.

Thank you
