### ISSUE TITLE
c3 time series scatter chart, time data in y axis.

### ISSUE THREAD

**Issue by dewanshamsul** [c3js/c3#2174]
* **C3 version: 0.4.10**:
* **D3 version: 3.5.5**:
* **Browser: Firefox 55.0.3**:
* **Client OS: Windows 10**:
* **Server OS: CentOS 6**:

I am working on a C3 time series scatter chart.

http://jsfiddle.net/dewanshamsul/f81ymrpc/1/

I want to use time data in the y axis like the following:

http://jsfiddle.net/dewanshamsul/t6rtLofc/6/

But it is not working.

I tried to use 

    y: 'Time',
        yFormat: '%H:%M:%S',

    axis: {
        y: {
            type: 'timeseries',
                tick : {
                        format: d3.time.format("%X",)
                },
        },

I saw one example in R where someone plotted time data in y axis so I was wondering whether it is supported or I am missing something?

**Comment by kt3k** [comment]
How about rotating axis by `axis: { rotated: true }` option? like http://jsfiddle.net/f81ymrpc/2/

**Comment by dewanshamsul** [comment]
I am extremely sorry. Somehow I posted the wrong jsfiddle. Please check the updated fiddle now.
http://jsfiddle.net/dewanshamsul/t6rtLofc/
I have Date in x axis in the following format 2017-09-05
I have Time in y axis in the following format 13:30:45
Getting to plot the time in y axis is the main issue.

**Comment by dewanshamsul** [comment]
It seems like the thing I am asking for is not supported at this moment. So I have to convert the time either to timestamp or in other format which are supported.
