### ISSUE TITLE
C3 & D3

### ISSUE THREAD

**Issue by jerryhall** [c3js/c3#2179]
Are we only able to use C3 with D3 3.5? 

I don't understand the dialog in the other issues as it relates to this question. 

Thanks!

**Comment by kt3k** [comment]
For the moment, yes. We need d3 3.5. We are trying to migrate to d3 v4 (#2143), but I can't say exactly when it happens.

**Comment by sipujena** [comment]
d3 3.5 is more than a year old and outdated almost. C3 needs an urgent update to work with current version of d3 or at lest d3 v4 .

**Comment by boris-petrov** [comment]
@kt3k, @panthony - this issue could be closed after support for D3 v4 has been added.

**Comment by panthony** [comment]
Support for D3 v4 added by https://github.com/c3js/c3/commit/ccff119809de05a68ff3e33521a79566bf12b903 and should be available in the `0.5.0` release.
