### ISSUE TITLE
Is there a way to place icon in place of text for Gauge Chart

### ISSUE THREAD

**Issue by lokeshcherukuri** [c3js/c3#2183]
Can we place an icon (some font awesome icon) instead of text as current Gauge value?

http://plnkr.co/edit/JgqxyrccRuhy7KOr12sp?p=preview

C3 version: 0.4.11
D3 version: 3.5.17.
Browser: Chrome.
OS: MacOS.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
