### ISSUE TITLE
Pie chart artifacts

### ISSUE THREAD

**Issue by ArtsiomYeliseyenka** [c3js/c3#2184]
![image](https://user-images.githubusercontent.com/21034967/30966066-42e11344-a460-11e7-8725-e1f5c3ba5125.png)

There are some unexpected artifacts on pie chart (strange vertical green line at the bottom of the chart). It's happens when one data item has very big value ( e.g. 5000+ ), and the other one is very small ( e.g. 4 ). 
And is there any way to remove separating white area between pie chart sectors?

**Comment by martingraham** [comment]
"And is there any way to remove separating white area between pie chart sectors?"

Add this rule to your css

```
.c3-chart-arc path {
    stroke-width: 0;
}
```

**Comment by ArtsiomYeliseyenka** [comment]
@martingraham Thanks a lot!
