### ISSUE TITLE
Stacked Bar chart as "Progress Par"

### ISSUE THREAD

**Issue by leonardolb560** [c3js/c3#2191]
Hi, i have this chart. As you can see, the Budget value of Ilustrador is 5 and burned value is 20.
However, the bar in this chart sum up 25, which causes some confusions and misunderstandment.

Is it possible to make this chart sum up 20?

![image](https://user-images.githubusercontent.com/20689140/31394243-40d8e966-adb4-11e7-804b-8fe2c59044eb.png)

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
