### ISSUE TITLE
Question about one legend for two lines

### ISSUE THREAD

**Issue by xmnlab** [c3js/c3#2193]
hi everyone,

I have a chart with upper and lower confidence interval. It is possible to have just one legend for both?

Thanks,

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
