### ISSUE TITLE
Percentage formate

### ISSUE THREAD

**Issue by Youfka** [c3js/c3#2209]
**C3 version 3.5.0**
**D3 version 3.5.17**
**Browser Chrome**
**OS Windows**

I have a graph with currency line, with some lines with number format and I want to add a line with percentage format, but I want it to show percents of maximum value. How can I do that?

**Comment by amitozdeol** [comment]
Some code would be better.

**Comment by Youfka** [comment]
`[
                ['data1', 250000, 200000, 160000, 140000, 210000],
                ['data2', 105360, 40000, 100000, 50000, 45000],
                ['data3', 115360, 54000, 145000, 34000, 69000],
                ['data4', 10%, 13%, 16%, 25%, 30%]
            ]`

I want data4 to display not as 10 + % after it, but as a percentage value from Y (for example, as 100 of 1000, and I want to display points as a percentage of the axis Y).

**Comment by amitozdeol** [comment]
I believe that's what you looking for? - https://jsfiddle.net/mcd6ucge/346/

**Comment by aleksey-korotkevich** [comment]
@Youfka I believe you can do this something like this, in some generic way, that does not depend on how much elements percent array has
https://jsfiddle.net/aleksey_korotkevich/xv3bL1fm

**Comment by Youfka** [comment]
thank you! It works now (I tried amitozdeol's solution)
