### ISSUE TITLE
Possible bug involving categories, colors, and names. Colors on graphs seem inconsistent only when names are given.

### ISSUE THREAD

**Issue by knightbk** [c3js/c3#2215]
* **C3 version**: 0.4.10
* **D3 version**: 3.5.6
* **Browser**: Chrome 
* **OS**: macOS Sierra (10.12)

Here is a fiddle describing the problem: https://jsfiddle.net/kj6o6L1w/

Note how the colors are inconsistent with how they are described in the code. As a trial, remove the names section from data and the colors will then be correct.

Am I misusing the product or is this a bug?

**Comment by NullVoxPopuli** [comment]
what was the solution?
