### ISSUE TITLE
d3 v4 needed, but c3 as well

### ISSUE THREAD

**Issue by heckerf** [c3js/c3#2222]
I need to use d3 v4, because I need Voronoi diagrams which are not available in d3 v3. But I also want to use c3js on the same page, which is not compatible to v4 in d3. 

Can anyone advise on how to achieve this?

**Comment by ivarkallejarv** [comment]
You can install d3 separately, a version that contains the necessary diagrams.
That way, even if c3 does not have the necessary version of d3 that you need, you don't depend on c3 updating their dependencies

**Comment by hgoebl** [comment]
I know that d3 v4 introduced many changes and it is far from being a "drop-in" replacement for v3.
But are there any plans to upgrade c3 to use d3 v4?

**Comment by ivarkallejarv** [comment]
Yes, and a quick search in issues brings up the relevant thread where it's tracked as well, namely this - https://github.com/c3js/c3/issues/2143

**Comment by uniquejava** [comment]
Looking forward, I am using d3-word-cloud plugin which based on d3 v4, I also want to use c3. They can't quite coexist so far.  Thanks for this hard work.

**Comment by jarkkombrain** [comment]
Billboard.js is c3 fork with d4 support.
https://naver.github.io/billboard.js/

**Comment by ontelo** [comment]
Billboard.js is c3 fork with d4 support.
https://naver.github.io/billboard.js/

**Comment by boris-petrov** [comment]
@kt3k, @panthony - this issue could be closed after support for D3 v4 has been added.

**Comment by panthony** [comment]
Support for D3 v4 added by https://github.com/c3js/c3/commit/ccff119809de05a68ff3e33521a79566bf12b903 and should be available in the `0.5.0` release.
