### ISSUE TITLE
How can i enable a particular point in area chart?

### ISSUE THREAD

**Issue by keshav1007** [c3js/c3#2223]
Hi,

I have drawn area chart using c3 and i don't want to enable points(dots) on the graph so i am hiding the points using:

point: {
    show: false
}

Now i want to enable a particular point in the graph (say at the index of 5). Is there any way to enable particular point in the graph? how can i achieve this?

**Comment by amitozdeol** [comment]
You can just make the color of the points transparent - http://jsfiddle.net/bLt1sojz/20/

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
