### ISSUE TITLE
seperate data input to x axis and y axis from seperate url (in terms of on x axis it is Date and on y axis it is intijer value)

### ISSUE THREAD

**Issue by aniketdhamane** [c3js/c3#2228]
example:  
setInterval(function(){
		var chart = c3.generate({
			
		    title: {
		        text:'Real Time Registration Chart '
		    },
		    bindto: '#chart',
		
		    data: {
		    	
		    	   url: 'attendance',
			       mimeType: 'json', 
			    	    length: 5	   
		    },
		  
		    axis: {
		    	
		        x: {
		            label: 'Date',
		            position: 'outer-middle' 	
		        },
		        y: {
		            label: 'Registrations',
		            position: 'outer-middle' 	
		        }
		    }
		})
		
		    }, 1500)

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
