### ISSUE TITLE
How to generate Daynamic registartion chart (on x axis date and on y Axis it is Registrations count) data from URL like from service How to generate it)

### ISSUE THREAD

**Issue by aniketdhamane** [c3js/c3#2229]

**Comment by amitozdeol** [comment]
Don't quite get it. Can you elaborate?

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
