### ISSUE TITLE
Only show circle points on hover

### ISSUE THREAD

**Issue by lucasharada** [c3js/c3#2237]
I need to remove all circle points by default and only show them when under the hover effect. The only way I could get it to work was when settings the width of the lines to be at least the same width of the circle points.

When setting `point: { show: false }`, all points are gone, including the hover effect. Is there a way to disable the circle points, but show them on hover?

* **C3 version**: 0.4.18
* **D3 version**: unknown [(this one)](https://d3js.org/d3.v3.min.js)
* **Browser**: Chrome 63.0.3239.84
* **OS**: MacOS High Sierra

**Comment by clichedmoog** [comment]
though this is not the perfect way but it can be archived by add style like
```
<style>
.c3-circle._expanded_ {opacity: 1 !important;}
<style>
```
with point option show:false

**Comment by cpcarrot** [comment]
You should just be able to use:

point: {
  r: 0,
  focus : { expand: { r:5}}
},

**Comment by panthony** [comment]
If further help is required please use the Google Group at https://groups.google.com/forum/#!forum/c3js.
