### ISSUE TITLE
Poor perfomance 10K points

### ISSUE THREAD

**Issue by Perrazoo** [c3js/c3#2242]
I'm trying to draw several series (around 10) in a line chart.

Summaryzing the code is like:
```
var chart = c3.generate({
    bindto: '#chart',
    data: {
        x: 'ts',
        xFormat: null, // Needed to "understand" millis in ts series 
	columns: [],
	type: 'line'
    },
    axis: {
        x: {
            type: 'timeseries',
                tick: {
                    fit: false // Only appears ticks with label
                }
            },
        y: {
            label: {
                text: 'kg',
                position: 'outer-top'
            }
        }
    },
    zoom: {
        enabled: true
    },
    line: { // For enable null values in series (gaps in charts))
        connectNull: false 
    }
});
var tsData = ['ts'].concat(tsItems); // tsItems is a 1000 item array
for (key in series) { // series is a map with 10 arrays
    columnsData.push([key].concat(series[key]));
}
chart.load({
    columns: columnsData
});
```
Making zoom is a pain and trying to move right-left the chart is painful. Looks the code well? I'm trying to detect if i have any bug or is something missing in my code, some refactor, ...

Thanks in advance

**Comment by aendrew** [comment]
Use a different library, there's no way to make C3 (or SVG more generally) performantly display multiple thousands of elements.

**Comment by aendrew** [comment]
Also please search before opening issues, there are literally dozens like this one.

**Comment by Perrazoo** [comment]
Thanks for the quick reply **aendrew** and sorry for the duplicated issue...
