### ISSUE TITLE
src/axis.js:666, `select(this).selectAll('text')` should be `selectAll('text')`, right?

### ISSUE THREAD

**Issue by marchage** [c3js/c3#2247]
* **C3 version**: 0.4.18
* **D3 version**: 3.5.17
* **Browser**: chrome, edge
* **OS**: windows

https://jsfiddle.net/te5xz643/1/

Hello,

I think 

```javascript 
$$.d3.select(this).selectAll('text').each(function () {
``` 

in [src/axis.js, line 666](https://github.com/c3js/c3/blob/69f975cfcf54626a36566a8b8236f63aec001951/src/axis.js#L666) should be changed to

```javascript
$$.d3.selectAll('text').each(function () {
``` 

Otherwise it is __only__ measuring __the first__ x-axis' tick-value for size in the process of `getMaxTickWidth`-ing (for example, to setting left padding on a rotated accordingly). 

I found out while working on a project that uses a very large font-size on potentially very long category tick value labels.

Am I forgetting something?

**Comment by marchage** [comment]
Whoops, bad English. I meant:
Otherwise it is only measuring the first x-axis' tick-value for size in the process of getMaxTickWidth-ing (for example, to determine left-padding on a rotated bar chart).

**Comment by panthony** [comment]
Hi,

```js
$$.d3.select(this).selectAll('text').each(...)
```

Is the same as:

```js
const axisElement = $$.d3.select(this);
const axisTexts = axisElement.selectAll('text');
```

Which means, for a given axis, we find the tick with the biggest text.

What you suggest would select all the `<text>` from the whole chart (actually from the whole document..)` since this is not scoped by anything, which is not what we want.
