### ISSUE TITLE
Change color and font-size don´t work.

### ISSUE THREAD

**Issue by FelipeGerolomo** [c3js/c3#2248]
* **C3 version**:
* **D3 version**:
* **Browser**:
* **OS**:

I´m trying change de color and font size of bar chart but dosen´t work! 

`.c3-axis-y text {
    fill: red;
    font-size:12px;
 }
 .c3-axis-x text {
     font-size:12px;
     fill:purple;
 }`

`getChartCluster() {
    const chart = c3.generate({
      bindto: '#chartClusterAlunos',
      padding: {
        left: 100
      },
      data: {
        x: 'x',
        columns:
          [
            ['x', 'Fantasma', 'Esforçados', 'Kamikazes', 'Turista', 'Assíduos'],
            ['value', 1000, 1170, 660, 1030, 900]
          ],
        type: 'bar',
        labels: true
      },
      legend: {
        show: false
      },
      tooltip: {
        show: false
      },
      size: {
        height: 350,
        width: 350
      },
      axis: {
        rotated: true,
        x: {
          type: 'category'
        }
      }
    });
  }`

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
