### ISSUE TITLE
Large values are displayed inaccurately

### ISSUE THREAD

**Issue by voodoo940** [c3js/c3#2249]
Attempting to use large values of a Counter64 result in different values than expected. (Max Counter64 is 18446744073709551615)

![counter64](https://user-images.githubusercontent.com/7227166/34577443-c3a99cc0-f146-11e7-8703-d7d1c4694bc1.PNG)

* **C3 version**: v0.4.18
* **D3 version**: v4.12.2
* **Browser**: Chrome
* **OS**: Windows 10

**Comment by panthony** [comment]
I don't know if there is anything that can be done.

If you type `18446744073709551615` in the console it output `18446744073709552000`.

This value is above the `MAX_SAFE_INTEGER` constant.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

I don't know if something can be done nor if it's worth it.

**Comment by GDFaber** [comment]
Closing this issue due to mentioned integer max length limitation.
