### ISSUE TITLE
c3 rounds negative values on the x axis

### ISSUE THREAD

**Issue by ashleydavis** [c3js/c3#2251]
I've found that C3 rounds negative value on the x axis, it doesn't have this behavior for positive values.

It should function the same way for both negative and positive values displayed on the x axis.

C3 version: 0.4.18
D3 version: 3.5.14
Browser: Chrome  63.0.3239.84 
OS: Windows 10

Here is a screenshot that shows the problem:

![c3 issue - negative values on the x axis are rounded](https://user-images.githubusercontent.com/625126/34593578-6e838054-f217-11e7-80fd-510952e1e572.png)

Jsfiddle example that demonstrates the problem:

https://jsfiddle.net/ee0Lxv07/

**Comment by panthony** [comment]
Fixed by 81316cd

**Comment by ashleydavis** [comment]
Thanks. C3 is awesome. I've written a chapter on it in my upcoming book!

http://bit.ly/2t2cJu2
