### ISSUE TITLE
Use comma as decimals separator on Y axis

### ISSUE THREAD

**Issue by Davidczz** [c3js/c3#2252]
Hello,

* **C3 version**:  0.4.11
* **D3 version**:  3.5.x

I want to format the values of the Y axis that are numbers. I currently have this format : XX.X What I want is to use the comma as separator of decimals : XX,X

I tried two methods :

```
y : {
            tick : {
                values : steps, 
                format : d3.format(",.1f")
            },
            min : steps[0],
            max : steps[steps.length-1]
         }
```
And to use the d3 formatter :

```
 y : {
                tick : {
                    values : steps, 
                    format : function(d) {
                        var s = d3.formatSpecifier("f");
                        s.precision = precisionFixed(0.1);
                        s.comma = true;
                        var f =  d3.format(s);
                        return f(d);
                     }
                },
                min : steps[0],
                max : steps[steps.length-1]
             }
```

But I realized that the doc of D3 was talking about D3 4.0.

Do you have an idea how can I use the comma as decimal separator ? I don't have idea anymore...

Thank you

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
