### ISSUE TITLE
Can we create a multi line graph with continuous time intervals(Ex: 10:15-10:30-10:45-11:00) on x axis and plot data according to time and y axis integer value? 

### ISSUE THREAD

**Issue by Sudhanshu4122** [c3js/c3#2256]
Can we create a multi line graph with continuous time intervals(Ex: 10:15-10:30-10:45-11:00) on x axis and plot data according to time and y axis integer value?

**Comment by Sudhanshu4122** [comment]
Problem Statement:I have the data of multiple vendors in which each  vendor can have the Bid Price(Y axis parameter) at different timestamps. So i have to plot the multiline graph with continuous time intervals on x axis (Ex: 10:15-10:30-10:45-11:00) and plot the bid price data of each vendor according to time in timestamp. I have plotted the graph with timestamp of bid price on x axis but how can i have the dynamic continuous time intervals based on timestamp min value and max value which may also have the difference say 2 days. So i want to have the continuous time intervals on the x axis of graph for each day and plot data accordingly? Can it be achieved using c3.js?

**Comment by Sudhanshu4122** [comment]
Also is it possible to have data points in between(not particularly Center) x axis continuous time ticks using C3.js as there is no example of C3 in which we have data points plotted in between x axis ticks(not particularly Center)?

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
