### ISSUE TITLE
Is there any option to left align the bars?

### ISSUE THREAD

**Issue by keshav1007** [c3js/c3#2257]
Hi All,

Is there any option to plot the bars from the left side instead of center of the graph. Because in my case there can be scenario where the graph will have more space but there will be only one bar to show and i wanted to show the bar on left side of the graph.

How can i achieve this?

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
