### ISSUE TITLE
Clicking on pie segments to filter the values

### ISSUE THREAD

**Issue by emlun007** [c3js/c3#2262]
Hi

C3 version: 0.4.18
D3 version: 3.4.9
Browser: Chrome 63.0
OS: Windows 10

I am using c3 to display os families of servers as a donut diagram:

![os_family_for_github](https://user-images.githubusercontent.com/32731446/35140031-f6e83c3a-fcf5-11e7-9929-60ad5f105b3a.png)

I wonder if it is possible to click on the  segments to filter the values to the segment that is selected.

**Comment by alicanyildiz** [comment]
c3 has an onclick method for data points, if I understand correctly you need something **[like that](https://jsfiddle.net/xyzndsgn/1Lnsy6ur/)**? 
And [here is the documentation for data.onclick method](http://c3js.org/reference.html#data-onclick)

**Comment by emlun007** [comment]
I have the onlick method that selects the pie slices on the graph, but what I need is to be able to sort my table with data by clicking on a slice, e.g. you click on "windows" on pie chart and you get only nodes with window in the table. i have tried to write something like:

`  document.querySelectorAll("[class^='c3-shape c3-shape c3-arc c3-arc-']").onclick = function() {
  document.querySelectorAll("[class^='c3-shape c3-shape c3-arc c3-arc-']").attr("class").replace("c3-shape c3-shape c3-arc c3-arc-", "");

  var PieSliceName = PieSlice.getAttribute("class");

  function FilterPie() {
    // Declare variables 
    var filter, table, tr, td, i;

    filter = PieSliceName.value.toUpperCase();
    table = document.getElementById('facts_table');
    tr = table.getElementsByTagName("tr");

    // Loop through all table rows, and hide those who don't match the search query
    for (i = 1; i < tr.length; i++) {
    // text from all the tds
    var combinedText = "";
    // get all the tds (array of them notice there is no [selectz] at the end)
    var td = tr[i].getElementsByTagName("td");

    // loop over all of them and accumulate their text
    for(var j = 0; jc < td.length; j++)
        combinedText += td[j].innerHTML.toUpperCase();

    // if filter is in the accumulated text then show the row else hide it
    if (combinedTextc.indexOf(filterc) > -1) {
        tr[i].style.display = "";
    } else {
        tr[i].style.display = "none";
    }       

}
}}`

but I couldn't make it work

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
