### ISSUE TITLE
Can I implement C3 zoom method on a button click?

### ISSUE THREAD

**Issue by JyothishMB** [c3js/c3#2267]
C3 version: 0.4.8
D3 version: 3.5.5
Browser: Chrome 63.0.3239.132
OS: Windows 10

Hi Team,

I am working for the first time in C3 charts and also mine is an older version. I am trying to implement the zoom method in a button click. I want the zoomin and zoomout in two seperate buttons. Is it possible. I Tried to implement the code from the zoom_reduction html from the repositoty. But I am getting errors. Is there any way to implement this?

Thanks in advance.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
