### ISSUE TITLE
Include c3 version number in minimized JS file

### ISSUE THREAD

**Issue by MinchinWeb** [c3js/c3#2277]
* **C3 version**: 0.4.18
* **D3 version**: n/a
* **Browser**: n/a
* **OS**: n/a

Please include the version number at the start of the minified version of the JS file.

This will be incredibility helpful when I revisit my site to decide what JS needs to be upgraded, or if I have to debug library incompatibilities later, or really any one who is using the library but it's not the center of an ongoing project.

For example, d3.min.js reads:

```js
// https://d3js.org Version 4.13.0. Copyright 2018 Mike Bostock.
(function(t,n){"object"...
```

Thanks for creating a great library!

**Comment by kt3k** [comment]
Thanks for the suggestion! The bundle file will have the license banner at the top from the next release!
