### ISSUE TITLE
Some bars of Bar chart are not showing even they are available on dom.

### ISSUE THREAD

**Issue by MuhammadAkif** [c3js/c3#2286]
I give data to chart in required format. but chart doesn't show data where as the svg elements were on DOM. Can you please Help as i need this urgently. 

C3 version: 0.4.15
D3 version: 3.5.0.
Browser: Version 63.0.3239.132.
OS: Windows 10.

**Comment by MuhammadAkif** [comment]
@jkuchta Please help me i am stucked.

**Comment by SirCumz** [comment]
Got the same issue, i copied the exact example displayed on the website, but i dont see the lines and bars

**Comment by SirCumz** [comment]
I'm using VUE JS, when i paste the code into the mounted() function of the VUE instance it works.

**Comment by MuhammadAkif** [comment]
i m usin react but it doesn't work anywhere

**Comment by MuhammadAkif** [comment]
@DanielBaird @santazhang  @ku  Please help guys !! i m stucked

**Comment by DanielBaird** [comment]
@MuhammedAkif put your test into a CodePen or something

**Comment by panthony** [comment]
For questions involving the interplay between C3.js and any other library (react, vuejs, ..) please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

This is likely an issue where the element is created and c3js is called but the element is not yet attached to the DOM.

Thank you!
