### ISSUE TITLE
Click event for stacked Area chart

### ISSUE THREAD

**Issue by keshav1007** [c3js/c3#2288]
Hi,

I have a stacked area chart and i need each area should be clickable and based on the area clicked data1/data2/data3 respective route will be done.

If I set data.selection.grouped = true, I am able to click on the whole area but the click event is getting triggered for all data(data1, data2 and data3).

If I set data.selection.grouped = false, Click is available only on the data point, but I need the whole area should be clickable.

Please let me know how can i achieve this.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you !
