### ISSUE TITLE
Move the contents of c3js/c3js.org repository here

### ISSUE THREAD

**Issue by kt3k** [c3js/c3#2291]
- The separation of docs and source code makes the maintainance of the project hard.
- Let's move the contents of https://github.com/c3js/c3js.org here!

At the same time, I'd prefer dropping the use of middleman in building of the site. Maybe that's possible by the use of gulp or something similar.

**Comment by panthony** [comment]
@kt3k In my opinion this should be fixed before accepting any new "feature" PRs.

And we should ask the submitter for both tests and documentations of the new option.

In the mean time only PRs for fixes and enhancements (no change to the API) should be accepted.

**Comment by kt3k** [comment]
> And we should ask the submitter for both tests and documentations of the new option.

Agree.

OK. I'll work on this soon. (probably in a week.)
