### ISSUE TITLE
Tooltip legend randomly switching order of equal values

### ISSUE THREAD

**Issue by alantygel** [c3js/c3#2293]
Hi,

I have a stacked bar chart, and I chose the legend order to the descent. However, when there are 2 or more equal values, the legend order shown on mouseover tooltip keeps randomly changing the order of the values that are equal.

Here you can see an example: https://jsfiddle.net/cgwLqbL8/ . Just pass the mouse over the bar and look at the tooltip order.

Is there any way to avoid this?

**Comment by channot77** [comment]
Hi,
I have the same problem. It was working well with v0.4.17 but not anymore since v0.4.18.
Maybe a regression introduced with issue #1814 that was delivered on v0.4.18.
So the only solution for me was to revert to v0.4.17 and wait now for a fix in a next release.

**Comment by alantygel** [comment]
Thanks , @channot77 .

Unfortunately the problem persisted in v0.4.20. Downgrading to 17 is still the way to fix it.

**Comment by kt3k** [comment]
Fixed at #2311 and it is released as v0.5.1.

See https://jsfiddle.net/cgwLqbL8/1/

You need to update D3.js as well to use C3 v0.5.x.
