### ISSUE TITLE
Area Chart XGrid line z-index for opacity1

### ISSUE THREAD

**Issue by svemoory** [c3js/c3#2294]
Hi,

How can I bring the guiding lines (xgrid-line) in front of the area chart?. Please see the example below when you hover over the guiding line is behind the area. I played with z-index but did not help. All the examples online have no opacity.

https://jsfiddle.net/SVNS/ea2hs9kh/1/

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you !
