### ISSUE TITLE
Unable to customize x-axis tick labels for time series

### ISSUE THREAD

**Issue by smeads** [c3js/c3#2300]
* **C3 lastest version**:
* **D3 lastest version**:

@netil I've noticed you've assisted several people with c3 questions/issues. I'm currently working on a spline graph which uses `type: "timeseries"` for the x-axis. I'm running into several issues getting the timeseries to match up the way I'd like it to. Most likely this is due to my lack of experience with c3, but some clarification might help me understand if what I'm trying to do is possible with c3, and if not maybe it will shed some light on some updates that could be added to future versions of c3.

<img width="1098" alt="screen shot 2018-02-22 at 8 17 20 am" src="https://user-images.githubusercontent.com/18606144/36546535-e7b81d48-17a8-11e8-8b9e-e6ede506a857.png">

Here is a [link](https://jsfiddle.net/smeads/coL18are/6/) to a jsfiddle, but for whatever reason it's not displaying the graph, but the code is there for reference.

In the screen shot above you'll notice that the current x-axis timeseries has repeating year labels/ticks. I need the time series to not show the first year (2018) and only show subsequent years once (2019, 2020, etc.). If I don't use `fit: false` the grid lines don't match up with the tick marks. I've even tried messing with the culling attribute but I can't seem to get it to do what I need also.

Another issue I'm having is that I only want to display 2 ticks for the y-axis (min, max), which in my case is the original payment and then the $0 amt. But, I still would like to keep the intermittent gridlines.

This is what I'd like the spline graph to look like. If there is anyone that can suggest what I'm doing wrong, or point out any limitations to c3 that I'm not aware of it would be much appreciated.

<img width="853" alt="screen shot 2018-02-22 at 8 31 05 am" src="https://user-images.githubusercontent.com/18606144/36547341-e9186ae2-17aa-11e8-9010-9a57e6bddced.png">

Thank you!

**Comment by netil** [comment]
Hi @smeads, currently I'm focusing on the new project.
Check out the history at https://github.com/c3js/c3/issues/1965

**Comment by smeads** [comment]
@netil thanks for the reply, and I was able to resolve some of the issues I was having.

And, billboard.js is looks great! I'll have to give it a shot on my next project.
