### ISSUE TITLE
Failed to parse x 'time' to Date object

### ISSUE THREAD

**Issue by JethroNg** [c3js/c3#2304]
I am constantly facing a failed to parse time to date object issue. I want to generate a graph which on the left (Y-axis) shows a probability. Say the probability is 0, 0.2, 0.4 etc.. to 1. On the graph, I would like to plot the probability of something at a specific time. The below code is what I am using.

arr1 is the array containing the probabilities.
arr5 is the array containing the timestamp for each of the probability in arr1. The time format is in "12:03:55".

The issue now is if I were to hard code the timestamps into the chart columns, the chart would display perfectly fine. However I am getting the time from a user uploaded .csv file, hence I am concatenating an array which has the timestamps. And this gives me the error of Failed to parse x '12:03:55' to Date object.

I did console.log(dataTime), so I know my concat has been performed correctly in the intended format. This is what the console.log returns.

`["times", "12:03:55
", "12:03:56
", "12:03:56
", "12:03:56
", "12:03:57
", "12:03:57
", "12:03:58
", "12:03:58
", "12:03:59
", "12:03:59
", "12:04:00
"]`

This is what the console.log for dataMood returns.

`["Mood", 0.3677342, 0.34968433, 0.32662648, 0.3163717, 0.78009516, 0.97079295, 0.97183245, 0.9724318, 0.9689829, 0.7293974, 0.12735543]`

Below is the code I am using.

`var labelMood = 'Mood';
  var dataMood = [labelMood].concat(arr1);
  var times = 'times';
  var dataTime = [times].concat(arr5);`

`var chart = c3.generate({
bindto: '#line',
    data: {
        x: 'times',
			xFormat: '%H:%M:%S',
        columns: [
		dataTime, dataMood
        ]
    },
    axis: {
        x: {
            type: 'timeseries',
            tick: {
                format: '%H:%M:%S'
            }
        }
    }
});`

I really can't see why this isn't working since the format of the concatenated object is the same as how I would've hard coded the times into columns. I'm at my wits end after having Googled for hours. Hopefully someone has came across this issued before and has solved it successfully.

**Comment by knightbk** [comment]
Hey there. I figured out your problem here. You can't natively transform the format of '12:03:05' (hours, minutes, seconds) to a date. try new Date('12:03:05') in your javascript console and you'll see it doesn't work. It expects a year and month along with it basically.

http://jsfiddle.net/Lkazydtb/1/

Check out this JS fiddle I made. It's a little more complicated as you'll see I had to take your strings and coerce them into a date object. I then added the minified d3 library to use d3.time.format on that date object.

Hope this helps!

**Comment by knightbk** [comment]
@JethroNg see above, forgot to tag you there

**Comment by panthony** [comment]
Indeed the timeseries chart cannot work with only the time part.

You could either use the time as simple categories or use the workaround provided.
