### ISSUE TITLE
Labels hidden due to lack of space and axis height doesn't work

### ISSUE THREAD

**Issue by dragGH102** [c3js/c3#2309]
C3 version: 0.4121
D3 version: 4.13
Browser: Chrome (latest)
OS: MacOS High Sierra

Issue: when too many data in a **rotated bar chart**:
- intermediate X labels (it's rotated, so on Y axis) not shown
- height attribute (which as far my understand goes, serves the purpose to make the chart bigger) not working

Tested at: http://c3js.org/samples/api_axis_label.html (but I have the same issue in my Angular 5 application)

Sample code to reproduce (note that I've put `height`attribute on all possible axes, but even on individual ones doesn't work):

```
var chart = c3.generate({
    data: {
        columns: [
            ['data1', 30, 200, 100, 400, 150, 250, 1, 1, 1, 1, 1, 1, 1, 1],
            ['data2', 50, 20, 10, 40, 15, 25, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
        ],
        axes: {
            data1: 'y',
            data2: 'y2'
        },
        type: 'bar'
    },
    axis: {
        rotated: true,
        x: {
            height: 2000
        }
        y: {
            label: 'Y Axis Label',
            height: 2000
        },
        y2: {
            show: true,
            label: 'Y2 Axis Label',
            height: 2000
        }
    }
});
```

**Comment by panthony** [comment]
Hi,

Could you provide a JSFiddle or Plunkr highlighting the issue?

Thank you !

**Comment by dragGH102** [comment]
@panthony If you just paste the code at  the link I provided, you'll get the code working :)
Anyway, if that's not enough, I'll create a fiddle as soon as I can

**Comment by panthony** [comment]
@dragGH102 Please, consider that there are currently +700 opened issues and that the time you spend on this (**once**) is time saved for everyone taking a look at it !

**Comment by dragGH102** [comment]
@panthony sure.
there you are: https://jsfiddle.net/1t6k26d5/1/

I am using this in a prod app, so a "deadline" / temporary workaround would be awesome

**Comment by dragGH102** [comment]
@panthony I provided a fiddle. COuld you please let me know is and (approximatively) when this is going to be fixed?
thanks a lot in advance

**Comment by panthony** [comment]
@dragGH102 `height` does not exists for y/y2 axis and is not used for x when rotated.

From what I understand the tick labels are not hidden, they are simply not generated.

If not given this is done automatically and not for all ticks.

If you are not happy with was was automatically choosen you can use `axis.x.tick.values` for instance:

```js
        x: {
             tick: {
                values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
            }
        },
```

Not sure there is anything to fix and even if there was I'm unable to give any E.T.A on any issue.

**Comment by dragGH102** [comment]
@panthony that works. thanks. closing the issue.

**Comment by ravindra-clairvoyant** [comment]
@panthony, "_height does not exist for y/y2 axis and is not used for x when rotated_" this is really painful and preventing from achieving the desired experience. Could you please guide us on how do we achieve this?

1. How to ensure there is a space between Y-axis tick values and Y-axis label?
2. How to ensure there is a space between X-axis tick values and the X-axis label when it's rotated?
