### ISSUE TITLE
Is this possible to generate data on non-inputted data put

### ISSUE THREAD

**Issue by tedwong** [c3js/c3#2310]
* **C3 version**: 0.57.0
* **D3 version**: 3.5.0
* **Browser**: Chrome Version 65.0.3325.162 (Official Build) (64-bit)
* **OS**: macOS 10.13.3

Consider the following chart, but the user select on the red arrow pointed area....Is this possible to show that point value? Not only the data point can give the value.

<img width="1471" alt="screen shot 2018-03-21 at 3 11 51 pm" src="https://user-images.githubusercontent.com/188722/37697910-a01fbc20-2d1a-11e8-9706-1a9664497c20.png">

**Comment by MrPeng2017** [comment]
I do not know.sorry.

**Comment by EnricoVogt** [comment]
If its not a "data-point" it is not possible yet

**Comment by panthony** [comment]
No this is not possible, there are no "data point" here to select.
