### ISSUE TITLE
Putting column values from variable

### ISSUE THREAD

**Issue by krychaj5** [c3js/c3#2313]
* **C3 version**: 0.4.22
* **D3 version**: 3.5.17
* **Browser**: Chrome  64.0.3282.186
* **OS**: Windows 8.1

Hello, I'm trying to pass column data from my variable. (to generate dynamic chart)

I'm trying to do this way and dont works:
http://jsfiddle.net/p1w31uau/

I dont know how to put my values.

**Comment by panthony** [comment]
You can find lot's of exemples here:

http://c3js.org/examples.html

In your case you want something like:

http://c3js.org/samples/simple_multiple.html

**Comment by krychaj5** [comment]
@panthony check the fiddle, not working

**Comment by panthony** [comment]
I did check the fiddle and you are not following the expected format at all.

You are passing
```js
[ 'data1', '3,2.67,2.5,2.4,3,2.57' ]
```

Instead of
```js
[ 'data1', 3, 2.67, 2.5, 2.4, 3, 2.57 ]
```

`vals` should be an array of values, not a string, and you should do this:

```js
[ 'data1' ].concat(vals) // merge both array into a single one
```

instead of
```js
[ 'data1', vals ]
```

To have the expected format.

**Comment by krychaj5** [comment]
@panthony 
Thanks, fixed. But there is another issue - look at y axis, decimal values are represented too long and it looks ugly, any way to fix that?

**Comment by panthony** [comment]
Yeah... JS can go funky with floating numbers.

You want this:

http://c3js.org/reference.html#axis-y-tick-format

Exemple:

http://c3js.org/samples/axes_y_tick_format.html

You should really spend some times through the samples :)

**Comment by panthony** [comment]
If any further help is required please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

This issue queue is to be used for reporting defects and problems with C3.js.
