### ISSUE TITLE
bower.json hasn't updated D3 dependency version

### ISSUE THREAD

**Issue by lepolt** [c3js/c3#2327]
We still use bower for some things, and installing c3 is one of them.

* **C3 version**: 0.5.1
* **D3 version**: 3.5.17
* **Browser**: Chrome
* **OS**: macOS

**Comment by kt3k** [comment]
We released the fix in [v0.5.2](https://github.com/c3js/c3/releases/tag/v0.5.2). Thanks for reporting the issue!
