### ISSUE TITLE
Timeseries charts defaulting to 1969-12-31

### ISSUE THREAD

**Issue by GeorgieSantiago** [c3js/c3#2338]
c3: v0.4.21
d4: v4.13.0
Browser: Firefox
os: macOS Sierra Version 10.12.3
Framework: Laravel v5.6.15

having issues creating a timeseries chart. All dates are defaulting to 1969-12-31

Getting this in the console: 
SyntaxError: 09 is not a legal ECMA-262 octal constant
SyntaxError: 08 is not a legal ECMA-262 octal constant
...

Here is the jsfiddle with my script.
https://jsfiddle.net/fwt73mom/

**Comment by strizhechenko** [comment]
You probably pass unixtime (seconds) values while Date() constructor takes milliseconds.
Try to multiply values by 1000, maybe it'll help.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you !
