### ISSUE TITLE
Tooltip not reactive like the one in the demo

### ISSUE THREAD

**Issue by MaazAli** [c3js/c3#234]
I noticed in the c3js.org homepage the line graph's tooltip changes position from left to right depending on the position of your cursor on the line graph. I couldn't find anything that enables that in the API. In my own implementation the tooltip is slightly bigger and so it actually ends up hiding behind the end of the page. 

How can I make it so the tooltip can detect the end of the graph and switch positions to make sure it keeps on displaying?

**Comment by toninofox** [comment]
Hi there, 
Any update of the MaazAli issue? we encounter the same issue of left hidden tooltip

**Comment by wumuyao1996** [comment]
This issue seems to only occur when someone tries to programmatically give a chart size/using the resize function.

**Comment by wumuyao1996** [comment]
c2y = document.getElementById('chart2height').value;
                c2x = document.getElementById('chart2width').value;
                chart1.resize({height: 1000, width: 1000})
                chart2.resize({height: c2y, width: c2x})


chart1 would be fine but chart 2 would be to the side
