### ISSUE TITLE
Creating multiple graphs duplicates data

### ISSUE THREAD

**Issue by rkhairandish** [c3js/c3#2342]
C3 version: 
D3 version: v3
Browser: Mozzila Firefox
OS: MacOS High Sierra

Creating multiple graphs duplicates data:

As you can see the data in graph 2 is the data in graph1+graph2 

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/22399477/38460006-9add56b8-3aa9-11e8-9da5-22dacd961614.png">

My code is here (but as i have the CSV files saved locally you won't to see the data)
- https://codepen.io/anon/pen/zWMLZy

**Comment by panthony** [comment]
@rkhairandish There is bug in your code, the `yLabel` is not declared in your function. That means it will end up in the global `window` variables which means you reuse the same on for each createGraph call.
