### ISSUE TITLE
arc background not drawn correctly

### ISSUE THREAD

**Issue by EnricoVogt** [c3js/c3#2343]
C3 version: 0.5.3

At the current version it seems the background for an arc is not drawn.

Here an example with the current version:
https://codepen.io/anon/pen/LdvrJW

And here an example with the old "working" one:
C3 version: 0.4.21

https://codepen.io/anon/pen/QmPxzP

**Comment by caique0202** [comment]
Same here. Any update?

**Comment by kt3k** [comment]
Released the fix #2401 as [0.6.3](https://github.com/c3js/c3/releases/tag/v0.6.3). Thanks for reporting!
