### ISSUE TITLE
Charts with scroll and zoom without subchart?

### ISSUE THREAD

**Issue by binakot** [c3js/c3#2347]
Good day.

Can I get something like this: https://www.amcharts.com/demos/line-chart-with-scroll-and-zoom
How can I get zoom area selection on primary chart without subchart? 
I need scrolling, zooming and area selection on the same chart. Is it possible in current release?

Cheers ☕️

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!

**Comment by binakot** [comment]
There is the topic on google groups (for guys who will look similar functionality):
https://groups.google.com/forum/#!topic/c3js/dcwvP7FYlk4
