### ISSUE TITLE
Error in latest version of c3

### ISSUE THREAD

**Issue by kafom** [c3js/c3#235]
I just pulled the latest version of c3 but for some reason I cannot get it to work. 
I recieve an error saying
Uncaught TypeError: undefined is not a function
  c3.generate   c3.js:312
  (anonymous function)  c3trial.html:30

The code that I have is straight from your website of getting started. 

I did not alter anything in the c3.js or c3.css files. 
I just copied and pasted the code below. 
Please advise. 

This is my code 
See below. 
<!DOCTYPE html>
<html>
<head lang="en">
    <title></title>
    
    <link href="lib/c3.css" rel="stylesheet" type="text/css">

```
<!-- Load d3.js and c3.js -->
<script src="lib/d3.v3.min.js" charset="utf-8"></script>
<script src="lib/c3.js"></script>
```

</head>

<body>
      <div id="chart"></div>
      <script>
          var chart = c3.generate({
              bindto: '#chart',
              data: {
                  columns: [
                      ['y', 100, 200, 300, 400, 150, 250]
                  ]
              }
          });
      </script>
</body>
</html>

**Comment by surbhibh** [comment]
i am facing the same issue "c3 is not defined". Please help.
I already followed the c3 document and include.

<link href="/path/to/c3.css" rel="stylesheet">


<script src="/path/to/d3.v5.min.js" charset="utf-8"></script>
<script src="/path/to/c3.min.js"></script>
