### ISSUE TITLE
Uncaught DOMException when data label contains unicode

### ISSUE THREAD

**Issue by alanhamlett** [c3js/c3#2353]
When a stacked area chart's group label contains unicode (`my\u007fapp`) this error occurs:

```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': '.c3-selected-circles-my\u007fapp' is not a valid selector
```

* **C3 version**: 0.5.3
* **D3 version**: 4.13.0
* **Browser**: Chrome 66.0.3359.81
* **OS**: Mac OS X

**Comment by panthony** [comment]
The idea would be to use `CSS.escape` to be safe, but it is not available in all browsers.

There is a polyfill out there (https://github.com/mathiasbynens/CSS.escape).

@kt3k How would you feel about introducing a new dependency ? Or copying the ~70 lines into the project directly.

**Comment by kt3k** [comment]
@panthony CSS.escape sounds appropriate to me 👍 
> How would you feel about introducing a new dependency ? Or copying the ~70 lines into the project directly.

I think both approaches would be OK, but if we add it as dependency, I feel it should be in devDeps, not in deps (like D3), and should be bundled in `c3.js` file.
