### ISSUE TITLE
different colors for gauge chart column issue

### ISSUE THREAD

**Issue by sridhark158** [c3js/c3#2365]
is it possible to achieve multiple column with different colors in individual column in gauge chart of c3?
like mentioned below

* **C3 version**: 0.5.4
* **Browser**: chrome.
* **OS**: Windows 10.

![need it](https://user-images.githubusercontent.com/32831520/39907688-f11334d0-5507-11e8-869e-0975804b38f8.png)

**Comment by sridhark158** [comment]
it's worked with chart js

**Comment by rahul-winner** [comment]
any idea if such gauges be supported with C3JS ?

**Comment by sridhark158** [comment]
@rahul-winner  it can be implemented in C3js 
i found similar like this http://jsfiddle.net/rtmdeqpg/

**Comment by srinivasyl** [comment]
@rahul-winner can we provide two different max values for each data source like you've column 1 and column 2. I want to set 100 as max value for column 1 and 200 as max value for column 2 is that possbile in c3.js
