### ISSUE TITLE
Legend rendering problems in RTL mode

### ISSUE THREAD

**Issue by bprzemek80** [c3js/c3#2375]
* **C3 version**: 0.4.18
* **D3 version**: 3.5.40
* **Browser**: Chrome
* **OS**: Windows 10

Hi

I have a problem with properly rendering legend in RTL mode. Below  there is a picture that shows the problem. 

URL to picture: https://photos.app.goo.gl/XZDxJUoaynKdmM326

**Comment by skrzepij** [comment]
Any news about supporting RTL mode?

**Comment by 2tallah** [comment]
just add direction ltr in chart div like this.<div id="chart" style="direction: ltr"></div>

**Comment by 2tallah** [comment]
just add direction ltr in chart div.

`<div id="chart" style="direction: ltr"></div>`

**Comment by aert** [comment]
Kudos @2tallah , works fine
