### ISSUE TITLE
Category on Y axis or reverse graph?

### ISSUE THREAD

**Issue by prtome** [c3js/c3#2379]
Hello,
I am trying to move from Chartjs to C3js. I have no problems with lines and donuts charts.
In this case (chartjs graph)  https://codepen.io/prtome/pen/aGWqWJ   I have a time series on x axis and a category on y axis.
Following a previous question I understand that categories on Y axis are not supported.
I tried the following : https://codepen.io/prtome/pen/zjVJEX
I get my data from a database, so I use the ids for the Y columns, and provide the names:
var toto={};
toto[0]="start date";
toto[1]='AAA';
toto['1_unica']='AAA';
toto[4]='BBBB';
etc...  Then my column datasets are:
['1',null, 1, 1, 1, null, null],
 ['1_unica',null, null, null, null, 1, 1],
  ['4',null, 4, 4, 4, null, 4],
etc..

the ticks are defined as
tick: {
        values: [0,1,4,8, 18],
        count:1,
        format: function (d) { return toto[d]; }
      }

It all works, I get the correct labels etc, BUT the spacing between my different Y ticks correspond to the values. Is there a way I can have regular ticks independently of the values ?

if not, I though about 2 solutions, one being to modify the retrieved data so that values are linear , or reverse the graph while building it: Y axis linear, x axis category and then rotate it to have the X and Y as I want them. Is that possible ? I could not find anything in the docs about that.

One last question, is it possible to change the colours of the grid? I cannot find that either .

Thanks a lot .

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
