### ISSUE TITLE
Stacked bar chart does not properly display when series values deffer a lot

### ISSUE THREAD

**Issue by Mohayemin** [c3js/c3#2382]
* **C3 version**: 0.4.11-rc4
* **D3 version**: 3.5.17
* **Browser**: Chrome 67.0.3396.62
* **OS**: Windows 10

Steps to reproduce:
1. Use google chrome (does not reproduce in latest Firefox dev edition and IE 11)
1. Create a stacked bar chart with one value differing a lot of times than another.
2. The big value bar is visible but small is not because of scalling
3. Hide the big value
4. The chart scales to the small value, but the bar is not visible

Fiddle: http://jsfiddle.net/mohayemin/7kYJu/5421/

**Comment by panthony** [comment]
Hi @Mohayemin 

Thanks for reporting this issue.

It appears to be already fixed as I cannot reproduce with the latest version:

http://jsfiddle.net/7kYJu/5422/

Do you confirm?

**Comment by Mohayemin** [comment]
Hi @panthony ,
Thanks, yes I have noticed myself that it does not occur in recent versions. However, right now I do not want to update the version. Can you please link me to the commits where it was fixed so that I can patch the fix and update to latest later when convenient?

I am closing the ticket anyway. I understand that there is no point to keep it open when its already fixed.

**Comment by panthony** [comment]
@Mohayemin I don't know how/when it was fixed. I just tested your sample on the latest jsfiddle. 

Probably a timing issue of some sort...
