### ISSUE TITLE
custom legend color error

### ISSUE THREAD

**Issue by prtome** [c3js/c3#2383]
* **C3 version**:0.6.1
* **D3 version**:4.13  and 5.4.0
* **Browser**: chrome
* **OS**: mac high sierra

Here is a codepen with the issue : https://codepen.io/prtome/pen/ERPzME

I am trying to build my  custom legend. A you can see the colours of the legend do not correspond to the colours of the graph
![image](https://user-images.githubusercontent.com/11536421/40987302-82b64cb2-68e8-11e8-81f9-9179d87a8b27.png)

in the console I have the following error when using D3 4.13
![image](https://user-images.githubusercontent.com/11536421/40987374-a5cad57e-68e8-11e8-951b-91137eb10d76.png)

There is no error in console with D3 5.40 (the current codepen) but legend colours are still wrong

**Comment by panthony** [comment]
I opened your codepen and did not had this JS error in the console.

The colors does not correspond because you are passing `data1`, `data2`, `data3` instead of `scan 1`, `scan 2`, `scan 3` to `chart.color`.
