### ISSUE TITLE
Gauge is not showing completely in half circle, the background arc goes missing. The gray color towards the end goes missing.

### ISSUE THREAD

**Issue by rahul-winner** [c3js/c3#2390]
* **C3 version**:  0.6.1
* **D3 version**: 5.4.0
* **Browser**: Chrome 66.0.3359.117 (Official Build) (64-bit)
* **OS**: Windows

I noticed after updating to latest version of C3 and D3. The gray color from background area on Gauge is not appearing.

Please check this jsfiddle
http://jsfiddle.net/rahul_winner/r9Lfkamz/

**Before Update**
![image](https://user-images.githubusercontent.com/4982751/41413074-9df67786-6fff-11e8-81d6-917f548a3352.png)

**After Update**
![image](https://user-images.githubusercontent.com/4982751/41413191-f1ec2cdc-6fff-11e8-8bad-61b8cb10e018.png)

Could you please take a look at it and address it. It will be a great help.

**Comment by rahul-winner** [comment]
does someone have any clue about it?

**Comment by 1Jesper1** [comment]
I would also like to know this. Seems the path is empty under class _c3-chart-arcs-background_

**Comment by rahul-winner** [comment]
@1Jesper1 
Exactly, I noticed that. Do you have any solution for this? 

Kindly let me know if you are asking for some other information.

**Comment by 1Jesper1** [comment]
No, I noticed the gauge is showing completely is C3 version 0.4.11.

**Comment by rahul-winner** [comment]
It is working till the time D3 is of 3.x where C3JS has 0.4.x version. 

As we update C3JS to latest which is using D3 5.x, we get to see this issue. I looked into the code however am not able to fix it as I'm not much familiar with D3.

**Comment by rahul-winner** [comment]
created PR https://github.com/c3js/c3/pull/2401 for fixing this issue. Could anyone please merge it to master?

**Comment by kt3k** [comment]
Released the fix #2401 as [0.6.3](https://github.com/c3js/c3/releases/tag/v0.6.3). Thank you @rahul-winner !
