### ISSUE TITLE
Feature request: index parameter in tooltip.format.title

### ISSUE THREAD

**Issue by boompig** [c3js/c3#2392]
In the current version of C3 (v0.6.2), the [tooltip.format.title][1] function only presents the parameter of the x-coordinate. This is not helpful if you want the title to relate to some other property of the underlying data. Having the data-point index as an additional parameter would be useful here.

Note that other functions under tooltip.format provide much more data such as id and index.

[1]: http://c3js.org/reference.html#tooltip-format-title

**Comment by panthony** [comment]
Fixed by #2553
