### ISSUE TITLE
get json 

### ISSUE THREAD

**Issue by Axiaomo** [c3js/c3#2396]
this is my json
![image](https://user-images.githubusercontent.com/22358671/41395650-115a642c-6fe1-11e8-8f3b-af2392992f61.png)

I want to make it happen.
![image](https://user-images.githubusercontent.com/22358671/41395630-fbf2b918-6fe0-11e8-9555-dca25e908f82.png)

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
