### ISSUE TITLE
BUG: C3 chart doesn't sort data correctly

### ISSUE THREAD

**Issue by MarcAntoineHebert** [c3js/c3#2402]
Hi,
I'm using C3 to generate a Scatter Graph. 
This is what I give him: 
```
[{x: 91, y: 50},
 {x: 91, y: 50},
 {x: 91, y: 50},
 {x: 91, y: 75}]
```

But when C3 generate the graph, it change the order for: 
```
[{x: 91, value: 50, index: 0},
 {x: 91, value: 50, index: 1},
 {x: 91, value: 75, index: 2},
 {x: 91, value: 50, index: 3}]
```

And I don't understand why it's swapping the **50** and the **75** at the end... 

Is it possible to fix it ?

* **C3 version**: 0.4.21
* **D3 version**: 4.13.0
* **Browser**: Google Chrome
* **OS**: macOS 10.13.5 (High Sierra)

**Comment by diegovincent** [comment]
What do you mean do you give the library:

```javascript
[{x: 91, y: 50},
 {x: 91, y: 50},
 {x: 91, y: 50},
 {x: 91, y: 75}]
```

If the standard input for charts is: 

```javascript
columns: [
        ['data1', 30, 200, 100, 400, 150, 250],
        ['data2', 50, 20, 10, 40, 15, 25]
      ]
```

Where exactly do you input that data?
