### ISSUE TITLE
Pie chart Label

### ISSUE THREAD

**Issue by prasanthmaran1** [c3js/c3#2406]
Hello folks,

I am just new to c3.js . There is any possibility to implement the pie chart label in c3 like highchart => https://www.highcharts.com/maps-demo/pie-basic .

Thanks

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
