### ISSUE TITLE
A fix commit about scaling issue hasn't merged into v0.4 branch

### ISSUE THREAD

**Issue by leeshing0315** [c3js/c3#2420]
A fix commit [#1891](https://github.com/c3js/c3/pull/1891) hasn't merged into v0.4 branch, so the scaling issue is still exist in [v0.4.23](https://github.com/c3js/c3/releases/tag/v0.4.23).

* **C3 version**: 0.4.23

**Comment by kt3k** [comment]
Thanks for pointing it.

We backported #1891 to v0.4 branch and published as [v0.4.24](https://github.com/c3js/c3/releases/tag/v0.4.24). Please check it.

However we strongly recommend to upgrade to v0.6.x versions of c3. We can't guarantee every bug fix lands in v0.4 branch.
