### ISSUE TITLE
Show value instead of percentage in tooltips of Pie Charts

### ISSUE THREAD

**Issue by MaazAli** [c3js/c3#244]
I noticed that the pie chart's tooltips automatically ignore their respective value and instead display the percentage of the pie they have.

How can I make it so tooltips instead show the value.

**Comment by genoth** [comment]
I have a similar question as MaazAli. I'd like to display both, the percentage and the value. Could you please add some detail to your response above? How are value, ratio, and id defined, and what do they do? 

Using the example [here](http://c3js.org/samples/tooltip_format.html), I tried using just value or just ratio, hoping that value means the value and ratio means percentage, but it's throwing an error.  Also, I am getting undefined for the variable d. 
```` 
tooltip: {
        format: {
            title: function (d) { return 'Data ' + d; },
            value: function (value, ratio, id) {
                var format = id === 'data1' ? d3.format(',') : d3.format('$');
                return format(value);
            }
//            value: d3.format(',') // apply this format to both y and y2
        }
    }
````
http://c3js.org/samples/tooltip_format.html

**Comment by tomfonseca** [comment]
This worked for me.

`                  tooltip: {
                    format: {
                        value: function (value, ratio, id) {
                            return 'R$ ' + (value).formatMoney(2, ',', '.');
                        }
                    }
                }
`
