### ISSUE TITLE
change axis position

### ISSUE THREAD

**Issue by sipolyashhivangi** [c3js/c3#2444]
Hi,
How can I change the position of y axis from left to right in c3?
For example I want to change y axis position from left to right. How can I do it?

Any will be appreciated.

**Comment by nnnuker** [comment]
Hi @sipolyashhivangi, in this particular case you can hide `y` axis and show `y2`, but do not forget to change data binding from `y` to `y2`.
https://c3js.org/reference.html#axis-y2-show
https://c3js.org/reference.html#data-axes
