### ISSUE TITLE
`data.labels=false` hasn't any effect for donut type

### ISSUE THREAD

**Issue by artemanufrij** [c3js/c3#2457]
My Data Object:
```
data: {
  labels: false,
  type: "donut",
  columns: [["free", 100 - this.cpuUsage], ["usage", this.cpuUsage]],
  colors: {
    free: "#80808040",
    usage: this.usageColor
  }
}
```
## expected:
Labels (in my case xx%) should be hidden.

## current behaviour:
Labels are visible

* **C3 version**:0.6.7
* **D3 version**:
* **Browser**: Chrome
* **OS**: Archlinux

**Comment by whellner** [comment]
@artemanufrij I don't believe the turning on/off of labels on the donut itself are controlled by the data config area.  Have you tried this:

`{
  data: {....},
  donut: {
    label: {
      show: false
    }
  }
}
`

**Comment by artemanufrij** [comment]
@whellner ok... it works as expected.

but I also tested on gauge... and it doesn't

```
        data: {
          type: "gauge",
          columns: [["usage", 0]],
          colors: {
            usage: this.usageColor
          }
        },
        color: {
          pattern: ["#3daee9", "#fdbc4b", "#c0392b"],
          threshold: {
            values: [40, 70, 100]
          }
        },
        tooltip: {
          show: false
        },
        legend: {
          hide: true
        },
        gauge: {
          label: {
            show: false
          }
        }
```

**Comment by panthony** [comment]
The option is working as expected for Gauge, aka: hidden min/max labels.

It is not supposed to hide the value (in '%') of the gauge.

I don't believe this is such an option, feel free to open a feature request for this if necessary.
