### ISSUE TITLE
Data doesn't appear on an invisible tab

### ISSUE THREAD

**Issue by nnnuker** [c3js/c3#2458]
Steps to reproduce:
1.  Open any page with c3 chart on new tab (for example [c3js.org](https://c3js.org/samples/chart_combination.html))
2.  Do not navigate to it untill the page will not be fully loaded
3.  See the chart with empty data
![image](https://user-images.githubusercontent.com/4987843/44457654-7e162900-a60c-11e8-8f07-1de189332b32.png)
4.  Moreover, if you hover mouse over the chart you can see "Uncaught INDEX_SIZE_ERR" error

When the chart is bulding on not visible tab the data will not appear because there is such condition:
https://github.com/c3js/c3/blob/22afe8150bb5020ea92d5a0ede944507354de05f/src/core.js#L681-L727

The code from inner else should be executed even if tab isn't visible.

* **C3 version**: 0.6.7
* **D3 version**: 5.6.0
* **Browser**: Chrome, Firefox, IE 11, Edge - latest versions
* **OS**: win10 x64

**Comment by serglo** [comment]
My ticket #2468 was closed as well in favor of this one. Please guys, this bug is known since 2015.

**Comment by AlexFloppy** [comment]
I have fixed these weird case by adding manually trigger resize event after page load:
`setTimeout(function () {
        window.dispatchEvent(new Event('resize'));
    }, 100);`
