### ISSUE TITLE
Feature request: Add different point shapes

### ISSUE THREAD

**Issue by nnnuker** [c3js/c3#2463]
It would be great if you could configure point shapes. You could see on examples below how it might look like:
![image](https://user-images.githubusercontent.com/4987843/44515333-f3483380-a6ca-11e8-8a19-1498316d2420.png)
![image](https://user-images.githubusercontent.com/4987843/44515693-e415b580-a6cb-11e8-8e38-fd79fa5d7a87.png)

This feature would be useful with scatter plots or with many lines to differentiate them. Of course it will be useful when you make a black and white print.

**Comment by panthony** [comment]
Duplicate with #1071
