### ISSUE TITLE
Chart height determination by parent element not working

### ISSUE THREAD

**Issue by EmilijusS** [c3js/c3#2467]
When chart height is unspecified it defaults to 320px, instead of parent element height.
It seems the reason is because ChartInternal.prototype.getParentHeight returns the height of chart itself. ChartInternal.prototype.getParentWidth on the other hand functions as intended.

https://github.com/c3js/c3/blob/947cd4794916109e33010e98c1dc0665be10c4e8/src/size.js#L75

**Comment by mscraigloewen** [comment]
I put in a PR for this to fix this issue.

**Comment by kt3k** [comment]
The fix has been released as [v0.6.11](https://github.com/c3js/c3/releases/tag/v0.6.11).

**Comment by kt3k** [comment]
I think we can't change this behavior without breaking exsting apps. (See #2567 ) Please use a workaround like `chart.resize({ height: parentDom.clientHeight })` for now.

**Comment by OlivierKamers** [comment]
Hi all,
I was wondering if there are plans for another attempt at a fix to avoid the need for a workaround?
