### ISSUE TITLE
Lines are not drown when chart tab is not active

### ISSUE THREAD

**Issue by serglo** [c3js/c3#2468]
* **C3 version**: version used by https://c3js.org/examples.html
* **D3 version**: version used by https://c3js.org/examples.html
* **Browser**: Chrome 68
* **OS**: Mac OS

When you visit https://c3js.org/examples.html and try to open the example "Timeseries Chart" (https://c3js.org/samples/timeseries.html) in a new tab, with the focus still on the current tab and switch to the chart tab after it is completely loaded, you will see only cirlces/dots as the datapoints, but without the lines.

Some examples like https://c3js.org/samples/simple_multiple.html seem not to have the bug.

We encountered the same issue in our production environment. A fix would be very appreciated. We already tried using `setTimeout function` and `transition: {duration: 100}` parameter without success.

Thank you in advance!

Current outcome:
![screen shot 2018-08-30 at 17 36 16](https://user-images.githubusercontent.com/1453557/44862583-4a29ac00-ac7b-11e8-9acb-1a73d292f102.png)

Desired outcome:
![screen shot 2018-08-30 at 17 37 24](https://user-images.githubusercontent.com/1453557/44862617-5f063f80-ac7b-11e8-8a54-76c13fac70e0.png)

**Comment by kt3k** [comment]
Closing in favor of #2458.
