### ISSUE TITLE
Grid interface missing "lines { front: boolean; }"

### ISSUE THREAD

**Issue by ErikThorsson** [c3js/c3#2470]
"c3": "^0.6.7",
"@types/c3": "^0.6.1",
"d3-ng2-service": "^2.2.0"
"typescript": "~2.7.2"

`
 grid: {
                lines: {
                    front: false
                },
                y: {
                    lines:{.....}
                }
            }
`

produces

`
Types of property 'grid' are incompatible.
    Type '{ lines: { front: boolean; }; y: { lines: { value: number; }[]; }; }' is not assignable to type 'Grid'.
      Object literal may only specify known properties, and 'lines' does not exist in type 'Grid'.
`

I had to add 
`lines?: {
        front: boolean;
    }`

to index.d.ts in @types to fix this.

**Comment by panthony** [comment]
Wrong repository -> https://github.com/DefinitelyTyped/DefinitelyTyped
