### ISSUE TITLE
How do i add categories with a foreach loop?

### ISSUE THREAD

**Issue by Andekl** [c3js/c3#2482]
I want to create categories with a foreach loop based on column entries in the database but can't figure out the syntax for it. What i've tried is:

```
type: 'category',
                categories: [@foreach (var entry in Model.ListOfScores)
                {
                  "'"+@entry+"'"+,
                } ]
```
The query:

```
var scoresBetted = _context.Bet.Where(i => i.MatchId == id).Select(a => a.ScoreBetted).ToList();
ListOfScores = scoresBetted;
```
But that obviously doesnt work.

The result i'm looking for is that categories ends up looking like this when it's populated by the loop:

`categories: [1-1, 4-1, 2,1]`

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

**It is not a catch-all support forum.**

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
