### ISSUE TITLE
c3js change area color using pointer-events has broken the customer tooltip

### ISSUE THREAD

**Issue by datavisorfrankhe** [c3js/c3#2485]
I need to change c3js area color when mouse is over, this is what I was doing:

```
d3.selectAll(".c3-area")
            .style("pointer-events", "all")
            .on("mouseenter", function(e) {
                d3.select(this).style("opacity", 1);
            }, false)
            .on("mouseleave", function(e) {
                d3.select(this).style("opacity", 0.7);
            }, false);
```

Now for the area chart, when mouse is over the different area, only that particular area is highlighted, and when mouse is out, color is restored.

BUT, I just noticed, this has disabled the tooltip function. when mouse is over the area,there is no more tooltip, which only happened when mouse is out of the area.

I think this is caused by the pointer-events:all settings.But if I do not set this, then mouseover is not triggered, if I set it to all, then tooltip is broken.

How can I fix this?

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

**It is not a catch-all support forum.**

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
