### ISSUE TITLE
how can i automatically hide unused legend-items under donut?

### ISSUE THREAD

**Issue by polynaris** [c3js/c3#2487]
I would like to automatically hide unused legend-items under donut. 
i would like to see only those legend-items, whose values at this moment are more than 0 (>0%).

Also, Is it possible to increase the distance between those legend-items?

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

**It is not a catch-all support forum.**

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
