### ISSUE TITLE
Can we provide different max values for each data source in c3.js gauge graph

### ISSUE THREAD

**Issue by srinivasyl** [c3js/c3#2492]
c3.js library accepts two data sources(production and time) in gauge graphs but only with one max value, Is there format to provide different max values for two data sources I used below format to accept two data sources for gauge graph

```
var chart = c3.generate({
    data: {
        columns: [
            ['production', 30],
            ['time', 60],
        ],
        type: 'gauge',
        onclick: function (d, i) { console.log("onclick", d, i); },
        onmouseover: function (d, i) { console.log("onmouseover", d, i); },
        onmouseout: function (d, i) { console.log("onmouseout", d, i); }
    },
    gauge: {
        label: {
            format: function(value, ratio) {
                return value;
            },
            show: false // to turn off the min/max labels.
        },
    min: 0, // 0 is default, //can handle negative min e.g. vacuum / voltage / current flow / rate of change
    max: 100, // 100 is default
        //max : [{production:100},{time:200}],
    units: ' %',
    width: 39 // for adjusting arc thickness
    },
    color: {
        pattern: ['#FF0000', '#F97600', '#F6C600', '#60B044'], // the three color levels for the percentage values.
        threshold: {
//            unit: 'value', // percentage is default
//            max: 200, // 100 is default
            values: [30, 60, 90, 100]
        }
    },
    size: {
        height: 180
    }
});

```
but this is accepting same max values for both data sources is there any provision for accepting two max values for each data source?

refer this fiddle: [](https://jsfiddle.net/srinivasyl/nd25q7s6/8/)

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

**It is not a catch-all support forum.**

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
