### ISSUE TITLE
How to onclick/onmouseover to legend and then show tooltips ?

### ISSUE THREAD

**Issue by tr00869963** [c3js/c3#2497]
Hello,I would like to click or mouse over on target legend and make it show that tooltip like we mouse over on part of pie chart
Is it possible to do this? here is image
https://imgur.com/a/HUE62y4

**Comment by tr00869963** [comment]
A problem is I have data like this
[https://imgur.com/a/01Jbxts](url)
some data too small and difficult to target it by mouse over

PS.I disable clicking the legends to show/hide the data in the graph

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

**It is not a catch-all support forum.**

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
