### ISSUE TITLE
[Request] Include the SASS files in NPM package

### ISSUE THREAD

**Issue by madflow** [c3js/c3#2500]
Currently the sass files are missing from the published NPM package. Including the sass files would allow a cleaner customization of the styles on an application level.

I am happy to create a PR - however I would need a hint at what point of the build pipeline this should be happening.

**Comment by kt3k** [comment]
@madflow Thanks for the request. There was already the same request (#2483), and we've just published the release with scss files (v0.6.8). Please update c3 to v0.6.8, and the scss files should be found in `c3/src/scss/`.

**Comment by madflow** [comment]
@kt3k Wow - thanks. Great coincidence! :D
