### ISSUE TITLE
Rotated chart with hidden subchart still able to interact with

### ISSUE THREAD

**Issue by u119102** [c3js/c3#2503]
* **C3 version**: 0.6.8
* **D3 version**: 5.7.0
* **Browser**: Chrome
* **OS**: Windows

I have a rotated bar graph with long x-tick values. I appears there is a hidden subchart that user can still interact with and zoom in with, even though no subchart or zoom is enabled. See my codepen below:

https://codepen.io/u119102/pen/NOpBmK?editors=1010

If you hover mouse over the middle of the word "January", mouse pointer "+" will show up, pull it down and the graph will zoom in (similar to a subchart functionality)

This does seem trivial in web-page view, but in mobile view, it's in the left side of the page where user tends to scroll with their finger, it can be quite irritating, especially since you cannot zoom all the way back out, without seeing the subchart. 

![image](https://user-images.githubusercontent.com/39293927/46720144-66c5f480-ccbb-11e8-9a41-126709b46fc7.png)

Please let me know if any other information need or it has already been solved.

Thanks.

**Comment by dmitryrazinkov** [comment]
We have the same issue as well, seems really bad

**Comment by kemallette** [comment]
Also experiencing this on v0.6.8

**Comment by kemallette** [comment]
Temporary work around that I used to avoid this on a non-interactive chart was:
`
g.c3-brush {
  display: none;
}
`
