### ISSUE TITLE
Enable/Disable c3js legend elements on page load. Also handle enabling/disabling the legend elements using a flag value.

### ISSUE THREAD

**Issue by raghav5253** [c3js/c3#2506]
I am not able to disable c3 js chart legend elements on page load. (in chart's config). Also, I have a requirement to enable/disable chart legend elements on the basis of a checkbox value. Tried finding in c3 js docs but couldn't find.

`                                  $scope.cpuChartArea = {
                      data: {
                    x: 'x',
                   columns: [
                    xLabels,
                    data1,
                    data2,
                    data3
                ],
                xFormat: '%m-%d-%Y %H:%M:%S',
                types: {
                    'data 1': 'area-spline',
                    'data 2': 'area-spline',
                    'data 3': 'area-spline',

                }
            },
            point: {
                show: false
            },
            axis: {
                y: {
                    tick: {
                        format: function (d) { return d + "%"; }
                    }
                },
                x: {
                    type: 'timeseries',
                    tick: {
                        //format: function (x) { return x.getFullYear(); }
                        format: '%H:%M' // format string is also available for timeseries data
                    }
                }
            },
            tooltip:{
                format:{
                    title:function (x) { return x.getDate() + "/" + x.getMonth() + "/" + x.getFullYear() + " " + x.getHours()+ ":" + x.getMinutes() },
                }
            }
        }`

* **C3 version**:
* **D3 version**:
* **Browser**:
* **OS**:

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
