### ISSUE TITLE
C3 chart with 2 decimal places

### ISSUE THREAD

**Issue by thieuanh1995hn** [c3js/c3#2510]
Can i config my percentages in donut chart to 2 decimals number ?

**Comment by panthony** [comment]
Please, take a look at the documentation before opening an issue:

https://c3js.org/reference.html#donut-label-format

And the issue queue is to be used for reporting defects and problems with C3.js, this is not a support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

**Comment by thieuanh1995hn** [comment]
@panthony  So what is exactly solution . What should do with :  
 label: {
    format: function (value, ratio, id) {
      return d3.format('$')(value);
    }
  }
