### ISSUE TITLE
Logarithmic plot

### ISSUE THREAD

**Issue by YakovL** [c3js/c3#252]
Hello everyone,
I've searched a bit here and on the examples page, but haven't found anything about logarithm-scaled axes. Is it possible to create them? If not, consider this as a feature request.
Best regards,
Yakov.

**Comment by abrin** [comment]
the following would also format the values:

```javascript
data_test_original = ['data1', 10, 100, 1000, 3, 500, 50, 5, 3000]
data_test = ['data1'];
for(var i=1; i<data_test_original.length; i++){
    data_test[i] = Math.log(data_test_original[i]) / Math.LN10;
}

var chart_test = c3.generate({
    size: {
        height: 240,
        width: 480
    },
    data: {
        type:"bar",
      columns: [
        data_test
      ],
      labels : {show:true,
          format: {
              data1 : function(d,id){console.log(id, Math.pow(10,d));return Math.pow(10,d).toFixed(0);}
          }
      }
    },
    axis : {
        y : {
            show:false,
            tick: {
               format: function (d) { return Math.pow(10,d).toFixed(0); }
            }
        }
    },
});
```

**Comment by robertlevy** [comment]
that's a pretty ugly hack.  would it be possible to expose an API that allows any d3 scale to be plugged in?

**Comment by Leprosy** [comment]
+1 ...I need to draw a chart in log scale.

**Comment by NullVoxPopuli** [comment]
I would also like the ability to set my y axis(es) to by log

**Comment by ericsvendsen** [comment]
I too would like to be able to use a log scale for the y axis.

**Comment by ergo** [comment]
Any news on this?

**Comment by panthony** [comment]
Tried to tackle this issue (#2100). This is not 100% perfect but it may be sufficient for a lot of cases.

**Comment by bhavikboricha009** [comment]
I tried @pbustosl workaround... it was helpful.

but when the data value is 1, the y axis was starting from 1 . also when the data value was 0 chart was not rendering.

i have done some workaround for that.
please refer this JSFiddle https://jsfiddle.net/86chryat/

**Comment by JetForMe** [comment]
d3.js directly supports log scale on an axis, so it'd be really nice if that could be surfaced in c3. It's a much nicer solution than recomputing the data, because it also handles the ticks.

**Comment by AbeHandler** [comment]
I agree log scale would be useful

**Comment by adrianbj** [comment]
@masayuki0812 - by closing this, does it mean you won't consider support for it? It's really a critical feature for certain applications. It would be great to have proper integration if you have the time / inclination please.
