### ISSUE TITLE
Initial legend render has incorrect width and height firefox

### ISSUE THREAD

**Issue by maarten-wachters** [c3js/c3#2552]
* **C3 version**: 0.6.11
* **D3 version**:
* **Browser**: Firefox 63.0.3 (64-bits)
* **OS**: Windows 10 Enterprise64-bit (10.0, build 17763)

Expected behaviour:  [Chrome, Safari, Opera](https://imgur.com/a/FyZk4Ik)
Current behaviour: [Firefox](https://imgur.com/a/wLIHsyR)

The legend should render in the top-right position and automatically assign the width and height. The initial render in firefox is as shown in the above example. Upon resizing the window, it however renders correctly.

**Comment by panthony** [comment]
May be related to #2614 and thus fixed by #2672.

The issue is old, please reopen if it still occurs.
