### ISSUE TITLE
TypeError: (intermediate value)(intermediate value)(intermediate value) is not a function

### ISSUE THREAD

**Issue by theSuiGenerisAakash** [c3js/c3#2561]
I have a simple component which is supposed to render a line chart using c3.js

I have already asked a [question](https://stackoverflow.com/questions/54197233/c3js-typeerror-intermediate-valueintermediate-valueintermediate-value-i) at StackOverflow. 

Just pinning down the content here as well

```
class AnalysisChart extends React.Component {

  componentDidMount() {
    this.renderGraph();
  }

  renderGraph = () => {
    c3.generate({
      bindto: document.getElementById('analysis-chart'),
      data: {
        columns: [
          ['data1', 1, 2, 3],
        ],
      },
    });
  }

  render() {
    return (
      <div id="analysis-chart" />
    );
  }
}
```

My code is failing with the error:

> c3.js:1228 Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value) is not a function at ChartInternal.initParams (c3.js:1228) at ChartInternal.init (c3.js:1190) at new Chart (c3.js:56) at Object.generate (c3.js:1177)

Referencing the issue with the same problem but which had it for a different set of versions of c3 and d3 #2326 

Works on [codepen](https://codepen.io/anon/pen/VqgRRX?editors=1010) without React.

* **C3 version**: 0.6.12
* **D3 version**: 5.7.0
* **Browser**: Chrome 71
* **OS**: OSX 10.12.6

**Comment by ondrejspilka** [comment]
npm install d3-time-format --save
