### ISSUE TITLE
Data Labels are not showing for pie chart 

### ISSUE THREAD

**Issue by caiceA** [c3js/c3#2569]
Data labels are not showing any help? 
<img width="830" alt="screenshot 2019-02-08 at 19 11 54" src="https://user-images.githubusercontent.com/16766231/52497226-d7334280-2bd5-11e9-891a-b9c05ffd7fce.png">
<img width="635" alt="screenshot 2019-02-08 at 19 14 00" src="https://user-images.githubusercontent.com/16766231/52497227-d7334280-2bd5-11e9-8724-fddaab9c5661.png">
<img width="797" alt="screenshot 2019-02-08 at 19 14 28" src="https://user-images.githubusercontent.com/16766231/52497228-d7cbd900-2bd5-11e9-9044-23c8a1812fbb.png">
<img width="441" alt="screenshot 2019-02-08 at 19 14 36" src="https://user-images.githubusercontent.com/16766231/52497229-d7cbd900-2bd5-11e9-914a-470693543e5e.png">

**THIS IS WHAT I WANT**

<img width="741" alt="screenshot 2019-02-08 at 19 15 45" src="https://user-images.githubusercontent.com/16766231/52497287-f7630180-2bd5-11e9-8823-9337ce2f3da0.png">

**Comment by vlarkovich** [comment]
Hi, could you provide more details about reproducing your issue?
I've tried to reproduce it with your code and everything looks good for me. Did you tried to [set](https://c3js.org/reference.html#pie-label-show) `pie: { labels: { show: true }}` ?
This is the code that I've used: `var chart = c3.generate({
    data: {
        columns: [
            ['Voiceemail / VR', 20],
            ['Hold-time', 60],
            ['Ring transfer', 20],
            ['Unanswered', 10]
        ],
        type: 'pie',
        pie: {
            title: "usage "
        }
    },
    color: {
      pattern: ['#EE9265', '#604670', '#54C2E2', '#BD4B8A', ]  
    },
    pie: {
        label: {
            show: true
        }
    }
});`
Result:
![image](https://user-images.githubusercontent.com/43816231/52551131-379bcd00-2dec-11e9-8957-ff24dcfadcd7.png)

**Comment by caiceA** [comment]
@vlarkovich thanks for your help, I tried to copy/pasting your code but still it's not working


<img width="845" alt="screenshot 2019-02-11 at 10 19 41" src="https://user-images.githubusercontent.com/16766231/52554292-a5dd9100-2de6-11e9-8207-2f7d23cf5c12.png">
<img width="831" alt="screenshot 2019-02-11 at 10 19 59" src="https://user-images.githubusercontent.com/16766231/52554294-a83feb00-2de6-11e9-8071-f96204629f85.png">


Video
------
https://youtu.be/4XdpmHMb27c

**Comment by caiceA** [comment]
i figured out it was disabled in the css i have fixed it thanks @vlarkovich

**Comment by caiceA** [comment]
close #2569
