### ISSUE TITLE
Timeline back button crash

### ISSUE THREAD

**Issue by pigmalien** [c3js/c3#2574]
Looks like you can't go back without naming a timeline.

C3 version: beta

Browser: Chrome.
OS: 10.

Error report information
Type: assertion failure
Message: invalid timeline
Stack: Error at Function.ǃi.ǃDaQ (https://editor.construct.net/r138/main.js:2:147114) at e (https://editor.construct.net/r138/main.js:2:108297) at window.assert (https://editor.construct.net/r138/main.js:2:108622) at window.ǃSpE.ǃDSQ (https://editor.construct.net/r138/main.js:177:123731) at i.ǃDSQ (https://editor.construct.net/r138/main.js:177:136996) at ǃi.ǃr.ǃO.ǃShc.ǃiuD (https://editor.construct.net/r138/main.js:177:126856) at HTMLButtonElement.ǃiXP.onclick (https://editor.construct.net/r138/main.js:177:124468)
Construct 3 version: r138
URL: https://editor.construct.net/r138/
Date: Mon Feb 18 2019 09:46:12 GMT-0500 (Eastern Standard Time)
Uptime: 176.9 s

Platform information
Browser: Chrome
Browser version: 72.0.3626.109
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
C3 release: r138 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7480D Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

[New project.zip](https://github.com/c3js/c3/files/2876129/New.project.zip)

**Comment by panthony** [comment]
Invalid issue
