### ISSUE TITLE
y-axis as time works on desktop but shows NaN on mobile

### ISSUE THREAD

**Issue by tmlmt** [c3js/c3#2575]
* **C3 version**: 0.6.12
* **D3 version**: 5.9.1

Working on:
* **Browser**: Firefox 
* **OS**: Ubuntu 18.04.2 LTS

Issue on:
* **Browser**: Brave and Safari
* **OS**: iOS 12.1.4

Hi guys. I am using a trick explained in several places in order to display a time on both axis:

``` 
y: {
   tick: {
      format: function(y) {
         return d3.timeFormat("%H:%M")(new Date(new Date('2000-01-01 00:00:00').getTime() + (y * 60000)));
         },
      count: 13
     },
    min: 0,
    max: 1440,
    padding: 0,
    label: "HH:SS"
}
```

This shows well on desktop, but I get only NaN on mobile. 

Fiddle: https://jsfiddle.net/z8gxqjuo/4/

**Comment by kt3k** [comment]
safari's Date constructor doesn't parse `2000-01-01 00:00:00` and returns Invalid Date object. (though it does parse `2000-01-01T00:00:00`)

I think you should use some library like moment or date-fns for parsing the date strings.

**Comment by tmlmt** [comment]
Many thanks for putting me on the right track @kt3k! :)
I solved my problem by using `new Date(2000,1,1,0,0,0)` instead of `new Date(‘2000-01-01 00:00:00’)`. I didn’t need a fancy parser for my simple case. The issue was not an issue. Closing
