### ISSUE TITLE
Loop Chart

### ISSUE THREAD

**Issue by scott-oliver** [c3js/c3#2581]
Is it possible to loop the charts displayed alongside a set timeout?

I've had a little joy playing with the following, but it causes the graph to reload somewhat sporadically.

```
var chart = c3.generate({
    data: {
        columns: [
            ['data1', 30, 200, 100, 400, 150, 250],
            ['data2', 50, 20, 10, 40, 15, 25]
        ]
    }
});

var test;
function testF1(){ test = setInterval( testF2, 20010 ); }
function testF2(){

setTimeout(function () {
    chart.load({
        columns: [
            ['data1', 230, 190, 300, 500, 300, 400]
        ]
    });
}, 10000);

setTimeout(function () {
    chart.load({
        columns: [
            ['data3', 130, 150, 200, 300, 200, 100]
        ]
    });
}, 10000);

setTimeout(function () {
    chart.unload({
        ids: 'data1'
    });
}, 10);

}

testF1()
```

For example, not all charts are coming through and/or displaying for what I would expect the correct amount of time is.

The goal here is to have the first chart load, after 10 seconds to change the data (or chart), repeat until all charts have been displayed and then loop back onto itself.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

Nonetheless, you called `setTimeout` at the same time with the same timeout value (`10000`) which probably explains the "sporadically" part.
