### ISSUE TITLE
.selected(targetId) not working

### ISSUE THREAD

**Issue by trajnisz** [c3js/c3#2583]
* **C3 version**: 0.6.12
* **D3 version**: 5.9.1
* **Browser**: Chrome  72.0.3626.119

fiddle: https://jsfiddle.net/oqc7tmbs/

I`m using selection. Using callback 'onselected' i want to access all selected data and to something with it. I found selected() method (https://c3js.org/reference.html#api-selected) and i wanted to use it but it always throws an error: "$$.main.selectAll(...).selectAll(...).filter(...).map is not a function".

**Comment by LiaanM** [comment]
Related to #2477

**Comment by panthony** [comment]
Closing as duplicate
