### ISSUE TITLE
Mac Chrome pwa desktop creates multiple previews

### ISSUE THREAD

**Issue by pigmalien** [c3js/c3#2585]
* **C3 version**: r136 Stable
* **D3 version**:
* **Browser**: Chrome 73
* **OS**: macOS Mojave

Running preview to the Chrome browser creates a second tab of the preview that never gets loaded.
This happens on the second launch of the browser preview.
Subsequent launches do the same.

**Comment by kt3k** [comment]
I'm afraid you're talking about Construct 3. https://www.construct.net/en/make-games/releases/stable/r136

C3.js is a different library.

**Comment by pigmalien** [comment]
All apologies
