### ISSUE TITLE
API's .load not refreshing data.regions (feature request with solution)

### ISSUE THREAD

**Issue by bennettdams** [c3js/c3#2591]
* **C3 version**: 0.6.14
* **D3 version**: 5.0
* **Browser**: all
* **OS**: all

The API's `.load` function doesn't refresh `data.regions`  (not to be confused with `chart.regions`)

There is an old issue #1234, which proposes to change the CSS manually, which is no viable solution.

Minimal example:  http://jsfiddle.net/m9z2vy0L

The code refactoring to make this possible should be pretty easy:
Adding `regions` to
https://github.com/c3js/c3/blob/master/src/api.data.js
and
https://github.com/c3js/c3/blob/master/src/api.load.js
made reloading work!

```
// api.data.js
Chart.prototype.data.regions= function (regions) {
    return this.internal.updateDataAttributes('regions', regions);
};
```

```
// api.load.js
// update regions if exists
if ('regions' in args) {
    Chart.prototype.data.regions.bind(this)(args.regions);
}
```

May I provide a pull request?

**Comment by berkkurkcuoglu** [comment]
You can use [API regions](https://c3js.org/reference.html#api-regions) instead.

**Comment by bennettdams** [comment]
@berkkurkcuoglu I'm pretty sure I can't, as `chart.regions` (what "API regions is a synonym for) is not the same as `data.regions`.

Chart regions determine a region for the whole chart, but I need to set regions for specific data sets (where some are e. g. shown as a dotted line), which is not possible with chart regions.
