### ISSUE TITLE
On click event of a bar chart/line chart

### ISSUE THREAD

**Issue by aishwaryak** [c3js/c3#262]
The "onclick" (or mouseover/mouseout) events are detected and work perfectly fine for a donut chart as seen in this example : 
http://c3js.org/samples/chart_donut.html
I tried incorporating the same for a bar chart or a line chart. It doesn't work. Are these events only for donut charts or is there any other possible way I can do it for these charts(Bar, Line and others)?

**Comment by mikias10** [comment]
What about clicking on the line instead of the dot?
