### ISSUE TITLE
data_number_format_l10n

### ISSUE THREAD

**Issue by AleshO** [c3js/c3#2620]
https://c3js.org/samples/data_number_format_l10n.html

something wrong...

**Comment by kt3k** [comment]
Thanks for reporting.

It seems that we need to update `d3.locale` usage.

```
Uncaught TypeError: d3.locale is not a function
```

**Comment by kt3k** [comment]
cc @masayuki0812

**Comment by AleshO** [comment]
How it looks?

**Comment by kt3k** [comment]
@AleshO We updated the documentation. https://c3js.org/samples/data_number_format_l10n.html
