### ISSUE TITLE
Tooltip bug on zoom-drag

### ISSUE THREAD

**Issue by ppKrauss** [c3js/c3#2637]
**Losing tooltip** bug.   <br/>The option `zoom:{enabled:true,type:'drag'}` is in conflict with `tooltip:{show:true}`.

Simple test: at the zoom-drag illustrated by [this sample](https://c3js.org/samples/interaction_zoom_by_drag.html), you can add `tooltip` option in it.

------

* **C3 version**: 0.7.1
* **D3 version**: 5.9.7
* **Browser**: Firefox v64.0
* **OS**: Windows v10

**Comment by panda-blue** [comment]
cf: https://github.com/c3js/c3/issues/2501

**Comment by ppKrauss** [comment]
Hi @panda-blue, thanks.  Yes seems the same problem... Close here?

**Comment by panthony** [comment]
Duplicate of #2501
