### ISSUE TITLE
Timeseries off by 1 day

### ISSUE THREAD

**Issue by peps** [c3js/c3#268]
I first ran into this issue on my own project, then noticed that its also happening on the Timeseries Chart example.

http://c3js.org/samples/timeseries.html

The chart should start on 2013-01-01 and end 2013-01-06 ... but the chart shows it shifted 1 day into the past. So it starts on 2012-12-31 and ends on 2013-01-05.

This causes the data points to be shown on the wrong dates.

**Comment by arundanegoudar** [comment]
Response From The Server:
{"x":[["2015-07-01"],["2015-07-02"],["2015-07-03"],["2015-07-06"],["2015-07-07"],["2015-07-08"],["2015-07-09"
],["2015-07-10"],["2015-07-11"],["2015-07-13"],["2015-07-14"],["2015-07-15"],["2015-07-16"],["2015-07-17"
],["2015-07-18"],["2015-07-20"],["2015-07-21"],["2015-07-22"],["2015-07-23"],["2015-07-24"],["2015-07-25"
],["2015-07-27"],["2015-07-28"],["2015-07-29"],["2015-07-30"],["2015-07-31"]],"data1":[["20.64"],["20
.35"],["34.1"],["8.19"],["22.19"],["12.77"],["12.81"],["27.22"],["19.87"],["16.03"],["11.24"],["20.39"
],["27.45"],["23.36"],["9.19"],["14.01"],["15.74"],["26.36"],["13.88"],["15.87"],["11.14"],["12.42"]
,["9.19"],["9.83"],["13.59"],["0"]]}

Error: Failed to parse x '2015-07-01' to Date object
