### ISSUE TITLE
Tooltip misalignment when zooming

### ISSUE THREAD

**Issue by michaelsweeney** [c3js/c3#2706]
* **C3 version**:  0.7.9
* **D3 version**: v5
* **Browser**: Chrome
* **OS**: Windows

The hover tooltip works fine when the chart is entirely zoomed out but upon zoom, it doesn't properly represent mouse position. It seems like the hover event is responding to the mouse position of the chart were it *not* zoomed in.

Example:
https://c3js.org/samples/interaction_zoom.html

**Comment by digEmAll** [comment]
The problem seems to happen also without the zoom, e.g. https://codepen.io/digemall/pen/wvwLWzb

If you move the mouse to the right from the first point on the left you can see that the auto-snap functionality seems broken.

**Comment by kt3k** [comment]
@michaelrodov @digEmAll 
We merged a fix (#2701) about handling of tooltips. Can you check if the issue still exists with the latest version (0.7.11)?

**Comment by digEmAll** [comment]
@kt3k: yes, I tested my code modifying one of the c3js.org examples (that apparently are already using 0.7.11) and it seems ok

**Comment by kt3k** [comment]
@digEmAll Thanks for confirming 👍
