### ISSUE TITLE
Dynamic JSON data

### ISSUE THREAD

**Issue by Firzen2nd** [c3js/c3#2707]
Hi, 

I have json like this:
`[
  {
    "CustomerGroupValue": {
      "Customer1": 1500,
      "Customer2": 1200,
      "Customer3": 900,
      "Customer4": 250,
      "Customer5": 150,
      "Customer6": 200,
      "Customer7": 100
    },
    "DateRange": "10. 2019",
    "TotalCapacityWithEfficiency": 6044.0,
    "TotalCapacityWithEfficiencyMax": 7990.0
  },
  {
    "CustomerGroupValue": {
      "Customer1": 1450,
      "Customer2": 1300,
      "Customer3": 950,
      "Customer4": 250,
      "Customer5": 150,
      "Customer6": 200,
      "Customer8": 100
    },
    "DateRange": "11. 2019",
    "Efficiency": 6222.0,
    "EfficiencyMax": 7990.0
  },
...
]`

The Customers can be different in each month (DateRange)
I want to draw chart like:
Customer as Stacked Bar
DateRange on X axis
Efficiency and EfficiencyMax as line.

Is there any way to do that? :)

**Comment by kt3k** [comment]
Sorry, this issue tracker is for bugs or feature requests for c3, and is not for general questions. Please use other platforms for this sort of questions such as [stackoverflow](https://stackoverflow.com), etc.
