### ISSUE TITLE
Add support for custom JSON data format

### ISSUE THREAD

**Issue by zoom2ashish** [c3js/c3#283]
I have JSON data containing some field which should not be refended. for example:

json: [
 { id: 1, name: 'abc', visits: 200 },
 { id: 2, name: 'efg', visits: 400 },
 { id: 3, name: 'pqr', visits: 150 },
 { id: 4, name: 'xyz', visits: 420 },
]

It will be great if I can pass JSON blob like this to C3 chart, and tell which field to render on x and y axis. For example: 'name' on x axis and 'visits' on y axis. On click, I should be able to get that object - { id: 1, name: 'abc', visits: 200 } -  into event handler for further action based on 'id'. 

Please let me know if c3 chart already has this functionality. If it has then how to do this.

Thanks,
Ashish

**Comment by nicktgr15** [comment]
Hi,

I'm trying to make use of the described functionality but it doesn't seem to be available anymore. Using the following dependencies:
```
<script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.js"></script>
```

This is the code that generates the chart (copied from the samples):
```
chart = c3.generate({
            data: {
                onclick: function (d, element) {
                    console.log(d);
                    console.log(element);
                },
                json: [
                    { id: 1, name: 'abc', visits: 200 },
                    { id: 2, name: 'efg', visits: 400 },
                    { id: 3, name: 'pqr', visits: 150 },
                    { id: 4, name: 'xyz', visits: 420 },
                ],
                keys: {
                    x: 'name',
                    value: ['visits'],
                }
            },
            axis: {
                x: {
                    type: 'categorized'
                }
            }
        });
```

When I click on one of the points I get back the following:

```
{x: 0, value: 200, id: "visits", index: 0, name: "visits"}
```
The "id" field doesn't have the expected value.

I also tried with the following data:

```
                 [
                    { id: 1, random: 'asdasd', name: 'abc', visits: 200 },
                    { id: 2, random: 'asdasd', name: 'efg', visits: 400 },
                    { id: 3, random: 'asdasd', name: 'pqr', visits: 150 },
                    { id: 4, random: 'asdasd', name: 'xyz', visits: 420 },
                ]
```

and the output on click was still:

```
{x: 0, value: 200, id: "visits", index: 0, name: "visits"}
```

Thank you,
Nik

**Comment by aendrew** [comment]
@nicktgr15 That looks fine to me, not sure what the issue is. Mind creating a Plunker demonstrating the issue and opening a new one if it still persists? Thanks!
