### ISSUE TITLE
Pie chart "responsiveness/responsiveless"

### ISSUE THREAD

**Issue by simo2409** [c3js/c3#297]
A thing that I really like of this library is that charts (for example area chart) fills up the container in which I place them and, when I resize window (having responsive html code), the chart changes dimensions based on container's dimensions.

The same does not happen for pie chart. Is this a bug or is it not possible to achieve the same result with pie charts?

Thank you for your work

**Comment by devipriya28** [comment]
Can you please show how you made pie chart responsive.
