### ISSUE TITLE
Tooltip questions

### ISSUE THREAD

**Issue by lblb** [c3js/c3#307]
1. Is there a way to disable vertical grey  guide line which appears with tooltip? It is usefull for line charts, however for bar charts it makes no sense.
2. Is it possible to ungroup tooltips, especially when multiple series exists? For instance I'd like to display a single tooltip when I hover a particular bar, or a node in a line chart. Similar as it does in a pie chart.

**Comment by bla211** [comment]
I tried using:

**Comment by bla211** [comment]
Hello,
I tried using:
tooltip: {grouped: false},
but now the tooltip does not appear at all on my bar charts, only line.

**Comment by Rarely** [comment]
I have the same issue has @bla211. It works fine for line charts, but bar charts, turning grouped: false leads to no tooltip at all.

**Comment by jpwilksch** [comment]
@bla211 and @Rarely, I also don't see a tooltip at all when using grouped:false with stacked bar charts, but only in Chrome. I think it is related to "SvgPathSeg is removed in chrome 48 #1465" (https://github.com/masayuki0812/c3/issues/1465).
