### ISSUE TITLE
Exporting this amazing chart 

### ISSUE THREAD

**Issue by muhdkhokhar** [c3js/c3#313]

**Comment by raj-mehta** [comment]
Hi , I am trying to convert c3 chart i.e SVG into Image but its not working.

**Comment by aendrew** [comment]
@raj-mehta Please ask on the [C3 Google Group](https://groups.google.com/forum/#!forum/c3js), this is a closed issue and the lack of detail you've provided with your query makes it practically impossible to help you.

**Comment by raj-mehta** [comment]
Thanks for your revert , 
 I using  the following svg and used on ur sample.html but chart on the browser and converted image from canvg don't match .

Sample SVG

<div id="c3-bar-chart" class="c3" style="max-height: 250px; position: relative;"><svg width="680" height="250" style="overflow: hidden;">
		<defs><clipPath id="c3-1437046737123-clip"><rect width="578" height="196"></rect></clipPath><clipPath id="c3-1437046737123-clip-xaxis"><rect x="-101" y="-20" width="710" height="70"></rect></clipPath><clipPath id="c3-1437046737123-clip-yaxis"><rect x="-99" y="-4" width="120" height="220"></rect></clipPath><clipPath id="c3-1437046737123-clip-grid"><rect width="578" height="196"></rect></clipPath><clipPath id="c3-1437046737123-clip-subchart"><rect width="578"></rect></clipPath></defs><g transform="translate(100.5,4.5)"><text class="c3-text c3-empty" text-anchor="middle" dominant-baseline="middle" x="289" y="98" style="opacity: 0;"></text><rect class="c3-zoom-rect" width="578" height="196" style="opacity: 0;"></rect><g clip-path="url(http://localhost:8080/InterActivityPOC/tranList_page.html#c3-1437046737123-clip)" class="c3-regions" style="visibility: visible;"></g><g clip-path="url(http://localhost:8080/InterActivityPOC/tranList_page.html#c3-1437046737123-clip-grid)" class="c3-grid" style="visibility: visible;"><g class="c3-xgrid-focus"><line class="c3-xgrid-focus" x1="289" x2="289" y1="0" y2="196" style="visibility: hidden;"></line></g></g><g clip-path="url(http://localhost:8080/InterActivityPOC/tranList_page.html#c3-1437046737123-clip)" class="c3-chart"><g class="c3-event-rects c3-event-rects-single" style="fill-opacity: 0;"><rect class=" c3-event-rect c3-event-rect-0" x="0" y="0" width="578" height="196"></rect></g><g class="c3-chart-bars"><g class="c3-chart-bar c3-target c3-target-Apr-2015" style="opacity: 1; pointer-events: none;"><g class=" c3-shapes c3-shapes-Apr-2015 c3-bars c3-bars-Apr-2015" style="cursor: pointer;"><path class=" c3-shape c3-shape-0 c3-bar c3-bar-0" d="M 115.6,196 L115.6,104.13119061437556 L231.2,104.13119061437556 L231.2,196 z" style="stroke: rgb(31, 119, 180); fill: rgb(31, 119, 180); opacity: 1;"></path></g></g><g class="c3-chart-bar c3-target c3-target-May-2015" style="opacity: 1; pointer-events: none;"><g class=" c3-shapes c3-shapes-May-2015 c3-bars c3-bars-May-2015" style="cursor: pointer;"><path class=" c3-shape c3-shape-0 c3-bar c3-bar-0" d="M 231.2,196 L231.2,18.727272727272734 L346.8,18.727272727272734 L346.8,196 z" style="stroke: rgb(255, 127, 14); fill: rgb(255, 127, 14); opacity: 1;"></path></g></g><g class="c3-chart-bar c3-target c3-target-Jun-2015" style="opacity: 1; pointer-events: none;"><g class=" c3-shapes c3-shapes-Jun-2015 c3-bars c3-bars-Jun-2015" style="cursor: pointer;"><path class=" c3-shape c3-shape-0 c3-bar c3-bar-0" d="M 346.8,196 L346.8,100.1722111433026 L462.40000000000003,100.1722111433026 L462.40000000000003,196 z" style="stroke: rgb(44, 160, 44); fill: rgb(44, 160, 44); opacity: 1;"></path></g></g></g><g class="c3-chart-lines"><g class="c3-chart-line c3-target c3-target-Apr-2015" style="opacity: 1; pointer-events: none;"><g class=" c3-shapes c3-shapes-Apr-2015 c3-lines c3-lines-Apr-2015"></g><g class=" c3-shapes c3-shapes-Apr-2015 c3-areas c3-areas-Apr-2015"></g><g class=" c3-selected-circles c3-selected-circles-Apr-2015"></g><g class=" c3-shapes c3-shapes-Apr-2015 c3-circles c3-circles-Apr-2015" style="cursor: pointer;"></g></g><g class="c3-chart-line c3-target c3-target-May-2015" style="opacity: 1; pointer-events: none;"><g class=" c3-shapes c3-shapes-May-2015 c3-lines c3-lines-May-2015"></g><g class=" c3-shapes c3-shapes-May-2015 c3-areas c3-areas-May-2015"></g><g class=" c3-selected-circles c3-selected-circles-May-2015"></g><g class=" c3-shapes c3-shapes-May-2015 c3-circles c3-circles-May-2015" style="cursor: pointer;"></g></g><g class="c3-chart-line c3-target c3-target-Jun-2015" style="opacity: 1; pointer-events: none;"><g class=" c3-shapes c3-shapes-Jun-2015 c3-lines c3-lines-Jun-2015"></g><g class=" c3-shapes c3-shapes-Jun-2015 c3-areas c3-areas-Jun-2015"></g><g class=" c3-selected-circles c3-selected-circles-Jun-2015"></g><g class=" c3-shapes c3-shapes-Jun-2015 c3-circles c3-circles-Jun-2015" style="cursor: pointer;"></g></g></g><g class="c3-chart-arcs" transform="translate(289,93)"><text class="c3-chart-arcs-title" style="text-anchor: middle; opacity: 0;"></text></g><g class="c3-chart-texts"><g class="c3-chart-text c3-target c3-target-Apr-2015" style="opacity: 1; pointer-events: none;"><g class=" c3-texts c3-texts-Apr-2015"></g></g><g class="c3-chart-text c3-target c3-target-May-2015" style="opacity: 1; pointer-events: none;"><g class=" c3-texts c3-texts-May-2015"></g></g><g class="c3-chart-text c3-target c3-target-Jun-2015" style="opacity: 1; pointer-events: none;"><g class=" c3-texts c3-texts-Jun-2015"></g></g></g></g><g clip-path="url(http://localhost:8080/InterActivityPOC/tranList_page.html#c3-1437046737123-clip-grid)" class="c3-grid c3-grid-lines"><g class="c3-xgrid-lines"></g><g class="c3-ygrid-lines"></g></g><g class="c3-axis c3-axis-x" clip-path="url(http://localhost:8080/InterActivityPOC/tranList_page.html#c3-1437046737123-clip-xaxis)" transform="translate(0,196)" style="visibility: visible; opacity: 1;"><text class="c3-axis-x-label" transform="" x="578" dx="-0.5em" dy="-0.5em" style="text-anchor: end;"></text><g class="tick" transform="translate(289, 0)" style="opacity: 1;"><line y2="6" x1="0" x2="0"></line><text y="9" x="0" transform="" style="text-anchor: middle; display: block;"><tspan x="0" dy=".71em" dx="0">0</tspan></text></g><path class="domain" d="M0,6V0H578V6"></path></g><g class="c3-axis c3-axis-y" clip-path="url(http://localhost:8080/InterActivityPOC/tranList_page.html#c3-1437046737123-clip-yaxis)" transform="translate(0,0)" style="visibility: visible; opacity: 1;"><text class="c3-axis-y-label" transform="rotate(-90)" x="-98" dx="0" dy="-80" style="text-anchor: middle;">Total Amount</text><g class="tick" transform="translate(0,196)" style="opacity: 1;"><line x2="-6"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dy="3">0</tspan></text></g><g class="tick" transform="translate(0,180)" style="opacity: 1;"><line x2="-6"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dy="3">100000000</tspan></text></g><g class="tick" transform="translate(0,164)" style="opacity: 1;"><line x2="-6"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dy="3">200000000</tspan></text></g><g class="tick" transform="translate(0,148)" style="opacity: 1;"><line x2="-6"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dy="3">300000000</tspan></text></g><g class="tick" transform="translate(0,132)" style="opacity: 1;"><line x2="-6"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dy="3">400000000</tspan></text></g><g class="tick" transform="translate(0,116)" style="opacity: 1;"><line x2="-6"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dy="3">500000000</tspan></text></g><g class="tick" transform="translate(0,99)" style="opacity: 1;"><line x2="-6"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dy="3">600000000</tspan></text></g><g class="tick" transform="translate(0,83)" style="opacity: 1;"><line x2="-6"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dy="3">700000000</tspan></text></g><g class="tick" transform="translate(0,67)" style="opacity: 1;"><line x2="-6"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dy="3">800000000</tspan></text></g><g class="tick" transform="translate(0,51)" style="opacity: 1;"><line x2="-6"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dy="3">900000000</tspan></text></g><g class="tick" transform="translate(0,35)" style="opacity: 1;"><line x2="-6"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dy="3">1000000000</tspan></text></g><g class="tick" transform="translate(0,18)" style="opacity: 1;"><line x2="-6"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dy="3">1100000000</tspan></text></g><g class="tick" transform="translate(0,2)" style="opacity: 1;"><line x2="-6"></line><text x="-9" y="0" style="text-anchor: end;"><tspan x="-9" dy="3">1200000000</tspan></text></g><path class="domain" d="M-6,1H0V196H-6"></path></g><g class="c3-axis c3-axis-y2" transform="translate(578,0)" style="visibility: hidden; opacity: 1;"><text class="c3-axis-y2-label" transform="rotate(-90)" x="0" dx="-0.5em" dy="-0.5em" style="text-anchor: end;"></text><g class="tick" transform="translate(0,196)" style="opacity: 1;"><line x2="6" y2="0"></line><text x="9" y="0" style="text-anchor: start;"><tspan x="9" dy="3">0</tspan></text></g><g class="tick" transform="translate(0,177)" style="opacity: 1;"><line x2="6" y2="0"></line><text x="9" y="0" style="text-anchor: start;"><tspan x="9" dy="3">0.1</tspan></text></g><g class="tick" transform="translate(0,157)" style="opacity: 1;"><line x2="6" y2="0"></line><text x="9" y="0" style="text-anchor: start;"><tspan x="9" dy="3">0.2</tspan></text></g><g class="tick" transform="translate(0,138)" style="opacity: 1;"><line x2="6" y2="0"></line><text x="9" y="0" style="text-anchor: start;"><tspan x="9" dy="3">0.3</tspan></text></g><g class="tick" transform="translate(0,118)" style="opacity: 1;"><line x2="6" y2="0"></line><text x="9" y="0" style="text-anchor: start;"><tspan x="9" dy="3">0.4</tspan></text></g><g class="tick" transform="translate(0,99)" style="opacity: 1;"><line x2="6" y2="0"></line><text x="9" y="0" style="text-anchor: start;"><tspan x="9" dy="3">0.5</tspan></text></g><g class="tick" transform="translate(0,79)" style="opacity: 1;"><line x2="6" y2="0"></line><text x="9" y="0" style="text-anchor: start;"><tspan x="9" dy="3">0.6</tspan></text></g><g class="tick" transform="translate(0,60)" style="opacity: 1;"><line x2="6" y2="0"></line><text x="9" y="0" style="text-anchor: start;"><tspan x="9" dy="3">0.7</tspan></text></g><g class="tick" transform="translate(0,40)" style="opacity: 1;"><line x2="6" y2="0"></line><text x="9" y="0" style="text-anchor: start;"><tspan x="9" dy="3">0.8</tspan></text></g><g class="tick" transform="translate(0,21)" style="opacity: 1;"><line x2="6" y2="0"></line><text x="9" y="0" style="text-anchor: start;"><tspan x="9" dy="3">0.9</tspan></text></g><g class="tick" transform="translate(0,1)" style="opacity: 1;"><line x2="6" y2="0"></line><text x="9" y="0" style="text-anchor: start;"><tspan x="9" dy="3">1</tspan></text></g><path class="domain" d="M6,1H0V196H6"></path></g></g><g transform="translate(40.5,250.5)" style="visibility: hidden;"><g clip-path="url(http://localhost:8080/InterActivityPOC/tranList_page.html#c3-1437046737123-clip-subchart)" class="c3-chart"><g class="c3-chart-bars"></g><g class="c3-chart-lines"></g></g><g clip-path="url(http://localhost:8080/InterActivityPOC/tranList_page.html#c3-1437046737123-clip)" class="c3-brush" style="pointer-events: all; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"><rect class="background" x="0" width="638" style="visibility: hidden; cursor: crosshair;"></rect><rect class="extent" x="0" width="0" style="cursor: move;"></rect><g class="resize e" transform="translate(0,0)" style="cursor: ew-resize; display: none;"><rect x="-3" width="6" height="6" style="visibility: hidden;"></rect></g><g class="resize w" transform="translate(0,0)" style="cursor: ew-resize; display: none;"><rect x="-3" width="6" height="6" style="visibility: hidden;"></rect></g></g><g class="c3-axis-x" transform="translate(0,0)" clip-path="url(http://localhost:8080/InterActivityPOC/tranList_page.html#c3-1437046737123-clip-xaxis)" style="opacity: 1;"><g class="tick" transform="translate(289, 0)" style="opacity: 1;"><line y2="6" x1="0" x2="0"></line><text y="9" x="0" transform="" style="text-anchor: middle; display: block;"><tspan x="0" dy=".71em" dx="0">0</tspan></text></g><path class="domain" d="M0,6V0H578V6"></path></g></g><g transform="translate(0,230)"><g class=" c3-legend-item c3-legend-item-Apr-2015" style="visibility: visible; cursor: pointer;"><text x="242.5" y="9" style="pointer-events: none;">Apr-2015</text><rect class="c3-legend-item-event" x="228.5" y="-5" width="76" height="18" style="fill-opacity: 0;"></rect><rect class="c3-legend-item-tile" x="228.5" y="0" width="10" height="10" style="pointer-events: none; fill: rgb(31, 119, 180);"></rect></g><g class=" c3-legend-item c3-legend-item-May-2015" style="visibility: visible; cursor: pointer;"><text x="318.5" y="9" style="pointer-events: none;">May-2015</text><rect class="c3-legend-item-event" x="304.5" y="-5" width="80" height="18" style="fill-opacity: 0;"></rect><rect class="c3-legend-item-tile" x="304.5" y="0" width="10" height="10" style="pointer-events: none; fill: rgb(255, 127, 14);"></rect></g><g class=" c3-legend-item c3-legend-item-Jun-2015" style="visibility: visible; cursor: pointer;"><text x="398.5" y="9" style="pointer-events: none;">Jun-2015</text><rect class="c3-legend-item-event" x="384.5" y="-5" width="67" height="18" style="fill-opacity: 0;"></rect><rect class="c3-legend-item-tile" x="384.5" y="0" width="10" height="10" style="pointer-events: none; fill: rgb(44, 160, 44);"></rect></g></g></svg><div class="c3-tooltip-container" style="position: absolute; pointer-events: none; display: none; top: 65.5px; left: 409.5px;"><table class="c3-tooltip"><tbody><tr><th colspan="2">0</th></tr><tr class="c3-tooltip-name-Apr-2015"><td class="name"><span style="background-color:#1f77b4"></span>Apr-2015</td><td class="value">567271823.82</td></tr><tr class="c3-tooltip-name-May-2015"><td class="name"><span style="background-color:#ff7f0e"></span>May-2015</td><td class="value">1094624214.53</td></tr><tr class="c3-tooltip-name-Jun-2015"><td class="name"><span style="background-color:#2ca02c"></span>Jun-2015</td><td class="value">591717743.17</td></tr></tbody></table></div></div>

**Comment by dosborn** [comment]
I'm getting the same issue as raj-mehta with the extra wide axis bars.  Did you find a solution to this?

**Comment by J-1** [comment]
The issue is that only inline styles matter when doing the export. I've modified my local version of c3 to include some additional styling (like fill-opacity:0 for line graphs that show a weird black background) and the image comes out how you'd expect.

**Comment by adrianf29** [comment]
@aendrew please tell me the source of this [http://times.github.io/axisJS/#/](url) i need this tutorial..please help me

**Comment by annatomka** [comment]
You can add PNG exporting feature to c3 charts using my module: https://github.com/annatomka/ng-c3-export

**Comment by morales-franco** [comment]
Hi @annatomka can I use https://github.com/annatomka/ng-c3-export whith async load graphs ? My code:

app.controller("ChartController", function ($http) {
    $http.get('URL').
      success(function (data, status, headers, config) {
          c3.generate({
              bindto: "#My-chart",
              data: {
                  type: 'pie',
                  columns: [
                    ['sample', 30],
                    ['sample2', 200]
                  ]
              }
          });
      }).
      error(function (data, status, headers, config) {
          debugger;
      });


--Draws the chart correctly but no download icon

**Comment by johnmarkli** [comment]
@annatomka Great module but I'm also having trouble with async loading graphs. The download button disappears once I re-generate the graph.

**Comment by aendrew** [comment]
@annatomka That is so good! I'm totally using your module next Angular project I do!

**Comment by adamrecsko** [comment]
+1

**Comment by annatomka** [comment]
@morales-franco  @johnmarkli I fixed the async loading issue, you can try it in the new version (0.1.5). I added some examples too.

**Comment by c5236786** [comment]
@annatomka it works great +1 .. but limitation is on IE and Safari

**Comment by mingli1015** [comment]
@annatomka  Great module but I'm also having trouble with the browsers. It don't work on Internet Explorer your module. Can you please fix the bug, please?

**Comment by aendrew** [comment]
Seriously here, people. If you have issues with annatomka/ng-c3-export, report them in the [annatomka/ng-c3-export issue queue](https://github.com/annatomka/ng-c3-export/issues).

Locking thread.
