### ISSUE TITLE
Long label on 2 lines

### ISSUE THREAD

**Issue by rakeshkhoodeeram** [c3js/c3#330]
Is it possible to display the label in 2 lines.
I have long labels and when I display my daya on a categorised bar chart (rotated),the long label takes a part of the graph, the graph is displayed in a smaller region then.

**Comment by heenaI** [comment]
also {axis: 'x', start: "2016-02-01", end: "2016-06-14", class: 'regionX', label: 'Label #1', vertical: true, padding: 10} does not work
