### ISSUE TITLE
colorize Y-Grid Lines

### ISSUE THREAD

**Issue by DieterSpringer** [c3js/c3#362]
Hi.

How can i colorize Y grid lines?
I want to show a chart with three lines and show the averages as Y-Grid-Lines. To make it clear, that the shown average is the value from a given line, i want to use the same color for the line in the graph and for the average.
I tried to archive this using CSS only, but failed, as i can only select 

```
<g class="c3-ygrid-line">
```

Is there another possibility? Or can you add an additional property of color to the grid-Lines?

**Comment by ecgdeveloper** [comment]
I want to show all grid lines solid in black color without specifying class for each element. Please provide solution if you are aware about it.

I don't know why c3.js showing grid lines dotted instead of solid lines. This doen't look good at all.
