### ISSUE TITLE
Adding onclick listener to the data bars/points in bar/line charts

### ISSUE THREAD

**Issue by abhishekdewan101** [c3js/c3#364]
Hi I wanted to know if there was a way of adding an onclick listener to the various bars of a bar chart. I was trying to follow the example given for the donught chart however, it is not working. Any information would be appreciated.

**Comment by dan-mesa** [comment]
@adrianbj +1

**Comment by tonyneel923** [comment]
Is this still the way to do this? I was having issues using the onclick handler on a bar chart. Specifically nothing was firing from inside the function.
