### ISSUE TITLE
Uncaught TypeError: Cannot read property 'width' of undefined

### ISSUE THREAD

**Issue by brooksbp** [c3js/c3#365]
With the latest release c3 release (download link from main website) and d3.v3.min.js

Google Chrome 36.0.1985.49 beta

I am surprised this doesn't work right out of the box.  Am I doing something wrong?

``` html
<!DOCTYPE html>
<html>
<head>
  <link href="c3.css" rel="stylesheet" type="text/css">

  <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
  <script src="c3.js"></script>

  <script>
    var chart = c3.generate({
     data: {
       columns: [
         ['data1', 30, 200, 100, 400, 150, 250],
         ['data2', 50, 20, 10, 40, 15, 25]
       ]
     }
   });
  </script>
</head>
<body>

  <div class='chart'>
  <div id="chart"></div>
  </div>

</body>
</html>
```

**Comment by DevInder1** [comment]
this error mainly occurs when your script function load first and then  html body so solution is to write script function at the bottom of body so that i will be able to find div id and bind graph to that it

**Comment by DevInder1** [comment]
<body>
<div id="chart"></div>

<script>
    var chart = c3.generate({
        bindto: '#chart',
        data: {
            columns: [
                ['data1', 30, 200, 100, 400, 150, 250],
                ['data2', 50, 20, 10, 40, 15, 25]
            ]
        }
    });
</script>
</body>
</html>

**Comment by DevInder1** [comment]
<body>
<div id="chart"></div>

<script>
    var chart = c3.generate({
        bindto: '#chart',
        data: {
            columns: [
                ['data1', 30, 200, 100, 400, 150, 250],
                ['data2', 50, 20, 10, 40, 15, 25]
            ]
        }
    });
</script>
</body>
</html>

**Comment by DevInder1** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>using c3</title>

    <link href="css/c3.css" rel="stylesheet" type="text/css">

    
    <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.js"></script>
   

</head>
<body>
<div id="chart"></div>

<script>
    var chart = c3.generate({
        bindto: '#chart',
        data: {
            columns: [
                ['data1', 30, 200, 100, 400, 150, 250],
                ['data2', 50, 20, 10, 40, 15, 25]
            ]
        }
    

 });

</script>
</body>
</html>

**Comment by leadsleadsleads** [comment]
eaef wsezw  ae 
![image](https://user-images.githubusercontent.com/34507213/34518109-d88a950c-f0a3-11e7-8ce1-d230b7628ec6.png)

**Comment by leadsleadsleads** [comment]
It is not working error may occurs as it is. i also use this solution..
![image](https://user-images.githubusercontent.com/34507213/34518133-04e43fcc-f0a4-11e7-89c4-13be96459d1c.png)

**Comment by leadsleadsleads** [comment]
I use this solution but error occurs..
![image](https://user-images.githubusercontent.com/34507213/34518290-d429e638-f0a4-11e7-88a8-145d7388f804.png)

**Comment by sagar232000** [comment]
try to use script inside the body tag like:

<html>
<head>
	<title>chart with c3</title>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.9.1/d3.min.js" charset="utf-8"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.6.13/c3.min.js"></script>
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.6.13/c3.min.css">
	
</head>

<body>
<div id="chart"></div>
<script>
	
		var chart=c3.generate({
			bindto:'#chart',
			size:{
				width:500,
				height:500
			},
			data:{
				columns:[
						['data1',20,200,23,45,45],
						['Ghandhinagar',30,56,230,202,21]
					],
				type:'line'
				}
			});
	</script>

</body>
</html>

**Comment by sagar232000** [comment]
try this way to solve problem:
use script inside the body tag like this:
![Capture](https://user-images.githubusercontent.com/25721642/54122125-3927d780-4422-11e9-85d9-5b0430264b0c.PNG)
