### ISSUE TITLE
Event to capture brush and zoom range

### ISSUE THREAD

**Issue by roydaniels** [c3js/c3#395]
-Hey

We are using C3 in our BigData Analytics at my company and thank you for creating such a great charting framework!

One thing we do need is the ability to use Crossfilter with C3. While this is already somewhat possible due to C3's nice API, one thing is missing is the ability capture the time range on a zoomed or brushed timeseries chart. 

What I've done as a bit of a hack was add a hook in `redrawForBrush()` to send the brush object to an event I added, `__subchart_onbrush(brush);`. I realize this isn't ideal (and is only for brushes not zooming), but it would be nice to have this functionality in the framework.

**Comment by mohamad-alibrahim** [comment]
@masayuki0812 i can't find the exampel. the exampel page is not found

**Comment by arrahman17** [comment]
@masayuki0812 Please, have you Any bar chart which shows x-axis and y-axis data and filter a third column in the data set
