### ISSUE TITLE
How use culling with time series ?

### ISSUE THREAD

**Issue by ihsansatriawan** [c3js/c3#408]
Hi, i found example culling in here http://c3js.org/samples/axes_x_tick_culling.html
i want to try to make x axis in time series (2014-01-01 until 2014-05-01) how i can make in x axis just show the first date of month (2014-01-01, 2014-02-01, 2014-03-01, 2014-04-01, 2014-05-01). I mean show in x axis,,,Thx for your help :)

**Comment by salok64** [comment]
How to use timeseries in y axis
