### ISSUE TITLE
how to format title ?

### ISSUE THREAD

**Issue by ashishsajwan** [c3js/c3#412]
in donut charts there is this title that shows up in center of donut 
see here http://c3js.org/samples/chart_donut.html
how can i apply html formatting to that title.. ??

**Comment by alexphelps** [comment]
@masayuki0812 do you have an example of how to do what you described above to format the text on two lines?

**Comment by aendrew** [comment]
@alexphelps Please ask on the [Google Group](https://groups.google.com/forum/#!forum/c3js). Thanks!

**Comment by alexphelps** [comment]
@aendrew - https://groups.google.com/forum/#!topic/c3js/e5C0IfupYWE
