### ISSUE TITLE
non clickable legend

### ISSUE THREAD

**Issue by pcout** [c3js/c3#426]
Hello,

Is it possible to have non clickable legends ?

thanks

**Comment by mathiasbanda** [comment]
Thanks guys this is helpful. My further question is how do I get to call the default behavior before or after my custom function in legend.item.onclick = function () {doCustomEvent(); doDefault()}

**Comment by mgimeno** [comment]
@mathiasbanda default behaviour is:
legend.item.onclick = function (id) { chart.toggle(id); }

**Comment by mathiasbanda** [comment]
My workaround was basically a cheat, I will do it properly now. Thanks
