### ISSUE TITLE
C3 Chart, y axis scale

### ISSUE THREAD

**Issue by luca-filipponi** [c3js/c3#450]
Hi, first of all congrats for your great library !
I've a questiona about the range of value created on axis using your chart.
I've set a min and a max value for the Y chart in this way: 

axis: {
            y: {
                show: true,
                max:maxValue,
                min:minValue,
                padding: {top:pad, bottom:0},
               } ..

Setting in this value 0 for min and 100 for max. 
And thats what appear:
![schermata 2014-07-18 alle 10 59 36](https://cloud.githubusercontent.com/assets/6905471/3624217/e8288972-0e59-11e4-8c50-03b6ef2c8ed9.png)
The value shown is:
0 10 20 30 40 50 60 70 80 90 100
There is a way in which I can have less value? for example:
0 20 40 60 80 100
Because this chart will be in a small windows, and too many values makes the chart hard to understand.
Thank you in advance for your help.

**Comment by smuuf** [comment]
This (setting ```axis.y.ticks = 5```)does nothing for me :disappointed:
Here is a *jsbin* using the version of C3 used at the C3.js website:

http://jsbin.com/zowomedece/1/

Did this functionality somehow disappeared, or am I doing something wrong?

**Comment by JamesMura** [comment]
@smuuf I think it was changed to `axis.y.tick.count=5`  [http://c3js.org/reference.html#axis-y-tick-count](c3js reference) 
Look at #560
