### ISSUE TITLE
Custom grid lines should be optionally positioned above the chart

### ISSUE THREAD

**Issue by rassie** [c3js/c3#462]
Even though grid lines are technically grids, they are mostly used as comparisons, in most cases also with labels on them. However, they are drawn together with the actual grids, which are positioned at the bottom of the z-stack. Therefore, labels and actual lines more often than not cannot be read. See [fiddle](http://jsfiddle.net/fMX8g/2/) for an example. In that fiddle, moving `.c3-ygrid-lines` manually to be a direct following sibling of `.c3-axis-y2` places that guide at the visually correct position.

Putting those guides above the chart should be possible with a direct graph configuration.

**Comment by pnorth423** [comment]
I'd like to change this property after `c3.generate` is called. 

I was trying to set `chart.internal.config[grid_lines_front] = false`, but changing that entry of the `chart.internal.config` object is not taking affect. 

I also tried to implement a d3 version of the JQuery option proposed by @alwerner, would anyone have any idea how I could acheive this ? Any help appreciated, thanks in advance : )
