### ISSUE TITLE
Disable legend clicking option

### ISSUE THREAD

**Issue by BenjaminRH** [c3js/c3#493]
Clicking the legends to show or hide the data in the graph is great -- mostly. It's terrible when there's just one, for example. It would be great if there was an option to disable that when there's only one.

**Comment by artemisclyde** [comment]
@masayuki0812 your solution overwrites the onclick function, but I still think it's misleading that the user can click the legend and the cursor changes on hover. An option to disable the onclick for legends would be great

**Comment by romain-gilliotte** [comment]
IMHO this is still a problem.
A workaround, is to use CSS to hide the button

```
.c3-legend-item {
  display: none;
}
```

**Comment by Hypersapien** [comment]
This would be better

```
    .c3-legend-item {
        cursor:default !important;
    }
```

**Comment by jeffreycastro** [comment]
Ended up doing a combination of the comments. Hovering on the legend still works, and clicking wont do anything, as well as the cursor pointer.

chart init:
```
c3.generate({
  ...
  legend: {
    item: { onclick: function () {} }
  }
});  
```  

css:
```
.c3-legend-item {
  cursor:default !important;
}
```
