### ISSUE TITLE
Animate left-to-right on x-axis

### ISSUE THREAD

**Issue by alwerner** [c3js/c3#502]
I'm trying to figure out how to smoothly increment both x and y2 values to animate data left-to-right on x-axis, and bottom-to-top on y2 axis, so that an area chart appears to grow on page load. I figured out how to update all x and y2 values simultaneously using chart.load - but the affect only grows on one axis, and tried using chart.flow to increment corresponding x and y2 values one at a time - but effect is stepped and not smooth.

Here is a highcharts demo that illustrates the type of animation I'd like to achieve:

http://www.highcharts.com/demo/area-basic

**Comment by mbonaci** [comment]
This is more like an FYI:
this works:
```
oninit: function () {
  this.main.append('rect')
    .style('fill', 'white')
    .attr('x', 0.5)
    .attr('y', -0.5)
    .attr('width', this.width)
    .attr('height', this.height)
    .transition().duration(1500)
    .attr('x', this.height)
    .attr('height', 0)
    .remove();
}
```
and this does not:
```
oninit: function () {
  this.clipChart
    .attr('height', 0)
    .transition().duration(2000)
    .attr('height', this.height);
}
```

on the same bar chart.
