### ISSUE TITLE
Ability to show/hide mouseover tooltip via API

### ISSUE THREAD

**Issue by roydaniels** [c3js/c3#509]
It would be great to be able to show and hide tooltips via a C3 API call. Something like `chart.tooltip.show()`, `chart.tooltip.hide()`. Each of those methods would then take a JSON object as its only parameter allowing the setting of the x-axis tooltip value to show/hide, position, and the particular dataset if tooltip grouping is turned off (with no parameters in `.hide()` meaning hide all).

It would enable developers an easy way to do something like what Datadog does in its time series charts where mousing over one chart also shows the same x-axis value of a different chart. A very important feature when comparing multiple charts that might have the same time range on the x-axis.

ref: http://vimeo.com/27541490 at about 1:05

**Comment by jaypinho** [comment]
Is this still working? I can't seem to get the tooltip to show or hide using the API at all -- I'm trying to conditionally show it for one data series but not for another one within the same chart, but the show/hide commands aren't working at all for me.

**Comment by loubrevetti** [comment]
does this feature work on donut and or pie charts, if so how.

**Comment by aleksandarr** [comment]
Is it somehow possible to show/hide tooltip that I created through API tooltip.contents?
