### ISSUE TITLE
How customize chart background with gradient color

### ISSUE THREAD

**Issue by nvcken** [c3js/c3#519]

**Comment by ivarkallejarv** [comment]
Combining methods from multiple sources, I arrived at this solution for changing the background of the chart -

//Set background opacity and fill
d3.selectAll('.chart g.c3-event-rects').style('fill-opacity', '1');
d3.selectAll('.chart g.c3-event-rects').style('fill', 'url(#something)');

//Insert gradient
let gradient = d3.select('defs')
      .append('linearGradient')
      .attr('id', 'gradient')
      .attr('x1', '50%').attr('y1', '0%')
      .attr('x2', '50%').attr('y2', '100%');

    gradient
      .append('stop')
      .attr('offset', '0%')
      .attr('stop-color', '#FFFFFF')
      .attr('stop-opacity', '1');

    gradient
      .append('stop')
      .attr('offset', '100%')
      .attr('stop-color', '#B38EE8')
      .attr('stop-opacity', '0');

It would be very nice if this was documented as well. I mean using gradients through inserting with d3 and using css notation as was mentioned in #1098 at least until support for gradients is made available

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
