### ISSUE TITLE
How essential is it for C3 to sort the x axis list?

### ISSUE THREAD

**Issue by fasiha** [c3js/c3#525]
Plotting experience from Python/Matplotlib, R, Matlab, Excel, etc., suggests that the ordering of the x values of a plot is important, i.e., if you use a non-sorted list of for your x axis and ask for a line plot, you'll get a jagged line. C3.js doesn't do this: it'll sort the x-axis data before drawing a "normal-looking" (but unexpected, and in some cases, incorrect) plot.

How important is this decision to C3's design? Can it be relaxed by a user-settable parameter? 

``` js
var chart = c3.generate({
    bindto : '#ch',
    data : {
        x : 'x',
        rows : [
            [ 'x', 'data1', 'data2' ],
            [ 11, 120, 300 ],
            [ 22, 160, 240 ],
            [ -33, 200, 290 ], // <----- note shuffled x point
            [ 44, 160, 230 ],
            [ 55, 130, 300 ],
        ]
    }
});
```

Background: I'm using `tooltip.contents` and a non-sorted list for x in a scatter plot, and have to create a lookup object to transform the x values to indexes just for this. The x list can't be stored sorted because it indexes many other lists.

**Comment by shafiquejamal** [comment]
Has this been implemented? The documentation (https://c3js.org/reference.html#data-xSort) says "not yet". I tried it, and it seems to not be working. Would you please provide an example? Thanks.

**Comment by OttoG** [comment]
@shafiquejamal it works for me with version 0.4.11. Setting _\<c3 chart object\>_`.data.xSort = false` solved a problem similar to the one described by the original poster. The dots keep their index numbers from the supplied data set (and the corresponding drawing order is respected) regardless of their x values.

That version is rather old, though. Perhaps the functionality has become broken in later versions?
