### ISSUE TITLE
Overlapping x-axis date labels for timeseries

### ISSUE THREAD

**Issue by runeksvendsen** [c3js/c3#527]
Here's an example: http://jsfiddle.net/gbdtjsba/1/

It would be nice if c3.js could figure out how many labels to draw, so they don't overlap. Also, tilting labels will help with really long labels, like so: https://i.stack.imgur.com/idpth.png

**Comment by mezase121** [comment]
this happens to me when using datetime and the date is exactly the same but for the time. Solution is to format the date so as to remove the time from it.

**Comment by Tarun-Gurnani** [comment]
If you are using dates , than always go with timeseries it will mazorly reduce your overlapping and othern than this rotate is nive one .
