### ISSUE TITLE
Allow stacked line/spline-area charts

### ISSUE THREAD

**Issue by jess-sol** [c3js/c3#54]
It'd be really nice if line, spline, line-area, and spline-are charts could be stacked.  It doesn't seem to function like this currently.

It'd be great for timeseries graphs, so a few different related metrics (like http status codes, sale types) could add up to a total(like number of requests, or sales).

**Comment by pistou** [comment]
I'm not sure if there is a regression bug or something but you can't stack area-* with another kind:

![bug](https://user-images.githubusercontent.com/6703711/39993952-05353d9c-5778-11e8-9562-de2e65769bbf.jpg)

As you can see, the area is broken, it doesn't take account of the line "offset".
