### ISSUE TITLE
Loading new JSON data into scatter plot replaces, instead of adding to existing data

### ISSUE THREAD

**Issue by kannes** [c3js/c3#557]
http://c3js.org/samples/chart_scatter.html shows a new category being added to a scatterplot at 1000 milliseconds.

I am trying to do the same but with data being loaded from JSON. I specified the same keys as when initially creating it. Instead of adding the new data as new category (and color) to the existing graph, C3 will remove the existing points, add the new ones and zoom to them.

Is this a bug or am I using it wrong?

```
var chart_scatterplot = c3.generate({
    bindto: '#chart_scatterplot',
    data: {
        json: jsonfile,
        keys: {
            x: 'xvariable',
            value: ['valuevariable'],
        },
        type: 'scatter',
    },
});

setTimeout(function () {
    chart_scatterplot.load({
        json: differentjsonfile,
        keys: {
            x: 'xvariable',
            value: ['valuevariable'],
        },
    });
}, 1000);
```

**Comment by ibrudy69** [comment]
@buremba @masayuki0812 Your original post is exactly what I also would like to do without having to do any funky changes from the inline C3 JSON format call as per the documentation to "columns" one later mentioned. A simple **chart.load** with "columns" works but still would like to know what the protocol for doing the same with the format below.

What I would like (just add a new json data set):
https://jsfiddle.net/d8g015n2/

While using/keeping my existing format:
data: {
            json: [{"date":"2020-03-05","Confirmed":1,"Active":1,"Recovered":0,"Help":0},{"date":"2020-03-06","Confirmed":2,"Active":2,"Recovered":0,"Help":0},{"date":"2020-03-07","Confirmed":2,"Active":2,"Recovered":0,"Help":0}],
            keys: {
                x: 'date', 
                value: ['Confirmed', 'Active', 'Recovered', 'Help'],
            },
            order: null   
        } ...

Much thanks in advance all and great d3 wrapper !!!
