### ISSUE TITLE
set tick count for y-axis?

### ISSUE THREAD

**Issue by sweatherall** [c3js/c3#560]
Is there any way to set the tick count for the y-axis like there is for x-axis?

I have y-values that do not make sense to be floats, yet when there are only 2 the chart gives me floating values between 0-1, 1-2.

Any suggestions are welcome, thank you.

**Comment by MayankProgenG** [comment]
In the generate() function you can set axis.y.tick to whatever value you would like. c3 will use this in place of the default 10.
object path eg:

var chart = c3.generate({
     axis: {
          y: {
              tick: {
              count: 4
          }
      }
}
    });
After tick of y axis is 4.

**Comment by WoodrowShigeru** [comment]
I find the `axis.y.tick` behavior lackluster. I.e., for a dataset like `["apples", 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]` and a tick setting of `10`, it generates a y axis of [0,0,0,0,0,0,1,1,1,1,1,1].

Here is a workaround:

```js
c3_config.axis.y.tick.count = Math.min(
  [
    // get unique values.
    ...new Map(
      c3_config.data.columns
        // skip x row if present.
        .filter((dataset) => dataset[0] !== 'x')

        // skip dataset key.
        .map((dataset) => dataset.slice(1))

        // merge all datasets into one set.
        .flat()

        // prepare for map constructor.
        .map((value) => [value, value])
    ).values()
  ].length,
  10
);
```

It basically uses either the preferred 10 or, if lower, the amount of unique values.
