### ISSUE TITLE
Bar Chart with Step Chart

### ISSUE THREAD

**Issue by SamMorrowDrums** [c3js/c3#566]
Aligning the steps with the centre of the bar does not really work as a chart.

If it is possible instead to have an option where the steps are flat above bars, and change value in between bars this would be much more effective.

This is only an issue when combining step charts with bar charts.

**Comment by alexhoma** [comment]
@masayuki0812 Hi, where do I have to place this "step-after" on my step chart function? Thank you!

**Comment by Mantish** [comment]
Hi
This is working fine for regular charts, but when the axis is rotated (like in the first screenshot), it doesn't look good.
This is due to the step interpolation that works in a "horizontal" way.
...I think I can provide a PR, if you agree this is something that needs to be fixed

**Comment by amran-mamoon-fn** [comment]
For a single data point, it's showing nothing. Is there any way to show a vertical line for a single data point?
```
var chart = c3.generate({
data: {
columns: [
['data1', 300]
],
types: {
data1: 'step'
}
}
});
```
