### ISSUE TITLE
C3 with crossfilter?

### ISSUE THREAD

**Issue by smbasha47** [c3js/c3#594]
Hi All,
   It it possible to plot c3 charts using crossfilter, because in my case i need to plot large data points.

Thanks in advance.
Mahaboob Basha.

**Comment by chintamanil** [comment]
Can someone give me an example of how to integrate crossfilter with c3. I am fairly new to both and d3 in general. Thanks ..

**Comment by zhiboz** [comment]
would be very appreciative if someone could share an example of c3 + crossfilter.

**Comment by aendrew** [comment]
By Crossfilter, do you mean [this](http://square.github.io/crossfilter/)? This is the first I've heard of it, though looks interesting.

**Comment by zhiboz** [comment]
Yes. That's the JavaScript library I was referring to.

**Comment by smbasha47** [comment]
@aendrew yes this will help to load large data points

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you!
