### ISSUE TITLE
Categorzied x axis (not time series) tick labels overlap when too long....

### ISSUE THREAD

**Issue by jsphkhan** [c3js/c3#605]
As you can see in the screenshot below, I have a chart that displays data based on browser user agents. Hence the x - axis tick labels are very very long. I wanted to format it to something shorter by appending an ellipsis after a certain number of characters. The category axis I am having is not a time series axis. Also I did not find any example based on formatting x-axis ticks for category axis. 
![screen shot 2014-10-08 at 12](https://cloud.githubusercontent.com/assets/1991609/4555199/626b627c-4eba-11e4-9c18-6bc25445a55e.png)

Thank you Joseph

**Comment by vnen** [comment]
@masayuki0812 I'm not sure if I should open a new issue. I tried to use `axis.x.tick.format` but the function receives an index number instead of the category string.

My workaround is to use `function (x) { return myFormat(chart.categories()[x]); })`. Is there another way to do this?

**Comment by otusweb** [comment]
@vnen Sorry for the beginner question, but how do you use the line function. I tried to add it to my c3.generate function, but it complains that chart is not defined.

i.e.: 
```
var chart;
chart = c3.generate({axis : {
        x : {
            type : 'category',
            tick: {
                format: function (x) { return myFormat(chart.categories()[x]); }}}}});
```

**Comment by vnen** [comment]
@otusweb well, I don't use c3 in a long time, so it might have have changed in newer versions, but here is how I used it: https://github.com/flikore/writerstrail/blob/v0.7.1/public/scripts/stats.js#L73
