### ISSUE TITLE
Gauge tick

### ISSUE THREAD

**Issue by toonhello** [c3js/c3#612]
Hi,
how i can add tick to gauge? 
I want to use as tachometer and i need to divide di arc in 5 steps.

Thanks in advance

**Comment by kjantzer** [comment]
Thanks for this @masayuki0812 :+1:

**Comment by kjantzer** [comment]
While implementing this, I found some issues with the rotation calculation.

`ticks: [25, 50, 75]` worked, but when I tried a numbers like `ticks: [70, 80, 90]`, the position of the ticks was not being calculated correctly.

Changing `rotate` to this fixed it:

```
rotate = (ratio * 180) - 90
```

I also added a few additions to make styling the ticks easier:

```
.classed('ticks', true)

...

.attr('data-reached', function(d){ 
	var val = chart.internal.data.targets[0].values[0].value;
	return d < val ? 'yes' : 'no';
});
````

Here's the updated example: http://jsfiddle.net/7kYJu/1565/
