### ISSUE TITLE
roate x axis labels in the reverse direction 

### ISSUE THREAD

**Issue by NidhiArien** [c3js/c3#614]
http://www.d3noob.org/2013/01/how-to-rotate-text-labels-for-x-axis-of.html

Can we rotate x axis labels in this manner? I have done this: http://c3js.org/samples/axes_x_tick_rotate.html, but rotating the other way seems much better. Any inputs would be appreciated.

**Comment by dunlapm** [comment]
This is still a bug with timeseries as @agdev says.

**Comment by piotrp88** [comment]
Any news? November 2017 and the bug is still there.
