### ISSUE TITLE
force line break in x axis tick text

### ISSUE THREAD

**Issue by daviestar** [c3js/c3#634]
Hey

http://jsfiddle.net/gbdtjsba/11/

I have fairly long labels in my graph.  I have added a hard height of 500px to the graph, and 200px to the x axis which works, but I'd like to make the axis height dynamic if possible.

Should I loop through the labels to find the largest one and calculate it's width before applying the graph, or does c3 have a feature which can do this?

Might be related to this one: https://github.com/masayuki0812/c3/issues/527

Thanks for a great library, so far it has saved me many hours of d3 programming :)

**Comment by jcsmorais** [comment]
@laurabrooks I'm not sure what you're referring to with "this", but `axis.x.tick.multiline` has been implemented for a while and I recently introduced support for `axis.x.tick.multilineMax` and added documentation for both (see [here](http://c3js.org/reference.html#axis-x-tick-multiline)), hopefully that helps.

**Comment by laurabrooks** [comment]
I was wondering about forcing a line break at a specified point in label text. multiline and multilineMax attributes will do the job though, thank you for the response @jcsmorais

**Comment by Sibasish19** [comment]
Hey is there any provision for multiline axis labels?

**Comment by github-peter** [comment]
I am plotting time series data with axis.x.tick.format = "%Y-%m-%d %H:%M:%S" and with axis.x.tick.multiline = true but end up with a plot with cluttered text and the "date-time label" overlapping. Am I using the library wrong or is there a bug multiline feature?

**Comment by GDFaber** [comment]
I'm closing this issue because multiline options already exist. Please refer to [the docs](https://c3js.org/reference.html#axis-x-tick-multiline) which were stated by @jcsmorais.
