### ISSUE TITLE
The y-axis always starts with zero

### ISSUE THREAD

**Issue by ntquyen** [c3js/c3#664]
Even I set `axis.y.min = 100000`. But it still always starts at zero. All I want is set a "false bottom" of the bar chart.
 I'm using c3 v0.3.0 and d3 v3.4.13. Please help!!

**Comment by rakhikarampuri** [comment]
Hello Masayuki

**Comment by rakhikarampuri** [comment]
Hello masayuki

**Comment by rakhikarampuri** [comment]
Hello Masayuki
  I also faced above problem i tried the 0.4.11 and 0.4.18
  to solve that problem i setted zerobased = true
then it's solved

thanks.
