### ISSUE TITLE
Add regions to load chart function

### ISSUE THREAD

**Issue by abologna-r7** [c3js/c3#704]
Hi,

Can you add the following code inside the char load function? This will add regions as well on load. Thanks.

```
        // update regions if exists
        if ('regions' in args) {
            config.data_regions = args.regions;
        }
```

**Comment by manbropig** [comment]
Hello!

I have a similar need and I'm calling `chart.internal.config.data_regions = args.regions` before `load` as you have instructed:
```
chart.internal.config.data_regions = highlightRegions;
chart.load({
    json: graphData, //send all data to chart
    keys: {
      x: graphBy, 
      value: loadedFields, 
    },
    unload: unloadFields //the data you want to unload
  });
```
But I'm not getting the regions highlighted. Is there something else I need to take care of?
If I create the chart with `highlightRegions` it works, but I won't know which regions need to be highlighted on generation of the chart.
Any help would be appreciated! Thanks a lot!
