### ISSUE TITLE
Click anywhere on chart, not just data items

### ISSUE THREAD

**Issue by pareeohnos** [c3js/c3#705]
I'm trying to implement a feature where the user can click anywhere on the chart to add kind of annotations, however C3 only recognises click events on data points. Setting `data.selection.grouped = true` as suggested elsewhere makes it partly work, however the `onclick` event callback is then called once per data item, and still only works for the data items themselves.

What i'm after is a way of recognising a click anywhere, so I am then able to calculate what the X value should be based on the x-axis' scale and use it elsewhere. Is there any way I can do this?

**Comment by Cobry** [comment]
Just a js code for example : http://jsfiddle.net/6dahdmda/

**Comment by Hypersapien** [comment]
> Just a js code for example : http://jsfiddle.net/6dahdmda/

This doesn't work for me. Nothing shows up in the Run panel.

**Comment by Hypersapien** [comment]
> Ah so it does! Initially this wasn't working as I expected, calling `chart.internal.x(xCoord)` returned `-2031062` but calling `chart.internal.x.invert(xCoord)` instead works as expected :) Thanks for all the help

I can't get to chart.internal when inside the click event. I just comes up as 'undefined'.

**Comment by Hypersapien** [comment]
> I think you can use `chart.internal.x` as `xScale` in your code. `chart.internal.x` is the actual scale function used internally, so I think it would be what you want. Could you try it?

I can't get to 'chart.internal' inside the click event. It just comes up as undefined.

**Comment by Hypersapien** [comment]
I'm using this method on a Stacked Area Graph, and I got it working. I can tell which X-axis value is being clicked on, but I don't know how to tell which vertical area of the graph is being clicked on.
