### ISSUE TITLE
Pie Chart with Json data

### ISSUE THREAD

**Issue by HarishkumarTVN** [c3js/c3#710]
Hi, I have an issue issue, my data as follows.

[{"LC":"xyz","count":1000},{"LC":"abc","count":2000},{"LC":"BCD","count":1500},{"LC":"Others","count":500}]';

Is it possible to generate pie chart ? i am able to generate line & bar but when using the chart type as pie. It is just showing 100 %.

Regards
Harish

**Comment by agdev** [comment]
Hi,
I have similar need, json data with two columns datalabel and value.
I think pie chart should work as other charts and not to exception.
