### ISSUE TITLE
Change label/value color on pies

### ISSUE THREAD

**Issue by JeanMeche** [c3js/c3#723]
Either I've missed it or I doesn't exist yet, 

Could you add the possibility to change the text color on pies. (the % value), it's white right now and it prevent using bright colors on the pies.

**Comment by agdev** [comment]
I do not see it is making any difference, I added d3.select('.c3-chart-arc text').style('color', '#000');
to http://c3js.org/samples/pie_label_format.html this sample.
I can see color is set on the text element but browser does not render in this color.
I tried to change color directly in debugger with same result.
I tried in latest chrome and firefox

**Comment by masayuki0812** [comment]
`fill` seems to work instead of `color`.

**Comment by agdev** [comment]
It changed only one text, not clear why no both. I used the same example and added 
d3.select('.c3-chart-arc text').style('fill', 'red');
Any ideas?
