### ISSUE TITLE
Tick formatting depending on x range

### ISSUE THREAD

**Issue by jonashaag** [c3js/c3#735]
Use case: Timeseries with zooming/unknown X range.

Want to show only dates when I have data of multiple days (but the full timestamps in tooltips), and more fine grained x values if I have data only of a few hours, or I have zoomed.

Easiest solution would be have the `axis.x.tick.format` function take three arguments `value`, `minValue`, `maxValue`, with the latter specifying the currently shown X range.

**Comment by myfbone** [comment]
I was wondering if it's possible now out of box or should I use hack?
