### ISSUE TITLE
Get category or custom property on chart click event

### ISSUE THREAD

**Issue by ImranAhmed** [c3js/c3#744]
When I click on the chart I want to either get the category label or get a custom property on my data object.

My data structure for the chart looks like as follows:
{
   'x': '1234',
   'url': 'www.google.com',
   'value': 10
 }

I have wired up the click event on the bar chart as follows:

 onclick: function (d,i) {
     console.log(d,i);
 },

However on the click event for bar 1234 the value of d is: (see console.log)

id: "value"
index: 0
name: "value"
value: 10
x: 0

I need the value: '1234 or even better 'url': 'www.google.com'. Is this possible?

jsfiddle here: http://jsfiddle.net/_ImranA/htvqok2a/

NB: 
- In the example I can probably do this easily using a lookup and the 'index' value as the data structure is simple and I have a reference to it. However in a more complex situation it would be nice to have direct access to 'url' or the value '1234' from the chart object without doing a look-up using index.
- I am working using angular and do not have access to jQuery.

**Comment by mboullouz** [comment]
@aendrew ~4yrs later and you jsfidle is still helpful, thank you
