### ISSUE TITLE
Gauge enhancements

### ISSUE THREAD

**Issue by Tropicalista** [c3js/c3#749]
Not sure if I'm right, but seems that gauge chart has limited features. A nice enahncements could be something like http://rendro.github.io/easy-pie-chart/ 

Would be great to have the possibility to create a full circle charts like in the example posted.

**Comment by carloschneider** [comment]
+1

**Comment by moxx** [comment]
+1

**Comment by Kinlaw** [comment]
+1

**Comment by Kinlaw** [comment]
I am currently working on a solution that allows the user to specify full circle (half circle being the default) as well as a starting angle. I feel like I can implement this without increasing the number of lines in the code by more than just a few. Is this still just a plugin candidate or would you accept a PR for that functionality?

**Comment by avoliva** [comment]
Were you able to implement this successfully?

**Comment by pbojinov** [comment]
@avoliva Just a heads up this has been implemented with the addition of the options `gauge.fullCircle` and `gauge.startingAngle`. 

Take a look at the following tests for how to use it - https://github.com/c3js/c3/blob/ccff119809de05a68ff3e33521a79566bf12b903/spec/arc-spec.js#L205-L223

**Comment by panthony** [comment]
Thanks for pointing this out @pbojinov !
