### ISSUE TITLE
Is it possible to change de Y axis max/min after create the chart?

### ISSUE THREAD

**Issue by leo-mck** [c3js/c3#753]
I can define a min/max for the Y axis doing this:

```
axis:{
    y: {
        max: 500,
        min: 0
    }
}
```

But can I change that max/min values manually without having to re-create the chart?

**Comment by ttynhi** [comment]
Can I change the Y axis max/min after upload chart from API the chart? Thanks ^^

**Comment by jayantsr83** [comment]
Hey @ttynhi  have you got any solution on this issue?

> Can I change the Y axis max/min after upload chart from API the chart? Thanks ^^
