### ISSUE TITLE
Add click event to x axis tick label

### ISSUE THREAD

**Issue by ImranAhmed** [c3js/c3#761]
I can easily add a click event to the chart data points.

Has anyone worked out how to add a click event to the tick label? I would expect it to be something like follows however this does not work

http://jsfiddle.net/_ImranA/m4pkzwcw/

I was able to do this using jQuery and binding to the tick label element after the chart has been rendered. However how would I do this in a non-jQuery environment like Angular?

**Comment by mscharfstein** [comment]
I'd like having this option too! Did it ever get created?

**Comment by AbdurRehman91** [comment]
Did this feature is integrated yet??

**Comment by AbdurRehman91** [comment]
I need this feature of adding click event on x-axis tick label
