### ISSUE TITLE
is it possible to customer c3.js to meet my new type of chart requirements?

### ISSUE THREAD

**Issue by madasuk** [c3js/c3#769]
I have a requirement of the new graphs Zoomable Sunburst With Updating Data (http://bl.ocks.org/kerryrodden/477c1bfb081b783f80ad), Heat Map (http://jsfiddle.net/indiemaps/gzPDU/), Zoomable Circle Packing chart (http://bl.ocks.org/mbostock/7607535), Co-occurrence Matrix  (http://bost.ocks.org/mike/miserables/)  Is there is any possibility for me to customize c3.js to yield these charts?

**Comment by mervinva** [comment]
I also have a requirement of graph Zoomable Sunburst With Updating Data . How can I use c3js to add this chart ?

**Comment by TheDesignerXD** [comment]
Sunburst charts are super useful!
Consider if you will parent child groupings... for things like:

- Fruits (25%)
-- Apple (20%)
-- Banana (20%)
-- Orange (20%)
-- Cherry (20%)
-- Strawberry (20%)
- Vegetable (25%)
-- Lettuce (33%)
-- Brussels Sprouts (33%)
-- Carrot (33%)
- Meat (25%)
-- Pork (33%)
-- Beef (33%)
-- Chicken (33%)
- Dairy (25%)
-- Yogurt (25%)
-- Cheese (25%)
-- Ice Cream (25%)
-- Milk (25%)

Here a sunburst would allow you to do an inner ring with (Fruit, Vegetable, Meat, Dairy) and an outer ring of all the rest of them but segmented off to match their parents in the inner ring.
The following example is simplified and shows age ranges (larger groups ex 18-34, and smaller child groups 18-24, 25-29, 30-34)
<img width="395" alt="screen shot 2018-06-12 at 3 22 30 pm" src="https://user-images.githubusercontent.com/5721469/41320808-1cf2330a-6e56-11e8-9722-8bf5dd6cfda8.png">
