### ISSUE TITLE
Set color of the regions

### ISSUE THREAD

**Issue by fbolognaboidi** [c3js/c3#77]
how can I set the color of the regions?
is it possible?

**Comment by viseth** [comment]
Hi,

How can we darken the regions' color. 
The default opacity is 1 but the output color looks light as if the opacity was 0.2

the actuall displayed colors

![image](https://user-images.githubusercontent.com/1708388/73003479-03a39700-3e06-11ea-8732-fae79b2fd2f9.png)

while it should be 

![image](https://user-images.githubusercontent.com/1708388/73003536-1f0ea200-3e06-11ea-8543-8e3305023e7c.png)


I've tried fill-opacity: 0.1 !important; but doesn't work.
Any idea ?Thanks;

**Comment by mvolkmann** [comment]
You can set the opacity in the object that describes each region. For example:

```js
  {start: 1, end: 2, color: '#d9d9d9', opacity: 1}
```
