### ISSUE TITLE
Flow with many new data points results in overlapping x axis tick labels

### ISSUE THREAD

**Issue by buggyvelarde** [c3js/c3#772]
Hi, 

First off, fantastic library! Thank you! 

I'm currently working on a graph display, with incremental updates to the data by polling. It's working really well, with only one minor issue: the tick labels. I first load() the graph with an initial data set, usually about 60 timepoints. Then, after a fixed time, I poll the server for any new data, typically returning 10 new timepoints, which I push onto the graph using flow(). The graph lines transition beautifully, but for every new timepoint a new tick is added. 

This means that the original graph may have had 6 or so axis tick labels, and then the first flow() call adds another 10, after the second flow() another 10 and so, resulting after a while in a continuous blur of tick labels at the bottom. 

I found I could mask this a little using the axis.x.tick.count option, but when I use this, all the ticks are redrawn after each flow, disrupting the otherwise smooth transition of the graph. 

Using version 0.4.4.

**Comment by nitin0708** [comment]
Hi

When all ticks available then its not showing tick text for all tick points.

**Comment by aendrew** [comment]
@nitin0708 That sounds like a different issue; this issue is about overlapping labels when using `chart.flow`. Could you please:

1. Research whether there's an existing issue that describes the behaviour you're encountering?
2. If not, open a new one?

Many thanks!
