### ISSUE TITLE
Reverse tick order with rotated axes

### ISSUE THREAD

**Issue by josh-s-g** [c3js/c3#787]
Is it possible to reverse the ordering of the vertical axis when `rotated: true`?

I'd like the have the tooltip behave horizontally as it does with rotated axes, but still display the data in the traditional xy chart way, with values increasing to the right and up. The vertical axis would still represent the independent variable.

**Comment by panthony** [comment]
Hi,

The issue queue is to be used for reporting defects and problems with C3.js, in addition to feature requests and ideas.

It is not a catch-all support forum.

For general support enquiries, please use the Google Group at https://groups.google.com/forum/#!forum/c3js.

All questions involving the interplay between C3.js and any other library (such as AngularJS) should be posted there first!

Thank you !
