### ISSUE TITLE
Inner placement of axis ticks on X axis of rotated charts

### ISSUE THREAD

**Issue by rassie** [c3js/c3#794]
Adding to #640: if a chart is rotated, its X-axis looks like an Y-axis, but it's not possible to put the tick labels inside the chart. `axis.x.inner` is not available, `axis.y.inner` only affects the Y axis (which looks like an X axis because the chart is rotated).

**Comment by uriklar** [comment]
+1

**Comment by h-kelley** [comment]
+1 This would be very useful to keep the look consistent for charts that use inner ticks.

**Comment by 0xfib** [comment]
+1
