### ISSUE TITLE
Use map datastructure for `columns`

### ISSUE THREAD

**Issue by devth** [c3js/c3#796]
This doesn't seem like a very good fit for nested arrays:

``` js
columns: [
  ['x', '2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06'],
  ['data1', 30, 200, 100, 400, 150, 250],
  ['data2', 130, 340, 200, 500, 250, 350]
]
```

Why not use a map?

``` js
columns: {
  'x': ['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06'],
  'data1': [30, 200, 100, 400, 150, 250],
  'data2': [130, 340, 200, 500, 250, 350]
}
```

**Comment by quarterto** [comment]
It makes no sense for the first item in the array to be the column name. An array is typically a list of homogeneous data. The column name is not part of the data.

Yes, it is slightly more painful to iterate through an object, but isn't the point of c3 to absorb some of the pain? A map is the correct data structure to use here.

**Comment by aendrew** [comment]
@quarterto I see your point, and it's probably doable without breaking backwards compatibility, but again, I don't see how it's much different from [`data.json`](http://c3js.org/reference.html#data-json) (apols, linked to the wrong page in my last comment). Although the example gives it in an array format, you can use `data.json` to parse a map-like object (See [this example](http://c3js.org/samples/data_json.html)):

```
var chart = c3.generate({
    data: {
        json: {
            data1: [30, 20, 50, 40, 60, 50],
            data2: [200, 130, 90, 240, 130, 220],
            data3: [300, 200, 160, 400, 250, 250]
        }
    }
});
```

You then use [`data.keys`](http://c3js.org/reference.html#data-keys) to choose values and possibly set categorical axes, etc. 

Does that suffice? I'm always up for adding more ways of parsing data in C3, but am just playing devil's advocate a bit here.

**Comment by quarterto** [comment]
Ah, `data.json` looks good, thanks.

**Comment by aendrew** [comment]
No worries, happy to help! :smile:

**Comment by azharuddinsayed** [comment]
here if i want to give a dynamic now of data as a json so how i can give can you please help me as my data is dynamically generating

**Comment by azharuddinsayed** [comment]
example i want to create a pie chart for n number location with name and emp count

**Comment by azharuddinsayed** [comment]
location name and emp count
