### ISSUE TITLE
Pie, donut and gauge charts don't respect interaction.enabled setting

### ISSUE THREAD

**Issue by snkashis** [c3js/c3#801]
`interaction:{enabled:false}` seems to work fine for other chart types like area/bar/line, but not pie? Testable quickly from http://c3js.org/samples/chart_pie.html

**Comment by merrihew** [comment]
Is it intentional that `interaction:{enabled:false}` does not disable mouse events on the legend? IMO, disabling interaction in the config should disable all mouse/touch functionality.

I'll gladly open a PR to introduce/fix this, but I wanted to confirm that the legend should function this way.
