### ISSUE TITLE
xFormat cannot parse unixtime

### ISSUE THREAD

**Issue by ogmw** [c3js/c3#805]
=====my html
var chart = c3.generate({
    data: {
        x: 'date',
        url: 'test.csv'
    },
    axis: {
        x : {
            type : 'timeseries',
            tick : {
                format : "%m-%d %H:%M"
            }
        }
    },
    zoom: {
        enabled: true
    }
});
========test.csv
date, eth0-rx, eth0-tx, eth1-rx, eth1-tx
1417622461000, 37, 2, 68, 33
1417622522000, 39, 2, 57, 23
1417622581000, 41, 3, 61, 23

**Comment by keyscores** [comment]
Is this documented somewhere in the reference? I am unable to get json data working with unix time.
For example:
{name: 'www.site1.com', data: 500, time: 1436744429891}

I'm using chart.load:

    keys: {
     value: ['data'],
     x:['time']
     }

and:

    axis:{
     x:{
     type: 'timeseries'
     }
    },

**Comment by aendrew** [comment]
@keyscores Here's a [fiddle](http://jsfiddle.net/g8f8uu12/4/) showing it in use. 

Key things:
* You should set tick format using a [D3 date string](https://github.com/mbostock/d3/wiki/Time-Formatting).
* When using JSON with `chart.load`, you need to also specify keys.
* Using JSON `chart.load` will totally replace chart contents; if you want the chart to update to accommodate the new data, you need to include it in the loaded JSON.

**Comment by keyscores** [comment]
Thanks Andrew its very clear now. Can I suggest adding this to the official
docs?

Lucas Geiger

**Comment by aendrew** [comment]
@keyscores Most definitely, definitely took me a minute to figure it out. Please comment on the above issue if you find documentation lacking anywhere else! Thanks!

**Comment by NullVoxPopuli** [comment]
the fiddle errors. Is there an updated example? I have javascript formatted times (with ms)

I also have multiple axes, here is my code: 

```js
    let model = this.get('model');
    let incomes = model.get('incomes');
    let registrationTimes = model.get('registrationTimes');
    let incomeTimes = model.get('incomeTimes');
    let registrations = model.get('registrations');
    let regTimes = [];
    let incTimes = [];


    registrationTimes.forEach(function (e) {
      regTimes.push(new Date(e * 1000));
    });

    incomeTimes.forEach(function (e) {
      incTimes.push(new Date(e * 1000));
    });

    let data = {
      xs: {
        Registrations: 'x1',
        Income: 'x2',
      },
      columns: [
        ['x1'].concat(regTimes), ['x2'].concat(incTimes), [
          'Registrations',
        ].concat(registrations), ['Income'].concat(incomes),
      ],
      axes: {
        Registrations: 'y',
        Income: 'y2',
      },
    };

    let config = {
      bindto: 'income-registrations-chart',
      size: {
        height: 700,
      },
      zoom: {
        enabled: true,
        rescale: true,
      },
      grid: {
        x: {
          show: true,
        },
      },
      axis: {
        y: {
          label: 'Total Number of Registrants',
        },
        y2: {
          show: true,
          label: 'Revenue',
          tick: {
            format: d3.format('$,'),
          },
        },
        x: {
          type: 'timeseries',
          tick: {
            culling: {
              max: 100,
            },
            count: 20,
            fit: true,
            rotate: 45,
            format: '%Y-%m-%d %H:%M:%S',
            // format: function (x) { return new Date(x).toString(); },
          },
        },
      },
    };

    this.set('config', config);
    this.set('data', data);

```

and then using `ember-c3`

```hbs
{{c3-chart data=data config=config}}
```

I'm using:

c3: 0.4.11
d3: 3.5.16

**Comment by NullVoxPopuli** [comment]
got it working: http://jsfiddle.net/DerNalia/kfz2eb60/
