### ISSUE TITLE
Zoom and pan behavior appears to be off

### ISSUE THREAD

**Issue by feus4177** [c3js/c3#809]
Zooming in and panning works fine until you zoom out. At this point you can zoom in again but panning no longer works. This doesn't appear to be a problem for the zoom example chart. For me the behavior is occurring on a chart where all the data is loaded after the fact. I'm not sure if that is relevant or not.

**Comment by michaelrodov** [comment]
It's quite possible that could be a bug, but it's really hard to verify it without more information. 

We get a lot of reports and the more info you give us, the more likely we'll be able to address it in a timely fashion.

Please [read the contributing guidelines](https://github.com/masayuki0812/c3/blob/master/CONTRIBUTING.md), then add the following information to your issue:

-  Operating system and web browser (with version)
-  What version of the library
-  If you were doing anything unusual, like using C3 in conjunction with a particular library or framework
-  Ideally, a [JSFiddle](https://jsfiddle.net/) example depicting the specific problem really helps us out. 
	* [Use this JSFiddle template](https://jsfiddle.net/aendrew/L4ocdkcq/)


Thank you for your cooperation — we rely on users like you to help make C3 the best charting library it can be!

**Comment by panthony** [comment]
No response from submitter
