### ISSUE TITLE
NULL value on line chart

### ISSUE THREAD

**Issue by panubear** [c3js/c3#81]
Dear Masayuki,
I have some suggestion on presenting 'null' values on line chart. Currently, it working well if 'null' values is the first or the last of data set. Considering null as the missing value, it could be in the middle of data set and my opinion is line should break into two part separately. I would be great if you could make improve on null value on line chart.
Thanks,
Panuwat

Excel
![excel](https://f.cloud.github.com/assets/6915603/2496360/f7decc5e-b31a-11e3-9ede-b29d287445bb.jpg)

C3
![c3](https://f.cloud.github.com/assets/6915603/2496361/ffc3359a-b31a-11e3-9a6b-5ff3414a8020.jpg)

**Comment by himanshugo** [comment]
Can anyone please tell me, What is the syntax of connectNull for c3-angular directive ?
I want to use that property in angularjs

**Comment by aendrew** [comment]
@himanshugo This really isn't the right place to ask; please try either [at c3-angular-directive](https://github.com/jettro/c3-angular-directive), or in [Gitter](gitter.im/masayuki0812/c3), or on the [Google Group](groups.google.com/forum/#!forum/c3js).

**Comment by freiit** [comment]
Maybe I'm late to the party, but this thread has still a high ranking on google, so: the answer is

    line: {
        connectNull: true,
    }

**Comment by ytzelf** [comment]
Any chance of having this implemented for area and area-spline charts?

Thanks a lot
