### ISSUE TITLE
d3.format("d") and axis.y.ticks results in blank tick values

### ISSUE THREAD

**Issue by catbusstop** [c3js/c3#816]
I'm trying to limit my y axis to integers using d3.format("d") but this alone gives me too many ticks so I'm also using axis.y.tick.count = 5  (as culling is not available on the y-axis by the looks of it). 

While this does limit my y-axis to integer values, a lot of the time, I get no label next to any of my ticks. I understand this is likely due to the fact that if my max value is something like 26, then 26/5 isn't going to give me int values. 

I've tried a few things such as calculating a new max value for the y-axis that divides nicely by my tick count and setting explicit values for the y-axis. These work, but the problem is that my graph gets updated frequently using chart.load(). As axis.y.max and axis.y.ticks are only set when the chart is created, my functions to calculate these aren't called, resulting in some weird looking graphs.

Ideally, axis.y.tick.culling would solve this, but is there some other way until that is supported?

**Comment by michaelrodov** [comment]
Hi
don't know If this is sill relevant, but I've faced the same issue and created a pull request that does exactly that (as far as I understand your request)
https://github.com/c3js/c3/pull/1688

Example: https://jsfiddle.net/michaelrodov/L4ocdkcq/8/

> Finds the closest "evengly" arranged set of y/y2 axis ticks, with count of ticks below the number specified in "count"
Turned on by setting axis.tick.isCountMax=true and axis.tick.count=number, arguments in chart definition JSON
Minimum number of ticks is 2, in case get getYDomain returns range smaller then 2, will build a range of first and last element

Once this PR will be merged you will get this functionality OOB

**Comment by panthony** [comment]
No response
