### ISSUE TITLE
C3 acts weird in Chrome when used inside of `table-cell` elements

### ISSUE THREAD

**Issue by danielgrippi** [c3js/c3#817]
**Platform**: OS X 10.10.1
**Chrome Version**: 39.0.2171.71 (64-bit)

Seeing some weird stuff when Chrome's non-native print dialog is invoked when c3 charts are contained within `display: block` elements within a `display: table-cell` element:  When the Chrome dialog is invoked, the c3 charts will break out of their containers, only to return to their state once the Chrome print dialog is closed.

**Comment by panthony** [comment]
Works well as long as the table-cell has a width & height.

Let's close this old issue.
