### ISSUE TITLE
data.onmouseover support for line charts

### ISSUE THREAD

**Issue by snkashis** [c3js/c3#818]
I have a feeling this is by design, but are there plans for individual callbacks per line in line charts? Right now, `data.onmouseover` returns all datapoints for each respective x-axis section, not the individual line you may be rolling over.

**Comment by phare2013** [comment]
Has this feature every been added? It is desirable to be able to mouseover a single point and get a popover for that point.

**Comment by nlevman** [comment]
Has this feature every been added? It is desirable to be able to mouseover a single point and get a popover for that point.
