### ISSUE TITLE
after window is made smaller then bigger chart does not resize

### ISSUE THREAD

**Issue by agdev** [c3js/c3#842]
Hi,
when testing resizing of c3 chart I see that after making window smaller then bigger chart does not resize. here is the jsfiddle:http://jsfiddle.net/agcsi/6363hL84/

Steps to reproduce:
1. Make window smaller in height
2. Maximize it

Chart will remain in small size and won't adjust.
C3 version: ~0.4.8

Thank you.

**Comment by ffssa** [comment]
I have this problem too! I am using C3 in combination with gridster. And it's not responding on a resize. Is there a other temporary solution?

**Comment by agdev** [comment]
@ffssa Until fix is in place you can wrap div that chart is contained in by another div 
<div id="parentContainer">
   <div id="chartContainer"></div>
</div>

on window resize event
function(){
var size = { height: $('#parentContainer')[0].offsetHeight - 10 }
chart.resize(size);
}

**Comment by shvelo** [comment]
This is still a problem

**Comment by preraksola** [comment]
Any update on this. I am also experiencing the same issue. I am using [c3-angular-directive](https://github.com/jettro/c3-angular-directive) in my angular app.

**Comment by fatore** [comment]
Still a problem in `v0.4.15`.

**Comment by panthony** [comment]
closing in favor of #1450
