### ISSUE TITLE
Resize Event for particular event.

### ISSUE THREAD

**Issue by udhaya2kmrv** [c3js/c3#846]
I have many charts in single page. I have full screen view of each chart. If i click it cant resize automatically. how i set resize chart action?

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 
Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
