### ISSUE TITLE
Timeseries Chart is not working with area types

### ISSUE THREAD

**Issue by makromat** [c3js/c3#862]
Hello masayuki0812 this is awesome! But only what is not working for me is Timeseries Chart with 'area-spline'  types lines. 

Is possible to do it somehow ?
Thanks a lot

**Comment by DanielApt** [comment]
Could you share some of your code? In the past I've been able to create timeseries with `area-spline`

**Comment by boatrite** [comment]
I had a similar problem before I noticed that I had accidentally taken the `types` hash outside of `data`. Double check to make sure types is nested under data as http://c3js.org/samples/chart_area_stacked.html demonstrates.

**Comment by michaelrodov** [comment]
Hi 
Area spline works in latest version
closed
