### ISSUE TITLE
Anyway to grab the coordinates of the brush region?

### ISSUE THREAD

**Issue by dalietimes** [c3js/c3#883]
I'm looking to select a piece of the data using the brush region as a way of filtering our statistics for a certain time period. Right now, the subchart is wonderful in showing the relevant area that you've selected, but it would be nice if the brush region could return a set of coordinates on the x-axis. Anybody have any thoughts on this? Thanks!

**Comment by masayuki0812** [comment]
How about `zoom` api? If you call this api when the chart is zoomed, it returns the zoomed domain. Once we get the domain, it seems that we can select the data according to the domain.

**Comment by mg1075** [comment]
Also, doesn't there need to be an "onbrushend" event handler to make this work?

**Comment by michaelrodov** [comment]
Hi there! 
We try to keep the issue queue clear for specific code-related problems with C3, 

Could you please try asking your question on either the [Google Group](http://groups.google.com/forum/#!forum/c3js) 
or [Gitter](https://gitter.im/masayuki0812/c3) instead? 

Thank you!​
