### ISSUE TITLE
Suggestion: Use ellipsis when running out of space on x-axis

### ISSUE THREAD

**Issue by CelineBen** [c3js/c3#916]
On the x-axis, the category names will be displayed in 2 or more lines if there is not enough space to show it all in one line. 
Example: http://jsfiddle.net/celinesweetiq/jvzkf8tq/

Would it be possible to add a display option that would use an ellipsis instead of a line break ?

Thank you.

**Comment by masayuki0812** [comment]
I think it's possible, but please let me mark enhancement at this moment.

**Comment by jcsmorais** [comment]
Hi @masayuki0812 - were there any efforts made towards addressing similar issues in recent versions?
I'm having a similar problem. Basically I have categories with variable lengths, and I'm looking for a way to have them ellipsified if they're too long.

**Comment by jcsmorais** [comment]
For future reference this has been addressed by #2364 and is now available on version [0.6.1](https://github.com/c3js/c3/releases/tag/v0.6.1)

/cc @kt3k
