### ISSUE TITLE
Read Categories from data (like with x column with timeseries)

### ISSUE THREAD

**Issue by dclairac** [c3js/c3#94]
Hi, 

I want to create a group bar chart with String as x values.
The only way I found to do that was to use categorized x axis like on this: http://jsfiddle.net/Jq6Zg/1/

My chart have to be update with c3.load, pointing to a csv file.
This fork fine with timeseries (x axis values are in the same csv file than data) but I found no way to do the same with custom String or categories.

Is it possible ?
If not, is there a workaround to update data and categories/labels in same time  from a unique data file ?

Thanks for your answer.

Dominique

**Comment by mbonaci** [comment]
Thanks both of you, great work. This is exactly what I was looking for, like `timeseries` (with strings as dates), but of type `bar`.

**Comment by clessley** [comment]
This post makes c3/d3 viable for locally hosted (aka sensitive) business data for use in a dashboard, but often the date needs to be sorted chronologically from the past (left x-axis at the origin) to the present (furthermost right x-axis). Its critical that the time.csv data must be sorted under the x column (the dates) with the most recent FIRST in the csv as:

```
x,data1,data2
16-03-02,49.19,7.21666667
16-03-01,46.97,56.4166667
16-02-29,49.26,85.1333333
```
Also, very helpful for Americans to change the date parameter from :
`format : "%y/%m/%d"` to `format : "%m/%d/%y"`
