### ISSUE TITLE
Question: Is there any way to adjust white space between bar chart?

### ISSUE THREAD

**Issue by panubear** [c3js/c3#95]
Hi,

I want to create chart look like this.
![untitled1](https://cloud.githubusercontent.com/assets/6915603/2546816/0362d74e-b642-11e3-8234-ff7de402626e.jpg)

Is there any approach to adjust the space between each bar to become closer? Current my C3 chart look like this.
![untitled2](https://cloud.githubusercontent.com/assets/6915603/2546822/2e1a98c8-b642-11e3-90f1-798df6ebbc9e.jpg)

Thanks,
Panuwat

**Comment by DogaIster** [comment]
Can someone solve this issue if data is received as :
columns: [
    ['data1', 20],
    ['data2', 30]
]

The above solution is just used for if data is received as:
columns: [
    ['data1', 20, 30]|
]

**Comment by clubajax** [comment]
Adding white space this way breaks the responsive stretchiness of the chart. This doesn't work.
