### ISSUE TITLE
Update from 0.1.42

### ISSUE THREAD

**Issue by 16n** [c3js/c3#950]
I was happy to took over a project that uses c3 but the version it uses is pretty outdated (0.1.42).
I now try to update c3 to the current version 0.4.9 but as it seems there were some major changes.

Is there a list of breaking changes so I do not have to depend on trial and error?

Thanks,
daseinhorn

**Comment by aendrew** [comment]
@daseinhorn Good question, that; given you're three minor versions behind, I'd guess there'd be a fair degree of backwards incompatibility. Might be worth documenting breaking changes somewhere, I don't think they're listed anywhere at the moment.

**Comment by masayuki0812** [comment]
Hi, as @aendrew said, there is no list of breaking changes at the moment unfortunately. However, I expect there is no serious breaking change (hopefully..) and additionally now c3 is well documented than before, so you can find the solution easily even if you got something wrong. Well, so I mean I'd like you to just try updating. Btw, I'll write this kind of information when I release a new version.

**Comment by missingdays** [comment]
@daseinhorn  Have you updated to new version successfully? if so, maybe you might wrire some notes about it?

**Comment by panthony** [comment]
No response from submitter
