### ISSUE TITLE
Enable .load() to update chart.data.names

### ISSUE THREAD

**Issue by albertodeobeso** [c3js/c3#978]
hi, the names directive works when the chart is being created, but what about when you want to do it later by making reference to a variable inside a javascript function. I tried this: 
(chart 5 previously loaded data and set the names property)

<this goes inside a function:>
chart5.load({
      columns: [
        ['data1',  0, 0, 0, 0, 0, 0, 0, 2886],
        ['data2', 0, 0, 0, 0, 0, 0, 0, 1018],
        ['data3', 0, 0, 0, 0, 0, 0, 0, .355],
        ['data4', 0, 0, 0, 0, 0, 0, 0, .355],
        ['data5', 0, 0, 0, 0, 0, 0, 0, .355],

        ],
      names: {data1 : 'US', data2 : 'China', data3 : 'UK', data4: 'Poland', data5:'Russia'} 
   });
}

what i need is to update the labels in the legend after the user select a different set of data. 

Thanks.

**Comment by albertodeobeso** [comment]
Instead of trying to use the load method I used this call:
chart5.data.names({
  data1: 'US',
  data2: 'Germany',
  data3: 'Russia',
  data4: 'India',
  data5: 'China',
  data6: 'Japan',
  data7: 'France'
});

**Comment by LukaszKrawczyk** [comment]
Yes, you can do it using `chart.data.names`, but I think there is still a problem here.

For example, we want to update data and names at the same time.
Now, we have to do the following:
```js
// update data and colors
chart.load({
  columns: [...],
  colors: {...}
});

// update labels
chart.data.names({
  data1: 'name'
});
```
Unfortunately, this will redraw chart two times (in `c3_chart_internal_fn.load` and `c3_chart_fn.data.names`).

According to [documentation](http://c3js.org/reference.html#api-load), `chart.load` can change color, classes, data but somehow can't change names. I think we should re-open this issue and add such functionality to `chart.load` - this will make API more useful and prevent chart from redrawing twice.

@masayuki0812 what do you think?

**Comment by aendrew** [comment]
:+1: Anything to improve `chart.load()`. TBH, my thought has always been that either we need to replicate all of `.generate()`'s functionality `.load()`, or remove `.load()` and make generate smart enough to act like load when redrawing a chart bound to the same element.

Reopening and renaming appropriately.

**Comment by michaelrodov** [comment]
Hi there! 
The issue was validated and it was not reproduced on the latest version
If the issue still persists, please upgrade to the latest version.
If you found a way to reproduce it on the latest version, please reopen / open a bug report.

Thank you!​
